### ISSUE TITLE
Keymap description editor UX problems

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1000]
When the halves are split, the keymap description editor has problems.

In this case, I can click on the keymap description, and it transforms to a textarea correctly. But afterwards, The Cancel and "Update description" buttons don't work when I click them.

Also, the Esc shortcut doesn't cancel the edit, neither in split, nor in merged mode.

**Comment by ert78gb** [comment]
I can not reproduce the button bugs on development mode. What is the OS and do you test it on released or development version.

The ESC cancellation [implementation](https://github.com/UltimateHackingKeyboard/agent/blob/425147745184b39f660d5e0b2c55d7cd51ee89d2/packages/uhk-web/src/app/components/editable-text/editable-text.component.html#L18) missed/never supported.

The 1007 PR contains the ESC feature

**Comment by mondalaci** [comment]
Do you have the halves split?

I can consistently reproduce this, but only when the halves are split.

**Comment by mondalaci** [comment]
Now I can see what causes this issue. See the following screenshot:

![image](https://user-images.githubusercontent.com/300402/62330177-3785ab80-b4b8-11e9-9f72-496fdb55c24e.png)

The keyboard-slider component covers the UI. The buttons are only clickable outside of keyboard-cover. The area of keyboard-cover depends on the size of the window - maybe that's why you couldn't reproduce this.
