### ISSUE TITLE
Upgrade to webpack2

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#101]
It's still in beta so maybe we shouldn't switch right away, but we should periodically check it to know when will be the good time to upgrade.

**Comment by NejcZdovc** [comment]
I think webpack 2 is ready, so we can update to it.

**Comment by fjozsef** [comment]
[Blogpost about the release](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.ddmdai4hp)

**Comment by fjozsef** [comment]
Currently it is blocked by [webpack svgstore plugin](https://github.com/mrsum/webpack-svgstore-plugin) since it doesn't support webpack 2, yet.
