### ISSUE TITLE
npm audit finds 396 vulnerabilities

### ISSUE THREAD

**Issue by tmandry** [UltimateHackingKeyboard/agent#1013]
```
found 396 vulnerabilities (15 moderate, 381 high) in 53600 scanned packages
  run `npm audit fix` to fix 396 of them.
```

`npm audit fix` fixes all of them, so this should be trivial to fix.

**Comment by mondalaci** [comment]
Closing issue due to the reasons mentioned in https://github.com/UltimateHackingKeyboard/agent/blob/master/NPM_UPDATES.md

**Comment by tmandry** [comment]
For what it's worth, I'm running locally with `npm audit fix` applied, and everything seems to work fine.

**Comment by mondalaci** [comment]
Gotcha, but I don't think you tested on all three major OSes. We rather wouldn't diverge from our policy.
