### ISSUE TITLE
What happened to 1.2.13

### ISSUE THREAD

**Issue by daenney** [UltimateHackingKeyboard/agent#1020]
It seems the 1.2.13 release was pulled? It's currently breaking package builds like the AUR AppImage build: https://aur.archlinux.org/cgit/aur.git/log/?h=uhk-agent-appimage.

The package got updated on 2019-07-15 to pull 1.2.13, https://aur.archlinux.org/cgit/aur.git/commit/?h=uhk-agent-appimage&id=035f8db12fdcc744dbf4e098a05fcc6cf0f9a7b1, then again 2 days ago b/c hashes changed (which suggests someone re-released an existing version): https://aur.archlinux.org/cgit/aur.git/commit/?h=uhk-agent-appimage&id=11f63a2006cfcc30b76d0fe222ab6fdaca4a2f41 and now there no tag or release of 1.2.13 at all: https://github.com/UltimateHackingKeyboard/agent/releases

**Comment by mondalaci** [comment]
1.2.13 was a pre-release which had major bugs in it, so it got deleted. Please don't depend on pre-releases in the future.

**Comment by daenney** [comment]
If it was a prerelease it shouldn't have been released as 1.2.13, that's not reasonable. Pre-release should be marked as such, it's what we have suffixes as -pre, -rc, -beta, -alpha for.

**Comment by mondalaci** [comment]
GitHub has a pre-release flag which was used for this pre-release. Regardless, building via CI is by far the most efficient way we can test new releases. We don't plan to change this practice.
