### ISSUE TITLE
Non-LTS version of nodejs required

### ISSUE THREAD

**Issue by dpiegdon** [UltimateHackingKeyboard/agent#1037]
When building the current master of the agent, I need a version of nodejs >= 12.0.0.
(Building on Gentoo Linux)
That also holds when cleaning the git repo and deleting ~/.npm/ .

<pre>
[dpiegdon@windfury:~/documents/documentation/UltimateHackingKeyboard_UHK/agent]> npm run build

> uhk-agent@1.2.13 prebuild ..../agent
> check-node-version --package

node: 8.12.0
Wanted node version >=12.0.0 <13.0.0 (>=12.0.0 <13.0.0)
To install node, see https://nodejs.org/download/release/v12.0.0/
npm: 6.4.1
Wanted npm version >=6.9.0 <7.0.0 (>=6.9.0 <7.0.0)
To install npm, run `npm install -g npm@6.9.0`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uhk-agent@1.2.13 prebuild: `check-node-version --package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uhk-agent@1.2.13 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ..../.npm/_logs/2019-09-11T20_11_52_535Z-debug.log
</pre>

The README states that the agent should run on an LTS version:

<pre>
### Step 1: Build Dependencies

You'll need Node.js LTS. Use your OS package manager to install it. [Check the NodeJS site for more info.](https://nodejs.org/en/download/package-manager/ "Installing Node.js via package manager") Mac OS users can simply `brew install node` to get both. Should you need multiple Node.js versions on the same computer, use Node Version Manager for [Mac/Linux](https://github.com/creationix/nvm) or for [Windows](https://github.com/coreybutler/nvm-windows)
</pre>

But 12 is not a current LTS version, as can be seen in https://nodejs.org/en/about/releases/ : v10 is the latest LTS.

My personal preference would be that you stick to an LTS version, thus to 10 for now. But thats of course not for me to decide.
[2019-09-11T20_11_52_535Z-debug.log](https://github.com/UltimateHackingKeyboard/agent/files/3602543/2019-09-11T20_11_52_535Z-debug.log)

**Comment by mondalaci** [comment]
Thanks for the heads-up! Just updated the README accordingly. The latest and greatest node is needed by some of our dependencies.

**Comment by dpiegdon** [comment]
:-(
