### ISSUE TITLE
Changing order of macro keys not working well

### ISSUE THREAD

**Issue by Makistos** [UltimateHackingKeyboard/agent#1040]
I'm trying to create a macro that types out the euro sign with mod+e. Not sure I have it done correctly,  I'm trying Press RAlt 0 1 2 8 Release RAlt. I made a mistake and needed to reorg them. But dragging and dropping macro items seems borked. After trying to fix the ordering I now have RAlt down RAlt up 1 8 2 0. If I now try to move RAlt up to last item by dropping it on 0 I suddenly have this order: RAlt down 8 2 0 RAlt up 1. 

So two items jumped instead of one. If I now try to fix this by moving 0 on top of 8, the order becomes 2 RAlt down 0 8 RAlt up 1.

It's impossible to fix the macro because the items jump all around.

I'm running Agent on Manjaro.

**Comment by mondalaci** [comment]
Thank you very much for reporting this issue! I can confirm that macro reordering is broken. We'll fix this soon.
