### ISSUE TITLE
Use native kboot firmware update on Linux and Mac. Use blhost on Windows.

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1042]
Make `npm run electron` use native kboot firmware update on Linux and Mac. Use blhost on Windows.

Make `npm run electron:kboot` use native kboot firmware update on every OS.
Make `npm run electron:blhost` use blhost firmware update on every OS.

**Comment by ttscoff** [comment]
Confirmed, `npm run electron:kboot` did seem to fix the issue on Mac.

**Comment by mondalaci** [comment]
@ttscoff Awesome, thanks for getting back to me on this one. We'll implement this issue soon.
