### ISSUE TITLE
command to return to base layer

### ISSUE THREAD

**Issue by sibel1us** [UltimateHackingKeyboard/agent#1043]
I want to be able to switch to base layout from othe layouts using the Escape-key, for example from the mouse layout. In programming IDE:s Escape key usually returns the IDE to the "default state" (closing possible dialogs and such). I haven't figured out a way to do this with the current version ("Layer switching is only possible from the base layer"). I don't need the key to do anything else but to switch back to the base layer.

**Comment by mondalaci** [comment]
We don't plan to implement this exact feature. Please note that it's already possible to toggle layers which is not exactly what you're after, but might be sufficient.

As an alternative solution, feel free to check out [Karel's UHK firmware fork](https://github.com/kareltucek/firmware). It provides advanced configuration possibilities, but it's harder to configure.
