### ISSUE TITLE
Building a crossplatform, mode showing in taskbar util, Need some guidance for detecting mode of keyboard

### ISSUE THREAD

**Issue by mohitt** [UltimateHackingKeyboard/agent#1051]
Hi All, 

This is more of question, I wanted to build a cross platform util, that would show the mode of the keyboard in the taskbar. Like mouse,fn or mod. Is it possible to detect that using some shell scripts on both windows and mac. 

I can take care of building the python util. Just need some guidance with hardware state detection.

Regards
Mohit

**Comment by mondalaci** [comment]
Hi Mohit,

I haven't planned to expose the LED display icons (and keymap text) via the UHK USB protocol because I believe it's of limited usability.

Would your taskbar work across all platforms? Can you provide a link to it?

A related problem is the USB access of the UHK by multiple applications simultaneously. I'm not sure if it's allowed in a cross-platform fashion.

**Comment by mohitt** [comment]
@mondalaci , I have not build it yet, wanted to check if it is feasible at all. I dont want to look at the keyboard to know what mode I am in. Sometime, I keep pressing keys and they dont work. Since I am in mouse mode, and this can be fixed just by looking at the screen. 

I just have to read the state of devices connected to machine, I am sure OS will tell me whether it is a mouse or a keyboard This could be a simple loop, there is no need to access the actual USB device, list all the connected devices and check the name string or some value, that can tell me whether it is mouse of a keyboard. Something must be changing when we switch between keyboard and mouse. Since OS starts to behave like a mouse is connected.

Not, a hardware programmer. So, have limited knowledge about system level details

**Comment by mondalaci** [comment]
Nothing changes on the USB level upon layer switching. The various USB interfaces (keyboard, mouse, etc) of the UHK are present regardless. You'd have to query the layers via a USB command which would have to be implemented on the firmware level. And then parallel device access may be an issue.

I'm sorry, but I don't plan to implement this, as it's not a widely requested feature, and we must focus on other issues. I'm closing this issue, but feel free to follow up, and I'll try to help you.

**Comment by mohitt** [comment]
So, when a UHK is connected to a machine, all USB interfaces are available. I suppose there should be a way to detect which device is sending interrupts like, whether the input is coming from UHK USB keyboard or UHK USB Mouse and I can just show an popup saying input is coming from UHK mouse. This would atleast show me the mode in which keys are being pressed.

So I can get a list of all usb devices and if the input being sent from matches to UHK mouse, I show a notification UHK mouse is active. Will this work ?

**Comment by mondalaci** [comment]
The suggested solution won't work. Such interrupts are handled on the kernel level, and not exposed via higher level APIs.
