### ISSUE TITLE
flash firmware on macbook pro with usbc 

### ISSUE THREAD

**Issue by nicodev3** [UltimateHackingKeyboard/agent#1053]
Tried to update from 8.5.3 to 8.6.0 on UHK 1.12.14

Here are the logs. Thanks for any help :-)

Start flashing firmware
[17:40:37.550] Agent version: 1.2.14
[17:40:37.550] [UhkHidDevice] USB[W]: 09 
[17:40:37.556] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[17:40:37.557] [DeviceOperation] USB[T]: Read left module version information
[17:40:37.557] [UhkHidDevice] USB[W]: 0e 01 00 
[17:40:37.564] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 05 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[17:40:37.566] [DeviceOperation] USB[T]: Read right module version information
[17:40:37.566] [UhkHidDevice] USB[W]: 00 01 
[17:40:37.572] [UhkHidDevice] USB[R]: 00 08 00 05 00 03 00 04 00 05 00 00 00 04 00 00 00 00 00 04 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[17:40:37.574] Device right firmware version: 8.5.3
[17:40:37.574] Device left firmware version: 8.5.3
[17:40:37.575] New firmware version: 8.6.0
[17:40:37.575] [UhkOperations] Operating system: Darwin 18.7.0 x64
[17:40:37.575] [UhkOperations] Start flashing right firmware
[17:40:37.575] [UhkOperations] Reenumerate bootloader
[17:40:37.575] [UhkHidDevice] Start reenumeration, mode: Bootloader
[17:40:37.583] [UhkHidDevice] reenumeration devices [ { vendorId: 1452,
    productId: 33026,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80700000/iBridge DFR brightness@80700000/HID Relay@0/IOUSBHostHIDDevice@80700000,0',
    serialNumber: '000000000000',
    manufacturer: 'Apple Inc.',
    product: 'iBridge DFR brightness',
    release: 513,
    interface: -1,
    usagePage: 65298,
    usage: 1 },
  { vendorId: 1452,
    productId: 33378,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80300000/iBridge ALS@80300000/HID Relay@0/IOUSBHostHIDDevice@80300000,0',
    serialNumber: '000000000000',
    manufacturer: 'Apple Inc.',
    product: 'iBridge ALS',
    release: 513,
    interface: -1,
    usagePage: 32,
    usage: 65 },
  { vendorId: 1452,
    productId: 20547,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80400000/Headset@80400000/HID Relay@0/IOUSBHostHIDDevice@80400000,0',
    serialNumber: '000000000000',
    manufacturer: 'Apple',
    product: 'Headset',
    release: 1,
    interface: -1,
    usagePage: 12,
    usage: 1 },
  { vendorId: 1452,
    productId: 33538,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80600000/iBridge Display@80600000/HID Relay@0/IOUSBHostHIDDevice@80600000,0',
    serialNumber: '0000000000000000',
    manufacturer: 'Apple Inc.',
    product: 'iBridge Display',
    release: 513,
    interface: -1,
    usagePage: 13,
    usage: 5 },
  { vendorId: 1452,
    productId: 636,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@0/IOUSBHostHIDDevice@80500000,0',
    serialNumber: 'FM7829707NTHYYMA1+TNZ',
    manufacturer: 'Apple Inc.',
    product: 'Apple Internal Keyboard / Trackpad',
    release: 2343,
    interface: -1,
    usagePage: 65280,
    usage: 11 },
  { vendorId: 1452,
    productId: 636,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@1/IOUSBHostHIDDevice@80500000,1',
    serialNumber: 'FM7829707NTHYYMA1+TNZ',
    manufacturer: 'Apple Inc.',
    product: 'Apple Internal Keyboard / Trackpad',
    release: 2343,
    interface: -1,
    usagePage: 1,
    usage: 6 },
  { vendorId: 1452,
    productId: 636,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@4/IOUSBHostHIDDevice@80500000,4',
    serialNumber: 'FM7829707NTHYYMA1+TNZ',
    manufacturer: 'Apple Inc.',
    product: 'Apple Internal Keyboard / Trackpad',
    release: 2343,
    interface: -1,
    usagePage: 65280,
    usage: 3 },
  { vendorId: 1452,
    productId: 636,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@2/IOUSBHostHIDDevice@80500000,2',
    serialNumber: 'FM7829707NTHYYMA1+TNZ',
    manufacturer: 'Apple Inc.',
    product: 'Apple Internal Keyboard / Trackpad',
    release: 2343,
    interface: -1,
    usagePage: 1,
    usage: 2 },
  { vendorId: 1452,
    productId: 636,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80500000/Apple Internal Keyboard / Trackpad@80500000/HID Relay@3/IOUSBHostHIDDevice@80500000,3',
    serialNumber: 'FM7829707NTHYYMA1+TNZ',
    manufacturer: 'Apple Inc.',
    product: 'Apple Internal Keyboard / Trackpad',
    release: 2343,
    interface: -1,
    usagePage: 65280,
    usage: 13 },
  { vendorId: 7504,
    productId: 24866,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14110000,0',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: -1,
    usagePage: 65280,
    usage: 1 },
  { vendorId: 7504,
    productId: 24866,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@1/IOUSBHostHIDDevice@14110000,1',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: -1,
    usagePage: 1,
    usage: 6 },
  { vendorId: 7504,
    productId: 24866,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@3/IOUSBHostHIDDevice@14110000,3',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: -1,
    usagePage: 1,
    usage: 128 },
  { vendorId: 7504,
    productId: 24866,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@2/IOUSBHostHIDDevice@14110000,2',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: -1,
    usagePage: 12,
    usage: 1 },
  { vendorId: 7504,
    productId: 24866,
    path:
     'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@4/IOUSBHostHIDDevice@14110000,4',
    serialNumber: '',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: -1,
    usagePage: 1,
    usage: 2 },
  { vendorId: 1133,
    productId: 45081,
    path:
     'IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice',
    serialNumber: '7C99D02958A7D284',
    manufacturer: 'Logitech',
    product: 'MX Master 2S',
    release: 6,
    interface: -1,
    usagePage: 1,
    usage: 6 },
  { vendorId: 1452,
    productId: 34304,
    path:
     'IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice',
    serialNumber: '',
    manufacturer: '',
    product: '',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 6 } ]
[17:40:37.584] [UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[17:40:37.690] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[17:40:37.690] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[17:40:37.694] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack:
   'Error: Cannot write to HID device\n    at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:92:301437)\n    at Generator.next (<anonymous>)\n    at s (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:46:1417)' }
[17:40:37.694] [UhkHidDevice] USB[W]: 09 
[17:40:37.696] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:92:299506
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:92:298996)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:46:1584
    at new Promise (<anonymous>)
    at Module.l (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:46:1361)
    at t.UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:92:298948)
    at t.UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/electron-main.js:92:300221)
    at Generator.next (<anonymous>)

[17:40:38.005] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[17:40:38.005] [UhkHidDevice] Device communication closing.
[17:40:38.006] [UhkHidDevice] Device communication closed.
Cannot write to HID device

**Comment by nicodev3** [comment]
Thanks, that is the issue.. Macbook Pro have USB C so I can’t plug the UHK without an adapter..

**Comment by mondalaci** [comment]
Can you possibly borrow an adapter and give it a try?

**Comment by nicodev3** [comment]
Just received my USB C to mini USB B adapter, everything ran fluently ! Can't live without my UHK !!!

**Comment by mondalaci** [comment]
So glad to hear, thank you!
