### ISSUE TITLE
Tweak the UX of drag handles when editing macro actions

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#106]
Apparently, @laxu is on the roll big time, so I keep these coming! :)

**Comment by laxu** [comment]
This was done mainly to prevent anything weird happening if you start reordering the items when you are editing them. Would need to test if it causes any real issues but in general I think it would be better to force the user to either save or cancel the editing before doing something else.

**Comment by mondalaci** [comment]
Ah, gotcha! I wasn't aware that it's the intended behavior. I tend to agree that allowing the user to drag macro actions while editing one may be confusing.

I'd like to suggest a little change which would suggest the user that it is clearly the intended behaviour. We could make the drag handles fade away when editing and fade back when finishing editing. I think it'd clearly convey the intention. Also, it'd be great if the space of the drag handle would stay unoccupied. This way, the position of the macro action titles would stay unchanged.

**Comment by fjozsef** [comment]
Dragging and editing could work together (the saving should only happen at clicking the save button). If @mondalaci you are sure to disable this functionality then okay, however I don't see any technical barrier.

Note: Editing and removing macro action also work together. Shouldn't we have to be consistent about disabling?

**Comment by mondalaci** [comment]
I don't feel strongly about this, but if editing and dragging is easy to implement together then I think we shouldn't hide the drag handles because I can imagine that doing so would confuse the user a bit.

**Comment by laxu** [comment]
I agree we should be consistent about disabling, I think editing should lock deleting as well. The only thing that would be allowed is editing another item as that essentially would cancel editing of the current one.

Fading the icons seems like a good idea.

**Comment by mondalaci** [comment]
Looks like we commented almost the same time, @laxu. How about allowing dragging while editing macro actions and allowing deleting while editing macros? I think it's the least confusing way to go.

Graying out the clone icon while editing a macro or keymap makes sense to me though because otherwise the user is not sure whether the old or new state of the key or macro action being edited will be cloned.

**Comment by laxu** [comment]
I think that's fine too. I'll remove hiding the sorting option and see how that works out.
