### ISSUE TITLE
macro type text wrong output

### ISSUE THREAD

**Issue by hallgren** [UltimateHackingKeyboard/agent#1067]
I tried out the default macro `Silent Bob's address` and it result in the following output:

Silent Bob
711+2880 Nulla St.
Mankato Mississippi 96522
)257= 563+7401

the final line result in wrong characters for 
( => )  
) => =

It seams to me that the macro presses the keys on the keyboard where it thing the characters are, instead of using the characters that the text holds. 

Agent version: 1.2.15

Firmware 8.6.0 is running on the left keyboard half.
Firmware 8.6.0 is running on the right keyboard half.

**Comment by mondalaci** [comment]
I don't consider this a bug. See https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

I'm closing this issue, but feel free to follow up regardless.

**Comment by kareltucek** [comment]
Btw, wouldn't it be good to communicate the behaviour to users in some better way? 

I mean, the Agent says nothing at all about the en-US mapping, the official web contains no FAQ, or direct link to the "accented-characters" article. Even the linked article itself says nothing at all about macros and  how the the discussed matter affects the way the text action is implemented...

**Comment by mondalaci** [comment]
@kareltucek You're totally right. We should clarify this.

We'll place a question mark icon according to the following image:

![image](https://user-images.githubusercontent.com/300402/67166945-aaeed900-f394-11e9-9d6a-eb30544396b7.png)

When hovering over the question mark icon, the following tooltip will appear:

> If you're using a non-US layout, the output of your UHK may differ from the text below. This is because USB keyboards send scancodes, not characters. Click on the question mark icon to learn more.

We'll make the cursor type pointer over the icon. Upon clicking the icon, it'll open the https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk URL in the browser.

**Comment by kareltucek** [comment]
What about something like:

> The text below is translated to scancodes via en-US mapping. Output will differ correspondingly if your computer's keymap differs from en-US mapping. Click to learn more.

I mean, you are explaining the reasons behind, but still miss the point of what is actually going to happen with the text.

**Comment by mondalaci** [comment]
@kareltucek Your explanation is way better than mine. Thank you, we'll use it!
