### ISSUE TITLE
Unable to flash firmware when attached to monitor's usb

### ISSUE THREAD

**Issue by EdmundsEcho** [UltimateHackingKeyboard/agent#1068]
## Issue
The Agent fails to upload the firmware.  Error message suggests to "remove all usb devices" and try again.

The Agent succeeds in uploading the firmware when I connect the keyboard to the computer directly.  The solution does not require that all usb devices be removed.

## Expected behavior
A. The error message suggest that I connect directly to the computer as a "first try".  This may save users the trouble of removing all usb devices (a real headache in my case with external drives symlinked to directories the OS relies on)

or
B. Even better,  flash the hardware via a usb from my computer monitor.

## Context/versions:
- latest Agent (downloaded Oct 20th). 
- Mac OS 10.14.6
- Mac Pro (Late 2013)
- LG Ultrawide 34UM88 with USB 3.0

Other
Data transmission works for typing and updating the keyboard settings/configuration. This is a firmware update issue only.

\- E

**Comment by mondalaci** [comment]
Can you please quote the exact error message? I can't find "remove all usb devices" in the code.

**Comment by mondalaci** [comment]
@ert78gb Can you find the relevant error message?

**Comment by ert78gb** [comment]
@mondalaci The referenced error message is: [link]( https://github.com/UltimateHackingKeyboard/agent/blob/ae82660bea7a0cf8c066a95b5f811368de57265e/packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html#L33)

This error message is visible when the the firmware upgrade failed
