### ISSUE TITLE
Agent does not seem to display version

### ISSUE THREAD

**Issue by EdmundsEcho** [UltimateHackingKeyboard/agent#1069]
The latest Mac OS version of the agent (downloaded Oct 20th), does not provide an "about Agent" drop down.  Note, I could not find it anywhere when trying to report on a previous issue.

**Comment by mondalaci** [comment]
Please specify the exact Agent version you downloaded.

**Comment by mondalaci** [comment]
I assume this happened because you built Agent from source. According to my knowledge, Agent uses the git tag as the version number.

I'm closing this issue but feel free to follow up.
