### ISSUE TITLE
Change scancode tooltip

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1076]
Regarding the scancode tooltip that is displayed in the key action popover and in macro key actions:

Make it look exactly as the Macro Type Text tooltip. Make the pointer type the same. Make it open the same URL when clicked.

Change the tooltip text to the following:
> The scancode key is translated to an actual USB scancode via en-US mapping. Output will differ correspondingly if your computer's keymap differs from en-US mapping. Click to learn more.

**Comment by kareltucek** [comment]
Are you sure about the change of the text? I think that the current text makes perfect sense in the context of key popover.

**Comment by mondalaci** [comment]
I think your phrasing is better and more general than mine, although I admit that the suggested phrasing is somewhat confusing because of the scancode field.

The thing that bothers me the most is that not only non-US characters are affected as various layouts move such characters (for example "$") to different locations.

Any suggestions?

**Comment by kareltucek** [comment]
Well, it's difficult to put something sensible into a few sentences :-(. The thing I don't like about my phrasing is that it is far too general and vague in this context - I think it is fine in the text macro context, but in this case, I think that it is good to have there the few sentences which tell the user exactly what to do.

Maybe combination of both?

> Labels are show according to en-US character-to-scancode mapping. This means that output may differ if your computer uses layout different from en-US. In such case, you need to pick the character of the desired key according to the en-US layout.
>
> Let's say you're a German user and want to map the Ö character. You can see that on US keyboards this is the semicolon key, so choose semicolon in this dropdown.
>
> Click to learn more about mappings and scancodes.

**Comment by mondalaci** [comment]
@kareltucek Masterfully phrased! We'll use your suggestion.

**Comment by mondalaci** [comment]
Resolved by ef1f8eda8f265c803d5179fa711b852b8ec28de5.
