### ISSUE TITLE
Change Mac previous and next tab shortcuts

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1079]
According to my findings, Ctrl+Tab and Ctrl+Shift+Tab work in Chrome and Visual Studio Code, but don't work in Safari.

Shift+Command+] and Shift+Command+[ however work in all of the above applications. Maybe the latter shortcuts should be used on Mac keymaps instead of the former ones.

I only use my Macbook for testing Agent, and I'm not a Mac user. I'd love to see some research about tabbed applications in the above respect before I implement this issue.

**Comment by mondalaci** [comment]
@ert78gb Please test this with as many tabbed Mac applications as you can.

**Comment by ert78gb** [comment]
Apps that I use all support both shortcut
`x` shortcut support
`-` shortcut not support

| Software | CTRL + Tab | Shift+Command+] |
| --------- | ------------ | ------------------ | 
| Safari 13 | x | x |
| Firefox 70 | x | x | 
| Chrome 78 | x | x |
| VS Code 1.40 | x | x |
| IntelliJ 2019.3 | x | x |
| Finder 10.15.1 | x | x |
| Terminal 2.10 | x | x |

**Comment by mondalaci** [comment]
Thanks for looking into it! This seems like a non-issue for recent apps, so I'm closing it.

**Comment by mondalaci** [comment]
Sharp insight from @ert78gb: Unlike Shift+Command+], Ctrl+Tab works regardless of the chosen OS layout so the latter is a better choice.
