### ISSUE TITLE
Left keyboard not connecting

### ISSUE THREAD

**Issue by jl01640** [UltimateHackingKeyboard/agent#1082]
I bought my UHK last week and when I split the keyboard the left half begins losing connection and eventually stops working. I've flashed the firmware multiple times getting different results depending on if it's split or not. I can get the keyboard to work if it's connected, but not while it's split.
[uhk.txt](https://github.com/UltimateHackingKeyboard/agent/files/3776091/uhk.txt)
[uhk2.txt](https://github.com/UltimateHackingKeyboard/agent/files/3776092/uhk2.txt)
[uhk3.txt](https://github.com/UltimateHackingKeyboard/agent/files/3776093/uhk3.txt)

**Comment by mondalaci** [comment]
1. Does your keyboard work reliably when the halves are merged?
2. Are you using the spiral cable that we provided?

**Comment by jl01640** [comment]
The keyboard mostly works with the two halves merged, but there was a point where the left half remained off even with the two merged.
I am using the spiral cable provided.

**Comment by mondalaci** [comment]
Can you reproduce this issue with other computers?

**Comment by jl01640** [comment]
The issue does not persist on a different computer

**Comment by mondalaci** [comment]
Is your UHK connected directly to your computer? If so, can you try it via a USB hub, preferably via a powered USB hub?

**Comment by jl01640** [comment]
It is connected to my computer directly and I currently don’t have a USB hub available. 
I believe this issue started after I used the software Remmina on my computer.

**Comment by mondalaci** [comment]
I don't think Remmine is related to this issue. Please provide the specs of your computer, especially the power supply.

**Comment by jl01640** [comment]
I am using a Lenovo Thinkpad X200 Laptop with a 20V Replacement AC Adapter
It’s currently running Debian

**Comment by mondalaci** [comment]
Can you reproduce this issue both when your charger is connected and when it's not connected?

**Comment by jl01640** [comment]
I unplugged the charger then plugged in the keyboard and it’s no longer having the issue, I plugged the charger back in and it seems to be working! Thank you! If this issue continues would you recommend a new AC adaptor or a powered usb hub?

**Comment by mondalaci** [comment]
This issue is probably a result of noisy power. I'm wondering whether you have a genuine power adapter or a cheaper clone. A genuine one should be a better choice. Alternatively a powered USB hub can also work, but a proper power adapter should be a better solution.

**Comment by jl01640** [comment]
You’re right I am using a cheap clone,    I will order a genuine model and update if it solves this. For now I need to connect the two halves together while my laptop charges then unplug the adapter to split the keyboard.
