### ISSUE TITLE
Add routes for add-on modules

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#109]
Upon clicking on the add-on modules in the side menu the root route gets activated which seems like a bug from the standpoint of the user. Let's add some very simple placeholder pages. The standard header style could be used with the add-on module puzzle icon, and the name of the module which matches the relevant side menu item. We could add "To be done..." as the sole content of such pages for the time being.

**Comment by NejcZdovc** [comment]
I can do this and add all to do pages (same goes for macro add)

**Comment by mondalaci** [comment]
You da man, Nejc! :+1:
