### ISSUE TITLE
Cannot update left keyboard half firmware

### ISSUE THREAD

**Issue by wrzosdev** [UltimateHackingKeyboard/agent#1090]
[Couldn't connect to the left keyboard half..log](https://github.com/UltimateHackingKeyboard/agent/files/3801163/Couldn.t.connect.to.the.left.keyboard.half.log)

I was updating firmware to 8.6.0 from 8.3.3(i believe) just after installing new agent version(1.2.15). Now i have version 0.0.0 on left half. It looks like bricked (?)

![image](https://user-images.githubusercontent.com/29088102/68079348-89580d80-fde8-11e9-9b68-63cc875017fe.png)

I tried disconnecting everything and updating again, but the same error every time.

**Comment by wrzosdev** [comment]
I have downgraded agent to 1.2.11 and i saw in logs instruction like

[03:11:33.265] [DeviceOperation] Cannot ping the bootloader. Please reconnect the left keyboard half. It probably needs several tries, so keep reconnecting until you see this message.

so i started to reconnecting until after couple seconds i've got different errors like in logs below


[Reconnecting,log](https://github.com/UltimateHackingKeyboard/agent/files/3801177/Reconnecting.log)

**Comment by wrzosdev** [comment]
Ok i've trying until success on 1.2.11 and after that updated agent to recent version and flashing firmware was successfull
I don't know if this story and logs may be useful for you but I let you decide if this issue should be closed now
If you have any questions don't hasitate to ask me
PS: this may be nice to hear that I've nearly started to panic if my loved one keyboard was broken - after all this time i forgotten how to use regular one and cannot imagine to work without UHK. This gear is legendary, great job guys;)

**Comment by mondalaci** [comment]
We'll improve the reliability of the firmware update process on Windows, but there's not much we can do right now due to 3rd party software issues.

Super glad you could make the update work, and happy to hear you love your UHK! :)
