### ISSUE TITLE
The integration dialog doesn't show up

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1099]
When downloading and launching a new Agent version, the following dialog always showed up on Linux, but not anymore starting with Agent 1.2.16. I think this dialog is useful and should show up.

![Screenshot from 2019-11-30 12-20-23](https://user-images.githubusercontent.com/300402/69899818-f7520f00-136b-11ea-9a1f-ad7f2bae19d5.png)

**Comment by kareltucek** [comment]
Cant talk for anyone other than myself, but I always found it annoying... (If I chose "no", then it would show up again on next start.)

**Comment by mondalaci** [comment]
@kareltucek I think it's useful for many, but now that you're saying, it would be great if there was a "Never show again" checkbox, too.

**Comment by mondalaci** [comment]
Also, upon auto-update, the integration of the new Agent version should automatically happen without a dialog if it was previously requested, and shouldn't happen if it wasn't previously requested.

**Comment by mondalaci** [comment]
Apparently, [desktop integration for AppImage has been removed from electron-builder in favour of AppImageLauncher.](https://github.com/electron-userland/electron-builder/releases/tag/v21.0.1), so the integration should work out of the box in (supposedly) newer distros in which AppImageLauncher is pre-installed.
