### ISSUE TITLE
New keymap creation

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#11]
Pressing the + button brings up a card based selection on the right with the available keymaps + a blank options. You can start off you keymap from them.

Once you selected the keymap the you will get to the keymap editor view with the data pre-populated based on your selection.
e.g "QWERTY clone" as the name

**Comment by mondalaci** [comment]
I failed to notice this issue and created #78 in the meantime, so closing this one now.
