### ISSUE TITLE
Change keymaps in macros

### ISSUE THREAD

**Issue by KeyAmam** [UltimateHackingKeyboard/agent#1108]
Hi, thank you for this awesome keytyping experience!
It would be great if it's possible to change keymaps in macros. What I would like to do is to set a macro like so:

- tap some key to change input source
- and then, change keymaps for the input source

**Comment by mondalaci** [comment]
Hi, and thanks for your nice words! Even though the suggested feature is not planned, I think it's already implemented in [Karlel's firmware fork](https://github.com/kareltucek/firmware).
