### ISSUE TITLE
Fn/Cmd keymaps look wrong when they are swapped

### ISSUE THREAD

**Issue by cvkline** [UltimateHackingKeyboard/agent#1118]
UHK on a MacBook Pro.  When I swapped Fn and Cmd, it looks correct on the Base and Fn layers, but like I have two Cmds on the Mod and Mouse layers. It all works fine but is a bit confusing.

Platform: UHK connected to a MacBook Pro
UHK Firmware: 8.7.0 both halves
Agent version: 1.3.0

Steps to reproduce:
• Be connected to a Mac device (not sure this really matters but that's my setup)
• In Agent, reset config, power-cycle keyboard
• Switch to QWERTY Mac (Fn+4)
• Click on QWERTY for Mac keymap in sidebar
• Click on left Fn key (bottom row, fourth from left)
• Select Keypress, LCmd
• Check All Keymaps,  check All Layers
• Click on Remap Key
• Now click on left Cmd (bottom row, third from left)
• Select Layer, then set to  "Activate the Fn layer by holding this key"
• Check All Keymaps,  check All Layers
• Click on Remap Key
• Save to Keyboard

Now look at the four layers in Agent for any "for Mac" keymap:
• Base and Fn layers will show the new (swapped) mappings for Fn and Cmd
• BUT the Mod and Mouse layers will show both keys as Cmd

Note, the key swapping does actually work on the keyboard, this appears to be an issue with how they are displayed in Agent.
![Screen Shot 2019-12-31 at 2 02 43 PM](https://user-images.githubusercontent.com/6576592/71647911-80899800-2cc2-11ea-9cb9-b8b811b087db.png)
![Screen Shot 2019-12-31 at 2 02 28 PM](https://user-images.githubusercontent.com/6576592/71647913-841d1f00-2cc2-11ea-8d4a-c501992ec985.png)

**Comment by mondalaci** [comment]
Thank you for elaborating on this. I can reproduce it by remapping any key to a layer switcher action on all layers.

This is not a bug but a deliberate behavior. When remapping a layer switcher action on all layers, it should actually only be remapped on the base layer and its own layer.

The reason for this behavior is that other layers may contain valid actions which are not triggered when switching this layer. See the left Mod key of the default keymap which is mapped to the mouse accelerate action on the mouse layer as an example of why overloading such keys can be useful.

**Comment by cvkline** [comment]
Aha, thank you for explaining this. It makes sense to me now, and now I get that on the mod layer, I really DO have two Cmd modifiers, because Mod+Fn as two layer switchers doesn't make sense but I might want to redefine Fn as something else in the Mod layer, as you point out with the Mouse layer.
