### ISSUE TITLE
Udev rules update broke Agent

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1127]
Hi, after 1.3.1 / UltimateHackingKeyboard/agent#1116 udev rules stopped working. At the moment Agent claims:

    Cannot talk to your UHK
    Your UHK has been detected, but its permissions are not set up yet, so Agent can't talk to it.
    You seem to have an old udev rule file installed. New Agent versions require and updated udev rule file to find your UHK.

I tried to:
- follow the instructions to udev file word by word
- check if the rule file has been written properly
- reconnect UHK
- restart X
- restart whole system

Archlinux here.

**Comment by mondalaci** [comment]
I cannot reproduce this issue on Linux Mint 19.3 Tricia.

Can you double check?

**Comment by kareltucek** [comment]
As far as user errors go, I am think I have done everything right. 

I.e., the file in /etc/udev/rules.d is the one shown in the script both by visual control and by diff  (see below). I have done the entire procedure at least three times (one of them now). All tries were with superuser privileges - first with sudo shell, then again word by word following the instructions (i.e., su shell + copy paste into terminal). I am sure of including both the udevadm commands and including an enter to execute the last one. 

    $ cat <<EOF >/tmp/rules-new
    > # Ultimate Hacking Keyboard rules
    > # These are the udev rules for accessing the USB interfaces of the UHK as non-root users.
    > # Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.
    > SUBSYSTEM=="input", GROUP="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0660"
    > SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
    > KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
    > EOF
    $ diff /tmp/rules-new /etc/udev/rules.d/50-uhk60.rules
    $ echo $?
    0
    $
    $ ls /etc/udev/rules.d/
    50-uhk60.rules  51-android.rules  99-jlink.rules

There are two other rule files, but I guess they should not be a problem. 

I can spend some time on investigation next week. Still, I have no experience with udev rules, so pointers would definitely be helpful.

**Comment by ert78gb** [comment]
The previous version of the udev file does not contain the `ATTRS` entries in the `SUBSYSTEM=="input"` row and `MODE="0666"` was.

```diff
-SUBSYSTEM=="input", GROUP="input", MODE="0666"
+SUBSYSTEM=="input", GROUP="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0660"
```

**Comment by kareltucek** [comment]
It seems that rules in `./packages/uhk-web/src/app/components/udev-rules/udev-rules.component.ts` and `./rules/50-uhk60.rules`  are not the same - the GROUP attribute is placed at different place. When I use the other version, Agent starts working fine.

The rule from Agent instructions:

    SUBSYSTEM=="input", GROUP="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0660"

The working rule:

    SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"

**Comment by mondalaci** [comment]
@kareltucek Thanks, we'll deduplicate the rules. So am I right that moving `GROUP="input"` just before `MODE="0660"` has made it work the rule for you on Arch? It's weird because I'd think it should be the same rule.

**Comment by kareltucek** [comment]
Yes, exactly.

Well, how does Agent check whether the rulefile is up to date? I assume simply by string comparison. 

I mean, (I believe) that the reason why Agent would not let me through was that it thought that the rulefile was not up-to-date rather than not having needed permissions. And since the instructions did not correspond to the actual checked string...

**Comment by mondalaci** [comment]
@kareltucek You're right that Agent does a string comparison of the rule files.

@ert78gb Please delete the rules directory, and deduplicate the udev rules for the instructions and the actual rules. This way, the rules will only be stored at one place.
