### ISSUE TITLE
GUI not rendering

### ISSUE THREAD

**Issue by scottStevenson8** [UltimateHackingKeyboard/agent#1131]
The agent is no longer rendering the app on my Macbook 2019, running OSX 10.15.2 Catalina. When focused, I see UHK Agent and Edit in the topbar but I am unable to maximise the app. I cannot interact with the app in any way.

It is not off screen. When I three finger swipe up to reveal open windows for UHK Agent I can see the blue window outline but nothing has rendered.

This persists after a fresh install of the newest version and older versions and restarting the machine.

Terminal output from /Applications/UHK Agent.app/Contents/MacOS/UHK Agent indicating that this might be something to do with saved settings inside the app. It does seem to be working, I just can't see it.

``` 
16:50:00.706 › [Electron Main] Create new window.
16:50:00.710 › [Electron Main] packagesDir: /Applications/UHK Agent.app/Contents/Resources
16:50:00.711 › [WindowState] load settings
16:50:00.713 › [WindowState] loaded settings {
  x: 949,
  y: 397,
  width: 1,
  height: 23,
  **isMaximized: false,
  isFullScreen: false**
}
16:50:00.717 › [WindowState] loaded settings is visible true
16:50:00.717 › [WindowState] return with loaded settings
16:50:00.934 › [UhkHidDevice] Devices before checking permission:
16:50:00.944 › {"vendorId":1452,"productId":33378,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80300000/Ambient Light Sensor@80300000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"000000000000","manufacturer":"Apple Inc.","product":"Ambient Light Sensor","release":513,"interface":-1,"usagePage":32,"usage":65}
16:50:00.945 › {"vendorId":1452,"productId":33538,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP17@1B/IOPP/IOBC@0,1/IOBufferCopyController/AppleUSBVHCIBCE@80000000/AppleUSBVHCIPort@80600000/Touch Bar Display@80600000/HID Relay@0/AppleUserUSBHostHIDDevice","serialNumber":"0000000000000000","manufacturer":"Apple Inc.","product":"Touch Bar Display","release":513,"interface":-1,"usagePage":13,"usage":5}

```

**Comment by ert78gb** [comment]
The width of the window is 1px. I don't know why. We will investigate it.
As a workaround please delete the `~/Library/Application Support/uhk-agent/Settings` file

**Comment by mondalaci** [comment]
@ert78gb When saving the window size, please make it at least 1024 x 786.

**Comment by scottStevenson8** [comment]
Deleting ~/Library/Application Support/uhk-agent/Settings fixed the issue.

Amazing job.

**Comment by mondalaci** [comment]
Glad it worked! We'll implement a general fix regardless, so reopening the issue.
