### ISSUE TITLE
[feature request] diagonal mouse movement

### ISSUE THREAD

**Issue by maplebed** [UltimateHackingKeyboard/agent#114]
When looking at the mouse controls in the GUI, it would be nice to have diagonals in addition to movement along the X and Y axis. 

![ultimate_hacking_keyboard_configurator](https://cloud.githubusercontent.com/assets/361454/18720206/a4e1d336-7fdf-11e6-802f-926d31722dc8.png)

**Comment by mondalaci** [comment]
This is certainly feasible but I can't see why it'd be truly useful. Why not just compose two directions?

**Comment by maplebed** [comment]
Adding specific keys for diagonals both makes it easier to move in that specific direction but also allows you to compose 8 additional directions (i.e. move at a 22.5° angle in addition to 45°)

Given that there is a native mouse layer, it feels to me like it should be as expressive as possible.

**Comment by maplebed** [comment]
(To be clear, this isn't a big deal, just something I noticed while poking around the live demo. Of course you should feel free to close will-not-fix or postpone-to-v2 according to your existing priority list.)

**Comment by mondalaci** [comment]
I can see how 22.5 angle increments would be more refined, but I can hardly imagine people actually using twice as many keys for moving around the mouse. For the time being, I set this to wontfix, but if many people will end up requesting this feature then we'll make it happen.
