### ISSUE TITLE
Agent 1.3.1 firmware 8.7.1 stability issues

### ISSUE THREAD

**Issue by evillase** [UltimateHackingKeyboard/agent#1141]
https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.3.1

I am using the above pre-release on 2 UHKs and the firmware 8.7.1 seems to have some stability issues.

I've noticed that one keyboard stops registering base layer alpha-numeric keys intermittently and the other keyboard will get stuck repeating an alpha-numeric character.

Both issues persisted until the keyboard was unplugged and plugged back into the system.

This is the first time I've seen instability in the keyboards, This is my first time going ahead of release firmware as well. These incidents only happened _once on each keyboard so far_, and I've been using the 8.7.1 firmware for about a week.

I'm filing as I saw unstable behavior on 2 separate keyboards using the same firmware.
I'll reply to this  issue if any more occur on either keyboard.
I know this is pre-release firmware as well.

Thanks!

**Comment by dbankmann** [comment]
Similar for me. Since I upgraded to the `firmware 8.7.1` the keyboard occasionally stops working (so far at least 5 times). 

As @evillase explained its either that it does not respond to pressing keys or sends a certain character repeatedly or both.

Also the workaround works for me.

**Comment by pcooke9** [comment]
Check out [https://github.com/UltimateHackingKeyboard/firmware/issues/261](url)

**Comment by mondalaci** [comment]
@evillase @dbankmann Please subscribe to UltimateHackingKeyboard/firmware#261 to help resolve this issue by testing the firmware versions attached there.

The firmware bundled with Agent will be downgraded to 8.7.0 until it gets fixed.

I'm closing this issue.
