### ISSUE TITLE
v1.3.2

### ISSUE THREAD

**Issue by oO0XX0Oo** [UltimateHackingKeyboard/agent#1142]
Hey,

did you remove most of the (binary) release files from it?

When I got the mail about the new version several minutes ago, I was able to download the v1.3.2 Win version.

Trying to use it (the x64 version of it), it never comes further than the initial "Loading keyboard configuration... Hang tight!" screen. It stays there forever. The previous v1.3.1 version works still fine...

**Comment by mondalaci** [comment]
I removed 1.3.2, and I'll keep rebuilding and removing it until it gets bug-free. See #1143.

**Comment by mondalaci** [comment]
I should also add for the sake of completeness that I only follow the remove-rebuild procedure for pre-releases when needed. Please only report issues for final releases in the future.
