### ISSUE TITLE
Improve Agent icons

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1166]
We should use SVG Agent icons everywhere in Agent.

1. The sunglasses of the menu Agent icon should be transparent, not white.

![image](https://user-images.githubusercontent.com/300402/74372431-e9dcea80-4dda-11ea-9838-ac446782d4a5.png)

2. The loading Agent icon doesn't seem very sharp. I don't think it's SVG.

![image](https://user-images.githubusercontent.com/300402/74372451-f06b6200-4dda-11ea-92fa-e75c5ad05f71.png)

**Comment by krokofant** [comment]
@mondalaci Are all the icon resources checked into the repository? I can't seem to find a "pure" version of the icon. The closest one is _agent-logo-with-text.svg_ but that has text.

**Comment by ert78gb** [comment]
everything is checked in. Agent also uses font-awesome
