### ISSUE TITLE
Cannot add Agent to "Favorites" on Ubuntu Dock

### ISSUE THREAD

**Issue by ajh3** [UltimateHackingKeyboard/agent#1168]
Version: **UHK.Agent-1.4.1-linux-x86_64.AppImage** (and prior versions), on Ubuntu 18.04.4

After installing/integrating the AppImage with AppImageLauncher, Agent cannot be "favorited" on the dock:

![Screenshot from 2020-02-17 14-36-59](https://user-images.githubusercontent.com/40405382/74690214-0b4f2500-5193-11ea-8933-53b1bd6457ab.png)

**Comment by mondalaci** [comment]
Do every Agent version exhibit this issue? Testing all would be overkill, but you could test the first release, too.

**Comment by mondalaci** [comment]
I think this issue is specific to Ubuntu Dock, and the solution should be found at https://askubuntu.com/questions/990833/cannot-add-custom-launcher-to-ubuntu-dock-add-to-favorites

Ubuntu Dock seems like quite a strange animal, and I'd rather not allocate resources for this.
