### ISSUE TITLE
"New macro" screen GUI is hypersensitive to mouse movement

### ISSUE THREAD

**Issue by ajh3** [UltimateHackingKeyboard/agent#1169]
Version: **UHK.Agent-1.4.1-linux-x86_64.AppImage**, on Ubuntu 18.04.4

On this screen, unless the mouse is held precisely still, clicking fails:

![Screenshot from 2020-02-17 14-38-57](https://user-images.githubusercontent.com/40405382/74690378-ba8bfc00-5193-11ea-891e-4dbb68fae4e1.png)

The problem doesn't seem to exist outside this particular screen/flow. The rest of the program is OK.

Tested with a Logitech G305 and a Microsoft Intellimouse Pro, both at 1600 DPI. Same problem with both mice.

**Comment by mondalaci** [comment]
The reason is that the entire macro action widget is a draggable, and the drag action gets triggered when moving the pointer while clicking on the widget.

We'll make the draggable action trigger only if the relevant icon (three dots aligned horizontally) is used.
