### ISSUE TITLE
Add possibility to map two none oppositional (diagonal) directions for mouse movement

### ISSUE THREAD

**Issue by KnoP-01** [UltimateHackingKeyboard/agent#1184]
Someone here ever played Nethack? There you move straight with Vi keys h,j,k and diagonal with y, u b and n there. I'd like to have that for the Mouse layer but there is neither a diagonal mouse movement nor is it possible to configure e.g. "up" and "left" at the same key.

Just saw https://github.com/UltimateHackingKeyboard/agent/issues/114

So here is my vote  :) Feel free to close :)

**Comment by kareltucek** [comment]
Feel free to check out my firmware fork at https://github.com/kareltucek/firmware. It can be done there (search for 'startMouse' and 'delayUntilRelease')...

**Comment by mondalaci** [comment]
Great job, Karel! This feature won't be implemented by the official UHK firmware, so closing this issue.
