### ISSUE TITLE
How to issue different scan codes for a single key depending on modifiers?

### ISSUE THREAD

**Issue by jscheidtmann** [UltimateHackingKeyboard/agent#1191]
I am using the UHK with German keyboard layout on Windows and Linux PCs. I now wanted to create a keyboard layer that remaps some keys to more accessible locations:

German Layout has the following things: 
`<RAlt>+<8> = "["`
`<RAlt>+<9> = "]"`
`<RAlt>+<0> = "}"`
`<RAlt>+<7> = "{"`

Where `<x>` means the key with "x" on top is pressed (as delivered), "x" means the respective character is shown on the screen. 

I want to map them to the `<[>` and `<]>` keys, meaning that the respective scancodes for curly braces should be issued when pressing `<shift>+<[>` and `<shift>+<]>`. I successfully mapped the square brackets, but amnow stuck with how to tell agent to configure the shifted versions. I.e. `<shift>+<[>` seems not to issue anything according to the display.

Is this possible? If not, is there a workaround? Thanks in advance, Jens

**Comment by mondalaci** [comment]
This will be implemented by #617. In the meantime, you can use https://github.com/kareltucek/firmware for advanced configuration scenarios.
