### ISSUE TITLE
UHK Agent setup hangs on Windows

### ISSUE THREAD

**Issue by surban** [UltimateHackingKeyboard/agent#1194]
![image](https://user-images.githubusercontent.com/1213857/76945473-d5709e00-6902-11ea-895e-96a0c1c1b5ad.png)

No further error message is provided. Only possible action is to close the setup window.

System information:
```
OS Name	Microsoft Windows 10 Pro for Workstations Insider Preview
Version	10.0.19582 Build 19582
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LENA
System Manufacturer	Dell Inc.
System Model	Precision 7530
System Type	x64-based PC
System SKU	0831
Processor	Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz, 2904 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.12.1, 19/11/11
SMBIOS Version	3.1
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0C1D71
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Bound
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19582.1001"
Time Zone	W. Europe Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.8 GB
Available Physical Memory	19.3 GB
Total Virtual Memory	36.5 GB
Available Virtual Memory	22.8 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Secure Memory Overwrite, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: Un-allowed DMA capable bus/device(s) detected
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

**Comment by mondalaci** [comment]
This hasn't every happened yet. Please retry the installation.

**Comment by mondalaci** [comment]
Given that it's hardly an Agent issue, I'm closing it, but feel free to follow up regardless.

**Comment by surban** [comment]
I've tried several times, including rebooting the whole machine.

Could you tell me how to capture a log of the setup process?

**Comment by mondalaci** [comment]
Please run the cmd command, then in the terminal start the installer and copy-paste its output.

**Comment by surban** [comment]
This does not output anything in the terminal.

![image](https://user-images.githubusercontent.com/1213857/76951369-deb23880-690b-11ea-81be-2527969db826.png)

**Comment by mondalaci** [comment]
This was a shot in the dark on my end to be honest. We've never debugged an installation issue so far because it has never occured yet. Even if we had a debug log, I'm not sure we could fix anything because the installer is integrated, and we may have no control over it.

This does look like an issue specific to your Windows installation. Can you install Agent on another computer?

**Comment by surban** [comment]
It works fine on another computer, so it's quite clear that this is a machine-specific issue. However, it would be nice to get the agent running on this machine as this is my main workstation now.

I will try to trace the problem using some Sysinternals tools. Could you also point me to the documentation of the installer?

**Comment by mondalaci** [comment]
@ert78gb Please help regarding the Windows intaller. I'm not sure which one it is.

**Comment by surban** [comment]
I've found the problem.

This occurs when `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\0b6dba6d-dd72-5279-b091-fcf82cfafc54` is left over in the registry from a previous installation of UHK agent.

After deleting the key the installation proceeded successfully.

**Comment by mondalaci** [comment]
Excellent job! Happy it works now, and thanks for sharing the solution.

**Comment by DevWouter** [comment]
Just tried installing it after having it uninstalled for quite some time. The installation hangs and if I clean up the registry like @surban suggest the problem goes away.

Might be easy to debug if you just export the entry from regedit, perform an uninstall and see if the key has been removed. If has been removed there might be a combination of problems (in which case you can import the regedit as to recreate a problematic install).
