### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by dougleville** [UltimateHackingKeyboard/agent#1205]
Would the team accept a PR to add a dark mode for the app?

**Comment by mondalaci** [comment]
I'm sorry, but dark mode would impose a long-term maintenance burden, as styles would have to work in both light mode and dark mode. I'd much rather dedicate our efforts to more important issues.

**Comment by pshirshov** [comment]
You can't imagine how bad is it - to look at an all-white window when you have some specific (but pretty common) vision issues. Please reconsider this - that's insanely unfriendly to your users.

**Comment by pshirshov** [comment]
Well, could anyone reopen this?

**Comment by mondalaci** [comment]
Please let's continue this discussion in #1360 which I've just reopened.
