### ISSUE TITLE
Add ability to map two keys pressed in quick succession

### ISSUE THREAD

**Issue by mihai-dinu** [UltimateHackingKeyboard/agent#1208]
### The problem
I would like to have the Escape key and the tilda (~) key easy to press. Tilda is in it's regular place, upper left corner, but to press escape I have to go to the `Mod` layer. I'm used to vim bindings and I've bound pressing `jk` to simulate `Esc` when in insert mode, but I would like to use this everywhere, not only in vim. 

### The proposal
Allow the user to map a pair of keys (regular keys, not modifier keys) pressed in quick succession to another key or action. This is particularly useful for keys on the Base layer, since the other layers have a lot more "key real-estate"

_Example:_ Pressing `j`, followed shortly by `k` will produce the same effect as pressing `Esc`

#### Why not just use the Mod layer?
Short answer is speed and cohesion. I can press `jk` a lot faster than I can press the Mod key and something, plus I'm already used to pressing this key combination for escape from vim. 

I'm sure this functionality could be useful for other scenarios as well.

I want to end by saying that I really enjoy the keyboard and the agent. They are top notch 👍

**Comment by mondalaci** [comment]
First up, thanks for the nice words and your suggestion!

I'm sorry but this feature is not planned. Be sure to check [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) though, as it may implement something like this.

I'm closing this issue, but feel free to follow up.

**Comment by kareltucek** [comment]
> Why not just use the Mod layer?

Why not use secondary role? Should work reliably and be quite comfortable :-).

Also, vim in a terminal allows to jump out via `<left alt>+<command key>` which is my favourite ergonomy-wise. 

> My fork...

Well... this is is so niche request that even I am not supporting it :-/.  

You (@mihai-dinu ) might try `ifGesture` or `ifShortcut` with small timeout might work to some extent on the fork, but I give no guarantees, and think that there are gonna be problems with it sooner or later. 

E.g. this on `j` key (on my fork):

    ifShortcut timeoutIn 100 final tapKey escape
    tapKey j

**Comment by mihai-dinu** [comment]
@mondalaci I undestand, thank you for the quick reply.

> > Why not just use the Mod layer?
> 
> Why not use secondary role? Should work reliably and be quite comfortable :-).

Can you elaborate on this please? As far as I can tell, the secondary role can only be assigned to modifier keys.

> Also, vim in a terminal allows to jump out via `<left alt>+<command key>` which is my favourite ergonomy-wise.

Good to know, but i would like to use this OS wide. 

I managed to work around this issue by using a complex modification in Karabiner.

**Comment by kareltucek** [comment]
> As far as I can tell, the secondary role can only be assigned to modifier keys.

Well, yes, I meant it as an alternative and was not sure if you are aware of the option... 

And also I have forgotten that official firmware doesn't allow secondaries on layer switches... having esc bound to "mouse"/capslock as a secondary role could be a suitable alternative otherwise.

**Comment by mihai-dinu** [comment]
Thank you for the suggestions. For now, the Karabiner workaround satisfies my needs. It's just that I wanted to have this functionality at a keyboard level rather than at the OS level, but also mapping Capslock to Esc works good enough.
