### ISSUE TITLE
Automatically switch mapping based on OS

### ISSUE THREAD

**Issue by giulianob** [UltimateHackingKeyboard/agent#1209]
It would be great if when the keyboard is connected to a computer we're able to choose which keymap to use for each OS. I switch between mac/windows/linux and it would be helpful if it was able to choose the right keymap when the keyboard turns on and detects which OS it's running under.

**Comment by mondalaci** [comment]
It's not possible to detect the host OS via USB from by the firmware. We could do this via Agent, but don't plan to. Feel free to build Agent and use packages/usb/switch-keymap.js in a script though.
