### ISSUE TITLE
Animate the opening/closing of macro actions

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#122]
It'd look really neat if macro actions expanded/shrunk upon edit. Macro action titles would expand vertically to show the macro action editor upon click, and shrink upon cancel/save.

**Comment by NejcZdovc** [comment]
So you would like to have animated toggle. Something like this http://www.w3schools.com/jquery/jquery_slide.asp?

**Comment by mondalaci** [comment]
Yes, I think it'd work great!

**Comment by fjozsef** [comment]
Should the new macro action editor also expand animated upon clicking "Add new macro action"?

**Comment by mondalaci** [comment]
@fjozsef Yep, that'd be sweet!
