### ISSUE TITLE
Make it possible to use the mouse layer key as a secondary role along with CAPSLOCK

### ISSUE THREAD

**Issue by gkpln3** [UltimateHackingKeyboard/agent#1233]
When trying to use caps lock with the mouse layer as a secondary role, the keyboard stops activating the capslock key.
I assume this is because the caps lock key is activated on the "key-down" event, which is probably not being sent when using secondary role.

But I would love it if I could still use the mouse layer while also using capslock (without any other modifier) if I only press the capslock key once without any other key.

**Comment by kareltucek** [comment]
My humble guess is that your OS is Mac, which requires caps lock to be pressed for a certain amount of time. With secondary role assigned, a key is activated only for a very brief moment on key release so your OS decides to ignore it.

**Comment by mondalaci** [comment]
@kareltucek Thanks, I'm pretty sure this is the case. I'm closing this issue, but we'll reply if needed regardless.

**Comment by gkpln3** [comment]
In case anyone ever occurs to see this issue again, I've eventually solved the issue by developing a small, open source tool for mac to disable this annoying caps lock activation delay.
https://github.com/gkpln3/CapsLockNoDelay
