### ISSUE TITLE
Add mouse speed preset and binding to keymap layouts

### ISSUE THREAD

**Issue by JangPooH** [UltimateHackingKeyboard/agent#1235]
There are only two options on mouse speed configuration on current version(1.4.3)
reset to 'PC default' , 'MAC default'

I think it will be helpful to add several user definable mouse speed presets.
and can be bound to keymap layout.

eg)
[ On 'Device > Mouse speed' Page ] 
'default for PC' = [100, 800, 1700, 200, 1600, 20, 20, 20, 10, 50]
'default for MAX' = [200, 2800, 4500, 2000, 4000, 10, 10, 10, 7, 12]
'my custom for PC' = [100, 600, 1200, 200, 1600, 30, 30, 30, 15, 50]
'my custom for MAC' = [200, 1600, 3400, 400, 3200, 15, 15, 15, 10, 40]

[ On 'Keymaps > * ' Page ]
keymap layout 'Colemak for PC': bound mouse speed = 'default for PC' 
keymap layout 'Colemak for MAC': bound mouse speed = 'default for MAC' 
keymap layout 'Dvorak for PC': bound mouse speed = 'default for PC' 
keymap layout 'Dvorak for MAC': bound mouse speed = 'default for MAC' 
keymap layout 'QWERTY for PC': bound mouse speed = 'my custom for PC'
keymap layout 'QWERTY for MAC': bound mouse speed = 'my custom for MAC' 

When use 'QWERTY for PC' layout, mouse speed configuration changed to 'my custom for PC'
When use 'QWERTY for MAC' layout, mouse speed configuration changed to 'my custom for MAC'

**Comment by mondalaci** [comment]
What if you'd set the mouse resolutions of your computers similarly? Then a single UHK mouse configuration may work with your computers.

**Comment by JangPooH** [comment]
@mondalaci 
Yes, It can be the solution for me. 
Feel free to treat this issue as just minor suggestion to closer fit the concept of UHK: 'hackable', 'configurable'

**Comment by mondalaci** [comment]
I'll keep it in mind. I've been thinking about this, and maybe we'll do it eventually, but it'd add to the complexity on the user side, and I'm not sure it's justified. I'm closing this issue, but feel free to follow up.
