### ISSUE TITLE
Cannot update left device from 8.5.3 to 8.9.3 using agent 1.4.5

### ISSUE THREAD

**Issue by robert-blip** [UltimateHackingKeyboard/agent#1258]
Somehow, I cannot update the left half.

1. Connect UHK
2. Start agent
3. Click on update

Log:
Start flashing firmware
Agent version: 1.4.5
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceOperation] USB[T]: Read left module version information
[UhkHidDevice] USB[W]: 0e 01 00 
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 05 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceOperation] USB[T]: Read right module version information
[UhkHidDevice] USB[W]: 00 01 
[UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[UhkHidDevice] USB[R]: 00 08 00 09 00 03 00 04 00 07 00 00 00 04 00 01 00 00 00 04 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Device right firmware version: 8.9.3
Device left firmware version: 8.5.3
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.9.3
[UhkOperations] Operating system: Windows_NT 10.0.18363 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] USB[T]: Enumerated device, mode: Bootloader
[UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:101:29343)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:43:1740)"}
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] Transfer error:  Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:27094)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26846
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26825)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:27094)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26846
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26825)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[DeviceService] start poll UHK Device
Cannot write to HID device

What am I missing?

Kind regards,
Robert

**Comment by robert-blip** [comment]
Hi, just ran the firmware upgrade on another computer using Ubuntu Studio and used the 1.4.5 agent image: all is updated now.

**Comment by mondalaci** [comment]
So glad to hear! I'm not sure what the root cause was, but I'm glad it's been solved.

**Comment by robert-blip** [comment]
Hi, now trying to update my 2nd keyboard (also on 8.5.3), but it has the same issue. Tried running the agent as administrator, but no change in success.
I will also try my old laptop.

FYI, the log:
Start flashing firmware
Agent version: 1.4.5
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceOperation] USB[T]: Read left module version information
[UhkHidDevice] USB[W]: 0e 01 00 
[UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 05 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceOperation] USB[T]: Read right module version information
[UhkHidDevice] USB[W]: 00 01 
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] USB[R]: 00 08 00 05 00 03 00 04 00 05 00 00 00 04 00 00 00 00 00 04 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Device right firmware version: 8.5.3
Device left firmware version: 8.5.3
[DeviceService] stop poll UHK Device
[UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceService] stopped poll UHK Device
New firmware version: 8.9.3
[UhkOperations] Operating system: Windows_NT 10.0.18363 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] USB[T]: Enumerated device, mode: Bootloader
[UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:101:29343)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:43:1740)"}
[UhkHidDevice] USB[W]: 09 
[UhkHidDevice] Transfer error:  Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:27094)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26846
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26825)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:27094)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26846
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:101:26825)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[DeviceService] start poll UHK Device
Cannot write to HID device

**Comment by mondalaci** [comment]
Fome some reason your UHK does not reenumerate as the bootloader. Please connect it directly to your computer and retry.

**Comment by robert-blip** [comment]
It is as direct as possible in that I connect to keyboard to the base of my Surface Book 2. I know the computer is actually in the display (that can be removed and become a tablet). There is no USB port on the tablet...

**Comment by robert-blip** [comment]
The second keyboard is updated fine using the old laptop. However as the battery is close to dead, it would be great to be able to update using the surface book 2 in the future ;-)

**Comment by mondalaci** [comment]
I'd definitely like this make this work, but wondering if this is a Surface Book 2 related issue. Would you possibly ask https://twitter.com/artPlusPlus/status/1210202599531700229 whether he has encountered this issue?

**Comment by robert-blip** [comment]
I can't send him a message.
He is also on gitbhub, maybe this works?

@artPlusPlus where you able to update?
