### ISSUE TITLE
Agent hangs on Windows 10 via USB hub

### ISSUE THREAD

**Issue by kiview** [UltimateHackingKeyboard/agent#1266]
After having version 1.4.5 installed on Windows 10 Pro 1909, I see the following behaviour:
![image](https://user-images.githubusercontent.com/5088104/83598469-0fe4f100-a56a-11ea-97b4-92a266cda561.png)

White content in UHK window and nothing renders, Windows reporting the application to not respond. After a couple of minutes, the text "Loading Keyboard configuration" and animated logo appears. After even more minutes, the GUI will render but now allow for any interactions. 

Running with elevated privileges does not change the observed behaviour. 

No problems in using the Linux version on the same PC with the same hardware (just FYI to eliminate the possibility of faulty hardware).

**Comment by mondalaci** [comment]
This must be an installation specific issue because noone else has reported it yet.

Is your UHK connected directly to your PC? If not, please connect it directly and retry.

**Comment by kiview** [comment]
Good idea, the UHK is connected to an Amazon USB3 hub (reporting as `Genesys Logic, Inc. Hub `under Linux with `lsusb`).

When connecting directly to the PC, the software works as expected under Windows. Under Linux (Ubuntu 20.04) however, the agent software also works when UHK is connected to the hub.

Shall we change the title the reflect the real issue?

**Comment by mondalaci** [comment]
I'm glad that connecting your UHK directly to your PC made Agent work on Windows. Would you elaborate on the configuration of your PC?

**Comment by kiview** [comment]
The UHK is connected to a [generic USB3](https://www.amazon.de/gp/product/B00GS19NWG/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1) hub (the hub has an external power source as well).

It only registers as `Generic SuperSpeed USB Hub` in Windows 10 device manager. As mentioned above, it reports as `Genesys Logic, Inc. Hub` under Linux with `lsusb`.

For what it's worth, I can make UHK Agent working by doing the following procedure:

1. Connect UHK to direct USB port
2. Start UHK Agent (connects successfully) and exit
3. Connect UHK via USB hub
4. Start UHK Agent again (connects successfully)

I'd be happy to help in any way possible to debug this issue, however, I am not really familiar with debugging hardware on Windows. Maybe it is easiest to debug the UHK Agent code that tries to establish the initial connection and see if it hangs? Just need a pointer a where to start this.

**Comment by mondalaci** [comment]
@kiview Can you reproduce the above on both Windows and Linux?

**Comment by kiview** [comment]
No, on Linux the Agent software works directly, also if UHK is connected to the hub.

**Comment by mondalaci** [comment]
@kiview What's the hardware configuration of your PC? I mean processor, motherboard, power supply.

**Comment by kiview** [comment]
For what it's worth, this error is gone now, not sure if a Windows update or anything changed something.
