### ISSUE TITLE
Alter the name generation algorithm for cloned macros/keymaps

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#128]
**Laci:**
another (somewhat related) bug: let's say i clone "New macro (3)" which should be named as "New macro (4)" (given that "New macro (4)" doesn't exist) but I get "New macro (3) (2)"
**Nejc:**
This is as intended
Let's say that you create New macro
New macro has a name "New macro (2)"
now you do some modifications
and then you duplicate it
in your scenario you would get "New macro (3)", which is not correct
it should be "New macro(2) (2)"
we have the same logic for keymaps
**Laci:**
i understand your logic but i think that "New macro (2)" and "New macro (2) (2)" are equally meaningless. it should be the duty of the user to properly name his macros. if not, he'll end up with chaos. i'd stick to the simpler naming scheme because i don't believe that the alternative naming scheme offer usability advantages. we simply end up with (more) meaningless numbers.
**Nejc:**
and what would be our logic behind it
if you duplicate macro/keymap that have default name "New macro (x)" or "VIM (x)" we should find next free x for name "New macro" or "VIM"?
**Laci:**
yes, exactly

**Comment by fjozsef** [comment]
I agree with Nejc, it works as inteded. The user should rename macro name before if he wants to avoid (2) (2).

**Comment by NejcZdovc** [comment]
PR with new generator is ready, so you can decide if you would like to accept it or delete it 😄

**Comment by NejcZdovc** [comment]
Personally I think that we shouldn't change it, because we could really confuse user with this new logic.

**Comment by mondalaci** [comment]
Assuming that the user properly names his keymaps/macros it shouldn't make a difference usability-wise because "New macro (7)" is just as meaningless as "New macro (4) (2)". The latter name is longer and seems more convoluted to me, however.

But I don't wanna force this on you. If you strongly feel that the current way is the Right way then you don't have to merge #131.

I've just tested the PR and it works well.

**Comment by NejcZdovc** [comment]
@fjozsef your call. I can understand @mondalaci and mine, so I am undecided or better yet I don't have strong opinion. What we are currently doing is playing around with dummy data and this flow probably will not be in usual user flow.

**Comment by fjozsef** [comment]
I was playing on Windows with files names:
Original file: file.ext
Copy of file.ext: file - Copy.ext
Copy of file.ext again: file - Copy (2).ext
Copy of file - Copy.ext: file - Copy - Copy.ext
It think we have implemented nearly approach (notice the duplicated Copy in the name), so I close this.
