### ISSUE TITLE
Firmware Update - ver 8.10.1

### ISSUE THREAD

**Issue by hollywoodhash** [UltimateHackingKeyboard/agent#1288]
I'm plugged straight into the motherboard - but tried a few different usb ports just in case and reinstalled latest Agent software. Keep getting the same error when trying to flash latest Agent bundle or @kareltucek latest release. 

I'm slightly new to this so it could be something simple I"m doing wrong just FYI.

[firmware-error_hollywood.txt](https://github.com/UltimateHackingKeyboard/agent/files/4890951/firmware-error_hollywood.txt)

**Comment by mondalaci** [comment]
@hollywoodhash Please try all USB ports of the motherboard.

**Comment by ert78gb** [comment]
@hollywoodhash Could you upgrade your windows OS to the latest version?
I see in the logs you use the `Operating system: Windows_NT 10.0.18362 x64` The `18362` build is the 2019 May update.
https://en.wikipedia.org/wiki/Windows_10_version_history

**Comment by hollywoodhash** [comment]
I updated to the latest Windows and tried all USB ports.. still getting the same error. I'm technically using Windows 10 Pro version - would that have anything to do with it?

[firmware-error_hollywood-v2.txt](https://github.com/UltimateHackingKeyboard/agent/files/4892031/firmware-error_hollywood-v2.txt)

**Comment by mondalaci** [comment]
This should work on Windows 10 Pro. Were you ever able to update your UHK firmware on this computer? if not, please give the update a try on another computer.

**Comment by hollywoodhash** [comment]
So the other computer trick ended up working after switching to the default config. I didn't know everything was stored on the board like that but pretty cool. I got Keral's flash to work as well just FYI. Thanks guys!
