### ISSUE TITLE
Auto update error popup | Windows 10

### ISSUE THREAD

**Issue by hsszyman** [UltimateHackingKeyboard/agent#1302]
![image](https://user-images.githubusercontent.com/18254249/87573465-f1aafe80-c69a-11ea-8a35-1c374cf52be0.png)
A few seconds after startup

![image](https://user-images.githubusercontent.com/18254249/87573573-2028d980-c69b-11ea-8290-abac20a267ee.png)

After exiting the original error message and clicking the update button

Let me know if there are any error logs I need to be pasting as well, and where to find them

**Comment by mondalaci** [comment]
Thanks for reporting! We'll look into it.

**Comment by mondalaci** [comment]
@hsszyman Which Agent version are you using? I'm asking because this issue should be fixed in Agent 1.5.0. Please give it a try and let me know.

**Comment by hsszyman** [comment]
Will do! I'll try it when I get home

**Comment by mondalaci** [comment]
Closing issue due to the lack of replies. Feel free to follow up any time regardless.
