### ISSUE TITLE
keyboard not working.

### ISSUE THREAD

**Issue by mdlopresti** [UltimateHackingKeyboard/agent#1305]
keyboard is non responsive.  attempted update from 8.5.x, here is log

[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[UhkOperations] Operating system: Windows_NT 10.0.18363 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkOperations] Waiting for bootloader
[UhkOperations] Flash security disable
[DeviceService] updateFirmware error {"message":"Invalid response length!","stack":"Error: Invalid response length!\n at Object.t.decodeCommandResponse (C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:64704)\n at C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:61442\n at new Promise (<anonymous>)\n at t.UsbPeripheral.<anonymous> (C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:61156)\n at Generator.next (<anonymous>)\n at C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:57:1938\n at new Promise (<anonymous>)\n at Object.l [as __awaiter] (C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:57:1683)\n at t.UsbPeripheral.sendCommand (C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:61107)\n at t.KBoot.<anonymous> (C:\\Users\\mike\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:46586)"}
[UhkHidDevice] Available devices:
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_01&col01#7&35c383aa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":1,"usagePage":1,"usage":6}
{"vendorId":1133,"productId":49713,"path":"\\\\?\\hid#vid_046d&pid_c231#2&20a291cc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":1,"interface":-1,"usagePage":1,"usage":2}
{"vendorId":1133,"productId":49714,"path":"\\\\?\\hid#vid_046d&pid_c232#2&6aae8d8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","release":1,"interface":-1,"usagePage":1,"usage":6}
{"vendorId":1133,"productId":49714,"path":"\\\\?\\hid#vid_046d&pid_c232#2&b4b7c37&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","release":1,"interface":-1,"usagePage":1,"usage":6}
{"vendorId":1133,"productId":49713,"path":"\\\\?\\hid#vid_046d&pid_c231#2&2d0d5a5a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","release":1,"interface":-1,"usagePage":1,"usage":2}
{"vendorId":1133,"productId":2651,"path":"\\\\?\\hid#vid_046d&pid_0a5b&mi_03&col01#7&346f2bdb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"Logitech G933 Gaming Wireless Headset","release":257,"interface":3,"usagePage":12,"usage":1}
{"vendorId":1133,"productId":2651,"path":"\\\\?\\hid#vid_046d&pid_0a5b&mi_03&col02#7&346f2bdb&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"Logitech G933 Gaming Wireless Headset","release":257,"interface":3,"usagePage":11,"usage":1}
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_01&col02#7&35c383aa&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":1,"usagePage":12,"usage":1}
{"vendorId":1133,"productId":2651,"path":"\\\\?\\hid#vid_046d&pid_0a5b&mi_03&col03#7&346f2bdb&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"Logitech G933 Gaming Wireless Headset","release":257,"interface":3,"usagePage":65347,"usage":514}
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_01&col03#7&35c383aa&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":1,"usagePage":1,"usage":128}
{"vendorId":1133,"productId":2651,"path":"\\\\?\\hid#vid_046d&pid_0a5b&mi_03&col04#7&346f2bdb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"Logitech G933 Gaming Wireless Headset","release":257,"interface":3,"usagePage":65280,"usage":1}
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_01&col04#7&35c383aa&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_01&col05#7&35c383aa&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":1,"usagePage":65280,"usage":2}
{"vendorId":2313,"productId":28,"path":"\\\\?\\hid#vid_0909&pid_001c&mi_03&col01#7&14543083&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"audio-technica","product":"AT2020USB+","release":256,"interface":3,"usagePage":12,"usage":1}
{"vendorId":1133,"productId":49277,"path":"\\\\?\\hid#vid_046d&pid_c07d&mi_00#7&2293676c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"026335633535","manufacturer":"Logitech","product":"Gaming Mouse G502","release":34818,"interface":0,"usagePage":1,"usage":2}
{"vendorId":2313,"productId":28,"path":"\\\\?\\hid#vid_0909&pid_001c&mi_03&col02#7&14543083&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"audio-technica","product":"AT2020USB+","release":256,"interface":3,"usagePage":11,"usage":5}
{"vendorId":7504,"productId":24864,"path":"\\\\?\\hid#vid_1d50&pid_6120#8&2d81a28b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at t.UhkHidDevice.<anonymous> (C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:27670) at Generator.next (<anonymous>) at C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938 at new Promise (<anonymous>) at Object.l [as __awaiter] (C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683) at C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:27588 at new Promise (<anonymous>) at t.UhkHidDevice.<anonymous> (C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:27567) at Generator.next (<anonymous>) at C:\Users\mike\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
Invalid response length!

**Comment by mondalaci** [comment]
Hi there, and sorry about this issue!

Please give a try to https://ultimatehackingkeyboard.com/knowledgebase?q=brick

**Comment by mdlopresti** [comment]
The keyboard is back up and working.  The issue was fixed after disassembly and before I could short the pads.  Maybe just being unhooked from power overnight fixed the issue?

**Comment by mondalaci** [comment]
I'm not sure what's happened, but I'm glad your UHK is working again. Cheers!
