### ISSUE TITLE
Cannot flash firmware

### ISSUE THREAD

**Issue by polyphanes** [UltimateHackingKeyboard/agent#1307]
Forgive me if I'm not submitting this right, first time using GitHub.

Using most recent version of UHK Agent on Windows 10.  Currently running 8.7.0 firmware on both halves, trying to flash to 8.10.1 bundled with UHK agent (I forgot to check for updates after a while).  The process fails, both when connecting UHK to computer via KVM switch as well as when plugging into a USB port directly on the machine (same issue both times).  Log attached below, from when UHK was connected directly to computer.  I don't know if this is a bug or a setup issue on my end (likely the latter, but I don't know how to troubleshoot this).

I should also note that UHK Agent on Windows 10 is extremely slow, not to the point of becoming wholly unresponsive but definitely with a notable lag of a second or more between clicks, presses, or any kind of responsive activity.  UHK Agent light on the UHK itself also blinks rather than holding steady, which I don't know if that's normal (I don't recall it being like that before).  I don't know if these issues are associated with the firmware update issues.

----

Start flashing firmware
Agent version: 1.5.0
Device right firmware version: 8.7.0
Device left firmware version: 8.7.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.10.1
[UhkOperations] Operating system: Windows_NT 10.0.18362 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices:
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_00#9&c764333&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":0,"usagePage":1,"usage":2}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_00#9&39e60ce4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":0,"usagePage":1,"usage":6}
{"vendorId":1151,"productId":49160,"path":"\\\\?\\hid#vid_047f&pid_c008&mi_03&col01#8&17dfe834&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Plantronics","product":"Plantronics .Audio 655 DSP","release":308,"interface":3,"usagePage":12,"usage":1}
{"vendorId":1151,"productId":49160,"path":"\\\\?\\hid#vid_047f&pid_c008&mi_03&col02#8&17dfe834&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Plantronics","product":"Plantronics .Audio 655 DSP","release":308,"interface":3,"usagePage":11,"usage":5}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col02#9&304d80f5&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":12,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col03#9&304d80f5&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col04#9&304d80f5&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col05#9&304d80f5&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col06#9&304d80f5&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col01#9&304d80f5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":1,"usage":6}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col07#9&304d80f5&0&0006#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_01&col01#9&2222809f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":1,"usagePage":12,"usage":1}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_01&col02#9&2222809f&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":1,"usagePage":1,"usage":128}
{"vendorId":3190,"productId":5662,"path":"\\\\?\\hid#vid_0c76&pid_161e&mi_02#7&1003338b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","product":"USB PnP Audio Device","release":256,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for bootloader
[DeviceService] updateFirmware error {"message":"Cannot find device with vendorId: 7504, productId: 24864","stack":"Error: Cannot find device with vendorId: 7504, productId: 24864\n    at C:\\Users\\sam\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:57:14310\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\sam\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:43:1740)"}
[UhkHidDevice] Available devices:
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_00#9&c764333&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":0,"usagePage":1,"usage":2}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_00#9&39e60ce4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":0,"usagePage":1,"usage":6}
{"vendorId":1151,"productId":49160,"path":"\\\\?\\hid#vid_047f&pid_c008&mi_03&col01#8&17dfe834&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Plantronics","product":"Plantronics .Audio 655 DSP","release":308,"interface":3,"usagePage":12,"usage":1}
{"vendorId":1151,"productId":49160,"path":"\\\\?\\hid#vid_047f&pid_c008&mi_03&col02#8&17dfe834&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Plantronics","product":"Plantronics .Audio 655 DSP","release":308,"interface":3,"usagePage":11,"usage":5}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col02#9&304d80f5&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":12,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col03#9&304d80f5&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col04#9&304d80f5&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col05#9&304d80f5&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col06#9&304d80f5&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col01#9&304d80f5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":1,"usage":6}
{"vendorId":9610,"productId":4103,"path":"\\\\?\\hid#vid_258a&pid_1007&mi_01&col07#9&304d80f5&0&0006#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SINOWEALTH","product":"Game Mouse","release":256,"interface":1,"usagePage":65280,"usage":1}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_01&col01#9&2222809f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":1,"usagePage":12,"usage":1}
{"vendorId":3141,"productId":30737,"path":"\\\\?\\hid#vid_0c45&pid_7811&mi_01&col02#9&2222809f&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"SONiX","product":"USB FS Keyboard","release":518,"interface":1,"usagePage":1,"usage":128}
{"vendorId":3190,"productId":5662,"path":"\\\\?\\hid#vid_0c76&pid_161e&mi_02#7&1003338b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","product":"USB PnP Audio Device","release":256,"interface":2,"usagePage":12,"usage":1}
{"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#8&38533108&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
{"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#8&147bf346&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1,"usagePage":1,"usage":6}
{"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#8&2c3f7f8b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2,"usagePage":12,"usage":1}
{"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#8&86841c9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3,"usagePage":1,"usage":128}
{"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#8&1b6efbf9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#8&38533108&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] start poll UHK Device
Cannot find device with vendorId: 7504, productId: 24864

**Comment by mondalaci** [comment]
Please don't use the KVM switch, but try to connect your UHK directly to your computer, and give a try to every USB port of your computer. If it still doesn't work, try to connect your UHK via a USB hub and retry.

**Comment by polyphanes** [comment]
So, just an update; the problem no longer exists.  I'm not sure how or why,
but just by leaving the UHK Agent open overnight, the problems seem to have
gone away: UHK Agent is instantly responsive in every way, the Agent LED
light on the UHK itself remains on when Agent is open, and (best of all)
the firmware was able to update.  Changing the USB ports to the ones on my
computer directly did not change the outcome, so it might have been a
problem on my end with some background process taking up processing time
from UHK Agent.

Sorry for the confusion, and thank you for your swift response!

-p

**Comment by mondalaci** [comment]
Thanks for your follow-up! I wish I knew what happened, but regardless, I'm happy that everything works on your end. I'm closing this issue.
