### ISSUE TITLE
Suggestion: Implement Nordic/Language modes

### ISSUE THREAD

**Issue by N0K0** [UltimateHackingKeyboard/agent#1308]
Hi!

As a Norwegian user I have some issues with the agent.

This is a picture of a standard Norwegian qwerty layout in the agent:
![image](https://user-images.githubusercontent.com/13900053/89133194-60e97500-d51a-11ea-9499-ada06e0a8377.png)

Optimally the key selector should be able to represent this layout like the following:
![image](https://user-images.githubusercontent.com/13900053/89133259-d1909180-d51a-11ea-9173-8aa4705c4f7f.png)

Æ, Ø and Å (as well as some other characters) is represented by the wrong letters. This makes it hard to select the correct letter from the dropdown list, as we need to remember what is what. Thankfully the "scan key code" works as expected.

This issue extends to the macro manager too, where Æ, Ø and Å is not even accepted?

Here is the information from QMK regarding language based key codes
https://beta.docs.qmk.fm/using-qmk/simple-keycodes/reference_keymap_extras

**Comment by mondalaci** [comment]
Hi, and thanks for your suggestion!

The reason we haven't implemented such features is explained in the "Accented characters in Agent" section of https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

We plan to provide foreign UHK keycap sets in our webshop eventually, possibly Nordic included. If we do so, chances are good we'll implement their visualization in Agent, but only for the provided keycap sets. Please subscribe to our [monthly newsletter](https://ultimatehackingkeyboard.com/newsletter) so we can keep you in the loop.

I'm closing this issue but feel free to follow up.
