### ISSUE TITLE
Feature request: make default keyboard layout optionally depend on connected computer

### ISSUE THREAD

**Issue by pbartyik** [UltimateHackingKeyboard/agent#1309]
It'd be nice to not need to switch manually to a non-default layout when connecting the keyboard to another device which requires different layout (think linux/windows different shortcuts for similar behaviour).

I have no idea if the keyboard can identify the computer in any way, so this is a long shot.

**Comment by mondalaci** [comment]
Unfortunately, OS fingerprinting via USB is unreliable, so there's no way for the UHK to detect the host OS.

**Comment by pbartyik** [comment]
what about mapping actual device not the OS? Not sure if a computer (regardless of OS) has a unique ID that can be grabbed through USB to be matched on?

**Comment by mondalaci** [comment]
There is no such device ID exposed via USB.

**Comment by luteijn** [comment]
Agent (or another program monitoring usb or triggered on usb device insert) could probably detect the keyboard though, and then send a command to run a specific function...

**Comment by mondalaci** [comment]
Assuming that the user runs Agent in the background all the time, it's feasible to implement this feature, but things can get complicated as far as adaptive mode is concerned. I'd much rather implement adaptive mode first and extend it with an OS matcher if there's significant interest.
