### ISSUE TITLE
Animate key swapping

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1321]
When a key is being dragged over the other keyboard half and it rotates, animate the rotation.

When releasing a key where no target is available, move the key back to its original position with an animation.

When releasing a key at its new position, move the keys to their final positions with an animation, animate the opacity of the source key from translucent to opaque, and animate the color of the target key from blue to gray.

**Comment by krokofant** [comment]
I would add to this:
1. Keep a "skeleton" (a key with a highlighted border) of the key you're moving so you can see where it's coming from
2. When releasing a key where no target is available, move it back and animate with _shake_
3. When releasing a key at the new position phase out the old key border, and phase in the new key

I think the context given to the user before and after the change is more important than the animations during the move of the key. The user should understand _the changes that have happened_ without the need for animations. I've given some more suggestions related to this in issue #1417

**Comment by mondalaci** [comment]
Thank you for your suggestion, but I'd stick to the original specification because I believe that it's visually cleaner while still being intuitive. If my original specification turns out to be unintuitive, I'll reconsider your suggestion.
