### ISSUE TITLE
Change video mode with one key

### ISSUE THREAD

**Issue by dns2utf8** [UltimateHackingKeyboard/agent#1324]
Hi all

I would like to program a key on a layer to change the video mode (eg. switch from all external screen to extended desktop) with the UHK.
The keycode is `0xe0 0x56 0xe0 0xd6`

This is not `Super` + `P` which is `0xe0 0x5b 0x19` and `0x99 0xe0 0xdb`. Also the longer key code works outside of windows and KDE.

My second attempt was to create a macro, but that did not work either.

In the agent I saw some special key codes like `International 1` are those helpful for that?

Cheers,
Stefan

**Comment by mondalaci** [comment]
Hi Stefan,

The mentioned scancodes don't look like USB scancodes. Please explain where did you get them from, and what you're trying to achieve in terms of shortcuts.

**Comment by mondalaci** [comment]
Closing due to the lack of replies. Feel free to follow up regardless.
