### ISSUE TITLE
Firmware update failed from 8.9.3 to 8.10.1 on Surface Book 2

### ISSUE THREAD

**Issue by robert-blip** [UltimateHackingKeyboard/agent#1325]
1. Start agent
2. Go to _Firmware_
3. Click on _Flash firmware 8.10.1 (bundled with Agent)_

![image](https://user-images.githubusercontent.com/66017623/90022626-49408800-dca2-11ea-8877-ba712edd0b09.png)

Not sure, but maybe Agent is not waiting long enough. When reenumerating, I can see a Windows message saying Configuring Bootloader. Then, Agent says it is not able to write. While the 'USB found' sound did not yet play.

When updating my Garmin watch, first the USB disconnect sound is played, then a USB connect sound is played after which the connection is finally made. This process takes some time. More than the amount of time that Agent is waiting. Of course this is a very differernt device, but you never know. :-)

Log:
Start flashing firmware
Agent version: 1.5.1
Device right firmware version: 8.9.3
Device left firmware version: 8.9.3
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.10.1
[UhkOperations] Operating system: Windows_NT 10.0.18363 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:32424)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:43:1740)"}
[UhkHidDevice] Transfer error:  Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:30188)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29942
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29921)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:30188)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1683)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29942
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29921)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1938
[DeviceService] start poll UHK Device
Cannot write to HID device

**Comment by mondalaci** [comment]
Did you retry the firmware update process multiple times? Perhaps Windows installs the driver after the first attempt and subsequent attempts succeed.

**Comment by robert-blip** [comment]
Yes, I did. I think around 7 or 8 times.
I was a bit carefull though as previously only one half was updated when re-trying multiple times. Of course, I do not want to brick the device and need difficult physical connections or additional software etcetera to unbrick it.

**Comment by mondalaci** [comment]
We will try to make an Agent build soon with increased bootloader timeout hoping to fix this issue. I'll follow up.

**Comment by mondalaci** [comment]
Please install the newly released Agent 1.5.2, then run the following commands in the terminal:

```
"UHK Agent.exe" --reenumerate-and-exit=bootloader,100000
"UHK Agent.exe" --reenumerate-and-exit=buspal,100000
```

Please save the output of the above commands to separate files and attach them. If everything goes as planned, Windows will install the device drivers required for the firmware update.

After running the above commands, execute Agent without any arguments as usual, then retry the firmware update.

**Comment by Fetz** [comment]
Hi I have the same issue, I tried to run those commands in the powershell terminal and it fails:
```
At line:1 char:19
+ "UHK Agent.exe" --reenumerate-and-exit=bootloader,100000
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'reenumerate-and-exit=bootloader' in expression or statement.
At line:1 char:50
+ "UHK Agent.exe" --reenumerate-and-exit=bootloader,100000
+                                                  ~
Missing argument in parameter list.
At line:1 char:1
+ "UHK Agent.exe" --reenumerate-and-exit=bootloader,100000
+ ~~~~~~~~~~~~~~~
The '--' operator works only on variables or on properties.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by mondalaci** [comment]
@ert78gb Please take a look at this.

**Comment by robert-blip** [comment]
Same here:
![image](https://user-images.githubusercontent.com/66017623/91483173-cec55a00-e896-11ea-9d06-620f04858fce.png)

**Comment by ert78gb** [comment]
The correct PowerShell commands

`Start-Process -FilePath "$env:LOCALAPPDATA\Programs\uhk-agent\UHK Agent.exe" -Args "-P --reenumerate-and-exit=bootloader,100000" -RedirectStandardError uhk-reenumerate-bootloader-err.log -RedirectStandardOutput uhk-reenumerate-bootloader-out.log -Wait`

`Start-Process -FilePath "$env:LOCALAPPDATA\Programs\uhk-agent\UHK Agent.exe" -Args "-P --reenumerate-and-exit=buspal,100000" -RedirectStandardError uhk-reenumerate-buspal-err.log -RedirectStandardOutput uhk-reenumerate-buspal-out.log -Wait`

These commands will write nothing to the output. Please be patient for 2.5 minutes.
Before you run these commands please unplug and plug your UHK.
After each command finished please unplug and plug your UHK again.
These commands will generate the following files in the working directory:
- uhk-reenumerate-bootloader-err.log
- uhk-reenumerate-bootloader-out.log
- uhk-reenumerate-buspal-err.log
- uhk-reenumerate-buspal-out.log

Please send us these files.

**Comment by robert-blip** [comment]
Hi,

Great that you are working on this issue!

Just ran the commands. First one seems to run OK. The second command exited quickly (later the USB ready message was reported by Windows 10).

Attached the files. GitHub wouldn't let me upload empty files, so the error logs are not there.

Kind regards,
Robert

[uhk-reenumerate-bootloader-out.log](https://github.com/UltimateHackingKeyboard/agent/files/5140519/uhk-reenumerate-bootloader-out.log)

[uhk-reenumerate-buspal-out.log](https://github.com/UltimateHackingKeyboard/agent/files/5140518/uhk-reenumerate-buspal-out.log)

**Comment by mondalaci** [comment]
Are you able to update the firmware in Agent now?

**Comment by robert-blip** [comment]
Not yet:
`Start flashing firmware
Agent version: 1.5.2
Device right firmware version: 8.9.3
Device left firmware version: 8.9.3
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
New firmware version: 8.10.1
[UhkOperations] Operating system: Windows_NT 10.0.19041 x64
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[DeviceService] updateFirmware error {"message":"Cannot write to HID device","stack":"Error: Cannot write to HID device\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:100:32386)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\rober\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:43:1759)"}
[UhkHidDevice] Transfer error:  Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:30187)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1957
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1702)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29941
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29920)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1957
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:30187)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1957
    at new Promise (<anonymous>)
    at Object.l [as __awaiter] (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1702)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29941
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:100:29920)
    at Generator.next (<anonymous>)
    at C:\Users\rober\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:43:1957
[DeviceService] start poll UHK Device
Cannot write to HID device
`

**Comment by robert-blip** [comment]
Note that the buspal command errored out without writing to the error log, see the normal log.

**Comment by Fetz** [comment]
The second command was running for more than 5 minutes so I interrupted but this is what it generated:

[uhk-reenumerate-bootloader-out.log](https://github.com/UltimateHackingKeyboard/agent/files/5143631/uhk-reenumerate-bootloader-out.log)
[uhk-reenumerate-buspal-out.log](https://github.com/UltimateHackingKeyboard/agent/files/5143632/uhk-reenumerate-buspal-out.log)

the files with this format `*-err.log` they were empty so I couldn't upload here. I tried as well to run the firmware update and I got as well the same error.

**Comment by ert78gb** [comment]
Thank you for helping us investigate the issue.

Could you save the changed user configuration to the keyboard?

**Comment by robert-blip** [comment]
> 
> 
> Thank you for helping us investigate the issue.
> 
> Could you save the changed user configuration to the keyboard?

Who do you ask? Fetz or me?
I don't recall changing anything. I connect the keyboard, start agent and try to update. Or is it something changed in the past?

**Comment by ert78gb** [comment]
I am asking it from both of you.

Please do the following test.
0. Close the Agent if running
1. Unplug and Plug your UHK
2. Change the User configuration
  - select your default keymap
  - change 'A' keypress action to 'B' keypress action
3. Click on the `Save to keyboard` button that appairing on the bottom left side on the screen.

Is it working without any error? 
If the save works then you can revert the changes.

**Comment by robert-blip** [comment]
Yes, no issues.
Pressing on A now presents a B on the screen.

**Comment by ert78gb** [comment]
thx @robert-blip .

It proves the communication between the Agent and UHK is working.
We have to fix the firmware issue only. I have an idea coming back soon

**Comment by ert78gb** [comment]
@robert-blip @Fetz I just now released the 1.5.3 version that maybe fix the issue. Cloud you try it?

**Comment by robert-blip** [comment]
Hi @ert78gb ,

Installed 1.5.3
Started Agent
Connected UHK (halves connected / closed)
Ran update at around 2313.
Errored out - display on UHK turned off
Restarting agent says firmware 0.0.0 on left side and 8.10.1 on right side.
Reconnecting UHK - both sides 8.10.1

Executed again at around 2315 (somehow I was expecting a message saying firmware is already up to date). But same behavior as mentioned above. UHK is working! Nice!

Can you tell from the log files whether the left side is really OK?

[uhk 1.5.3 20200828 2313.log](https://github.com/UltimateHackingKeyboard/agent/files/5144243/uhk.1.5.3.20200828.2313.log)

[uhk 1.5.3 20200828 2315.log](https://github.com/UltimateHackingKeyboard/agent/files/5144244/uhk.1.5.3.20200828.2315.log)

**Comment by robert-blip** [comment]
Hi, I just updated my 2nd UHK (halves disconnected, also from 8.9.3):
![UHK update](https://user-images.githubusercontent.com/66017623/91633844-076e4c00-e9db-11ea-9e4b-b3e4a666754d.png)

Same behavior. At the end 8.10.1 is shown for both sides!! Great!!

Left side did log some errors though, attached the file:
[uhk 1.5.3 2nd keyboard 20200829 1128.log](https://github.com/UltimateHackingKeyboard/agent/files/5145011/uhk.1.5.3.2nd.keyboard.20200829.1128.log)

**Comment by ert78gb** [comment]
The SurfaceBook handles very weirdly the "restart command" of the keyboard. The hardware/OS just "remove" the device before successfully delivery the response of the "restart command". I will implement this special case this weekend.

I am happy you could updated the latest firmware.

**Comment by ert78gb** [comment]
@robert-blip @Fetz I just now released the 1.5.4 version that maybe fix last part of the left side firmware upgrade. Could you try it?

No problem the firmware version of your keyboard is the latest.

**Comment by robert-blip** [comment]
Hi @ert78gb,

Perfect!

![image](https://user-images.githubusercontent.com/66017623/91659261-6ce73900-eabe-11ea-9b37-03f422512d14.png)

**Comment by mondalaci** [comment]
Looks like this issue has been fixed, so I'm closing this issue. Surface Book 2 is really weird when it comes to USB, and this is the best fix we can offer for now.
