### ISSUE TITLE
two-column display for mouse speed sometimes ends up mis-aligned

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#1337]
In agent 1.5.2 the mouse speed page was changed to a two-column layout.

At certain window widths, the text to the right of the sliders becomes word-wrapped, which changes the height of the whole element. This leads to mis-aligned rows (the rows in the left and right columns using different height).

Wouldn't you want to change this to a proper table, or find some other ways to keep the rows of both columns aligned?

See screenshot:

![image](https://user-images.githubusercontent.com/591785/91540435-14c40180-e91b-11ea-95f1-b954469fe1c7.png)

**Comment by mondalaci** [comment]
Thanks for the heads-up! Implementing this responsive layout with a table would result in redundant markup, but we'll give a shot to `white-space: nowrap` CSS.
