### ISSUE TITLE
Feature Request: Allow Secondary Mode Activation After Double-Tap Mode Activation

### ISSUE THREAD

**Issue by NickDaly** [UltimateHackingKeyboard/agent#1339]
**Feature Request:** Allow Secondary Mode Activation After Double-Tap Mode Activation

**Agent:** 1.5.4
**Firmware:** 8.5.3

**Summary:** It would be nice if the UHK supported activating a secondary-mode by pressing a mode-switch key after enabling a mode with a double-tap.

**Rationale:** For example, I find myself locking (double-tapping) mouse-mode quite frequently because my work tools are extremely anti-keyboard.  In mouse-mode, I have the number keys bound to numbers because that's the common use case.  This setup makes quitting a program (via Alt+F4) cumbersome.  Typing Alt+F4 while mouse-mode is locked requires double-tapping mouse-mode to disable it, then pressing the mod-mode key and Alt+4, and then double-tapping back into mouse-mode.

**Solution:** It would be nice if a locked mouse-mode would temporary give way to mod-mode while I pressed the mod-mode button.  Then, pressing Alt+F4 during mouse-mode would simply require pressing Alt+Mod+4.  Since the layer-switch buttons are currently disabled while a non-default layer is locked, there shouldn't be any possible key conflicts.

Thank you for your time and all your hard work!

**Comment by mondalaci** [comment]
Hi there! Although we don't plan to support, this feature, give a shot to [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) which likely supports it.
