### ISSUE TITLE
ISO key not mapped correctly (swedish keyboard)

### ISSUE THREAD

**Issue by cyberw** [UltimateHackingKeyboard/agent#1352]
On my swedish Macbook Pro, my ISO key is labeled:

```
> (with shift)
< (without)
```

But my UHK ISO key (mapped to `| ISO`) outputs:

```
° (with shift)
§ (without)
```

I have tried other settings, but there is nothing I can select that matches `< >`

**Comment by mondalaci** [comment]
The `| ISO` scancode of the UHK emits the standard ISO key scancode. Please use another ISO USB keyboard with your Macbook Pro, and pressing its ISO key should result in the same character. Your Mac OS layout must map the ISO key to `§`, `°`.

I'm closing this issue, but feel free to follow up.

**Comment by cyberw** [comment]
I tried it, you are right. I'll dig into it, thanks!

**Comment by cyberw** [comment]
Any ideas @mondalaci ?

**Comment by cyberw** [comment]
I guess I should note that this was not a problem earlier, but I'm not sure what might have changed...

**Comment by cyberw** [comment]
Aha! Nuking /Library/Preferences/com.apple.keyboardtype.plist and then restarting helped! (as suggested by some ticket on SO). Probably a bug/corrupt file in macos.
