### ISSUE TITLE
Tie mouse settings to a keymap

### ISSUE THREAD

**Issue by trueneu** [UltimateHackingKeyboard/agent#1353]
Hello!

That's probably a strange usecase, but still -

I'm using 3 different keymaps for 3 different OSes, each with their own mouse speed and acceleration settings. It may be just me, but it's far easier for me to fine-tune UHK's Mouse speed settings for each OS than to converge mouse settings between Windows, Linux and macOS so the pointer behaves more or less the same. It would be great if mouse settings could be set up independently for each keymap.

I can think of another usecase - if different mouse settings were used for different workflows, e.g. everyday settings and drawing stuff settings (which would probably benefit from lower base speed, for example).

What do you think?

**Comment by mondalaci** [comment]
Hi there!

It's not just you. I'm closing this issue in favor of https://github.com/UltimateHackingKeyboard/firmware/issues/300
