### ISSUE TITLE
Macro that toggles layer

### ISSUE THREAD

**Issue by itainoam** [UltimateHackingKeyboard/agent#1358]
Hi there!

I'd like to have a macro that toggles the mouse layer. Use cases:

1. A mouse click that turns off mouse mode. Useful when clicking on input fields.
2. A key that focuses on the address bar and then turns off mouse mode so you can enter the desired url

Is it now possible?

Thanks so much!

**Comment by mondalaci** [comment]
Hi @itainoam!

This feature is not supported by the official UHK firmware, but chances are https://github.com/kareltucek/firmware supports it, so give it a try.

**Comment by kareltucek** [comment]
Yes, the firmware should do the trick, however, interoperability of the standard and the extended layer mechanism is somewhat limited.

Long story short, you might need to change your standard mouse-layer controls to the macro-driven ones too. (Still, you are welcome to report any findings in the referenced repository.)
