### ISSUE TITLE
Not enough flexibility for linux magic keys. A better macro mechanism is required?

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1359]
Hi,

I like the keyboard, I've ordered two for my small company and hope to order more.

There are several things which may/should be improved though.

For example, there is no way to enter linux magic key sequences (`alt+prtscr+letters`) with default keyboard configuration. And in general I would need to map/remap too many keys on "mod" or "fn" layer" to make it work. Also these combinations are just hard to press, especially when the keyboard is split.

For now I've solved that by creating some macros bound to "fn" layer, though I'm wondering if it may be possible to implement some kind of a high-priority mapping mechanism which would listen for specific key combinations and override any layer-specific mapping in case it detects such combination?

E.g. I want to be able to say that "Mod+PrtScr+Alt+S" should always be considered as exactly that combination even if I have something bound to Mod+S or Mod+Alt+S.

**Comment by mondalaci** [comment]
Hi, and thanks for your great support!

Please take a look at [Karel's UHK firmware fork](https://github.com/kareltucek/firmware), which allows for many advanced features.

I'm closing this issue now, but feel free to follow up.

**Comment by pshirshov** [comment]
Probably it may be possible to achieve working magic keys with that firmware, though it would assume a very fair amount of work and the UX is dismal.

I think it's still a good idea to consider fixing/improving it in the core, what a hacking keyboard does not support these linux shenanigans?..

**Comment by kareltucek** [comment]
Regarding the firmware, I can imagine `ifShortcut`, `ifGesture`, or nested layer holds/toggles being useful (e.g., a macro somewhere on mod layer which would `pressKey printScreen; holdLayer base; releaseKey printScreen` sounds quite simple). 

Regarding vanilla firmware - did you know that a pressed key retains its original "press" role until released, even if its layer has been released in the meantime? This means that you can `press mod; press prtscr; release mod; press  alt; press S`. I think it should make it easier.

> I think it's still a good idea to consider fixing/improving it in the core

Just as a mental exercise - do you have any specific ideas/proposals which would work well with Agent UI and with vanilla firmware's features?

**Comment by mondalaci** [comment]
@pshirshov The way I see it, it's not about fixing/improving the core but adding countless niche features that very few use, yet these features would complicate the UI very much at the expense of everybody and for the benefit of few. There is no perfect solution, but I think Karel's solution comes close.

**Comment by pshirshov** [comment]
> Just as a mental exercise - do you have any specific ideas/proposals which would work well with Agent UI and with vanilla firmware's features?

Yes, I have some ideas. Internally I would add a trie containing sequences of high-priority commands and verify my inputs against that trie before any other logic. In case my lookup finished at a leaf with a configured action it should be executed instead of regular rules.

The Agent UI may contain an additional tab, something like "high-priority combinations" allowing you to type a sequence of keystrokes and map a command/action to it.

> but adding countless niche features that very few use

I'm not sure if magic key support is a niche feature. I guess that many people may need to type these combinations on regular basis.

**Comment by kareltucek** [comment]
> Yes, I have some ideas. Internally I would add a trie containing scancodes of the sequences of high-priority commands and verify my inputs against that trie before any other logic. In case my lookup finished at a leaf with a configured action it should be executed instead of regular rules.

So when you are in the middle of the lookup, what do you do? Are you sending the already-pressed scancodes, or are you waiting for further input?

> Usually you need sequences of magic keys. Typical input is something like s-s-u-u-s-s-b. So that wouldn't actually make things that much easier.

Does a sequence of magic keys require prtscr to be released? If yes, then you've got a point.

**Comment by pshirshov** [comment]
> So when you are in the middle of the lookup, what do you do? Are you sending the already-pressed scancodes, or are you waiting for further input?

In case my sequence continues to be a potential match the keyboard should wait and don't send anything.

> Does a sequence of magic keys require prtscr to be released? If yes, then you've got a point.

No. You have to hold prtscr. https://en.wikipedia.org/wiki/Magic_SysRq_key

**Comment by pshirshov** [comment]
I guess what may actually work is to use your key cluster module to input the required modifers without switching layers.

And it's a real shame that you have just the 3-key version.

**Comment by kareltucek** [comment]
> In case my sequence continues to be a potential match the keyboard should wait and don't send anything.

So when the sequence continues to be a potential match, but the user's intention is different, then you "randomly" stop responding? What if the user wants to alt+click-drag with his mouse?

I mean, the answer is "maybe yes, that's what the user wants", but doing this as a global feature in the way you describe will lead to a lot of nondeterminism in keyboard's behaviour, which will be unwanted in most cases. And the usefulness of it is very limited, as scenarios as yours can be (and should be) circumvented by better organization of the mapping, or by implementing some other general but less-niche features (such as the nested layer switching).

> No. You have to hold prtscr. https://en.wikipedia.org/wiki/Magic_SysRq_key

Then where is the problem? It suffices to press the hard-to-reach-prtscr once and then continue to hold it through the entire sequence. If you place it at a side of your keyboard to hold with the pinky, then it is a piece of cake: `press mod; press prtscr; release mod; press alt; tap S; tap S; tap U; tap U ...`

Or you can easily sacrifice one of your layer switchers for such important key. (I find myself never use right GUI or right FN. Actually I never use left FN either.)
