### ISSUE TITLE
ANSI and ISO layouts

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#136]
The ANSI vs the ISO layout must be displayed according to the UHK version connected. The UHK will expose [this information](https://github.com/UltimateHackingKeyboard/agent/blob/1063cb2e6eaee9c4a8c8b9abcd2e1f509c34d367/usb/read-iso-jumper.js) via USB.

**Comment by NejcZdovc** [comment]
Blocked by #152

**Comment by NejcZdovc** [comment]
Blocked by #152

**Comment by mondalaci** [comment]
When implementing this issue, please note that the ids of the keys in the new SVG files has changed. Previously, the numbering of the keys was purely incremental, but now there are missing elements here and there. This is intentional, as the ids of the keys will be in sync with the keyboard matrices this way. The firmware will be able to map the keys 1:1, instead of [having to remap the keys](https://github.com/UltimateHackingKeyboard/firmware/pull/29/files#diff-38daa16261043ce68cdd4b307686febeR53) according to the shape of the keyboard matrices. The firmware should have no such knowledge built in. Admittedly, this approach does waste a little space, but given the vast hardware resources available, simplicity should prevail.

Another thing to note is that the size of the key action arrays should be based on the `keyCount` fields of the [uhk60-left-half/module.json](https://github.com/UltimateHackingKeyboard/agent/blob/master/modules/uhk60-left-half/module.json) and [uhk60-right-half/module.json](https://github.com/UltimateHackingKeyboard/agent/blob/master/modules/uhk60-right-half/module.json) files respectively.
