### ISSUE TITLE
flatpak / snapd packages

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1361]
Hi!

I think it would be very nice to have the Agent available in flatpak (and, maybe, snapd) so the user may install it quick and easy.

Flatpak is very popular now, easy to use and supported by almost any linux distro. snapd covers all the ubuntu flavors. 

Usually it's very easy to package an app for both of these systems. So, believe it should be a relatively simple job to create a Github Action publishing every release tag to flathub.

Here is an example of an electron app packed for flathub: https://github.com/flathub/com.bitwarden.desktop
Just 3 simple files, less than 100 lines in total.

**Comment by mondalaci** [comment]
Hi there!

I'm sorry, but we won't support snaps given our experience regarding #709.

Whichever package format is used, Agent would have to be able to check if it's running in a non-AppImage environment. If so, Agent's auto-update mechanism would have to be disabled to not interfere with the auto-update mechanism of the package system used.

Given our limited resources, past experience, and the general lack of requests, we can't allocate resources for this issue.

**Comment by pshirshov** [comment]
I understand your frustration with Snapd, though FlatPak is lot simpler to use and lot more reliable (IMO).

I hope that you may reconsider your decision at one point. Regarding lack of requests - I've linked a NixOS issue which, probably, wouldn't arise if there would be a FlatPak image available.
