### ISSUE TITLE
Support Fn modifier on macOS / MacBook

### ISSUE THREAD

**Issue by neko-kai** [UltimateHackingKeyboard/agent#1366]
Currently the knowledge base states that `Fn` keys on laptops are special / internal to laptops and cannot be sent over USB as normal keys/modifiers (https://ultimatehackingkeyboard.com/knowledgebase/how-can-i-map-the-fn-key-of-my-laptop-to-the-uhk)

However, this does not seem to apply to MacBook's `Fn` key, checking with the [`Key Codes`](https://apps.apple.com/us/app/key-codes/id414568915?mt=12) app, macbook's Fn seems to be a Normal Modifier, like the others and is received by the OS and processed as a normal key. Here is the data from a key down press of Fn from the Key Codes app:

<img width="840" alt="Screenshot 2020-10-28 at 17 22 00" src="https://user-images.githubusercontent.com/450507/97472802-25581e80-1942-11eb-92fa-957f37005496.png">

Pressing the Fn key applies `0x800000` mask to MODMASK. Also Apple's standalone keyboards are also capable of sending Fn keys. 
I cannot be absolutely sure how all that works and whether a USB keyboard can do the same thing - or if Apple hardware sends some kind of proprietary signal - but at least from inside the OS, the Fn key looks like a normal modifier, and perhaps could be sent by UHK keyboard to support some Macos Fn-specific hotkeys or remap them to another layer.

Thanks!

**Comment by mondalaci** [comment]
@neko-kai Thanks for the heads-up!

@xxxajk @Lauszus Any insights about whether/how Mac Fn is exposed via USB?

**Comment by Lauszus** [comment]
@mondalaci no not really. I guess you have tried to check what other keyboard do via Wireshark?

**Comment by mondalaci** [comment]
@Lauszus I don't have time to do protocol debugging these days, so I'd much rather rely on you, guys. But according to your answer, this is not trivial even for you, so I feel less inept. :)

**Comment by Lauszus** [comment]
@mondalaci haha I might take a quick look this weekend ;)

**Comment by neko-kai** [comment]
Hmm, Karabiner Elements reports a different keycode for Fn — `65538`, not `65535`.
Karabiner can also be used to workaround for this issue since it can remap keys — you may assign a rare key such as Scroll Lock to UHK's Fn then remap it to Mac Fn using Karabiner.

<img width="550" alt="Screenshot 2020-12-10 at 18 31 59" src="https://user-images.githubusercontent.com/450507/101814656-59645900-3b16-11eb-9769-e618e4068c6f.png">

**Comment by dustinpaluch** [comment]
I'm interested in support for this as well, mostly so that I don't lose the ability to control my screen's brightness via fn + f1/f2.

**Comment by mondalaci** [comment]
@benedekkupper Any ideas whether this feature is feasible?

**Comment by dustinpaluch** [comment]
I just realized you already have volume control and media keys by default on the fn layer. I would be just as happy with some screen brightness bindings there. Actually supporting the mac keyboard fn key is not that important to me in that case.

**Comment by benedekkupper** [comment]
There is currently (since 2018) HID usage support for sending the actual state of the Fn key, just like Shift, Alt, etc, see [this HUTRR](https://www.usb.org/sites/default/files/hutrr73_-_fn_key_and_keyboard_backlight_brightness_0.pdf). Whether or not MacOS is using this usage remains to be seen, I don't have the setup to analyze this.

The other approach is adding the functionality to the custom Fn layer as it's done for volume and playback. We would need to collect all the use-cases. Screen brightness is already defined by [HID usage since 2012](https://www.usb.org/sites/default/files/hutrr41_0.pdf), so that should work.

**Comment by mondalaci** [comment]
@benedekkupper Thanks for the great findings! I didn't know about these scancodes. I've tested them using the [arbitrary scancodes feature of Agent](https://ultimatehackingkeyboard.com/blog/2021/10/31/production-progress-spare-parts-bonanza-new-agent-release#new-agent-features):

![image](https://user-images.githubusercontent.com/300402/147793691-4cfdf398-d8bd-45da-835c-516b017b848e.png)

Only M111 and M112 worked, but they worked both on a Windows 10 laptop and a MacBook Pro. Chances are they'd work on Linux, too, but I don't have a Linux laptop to test them, only a Linux Mint desktop on which they don't seem to trigger any action.

We'll add two new menu items named "Decrease Screen Brightness" (M112) and "Increase Screen Brightness" (M111) in this order after "History Forward". If they don't fit horizontally, let's call them rather "Screen brightness -" and "Screen brightness +". Let's use the sunset and sunrise font awesome icons on the keys.

Let's not implement the native Fn scancode, as I'm sure users would confuse the UHK Fn layer and the native Fn key.

**Comment by neko-kai** [comment]
@mondalaci 
> Let's not implement the native Fn scancode, as I'm sure users would confuse the UHK Fn layer and the native Fn key.

Confusion is not inevitable, you could call it 'Native Fn', or better, 'Laptop Fn', I think that would be unambiguous enough.

**Comment by mondalaci** [comment]
@neko-kai I rather don't want to get native Fn exposed for the time being. I'll reconsider if we still get such requests after exposing the screen brightness scancodes.

**Comment by neko-kai** [comment]
@mondalaci 
Well, originally I opened this issue because I needed Fn for a macOS window manager that uses Fn modifier by default ([Swish](https://highlyopinionated.co/swish/)), so that at least wasn't about screen brightness.

**Comment by benedekkupper** [comment]
According to the [Linux kernel](https://elixir.bootlin.com/linux/latest/C/ident/apple_input_mapping), the Fn key has at least three different possible known HID usage IDs, 0x00ff0003, 0xff000003 and 0xff010003. As these are custom IDs, they are interpreted differently by the OS depending on the USB device's VID:PID, making it unfeasible to properly implement in the firmware.

I think it would be more reasonable to ask Swish and any other application authors to change their key mapping to a button that is uniformly present on a wide array of stock keyboards instead.

**Comment by mondalaci** [comment]
Given the above, I'm closing this issue and may reconsider later.
