### ISSUE TITLE
Move the mouse diagonally

### ISSUE THREAD

**Issue by aceofknaves** [UltimateHackingKeyboard/agent#1368]
Hello,

Would it be possible to add bindings to move the mouse diagonally? The agent doesn't seem to support this. I am able to achieve the effect in practice by holding the "mouse" modifier and two distinct directional keys (mouse + up + left). Is this something that is supported by the firmware and could be added to the agent?

**Comment by mondalaci** [comment]
Hi there,

The reason Agent doesn't support this feature is that it wasn't requested yet. As a rule of thumb, we only add features that are popular to keep Agent simple.

@kareltucek Does your firmware support this feature via macros?

I'm closing this issue, but feel free to follow up regardless.

**Comment by kareltucek** [comment]
> @kareltucek Does your firmware support this feature via macros?

Theoretically yes. In practice, I will have to look into it, since it seems to be broken atm. Will follow up later.

**Comment by kareltucek** [comment]
Alright, it seems I accidentally dropped the relevant hook during one of the bigger rebases. Anyway, it is fixed now, so feel free to try out https://github.com/kareltucek/firmware . 

This should do the trick:
```
$startMouse move up
$startMouse move left
$delayUntilRelease
$stopMouse move left
$stopMouse move up
```
