### ISSUE TITLE
KERNEL_SECURITY_CHECK_FAILURE on Win10 + AMD Ryzen 9 config

### ISSUE THREAD

**Issue by gorrt** [UltimateHackingKeyboard/agent#1369]
Firmware: 8.9.3
UHK Agent: 1.4.5 (1.5.5 too)
OS: Windows 10 Pro, ver. 2004
Motherboard: ASUS PRIME X570-PRO
BIOS: 2606 (release 08/13/2020)
CPU: AMD Ryzen 9 3950X
Stop code: KERNEL_SECURITY_CHECK_FAILURE, DPC_WATCHDOG_VIOLATION

The UHK Agent cannot recognize the device and after that the blue death was happened. Always.
With another USB keyboard the config is stable, and UHK is working properly on my other (Intel based) workstation. It's weird.

**Comment by mondalaci** [comment]
This is very strange, and we haven't yet encountered this issue yet.

Please connect your UHK via a USB hub, then directly to your PC, and try every one of its USB ports.

**Comment by laxu** [comment]
Never seen this on my Ryzen 7 3700X using Gigabyte X570 ITX. I have mine connected with a CableMatters USB switch/hub and have had it connected directly to mobo USB port as well. 

My UHK uses the latest keyboard firmware version though so it might be worth trying to upgrade it and see if the problem goes away.

**Comment by mondalaci** [comment]
Closing this issue due to the lack of replies, but feel free to follow up anytime.
