### ISSUE TITLE
Type special unicode characters

### ISSUE THREAD

**Issue by sourabh2311** [UltimateHackingKeyboard/agent#1372]
Consider ■ [U+25A0], I would like to have a key in my "Fn" layer type this character. But I can't paste this under "New macro action"->"Type text". 
I can have macro type "U+25A0" but then I would have to as well press "Alt+x" to process this.

**Comment by mondalaci** [comment]
USB keyboards don't send characters, but scancodes. Then the OS maps the scancodes to characters. Unicode characters are meant to be invoked via OS-specific Alt codes. Please see https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk
