### ISSUE TITLE
UI glitches

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1379]
Probably as a result of the recent Bootstrap upgrade, there are some UI glitches. Some of them are bad enough that I can't release a new Agent version before getting them fixed. Below are all of the issues I could find.

1. Sometimes, clicking on the first (or possibly other) macro action of a macro messes up the UI:

![image](https://user-images.githubusercontent.com/300402/99887173-63471a80-2c42-11eb-9adb-d0f0916f188b.png)

2. Level 1 or level 2 macro action link buttons shouldn't ever be wrapped:

![image](https://user-images.githubusercontent.com/300402/99887206-a608f280-2c42-11eb-80de-4c4782a39a38.png)

3. Regarding the previous screenshot, the modifier tooltip icon shouldn't be wrapped if not necessary.
4. The tooltip of the modifier row should have the same amount of space leftward as the other tooltip icons. The space of the bottom tooltip should be a bit more, too:

![image](https://user-images.githubusercontent.com/300402/99887240-fbdd9a80-2c42-11eb-86d4-dda40e69845f.png)

5. There's excess space above and below "Are you sure?":

![image](https://user-images.githubusercontent.com/300402/99887302-760e1f00-2c43-11eb-9fc4-058f4cb65f23.png)

6. Too much bottom padding:

![image](https://user-images.githubusercontent.com/300402/99887435-b28e4a80-2c44-11eb-900c-675c2ff880e3.png)

You're welcome to fix these issues, @laxu or @ert78gb. Whoever starts to fix it, please comment here first.

**Comment by ert78gb** [comment]
I pick up this issue

**Comment by mondalaci** [comment]
7. The macro UI is sometimes cut off

![image](https://user-images.githubusercontent.com/300402/99936407-5d952600-2d63-11eb-9212-2dfdb7696d9c.png)

8. When clicking on the macro action, often it doesn't get opened, and only the scrollbar shows up.

![image](https://user-images.githubusercontent.com/300402/99936623-deecb880-2d63-11eb-98e3-940cdb8f2182.png)
