### ISSUE TITLE
Some keys are not working

### ISSUE THREAD

**Issue by Lapis55** [UltimateHackingKeyboard/agent#1380]
'6','t','g','b' keys in my UHK happened to be not working.
To fix the issue, I tried firmware update but failed.
I also disconnect and reconnect UHK several times, but the situation doesn't change.

How should I do?

**Comment by mondalaci** [comment]
Hi, and sorry to hear about this issue!

This is a [hardware issue](https://ultimatehackingkeyboard.com/repair-and-modding/esd-protection-guide). Please [contact us here](https://ultimatehackingkeyboard.com/contact-us), and we'll repair your UHK.
