### ISSUE TITLE
Collapsing items in sidebar doesn't work

### ISSUE THREAD

**Issue by Jopie01** [UltimateHackingKeyboard/agent#1386]
I've downloaded the most recent version of the agent (1.5.7) and came across a weird thing in the sidebar on the left.

You can collapse different items like 'Device', 'Keymaps' or 'Marcos'. You hover over them and you see a small up or down icon. When you click on that icon, that particular item will be opened or closed.

However, when you close an item, the text belonging to that item will not go away, but stays there. The text of the other item is then flowing through it making things unreadable.

**Comment by mondalaci** [comment]
@Jopie01 Thanks for your report! I can clearly reproduce this issue.

@ert78gb Can you fix it quickly?

**Comment by ert78gb** [comment]
I am checking today
