### ISSUE TITLE
Key action popover positioning

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#139]
The popover should be positioned according to the related key.

**Comment by fjozsef** [comment]
Blocked by #56

**Comment by mondalaci** [comment]
I'd like to add an important point regarding the implementation of this issue.

We were thinking about positioning the popover above / below the choosen key depending on the space available above / below the key. I think it would be more intuitive for the user if we always displayed the popover below the choosen key. The reasons being:

* The content of various tabs within the popover have very different height. If the popover was positioned above a key and the user wanted to switch between the tabs then the tab bar would move around vertically every time when the content of the new tab has different height than the content of the previous tab which would be very disturbing.
* The more consistent the behavior of the UI, the easier it is to interact with it. Always displaying the popover below the key is more consistent than displaying it above or below depending on the space available.

If the popover displayed is outside of the current viewport, then we should smooth-scroll downwards until the whole popver fits into the viewport.
