### ISSUE TITLE
Side menu layout issues on hover

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1391]
Hovering over the Keymaps menu makes its submenus smaller by adding extra space rightward:

![image](https://user-images.githubusercontent.com/300402/100891836-fb9e9400-34b9-11eb-9f3b-94d53db8879d.png)

Hovering over the Macros menu results in the same behavior and it wraps the "Go to UHK site in browser" macro name:

![image](https://user-images.githubusercontent.com/300402/100891879-0822ec80-34ba-11eb-9707-6716fc36e389.png)

**Comment by ert78gb** [comment]
I can't reproduce this bug. I tried on Mac and Linux. Can you write the reproduction steps?
