### ISSUE TITLE
Sha512sum does not add up for UHK.Agent-1.5.8-linux-x86_64.AppImage

### ISSUE THREAD

**Issue by fa222ny** [UltimateHackingKeyboard/agent#1396]
Hey I was downloading the "UHK.Agent-1.5.8-linux-x86_64.AppImage", when checking the sha512 sum it does not match the checksum specified in the "latest-linux.yml" the sha512: LCGH/VzGVYZSqNkgy/eMVUYH2ce0fnC5n2mFtvWqth36gX4XGX8rw4Ky+FStsWFM8y7e5VuRKXBsb9wiDeCECw==

however when I run sha512sum on the file I get: 2c2187fd5cc6558652a8d920cbf78c554607d9c7b47e70b99f6985b6f5aab61dfa817e17197f2bc382b2f854adb1614cf32edee55b9129706c6fdc220de0840b, is there something wrong with the file?

**Comment by mondalaci** [comment]
I think the file should be fine, and this is probably an issue regarding the build process. @ert78gb will look into this soon.

**Comment by ert78gb** [comment]
Hello,

The electron builder uses the following hash calculation https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/util/hash.ts

Node uses OpenSSL behind the scenes.
The `openssl dgst -sha512 -hex UHK.Agent-1.5.8-linux-x86_64.AppImage` returns with the `2c2...40b` hash. It is the same as the `sha512sum` result.
The electron-builder uses the `openssl dgst -sha512 -binary UHK.Agent-1.5.8-linux-x86_64.AppImage | openssl enc  -A -base64` command.

**Comment by fa222ny** [comment]
Alright that explains it, thanks for the info.
