### ISSUE TITLE
Deleted macro shouldn't be present in the keymaps it was used

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#140]
1.: Assign your macro to a keymap
2. Delete that macro
3. The macro will be still assigned to the keymap which will throw errors.

**Comment by NejcZdovc** [comment]
Solved in #177

**Comment by mondalaci** [comment]
Why did you postpone this issue from version 0.8 to 0.9, @NejcZdovc? I'd like to make it our policy to always fix bugs before doing anything else.

**Comment by fjozsef** [comment]
It is not prosponed, see the current status on the right.

**Comment by mondalaci** [comment]
Thanks for the correction, @fjozsef. Sorry @NejcZdovc, looks like you actually moved this issue from 0.9 to 0.8 and not vice versa. The way GitHub displays this event is not intuitive.

**Comment by fjozsef** [comment]
e48fdea89d346823fd81a39d5f6a0f41ee1e6a10 reintroduced this bug.
