### ISSUE TITLE
Validate macro actions

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#141]
The Save button of Macro actions must be disabled in the following cases:

* Type text macro action: empty text field
* Key macro action: Scancode None and no modifiers selected
* Mouse action: Move pointer and Scroll: Any of the X, Y fields are empty
* Mouse action: Click and Hold and Release button: None of the buttons are pressed
* Delay: empty or zero delay field

**Comment by attilacsanyi** [comment]
I implemented all review comments. Thanks @ert78gb. Would you mind to check another time @mondalaci ;-)

**Comment by mondalaci** [comment]
Done in #395.
