### ISSUE TITLE
UHK left half is dead after firmware flash (firmware 0.0.0)

### ISSUE THREAD

**Issue by Peter-Odd** [UltimateHackingKeyboard/agent#1415]
I had firmware version 8.6.0 on both right and left devices.
My agent version was 1.5.1.
I pressed the 'Flash firmware' button (to version 8.10.1) and the device seemed to be flashed as it should (see screen shot). The left half was dead though (didn't register keypresses and the display was not lit).

The Agent GUI stated the left keyboard half ran firmware 0.0.0. Right half firmware 8.10.1.
The right side works as expected, but not the left one.
I tried to flash firmware once again, first keyboard halves splitted then joined, without success :(. 
This was done at a PC (Lenovo), first with the UHK connected via USB-hub, then connected directly to the computer.

I then connected it to another computer (mac). Same result when trying to flash firmware.
I more than love my UHK, and I really need it to work.

Please see attached logs; two files:
flash_firmware_first_try_on_pc.txt:
this log shows what happened when the left half became dead.

Also a red error message top right corner showed some information when trying to flash on pc, see attached image. 

flash_firmware_second_try_on_mac.txt:
this log shows what happened when trying to flash firmware on another computer.

[flash_firmware_first_try_on_pc.txt](https://github.com/UltimateHackingKeyboard/agent/files/5866950/flash_firmware_first_try_on_pc.txt)
[flash_firmware_second_try_on_mac.txt](https://github.com/UltimateHackingKeyboard/agent/files/5866952/flash_firmware_second_try_on_mac.txt)
![Untitled](https://user-images.githubusercontent.com/5655272/105714815-1e2eb580-5f1d-11eb-869f-6a1c9e8890c7.png)

**Comment by mondalaci** [comment]
@ert78gb Any ideas what gone wrong during the update? flash_firmware_first_try_on_pc.txt looks fine to me.

@Peter-Odd Reconnecting the left half should help. Please retry on multiple computers. If everything else fails, we'll recall and fix your UHK.

**Comment by Peter-Odd** [comment]
@mondalaci I have disconnected and reconnected the left half multiple times, both via the cable and without the cable. I will give it some more tries and test more computers. I will let you know shortly!
Thanks for the prompt reply!

@ert78gb no qualified ideas I'm afraid.. everything seemed ok except for the red error message top right.

**Comment by ert78gb** [comment]
@Peter-Odd The red error message is the app auto-updater error. The firmware upgrade is looks fine in the logs.
We can see more in the logs if you start the app with --log=all. Use the DEBUG=kboot* environment variable to log the USB communication.

The auto-updater started to download the new update in the background, but it would not break the firmware upgrade. Unfortunately there is no function to cancel the app update download process.

**Comment by ert78gb** [comment]
@Peter-Odd If you download the [1.5.7](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.5.7) and start the app update then this version also drop any error?

**Comment by Peter-Odd** [comment]
Will try tomorrow! Thanks

**Comment by Peter-Odd** [comment]
Hi again,
Great success! The UHK is now alive again, thank you guys! :)
**Solution:** I connected the UHK to another PC (hp this time). Latest Agent (1.5.8). Now firmware 8.10.2 on both left and right sides.
Now I can sleep again :)

**Comment by Peter-Odd** [comment]
If you're interested, here is the exteded log file (--log=all) on the PC that couldn't update the firmware. I had to abort the agent since it kept printing '13:15:16.885 > [UhkOperations] Try to connect to the LeftKeyboardHalf' forever as it seems.

[uhk_firmware-update_1.5.8_pc.txt](https://github.com/UltimateHackingKeyboard/agent/files/5873242/uhk_firmware-update_1.5.8_pc.txt)

**Comment by mondalaci** [comment]
@Peter-Odd So glad to hear! :)
