### ISSUE TITLE
Improvements to pending keyboard changes

### ISSUE THREAD

**Issue by krokofant** [UltimateHackingKeyboard/agent#1417]
- [ ] Discard all changes (So I don't have to restart Agent)
- [ ] Undo latest change
- [ ] Highlight keys that have unsaved changes
- [ ] Confirm window close when there are unsaved changes

I think the _discard all changes_ and _confirm window close_ are the easiest to implement.

#### Example of buttons (next to the current _Save to keyboard_ button)
![image](https://user-images.githubusercontent.com/5908498/105958208-9959ae00-607a-11eb-8ee7-46cd00885cda.png)

#### Example of highlight
![image](https://user-images.githubusercontent.com/5908498/105959161-d83c3380-607b-11eb-9b5b-173bb7b37647.png)

**Comment by mondalaci** [comment]
I understand your point of view, but I think the suggested UI elements are too heavy compared to the value they provide to most users. Especially considering that it's easy to restore any previously saved configurations under the Configurations menu.

Your last suggestion has merit, but nobody has complained about it yet, so let me reconsider it later.
