### ISSUE TITLE
[Regression] Keymap description not editable

### ISSUE THREAD

**Issue by krokofant** [UltimateHackingKeyboard/agent#1418]
Probably occurred after #1378 and the edit issue seems to have appeared before in #1000.

Can probably be fixed by adding back `position: relative;` to the `editable-text` https://github.com/UltimateHackingKeyboard/agent/blob/master/packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.scss

The svg overlays the description (as described in the old issue):
![image](https://user-images.githubusercontent.com/5908498/105965359-9911e080-6083-11eb-9a73-58a83a314acd.png)

___
I also noticed that the styles of the editable-text has broken css, but I can't find where it's set like this (`0: margin-top;`):
![image](https://user-images.githubusercontent.com/5908498/105964402-69aea400-6082-11eb-9e7c-15b03101c036.png)
```html
<editable-text _ngcontent-mji-c69="" placeholder="No description provided for this keymap." _nghost-mji-c68="" class="ng-tns-c69-4 ng-trigger ng-trigger-moveDescription ng-untouched ng-pristine ng-valid ng-star-inserted" style="margin-top:-6.5%;0:margin-top;margin-top:-6.5%;"><div _ngcontent-mji-c68="" class="text-center">
    <!---->

    <span _ngcontent-mji-c68="" class="editable ng-star-inserted" style="">
        <span _ngcontent-mji-c68="">QWERTY is the mother of all layouts. This is the PC version.</span>
    </span><!---->
</div>

<!---->
</editable-text>
```

**Comment by mondalaci** [comment]
@krokofant Thanks so much for reporting this! I can clearly reproduce this bug.

@ert78gb Please consider the suggested fix and make a PR.
