### ISSUE TITLE
Mapping key for long press

### ISSUE THREAD

**Issue by pwntester** [UltimateHackingKeyboard/agent#1434]
Hi, 

Im trying to map my L-Ctrl in the following way:
- when pressed along with other key behave as Ctrl modifier
- when single pressed behave as backspace
- when pressed and hold (but no other keys are pressed) behave as backspace

Is this even possible? I get the first two by using the `secondary role`, but if I keep it pressed to delete multiple chars, it doesnt do anything (probably sits there waiting for me to press another key)

Thanks

**Comment by mondalaci** [comment]
Hi there!

Your use case is the "Activate primary action" case of https://github.com/UltimateHackingKeyboard/agent/issues/792#issuecomment-626144108

@kareltucek Does your [firmware fork](https://github.com/kareltucek/firmware) support this use case, possibly on a per-key basis?

**Comment by kareltucek** [comment]
Not directly. There are some ways around however.

**Comment by pwntester** [comment]
@kareltucek Would lo e to hear about them!

**Comment by kareltucek** [comment]
I guess ths should work:
```
$ifSecondary ifInterrupted final holdKey LC-
$holdKey backspace
```
Except that `ifSecondary` uses a more advanced resolution strategy, which you might like or not.

More vanilla version would have to use active waiting, which would go something like:
```
$ifNotInterrupted ifNotPlaytime 300 goTo @0
$ifInterrupted final holdKey LC-
$holdKey backspace
```

**Comment by pwntester** [comment]
Thanks, both of them work, but for the secondary role I have to keep it pressed for a long time. So for example, when using it for `<Ctrl-C>` I have to keep both keys hold for some time, so when its finally handled, I end up entering multiple `<Ctrl-C>`.

**Comment by kareltucek** [comment]
Actually, you just need to hold the Ctrl for 50ms longer than the C. 

Anyway, I am quite bewildered about this, because actually quite many people finde the timeouts of this feature "extremely long", while I perceive them as "below the trashold which I can constiously distinguish".

**Comment by pwntester** [comment]
> With the second one, I need to press Ctrl for a little longer than I would like before pressing the second key. Is there a way to control the wait time in the second macro?

Actually, I think the one I have to hold longer than Im used to is the `c`. can that time be reduced?

**Comment by kareltucek** [comment]
> > With the second one, I need to press Ctrl for a little longer than I would like before pressing the second key. Is there a way to control the wait time in the second macro?
> 
> Actually, I think the one I have to hold longer than Im used to is the `c`. can that time be reduced?

Well, there are two ways to trigger secondary role with the `ifSecondary` condition. One is to hold the dual-role key for at least 350ms, while tapping another key within this interval. The other way is to release the second key at least 50ms before releasing the dual-role key. 

To mess with the timeouts, you can use `resolveSecondary` (see the README for more info). But actually there it is a feature. The `ifSecondary is designed to prevent writing interaction of alphanumeric keys. Since you are after a regular secondary role, the right way is probably to fix the other approach.

> With the first one, when I want to use the secondary role, I have to keep it pressed for a long time. So for example, when using it for <Ctrl-C> I have to keep press Ctrl then C and then keep them pressed for some time until they are handled. But then I got as many<Ctrl-C> as the time I was holding them together. Is there a way to improve it?


Mmmm I see the problem, but atm, I do not see any elegant solution. Sorry!

**Comment by mondalaci** [comment]
This is quite a niche use case, so we don't plan to implement it. I'm closing this issue, but feel free to continue the conversation regardless.
