### ISSUE TITLE
Saving to the EEPROM

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#145]
When the  user saves something in the agent, change will automatically be saved in the EEPROM. Limit of it is 1 000 000 writes. When you reach 500 000 writes user will be notified about it and option for disabling automatic save will be provided. There will also be a health bar which will display how many writes do you still have.

**Comment by TorC8** [comment]
I'm not sure how much of an issue this is.  If it auto-saves every time an individual key for a layer is set, then maybe.  If it is only on user "save keymap" command, then it's a non-issue, to the point the user will be dead and the electronics corroded past use before the million writes is hit.

To put some numbers to it, if it auto-saves every key set, then a user who makes 100 changes every day won't hit the 1 000 000 save mark for more than 27 years.

A more likely case of a power user tweaking who tweaks a few dozen keys a week with major setting of a couple hundred keys every couple months will get three and a quarter centuries out of the EEPROM.

**Comment by mondalaci** [comment]
@TorC8 Great points, and your math is correct. I think we probably worry too much about EEPROM wear given these numbers, and we shouldn't make extra effort in this respect.

I'd rather make auto-save dependent on the user experience. It should take no more than a second (and usually a lot less time) for the configuration to be transferred to the UHK. We should implement it and see how it performs. If it will be as seemless as I believe it will be, then we can implement it and provide no alternative options.

**Comment by TorC8** [comment]
@mondalaci Without having had the chance to really play with Agent yet, I'm inclined to think transferring to the keyboard on every key adjust is less than wise, unless it goes to a staging area, and only gets applied on user command.  I'm not sure the latter would be all that different from saving to computer and uploading to KBD on command.  It also sidesteps the issue of the FW worrying about saving changes to current keymap without applying them to avoid an unusable keyboard.  I know I would have to work to adjust my keymap with a factory reset UHK if something went screwy with an editing session.
For more complex adjustments in transfer-every-key mode, there is likely to be a significant time with the keyboard in a less-than-perfectly-usable state, fertile ground for random outside interruptions (phone rings, end of available editing time, power failure, etc.) calling the user away.

**Comment by mondalaci** [comment]
@TorC8 The chance of data corruption is minimal given how the configuration update will be implemented. First, the configuration gets transferred to the RAM of the UHK over USB. Then it gets validated by the firmware. Finally, it gets saved from the RAM into the EEPROM in a very quick burst to mimize the chance of data corruption. In the unlikely case of the configuration getting corrupted, Agent should be able to detect and fix the situation automatically.

There's also the option of applying the changes in the RAM real-time, but not saving it to the EEPROM permamently, only upon explicit user interaction.

I don't think we can figure this out simply by talking about it. We should try different scenarios in Agent and see what works best. In any case, user experience should prevail.

**Comment by TorC8** [comment]
I was thinking, not of data corruption, but the more high-level case of incomplete editing of a keymap leaving an absurd and impossible to actually use layout stored.
Consider what happens if someone decides to start overhauling their primary keymap, and half-way through gets called away for some random reason and can't get back to the edit for a week.  What state will the UHK be left in?

**Comment by mondalaci** [comment]
I can see what you mean, although I think it's not a very usual use case. But it's better to keep every use case in mind when making the final decision, including yours!

**Comment by TorC8** [comment]
Perhaps not usual, but I think it would make it more comfortable to play around if nothing were committed to use on the UHK without invoking an explicit "save-to-UHK" or "activate" command.  It would also ensure that any ire over a UHK getting into a state of impossible to use config is appropriately directed back at the user who saved a bad config to the keyboard (or the practical joker who sent them such a config), not at Agent.
