### ISSUE TITLE
Macro deletion focus behavior change

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1454]
User story: Due to module-induced config size increase, I've finally exhausted all config memoyr, and therefore have been forced to clean up my config. This means throwing out approximately 10 keymaps and 80 related macros. Now my problem is that macro deletion via the gui is pretty painful, because I have to repeatedly cover the entire screen with my mouse back and forth while cycling "select macro" and "delete macro" actions.

Current behaviour:
- When a macro is deleted, alphabetically first macro in the left pane is focused. 

Proposed behaviour:
- When a macro is deleted, macro directly below or above gets focused.

Corollary - if the proposed behaviour gets implemented, it suffices to focus the first macro of a block which is to be deleted and then repeatedly click "delete macro" without having to move mouse at all.

**Comment by mondalaci** [comment]
Fair enough. When a macro is deleted, the macro directly below it will be focused.
