### ISSUE TITLE
Call macros from a macro

### ISSUE THREAD

**Issue by KnoP-01** [UltimateHackingKeyboard/agent#1464]
For long macros it would be convenient to structure those. For this it would be nice to be able to call a macro directly from a macro. It may be possible to enter a key combination which calls a macro, I haven't tried. But a direct call would be much more convenient.

**Comment by kareltucek** [comment]
You might be interested in this fork - https://github.com/kareltucek/firmware .

Within current official firmware/Agent is a bit of a science fiction. (Not saying that it's bad - just unrealistic within currently applied policies and philosophies.)

**Comment by kareltucek** [comment]
It may be possible to enter a key combination which calls a macro. Not possible, and even if it was, it would not be a good idea due to blocking/nonblocking nature of doing such thing.

**Comment by mondalaci** [comment]
This is not planned for the time being. Karel's UHK firmware fork is recommended for using such advanced macro-related features.
