### ISSUE TITLE
The screen shouldn't jump after editing macro items

### ISSUE THREAD

**Issue by KnoP-01** [UltimateHackingKeyboard/agent#1465]
I would love to see line/item numbers in the macro editor. 

For me it's hard to edit long macros, because I loose track where I was editing.

For example, when changing a delay the screen jumps to the end of the macro. Now I have to go through all instructions again to track down where my last change was.

Another example, I want to add a new instruction at the top of a long macro. I have to use the mouse to drag the new instruction up. As I reach the top of the screen I have to drop the instruction, scroll and drag it again. After scrolling sometimes it's hard to see which exact instruction I want to drag further to the top.

All this would be a bit more convenient with (hopefully) simple line numbers.

**Comment by mondalaci** [comment]
The screen shouldn't jump to the end of the macro when editing macro items, so we'll fix this.

As for line numbers, I'm worried that they'd make the UI slightly noisier. Is there anybody else who'd love to see this feature?

**Comment by kareltucek** [comment]
[just spamming] - with my 100+ macros I would love to hear the usecase which calls for it!

**Comment by mondalaci** [comment]
@ert78gb Let's fix the jumping issue now.

**Comment by mondalaci** [comment]
Resolved by #1471.

**Comment by KnoP-01** [comment]
Thanks!
