### ISSUE TITLE
Module buttons disappear when trying to drag them

### ISSUE THREAD

**Issue by achikin** [UltimateHackingKeyboard/agent#1466]
Agent version: 1.5.10 (web demo)

Issue: some of the module buttons disappear when trying to drag them around. See video.

https://user-images.githubusercontent.com/611419/111165031-a6414b00-85af-11eb-9f30-a14a138268ec.mov

**Comment by mondalaci** [comment]
Thanks for reporting! I can clearly reproduce the issue. Non-rectangle keys are affected.
