### ISSUE TITLE
Weird config loading behaviour.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1474]
Agent runs into a bunch of weird problems. I've got here a Planck connected too (which is the only new thing in my current setup, apart from trying to increase and decrease the baud rate this morning), but disconnecting it does not seem to help after all.

- Reports eeprom error and hangs on loading.
- Loads, including all configs, but shows only right keyboard half.
- Loads, but including factory config, apparently in the web demo mode.

[l.txt](https://github.com/UltimateHackingKeyboard/agent/files/6220790/l.txt)
[l2.txt](https://github.com/UltimateHackingKeyboard/agent/files/6220818/l2.txt)

![2021-03-29-113606_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/112818645-0c37d300-9084-11eb-8717-a935319ff717.png)
![2021-03-29-113541_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/112818658-0f32c380-9084-11eb-8295-d9e4ea1b932a.png)
![2021-03-29-113428_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/112818673-11951d80-9084-11eb-9284-ceebcd6266c7.png)
![2021-03-29-113329_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/112818692-1528a480-9084-11eb-9201-4ba8a45a9e58.png)
![2021-03-29-113225_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/112818699-18239500-9084-11eb-8e5e-9b898609dfa2.png)

The keyboard itself runs fine, am just not able to load it in the Agent.

**Comment by mondalaci** [comment]
1. Can you consistently reproduce this error on multiple computers?
2. Do you happen to run multiple instances of Agent in parallel?

**Comment by kareltucek** [comment]
1. No. Other computer works fine.
2. No.
