### ISSUE TITLE
Unable to update to latest firmware

### ISSUE THREAD

**Issue by stphnlwlsh** [UltimateHackingKeyboard/agent#1478]
Currently on 8.10.2 with the latest agent. I have tried joining keyboard halves and plugging into multiple USB ports on the back of my machine. Any suggestions to get the latest ?

```
Start flashing firmware
New firmware version: 8.10.3
Agent version: 1.5.11
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":7504,"keyboardPid":24866,"bootloaderPid":24864,"buspalPid":24865}
[DeviceService] updateFirmware error {"message":"Cannot read property 'firmwareVersion' of undefined","stack":"TypeError: Cannot read property 'firmwareVersion' of undefined\n    at t.DeviceService.<anonymous> (C:\\Users\\steph\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:570659)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\steph\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:848737)"}
[DeviceOperation] Read "1" version information
[DeviceService] start poll UHK Device
Cannot read property 'firmwareVersion' of undefined

```

**Comment by mondalaci** [comment]
Can you update to the 8.10.8 firmware version, which is bundled with Agent 1.5.11?

If not, please try updating on another computer, and let me know about the result.

**Comment by stphnlwlsh** [comment]
I believe this was an issue in the past, but I thought it had been fixed. My main machine is AMD, and it does not update there. Updated just fine on my Intel machine.

**Comment by mondalaci** [comment]
So glad to hear that the firmware update works on your Intel machine! We've noticed a relevant bug that may cause this issue in some environments, #1479 should fix it, and the next Agent release will contain it. I'm closing this issue.
