### ISSUE TITLE
Slow USB devices cause Agent software to hang

### ISSUE THREAD

**Issue by firngrod** [UltimateHackingKeyboard/agent#1482]
Connecting a USB device which is slow to respond when the Agent scans for connected UHKs makes the Agent software hang to a point where it's effectively unusable.

Detailed info:
I have a USB microphone (Blue Snowball Ice) which has an issue in which it is slow to respond to some USB enum or hardware info command or something like that.  It's quite buggy really, on Linux it only works if I jump through a lot of hoops, and it has also caused my Linux partition to bool slower on occasions.

Regardless, this unresponsiveness makes Agent hang every time it rescans connected USB devices to locate any connected UHKs, making the software virtually unusable when this microphone is connected.  Flashing firmware downright does not work since it doesn't find the UHK before the UHK has given up showing as a target for the firmware flash.  I've had similar issues on my workplace with other hardware, so the issue is not unique to this one microphone.  In my case, I can just disconnect my mike for a bit, but with other hardware, that might not be an option.

Maybe some parallellization or something is possible?

**Comment by mondalaci** [comment]
We haven't ever heard about this issue. Please list the affected USB devices.

Can you reproduce this issue with every affected device and computer, or only specific device-computer combinations are affected?

**Comment by firngrod** [comment]
I'm not sure what to give you about the device except that it's a Blue Snowball Ice microphone (https://www.bluemic.com/en-us/products/snowball-ice/).
USBView gave me the following information about the device:  https://pastebin.com/TyqaNx68
USBView also took noticably longer time to list the USB devices with the microphone plugged in than without it.
If you need anything else, I'll be happy to provide you with what you need.

I've verified the issue on both my home PC and my work laptop, with the device plugged directly into either one, or through various levels of dongles.

Like I mentioned, there's clearly an issue with the device.  It's just dragging the Agent down with it.

I have a couple of spare computers lying around on which I could do further tests if needed, or I could set one up for you to play with through a remote session or something if you want to address it.  If you haven't heard about it before, maybe it's not worth the effort.  Once I can get back to the office, I'll see if I can figure out which hardware, if any, caused the same issues at that location.  I might misremember about having the issue at work.

**Comment by firngrod** [comment]
Output from the Agent:  https://pastebin.com/mR1PwgGh

I don't expect that you'll be able to fix the USB hanging issue, but maybe the UI can be made usable while waiting for the USB listing or something.

**Comment by mondalaci** [comment]
@ert78gb Any ideas based on the log?

**Comment by ert78gb** [comment]
10 sec the listing of the USB devices. It is really really slow.
If the main thread of the Electron is blocked then it blocks the renderer project and causes the hanging.

@firngrod I don't see any microphone device in the Agent's log.

@mondalaci From Node 12 the `worker_thread` available feature we can try to use to run the USB communication but have to measure the extra process communication how changes the overall performance. We introduce a new interprocess communication Renderer Process <=> Main Process <=> Worker Thread

**Comment by mondalaci** [comment]
@firngrod I talked with @ert78gb, and making the UI non-blocking to quickly display an error message (which wouldn't solve the core of the issue) would likely take 6-12 hours of work. I'm sorry, but we can't justify spending so much time on a one-off issue.

If this issue gets more prevalent, we're willing to spend more time on it, but as for now, I'm closing it. Feel free to follow up anytime.

**Comment by firngrod** [comment]
That's understandable.  I'll just unplug the microphone when I need to use Agent.
@ert78gb Yes, the microphone was plugged in while I ran the Agent for that output log.
