### ISSUE TITLE
On Linux: Device connection state query error Error: /tmp/.org.chromium.Chromium.0PTaT1: Fehler beim Mappen des Shared Objects

### ISSUE THREAD

**Issue by matacino** [UltimateHackingKeyboard/agent#1491]
I run across an error trying to run the agent after a while not needing to:

Device connection state query error Error: /tmp/.org.chromium.Chromium.0PTaT1: Fehler beim Mappen des Shared Objects
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/karl/bin/squashfs-root/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at loadBinding (/home/karl/bin/squashfs-root/resources/app.asar/node_modules/node-hid/nodehid.js:19:46)

Since a while ago the agent was running fine, I could not get it running today. Not with --appimage-extract-and-run nor with --appimage-extract and than trying to run it from the extracted. 

I could not find a solution on the uhk.io - resources so I am sharing my **solution here**:

After a while (reconnecting USB, connecting on USB2, removing all other USB-Devices, rebooting, trying lots of this and that) I could find similar problems for other electron-APPs: https://github.com/signalapp/Signal-Desktop/issues/2620

In the time after my last using of the agent I reconfigured my /tmp-Directory beeing held in Memory and for security-reasons with the noexec-Option:
`tmpfs     /tmp    tmpfs   defaults,size=20%,noatime,noexec,nosuid                 0   0`
The **noexec-option** is the **cause of the problems**. It seems electron runs things from /tmp somehow (even this is not advised).
Since I had not the time fixing electron or building special starting-scripts like in https://github.com/signalapp/Signal-Desktop/issues/2595 sugested, I ended up simply **remounting /tmp temporarely with the exec**-option:
**sudo mount -o remount,exec /tmp**
after this the agent was running silky-smooth like a well shaked James-Bond-Zohan-Dvir-mixed-soap ;-)

**Comment by mondalaci** [comment]
Thank you very much for reporting this issue and sharing the solution! :)

@ert78gb Any ideas on how to make Agent run well in such environments?

**Comment by ert78gb** [comment]
Based on the [comment](https://github.com/electron/electron/issues/24242#issuecomment-648914819)
`node-hid` is a native module and electron extract it to the tmp directory. We can change the build script to not bundle the `node-hid`. 

We also use `sudo-prompt` to set the udev rules and it is run a file. We have to test it too.

**Comment by mondalaci** [comment]
According to the estimation of @ert78gb, fixing this issue is quite time-consuming, nobody else has encountered it, and we have much to do nowadays. Given the above, I'm closing this issue, but we'll reopen and fix it if it proves to be more prevalent.

**Comment by matacino** [comment]
this describes a recommended  solution https://github.com/electron/electron/issues/24242#issuecomment-648914819
