### ISSUE TITLE
Agent 1.5.12 can't find my device - intermittent issue

### ISSUE THREAD

**Issue by dustyculler** [UltimateHackingKeyboard/agent#1492]
I updated to Agent 1.5.12, and Agent could not see my UHK.  I tried opening Agent a few times and only had luck twice.  Once was after a reboot, but then it couldn't find it again later and another reboot didn't fix it.  The other time was when I re-installed 1.5.12 and it saw the device on the first open, but not on two subsequent attempts.

In the upper left corner it says "No device detected", and stays at the "Loading keyboard configuration... Hang tight!" page until I close Agent.  I've left it open for around five minutes before closing.

I was able to update the firmware to 8.10.9 the one time 1.5.12 found my device, but it's only found the device once out of the six or so times I've opened Agent, so it doesn't appear the firmware version has an effect on this issue.  I've not had this issue with previous versions.

As 1.5.12 wasn't seeing my UHK consistently, I've uninstalled 1.5.12 and installed 1.5.11 which is always seeing my device without fail.

I'm on a Ryzen system running Windows 10 with the keyboard plugged directly into a USB port on the motherboard.

Please let me know if there's anything you'd like me to do to help troubleshoot the cause.
Thanks.

**Comment by dustyculler** [comment]
I just moved the UHK from the USB 3.2 Gen1 port to a USB 2.0 port and Agent 1.5.12 was able to see my UHK consistently with about 10 tries.

I wonder if this may have more to do with USB issues with AMD 500 series Ryzen motherboards.  I'll try updating my bios to the latest version later this evening and report back if it works normally in the original USB 3.2 Gen1 port.  I'm fine leaving it in the USB 2.0 port, just figured I'd see if that resolves the issue out of curiosity.

**Comment by dustyculler** [comment]
I should mention that while I had heard there was an intermittent USB issue with AMD 500 series motherboards, I haven't noticed any of these issues on my B550 board.

Unfortunately updating the BIOS on my board to one with AGESA 1.2.0.2 (which AMD said should fix the intermittent USB issue they've identified) didn't result in agent finding the UHK on the USB 3.2 Gen1 port.

After a little more experimenting I found that Agent 1.5.12 always finds the UHK when plugged into either a USB 2.0 or USB 3.2 **_Gen2_** port, but fails the majority of the time on any of my four USB 3.2 Gen1 ports.  Interestingly when it fails to find the UHK, unplugging the keyboard and plugging it into another USB 3.2 Gen1 port while Agent is open causes it to find the UHK, even though it's being plugging into one of the same ports it normally fails to find the UHK on at Agent startup.

**Comment by mondalaci** [comment]
Thank you very much for the detailed bug report!

Would you please paste the command line output of Agent when it doesn't find your UHK? Then we'd look into this issue.

**Comment by dustyculler** [comment]
C:\Users\dusty\AppData\Local\Programs\uhk-agent>
17:17:31.492 > [Electron Main] init services.
17:17:31.496 > [Electron Main] packagesDir: C:\Users\dusty\AppData\Local\Programs\uhk-agent\resources
17:17:31.522 > [Electron Main] Create new window.
17:17:31.523 > [WindowState] load settings
17:17:31.525 > [WindowState] loaded settings {
  x: 1282,
  y: 119,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
17:17:31.526 > [WindowState] loaded settings is visible true
17:17:31.527 > [WindowState] return with loaded settings
17:17:31.611 > [DeviceService] start poll UHK Device
17:17:31.800 > [UhkHidDevice] Devices before checking permission:
17:17:31.889 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col01#8&323e27d7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":1,"usage":2}
17:17:31.890 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col02#8&323e27d7&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":12,"usage":1}
17:17:31.890 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col03#8&323e27d7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":1,"usage":128}
17:17:31.891 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col04#8&323e27d7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":65468,"usage":136}
17:17:31.891 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#9&4b8f890&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":3,"usagePage":1,"usage":128}
17:17:31.892 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#9&28903652&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":2,"usagePage":12,"usage":1}
17:17:31.892 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#9&1f1e4532&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":4,"usagePage":1,"usage":2}
17:17:31.892 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col01#8&e66ea15&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":1}
17:17:31.893 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col02#8&e66ea15&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":2}
17:17:31.893 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#9&10ccaa0d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":1,"usagePage":1,"usage":6}
17:17:31.894 > {"vendorId":9934,"productId":418,"path":"\\\\?\\hid#vid_26ce&pid_01a2#7&113d5874&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"A02019100900","manufacturer":"ASRock","product":"LED Controller","release":0,"interface":-1,"usagePage":1}
17:17:31.894 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_00#8&1a7a9b92&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":0,"usagePage":1,"usage":6}
17:17:31.894 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col03#8&e66ea15&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":4}
17:17:31.895 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&34a3e7cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":0,"usagePage":65280,"usage":1}
17:17:32.071 > [UhkHidDevice] Available devices:
17:17:32.071 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col01#8&323e27d7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":1,"usage":2}
17:17:32.072 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col02#8&323e27d7&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":12,"usage":1}
17:17:32.073 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col03#8&323e27d7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":1,"usage":128}
17:17:32.073 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_01&col04#8&323e27d7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":1,"usagePage":65468,"usage":136}
17:17:32.073 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#9&4b8f890&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":3,"usagePage":1,"usage":128}
17:17:32.074 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#9&28903652&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":2,"usagePage":12,"usage":1}
17:17:32.074 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#9&1f1e4532&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":4,"usagePage":1,"usage":2}
17:17:32.075 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col01#8&e66ea15&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":1}
17:17:32.075 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col02#8&e66ea15&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":2}
17:17:32.075 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#9&10ccaa0d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":1,"usagePage":1,"usage":6}
17:17:32.076 > {"vendorId":9934,"productId":418,"path":"\\\\?\\hid#vid_26ce&pid_01a2#7&113d5874&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","serialNumber":"A02019100900","manufacturer":"ASRock","product":"LED Controller","release":0,"interface":-1,"usagePage":1}
17:17:32.076 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_00#8&1a7a9b92&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":0,"usagePage":1,"usage":6}
17:17:32.077 > {"vendorId":1133,"productId":50475,"path":"\\\\?\\hid#vid_046d&pid_c52b&mi_02&col03#8&e66ea15&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Logitech","product":"USB Receiver","release":9233,"interface":2,"usagePage":65280,"usage":4}
17:17:32.078 > {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&34a3e7cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":0,"usagePage":65280,"usage":1}
17:17:32.078 > [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#9&34a3e7cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":257,"interface":0,"usagePage":65280,"usage":1}
17:17:32.080 > [DeviceService] init success
17:17:32.081 > [AppUpdateService] init success
17:17:32.081 > [AppService] init success
17:17:32.081 > [SudoService] App root dir:  C:\Users\dusty\AppData\Local\Programs\uhk-agent\resources
17:17:32.089 > [DeviceService] Udev info: Ok
17:17:32.250 > [DeviceOperation] Read "1" version information
17:17:32.255 > [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.9',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 1,
    name: 'UHK 60 v1',
    vendorId: 7504,
    keyboardPid: 24866,
    bootloaderPid: 24864,
    buspalPid: 24865
  }
}
17:17:32.458 > [AppRendererService] init success
17:17:32.473 > [DeviceRendererService] init success
17:17:32.475 > Renderer appStart effect start
17:17:32.476 > [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
17:17:32.477 > [AppUpdateService] app started. Automatically check for update.
17:17:32.477 > Checking for update
17:17:32.478 > [AppUpdateService] checking for update
17:17:32.478 > sendIpcToWindow: checking-for-update null
17:17:32.476 > [AppRendererService] getAppStartInfo
17:17:32.486 > [AppService] getAppStartInfo
17:17:32.476 > Renderer appStart effect end
(node:19608) UnhandledPromiseRejectionWarning: Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (C:\Users\dusty\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1237292)
    at Generator.next (<anonymous>)
    at s (C:\Users\dusty\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1300180)
(Use `UHK Agent --trace-warnings ...` to show where the warning was created)
(node:19608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
17:17:36.084 > Update for version 1.5.12 is not available (latest version: 1.5.12, downgrade is disallowed).
17:17:36.085 > [AppUpdateService] checkForUpdate success
17:18:04.778 > [WindowState] save settings: {
  x: 1282,
  y: 119,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
17:18:04.780 > [WindowState] save settings success
17:18:04.792 > [Electron Main] win closed
17:18:04.793 > [DeviceService] stop poll UHK Device
17:18:04.794 > [DeviceService] stopped poll UHK Device
17:18:04.795 > [DeviceService] Device connection checker stopped.
17:18:04.796 > [UhkHidDevice] Device communication closing.
17:18:04.797 > [UhkHidDevice] Device communication closed.

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
I think the #1501 Pr fix the issue

**Comment by mondalaci** [comment]
The next Agent release will contain the fix. Please reopen this issue if it persists after testing the upcoming Agent release.
