### ISSUE TITLE
Display help instructions to the user in case of USB issues

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#151]
Various OSes pose various challenges regarding setting up USB communication:
- For Linux `50-uhk-write-access.rules` must be set up
- For Windows, there seems to be a WinUSB related setup issue
- And who knows what Mac specific issues we'll encounter with

We should detect whether there are any USB related issues and if such, we should display instructions to the user. Given the above, the implemention must be OS-specific.

Ideally, we should fix the issue with a click of a button but implementing it may take too much time. For the first run, let's aim for some simple instructions and implement a more convenient solution later.

It'd be great to implement this by v1.0 or else chances are we'll be flooded with support requests.

**Comment by TorC8** [comment]
Hopefully people will keep a current copy of Agent, but it might be worth implementing a redirect to a webpage you can control and keep current early or otherwise implement a check for current version of Agent and notify the user if old before they get a chance to send a support request.

**Comment by mondalaci** [comment]
@TorC8 Great point! Just added #250.

**Comment by mondalaci** [comment]
Closing this issue, as it has been superseded by #258, #259, #260, #261, and #262.
