### ISSUE TITLE
UHK Keyboard not recognized after update

### ISSUE THREAD

**Issue by sunlecrad1** [UltimateHackingKeyboard/agent#1510]
While creating a test macro I started to assign it to a F1 key then decided to change to the “Q” letter and reassign the F1 key to NONE.
It did not remap, and I decided to reload the firmware which gave the multiple error in red in the attached picture. The save to keyboard made the UHK not recognized anymore and now after trying on several computers and even changing the cables in case the UHK keyboard in not usable anymore and absolutely not recognize. The message “Cannot find your UHK Please plug it in!” shows all the time even wire connected!
On an other computer when connecting the UHK the pilot is trying to connect the new device and finally says (In French) “The Pilot could not be installed  UHK Bootloader Peripheral not connected”.

Error showed :  [http://www.senezconsulting.com/!_20210504_ERROR_UHK_not_usable_01.jpg](url)
Pilot error : [http://www.senezconsulting.com/!_20210504_ERROR_UHK_not_usable_02.jpg](url)
error Cannot find your UHK Please plug it in!” : [http://www.senezconsulting.com/!_20210504_ERROR_UHK_not_usable_03.jpg](url)

**Comment by mondalaci** [comment]
Please download the freshly released Agent 1.5.13, start it up, and it should fix your UHK.

Are you running Windows 7? If so, please try Agent with a newer Windows version.

Please let me know about the results.

**Comment by sunlecrad1** [comment]
Hi Mondalaci,
Thank you for your help on thois matter. László Monda is doing great as support also.
The issue happened and I am using a Windowns 10. I only tried on an other computer with 7 to check if the keyboard was recognised to find out if it was really coming from the Keyboard and not the computer. The result was and stilll is the same.
Changing the cables does not do anything either. Thanks again. Patrice

![!_20210504_ERROR_UHK_not_usable_04](https://user-images.githubusercontent.com/28166224/117070578-38eba400-ad2e-11eb-881d-32707ab633b2.jpg)
![!_20210504_ERROR_UHK_not_usable_05](https://user-images.githubusercontent.com/28166224/117070587-3b4dfe00-ad2e-11eb-8c39-3757e50017de.jpg)
![!_20210504_ERROR_UHK_not_usable_06](https://user-images.githubusercontent.com/28166224/117070592-3db05800-ad2e-11eb-97d3-61b25f1dc80a.jpg)

**Comment by sunlecrad1** [comment]
Hi László Monda,



I sent this via GitHub to Modalaci but still not recognised ddespite I am still using a Windows 10. And 1.5.13 Agent.

Thanks,



Patrice : +33 648180135







Hi Mondalaci,
Thank you for your help on thois matter. László Monda is doing great as support also.
The issue happened and I am using a Windowns 10. I only tried on an other computer with 7 to check if the keyboard was recognised to find out if it was really coming from the Keyboard and not the computer. The result was and stilll is the same.
Changing the cables does not do anything either. Thanks again. Patrice

[!_20210504_ERROR_UHK_not_usable_04]<https://user-images.githubusercontent.com/28166224/117070578-38eba400-ad2e-11eb-881d-32707ab633b2.jpg>
***@***.***D7413B.70B25410]
***@***.***D7413B.70B25410]


De : László ***@***.***>
Envoyé le :mardi 4 mai 2021 22:38
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [UltimateHackingKeyboard/agent] UHK Keyboard not recognized after update (#1510)


Please download the freshly released Agent 1.5.13, start it up, and it should fix your UHK.

Are you running Windows 7? If so, please try Agent with a newer Windows version.

Please let me know about the results.

**Comment by mondalaci** [comment]
Thanks for the nice words! :)

Please run Agent 1.5.13 on Windows 10, and follow [these instructions](https://ultimatehackingkeyboard.com/repair/unbricking-the-right-keyboard-half) to unbrick your UHK.

**Comment by sunlecrad1** [comment]
A great thanks to Mondalaci, the UHK is back an runnning after unbricking and a bit too much disassembly than needed from my part. You can watch the video [https://youtu.be/2fDJIB7D66Y](url) for details if you are interested for quality and follow-up purpose.

**Comment by sunlecrad1** [comment]
A great thanks to Mondalaci, the UHK is back an running after unbricking and a bit too much disassembly than needed from my part. You can watch the video https://youtu.be/2fDJIB7D66Y<https://github.com/UltimateHackingKeyboard/agent/issues/url> for details if you are interested for quality and follow-up purpose.


Köszönöm,

Patrice SENEZ


De : László ***@***.***>
Envoyé le :mardi 4 mai 2021 23:18
À : ***@***.***>
Cc : ***@***.***>; State ***@***.***>
Objet :Re: [UltimateHackingKeyboard/agent] UHK Keyboard not recognized after update (#1510)


Thanks for the nice words! :)

Please run Agent 1.5.13 on Windows 10, and follow these instructions<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fultimatehackingkeyboard.com%2Frepair%2Funbricking-the-right-keyboard-half&data=04%7C01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637557599345894901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zrV6UuF3WmgLUurW%2F1DoqrK%2F3eH90O3R7JOHlyyctRM%3D&reserved=0> to unbrick your UHK.

**Comment by mondalaci** [comment]
So glad you managed to unbrick your UHK! Excellent job!

Shorting the reset pin is needed very rarely. If it's needed again, instead of fully disassembling the two halves, it's sufficient to only remove the top part of the right half which should take about 10% of the time.

**Comment by sunlecrad1** [comment]
My pleasure, yeah found out while doing it that I went to far in the disassembly  but it’s ok!

Spare question : Is there anyway to have a loop programmed on the keyboard like a Do-Loop, For-Next, or While-Wend type ?

Thanks,

Patrice



De : László ***@***.***>
Envoyé le :jeudi 6 mai 2021 11:44
À : ***@***.***>
Cc : ***@***.***>; State ***@***.***>
Objet :Re: [UltimateHackingKeyboard/agent] UHK Keyboard not recognized after update (#1510)


So glad you managed to unbrick your UHK! Excellent job!

Shorting the reset pin is needed very rarely. If it's needed again, instead of fully disassembling the two halves, it's sufficient to only remove the top part of the right half which should take about 10% of the time.

**Comment by mondalaci** [comment]
I'm sorry, but loops are not supported. You can modify [the firmware](https://github.com/UltimateHackingKeyboard/firmware/), but we can't provide substantial help.

**Comment by sunlecrad1** [comment]
Hi,

 

I created a Github issue so I can transfer some self-explanatory videos
about three issues I am encountering :

                

sunlecrad1/UHK_not_recognized_-_lights-FTY

 

 

*	UHK got some red errors and then is not recognized as plugged!
*	FTY says with the lights and not QWY as usual!!
*	Mousse module blinking and not steady enough!

 

Kind regards,

 

Patrice SENEZ

***@***.*** ***@***.***> 

 

Tel :01133 (0) 648180135

Cpuntry := France

 

 

 

De : Patrice SENEZ ***@***.***> 
Envoyé : mercredi 5 mai 2021 22:18
À : UltimateHackingKeyboard/agent
***@***.***>;
UltimateHackingKeyboard/agent ***@***.***>
Cc : State change ***@***.***>; Patrice SENEZ
***@***.***>; ***@***.***
Objet : RE : [UltimateHackingKeyboard/agent] UHK Keyboard not recognized
after update (#1510)

 

A great thanks to Mondalaci, the UHK is back an running after unbricking and
a bit too much disassembly than needed from my part. You can watch the video
https://youtu.be/2fDJIB7D66Y
<https://github.com/UltimateHackingKeyboard/agent/issues/url>  for details
if you are interested for quality and follow-up purpose.

 

Köszönöm,

 

Patrice SENEZ

 

 

De : László Monda ***@***.***> 
Envoyé le :mardi 4 mai 2021 23:18
À : UltimateHackingKeyboard/agent ***@***.***> 
Cc : PatriceSENEZ ***@***.***> ; State change
***@***.***> 
Objet :Re: [UltimateHackingKeyboard/agent] UHK Keyboard not recognized after
update (#1510)

 

Thanks for the nice words! :)

Please run Agent 1.5.13 on Windows 10, and follow these instructions
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fultimate
hackingkeyboard.com%2Frepair%2Funbricking-the-right-keyboard-half&data=04%7C
01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640afb435aaaaaaaaaaaa%
7C1%7C0%7C637557599345894901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJ
QIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zrV6UuF3WmgLUurW%2F
1DoqrK%2F3eH90O3R7JOHlyyctRM%3D&reserved=0>  to unbrick your UHK.


You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2FUltimateHackingKeyboard%2Fagent%2Fissues%2F1510%23issuecomment-83225565
3&data=04%7C01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640afb435a
aaaaaaaaaaa%7C1%7C0%7C637557599345894901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4
wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=66tY6rC
%2BpBjnwqzXHCsGEnLoFB5kXpzmi3yC3TBezjk%3D&reserved=0> , or unsubscribe
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FAGW4QUAE4ODFK4A5XJNFDZLTMBQD3ANCNFSM
44C2BZ6A&data=04%7C01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640
afb435aaaaaaaaaaaa%7C1%7C0%7C637557599345904857%7CUnknown%7CTWFpbGZsb3d8eyJW
IjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=
1XQeB5DKRTBmkxgDlSnPp%2BbEudhXfKLAsbpfAVPiNm0%3D&reserved=0> .
<https://github.com/notifications/beacon/AGW4QUAFWB4AIRATDGTHRNLTMBQD3A5CNFS
M44C2BZ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGGNTNJI
.gif>

**Comment by mondalaci** [comment]
@sunlecrad1 Please reformat your previous message because it's very noisy and hard to read. Going forward, please use the Preview function of GitHub before posting messages.

**Comment by sunlecrad1** [comment]
Hi,

I encounter new issues with my UHK.

 

*	First is it not recognized anymore and says FTY with the lights!
*	Then the mousse module extension is blinking and not steady
functioning.

I will share a folder with explanations videos via WeTRansfer.

 

Hope you can get them and read them in .mov !

 

Kind regards,

 

Patrice SENEZ

TEL! 01133 648180135

***@***.*** ***@***.***>


 

 

 

De : Patrice SENEZ ***@***.***> 
Envoyé : mercredi 5 mai 2021 22:18
À : UltimateHackingKeyboard/agent
***@***.***>;
UltimateHackingKeyboard/agent ***@***.***>
Cc : State change ***@***.***>; Patrice SENEZ
***@***.***>; ***@***.***
Objet : RE : [UltimateHackingKeyboard/agent] UHK Keyboard not recognized
after update (#1510)

 

A great thanks to Mondalaci, the UHK is back an running after unbricking and
a bit too much disassembly than needed from my part. You can watch the video
<https://github.com/UltimateHackingKeyboard/agent/issues/url>
https://youtu.be/2fDJIB7D66Y for details if you are interested for quality
and follow-up purpose.

 

Köszönöm,

 

Patrice SENEZ

 

 

De :  ***@***.***> László Monda
Envoyé le :mardi 4 mai 2021 23:18
À :  ***@***.***> UltimateHackingKeyboard/agent
Cc :  ***@***.***> PatriceSENEZ;
***@***.***> State change
Objet :Re: [UltimateHackingKeyboard/agent] UHK Keyboard not recognized after
update (#1510)

 

Thanks for the nice words! :)

Please run Agent 1.5.13 on Windows 10, and follow
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fultimate
hackingkeyboard.com%2Frepair%2Funbricking-the-right-keyboard-half&data=04%7C
01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640afb435aaaaaaaaaaaa%
7C1%7C0%7C637557599345894901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJ
QIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zrV6UuF3WmgLUurW%2F
1DoqrK%2F3eH90O3R7JOHlyyctRM%3D&reserved=0> these instructions to unbrick
your UHK.


You are receiving this because you modified the open/close state.
Reply to this email directly,
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2FUltimateHackingKeyboard%2Fagent%2Fissues%2F1510%23issuecomment-83225565
3&data=04%7C01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640afb435a
aaaaaaaaaaa%7C1%7C0%7C637557599345894901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4
wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=66tY6rC
%2BpBjnwqzXHCsGEnLoFB5kXpzmi3yC3TBezjk%3D&reserved=0> view it on GitHub, or
<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FAGW4QUAE4ODFK4A5XJNFDZLTMBQD3ANCNFSM
44C2BZ6A&data=04%7C01%7C%7Cc4903114d86f499226a108d90f423893%7C84df9e7fe9f640
afb435aaaaaaaaaaaa%7C1%7C0%7C637557599345904857%7CUnknown%7CTWFpbGZsb3d8eyJW
IjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=
1XQeB5DKRTBmkxgDlSnPp%2BbEudhXfKLAsbpfAVPiNm0%3D&reserved=0> unsubscribe.
<https://github.com/notifications/beacon/AGW4QUAFWB4AIRATDGTHRNLTMBQD3A5CNFS
M44C2BZ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGGNTNJI
.gif>

**Comment by mondalaci** [comment]
Regarding the FTY issue, please run Agent, which may offer to fix your configuration. If it doesn't, please try to reproduce this issue with other computers.

As for the blinking key cluster module, please [fasten its screws](https://ultimatehackingkeyboard.com/repair/fastening-module-steel-guide-screws).
