### ISSUE TITLE
Key remappings won't work in Agent version: 1.5.13 on Win10

### ISSUE THREAD

**Issue by khwerhahn** [UltimateHackingKeyboard/agent#1511]
Hi I'm trying to swap the Z and Y key. The agent shows that this is the case, but when typing, it doesn't work. The windows keyboard settings are set to German, but still no change.

**Comment by mondalaci** [comment]
Hi there! I can see that you closed this issue. Have you solved it? In any case, here's a relevant blog post: https://ultimatehackingkeyboard.com/knowledgebase/how-can-i-type-accented-characters-with-the-uhk

**Comment by khwerhahn** [comment]
Thanks for the fast reply. I figured it out. Basically, I had to reset to the default layout and the windows keyboard settings changed it to the german layout. It is a bit confusing. Is there a way for the Agent to display what the true output will be? Basically, what you type is what you get?

**Comment by mondalaci** [comment]
Yes, we plan to add several non-US languages, including German, eventually.
