### ISSUE TITLE
Trouble Updating Firmware

### ISSUE THREAD

**Issue by tywine** [UltimateHackingKeyboard/agent#1512]
Start flashing firmware
New firmware version: 8.10.9
Agent version: 1.5.13
[DeviceService] updateFirmware error {"message":"Communications error with UHK. Response code: undefined","stack":"Error: Communications error with UHK. Response code: undefined\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\tywin\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1239132)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\tywin\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1302211)"}
[DeviceService] Read hardware modules information failed Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (C:\Users\tywin\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1239132)
    at Generator.next (<anonymous>)
    at s (C:\Users\tywin\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1302211)
[DeviceService] start poll UHK Device
Communications error with UHK. Response code: undefined

**Comment by mondalaci** [comment]
Please copy-paste the entire firmware update log.

**Comment by tywine** [comment]
Hey László, here is the whole log:

Start flashing firmware
New firmware version: 8.10.9
Agent version: 1.5.13
[DeviceService] updateFirmware error {"message":"Communications error with
UHK. Response code: undefined","stack":"Error: Communications error with
UHK. Response code: undefined\n    at t.UhkHidDevice.<anonymous>
(C:\\Users\\tywin\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1239132)\n
   at Generator.next (<anonymous>)\n    at s
(C:\\Users\\tywin\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1302211)"}
[DeviceService] Read hardware modules information failed Error:
Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous>
(C:\Users\tywin\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1239132)
    at Generator.next (<anonymous>)
    at s
(C:\Users\tywin\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1302211)
[DeviceService] start poll UHK Device
Communications error with UHK. Response code: undefined

**Comment by ert78gb** [comment]
Hello @tywine,

Please run the agent with the `--log=all` command line argument and please set the `DEBUG=kboot` environment variables. And send me the terminal output. thx.

**Comment by tywine** [comment]
Hey László,

I tried the update again with a different cable. That fixed it.

Sorry for the bother. <3
