### ISSUE TITLE
Feature request: Allow copying/duplicating macro actions

### ISSUE THREAD

**Issue by Nicd** [UltimateHackingKeyboard/agent#1528]
For example currently I am writing a macro that entails the following:

* Type text
* Hit key
* Type same text
* Hit same key
* Type same text
* Hit same key
* And so on for a few times

It would be handy if I could duplicate the different actions so I didn't have to manually redo them every time.

**Comment by mondalaci** [comment]
Thanks for your suggestion, but according to the feedback we've been getting, this is not a usual use case. I'll close this issue for now, but I'll keep an eye on similar requests and reopen this one if justified.
