### ISSUE TITLE
misplaced recording dot on keycluster right mouse button

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#1535]
Agent version: 1.5.14

When I right-click the keycluster right mouse button to record a new binding, the "recording dot" looks misplaced - it is not centered over the button (see screenshot). Totally minor, but I spotted it and wanted to record the issue so it can eventually be addressed.

![image](https://user-images.githubusercontent.com/591785/121689132-8e9d3400-cac4-11eb-8d1f-1402c3aa0ca1.png)

**Comment by mondalaci** [comment]
I can reproduce this. Great catch!

**Comment by mhantsch** [comment]
Totally by accident, but you're welcome :)
