### ISSUE TITLE
Allow configuration of per-layer event types from mouse devices

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#1536]
Mouse movements on trackball, keycluster, trackpad can produce different events depending on the active layer:
- mouse position movements (i.e. mouse move events)
- cursor movements (i.e. up/down/left/right keystrokes)
- scroll movements (i.e. mouse scroll wheel events)

At the moment these modifiers seem to be hardcoded:
- Base layer= mouse movements
- Fn layer = cursor movements
- Mod layer = scroll movements

I have reconfigured some of the layer keys on my UHK, or put them on secondary only. These assignments now make it inconvenient to press them together with mini-trackball or touchpad movements, so I would like to reassign them. But that's not possible at the moment.

What I could foresee is that Agent allows me to assign these layer-to-event-type mappings for each of the "mouse movements"-producing devices. So I could for example map something like:

Mini-trackball: 
- Base layer => scroll events
- Mouse layer => mouse movements
- Mod layer => cursor movements

Touchpad:
- Base layer => mouse movements
- Mouse layer => scroll events
- Mod layer => cursor movements

At the end, this would make these movements more consistent with how I have mapped my own layers, and would also make it easiers to press some combinations.

Probably needs changes in the firmware as well.

**Comment by mondalaci** [comment]
What you're asking will be possible via [smart macros](https://github.com/UltimateHackingKeyboard/firmware/issues/351). Closing it as a duplicate, but feel free to follow up.

**Comment by mhantsch** [comment]
Oh I see, it's the "Module navigation modes". I had overlooked this part when I read through the smart macros proposal. So I guess I would set this via an $onKeymapChange or $onInitKeyboard trigger. Understood!
