### ISSUE TITLE
UHK Agent hangs when JBL Pebbles is connected

### ISSUE THREAD

**Issue by neptaco** [UltimateHackingKeyboard/agent#1539]
There is a speaker called JBL Pebbles.
JBL Pebbles (https://www.amazon.com/dp/B00F8HRSN2)

When Pebbles connected via USB, the UHK Agent behaves slowly and does not respond.
When the Pebbles's USB connection is disconnected, it works properly.

UHK Agent: 1.5.14
Firmware: 8.10.9

**Comment by mondalaci** [comment]
1. Please include the log of Agent when this issue occurs.
2. Please connect JSB Pebbles via all the other USB ports of your computer, one by one, and let us know whether every one of them exhibits the issue.

**Comment by mondalaci** [comment]
Closing issue due to the lack of feedback.
