### ISSUE TITLE
Agent won't load

### ISSUE THREAD

**Issue by raurosil** [UltimateHackingKeyboard/agent#1540]
Hello.

From days to now, the agent won't load, only show a white screen and I cannot do nothing and I run it with administrator rights.

Can you tell me if I can run admin with any command to bypass it or to get the error?

Thanks.

![imagen](https://user-images.githubusercontent.com/35873367/122788118-4ea13280-d2b6-11eb-9f5c-9f04f506b80c.png)

**Comment by mondalaci** [comment]
Hi there!

So does Agent work correctly if you run it as admin?

Please include the command line log of Agent when it exhibits the above issue.

**Comment by ert78gb** [comment]
- It writes the logs not the console and the log files. The location of the logs https://www.npmjs.com/package/electron-log

**Comment by raurosil** [comment]
I have installed (electron) but I don't know to run it.
If I run Agent from CMD with admin rights like this:
"UHK agent.exe"

the command window register this, but stills in white:

18:07:46.027 > [Electron Main] init services.
18:07:46.039 > [Electron Main] packagesDir: C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
18:07:46.151 > [Electron Main] Create new window.
18:07:46.158 > [WindowState] load settings
18:07:46.170 > [WindowState] loaded settings {
  x: 300,
  y: 60,
  width: 1024,
  height: 806,
  isMaximized: false,
  isFullScreen: false
}
18:07:46.181 > [WindowState] loaded settings is visible true
18:07:46.190 > [WindowState] return with loaded settings
18:07:46.418 > [DeviceService] init success
18:07:46.429 > [AppUpdateService] init success
18:07:46.440 > [AppService] init success
18:07:46.450 > [SudoService] App root dir:  C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
18:07:46.494 > [DeviceService] Udev info: Ok

**Comment by raurosil** [comment]
Sorry, wrong button

**Comment by ert78gb** [comment]
Pls use the --log=all argument. Currently, I dont see why Agent can connect to the UHK keyboard

**Comment by raurosil** [comment]
The same...

C:\Users\raurosil\AppData\Local\Programs\uhk-agent>"UHK Agent.exe" --log=all

C:\Users\raurosil\AppData\Local\Programs\uhk-agent>
18:20:25.768 > [Electron Main] init services.
18:20:25.774 > [Electron Main] packagesDir: C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
18:20:25.859 > [Electron Main] Create new window.
18:20:25.861 > [WindowState] load settings
18:20:25.866 > [WindowState] loaded settings {
  x: 618,
  y: 133,
  width: 1024,
  height: 806,
  isMaximized: false,
  isFullScreen: false
}
18:20:25.870 > [WindowState] loaded settings is visible true
18:20:25.872 > [WindowState] return with loaded settings
18:20:26.038 > [DeviceService] init success
18:20:26.041 > [AppUpdateService] init success
18:20:26.044 > [AppService] init success
18:20:26.049 > [SudoService] App root dir:  C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
18:20:26.083 > [DeviceService] Udev info: Ok

**Comment by raurosil** [comment]
Any other idea? 👍

**Comment by ert78gb** [comment]
Sorry for the late response. Can you open the developer console with F12?

**Comment by raurosil** [comment]
Hi.
I'm trying to execute with:
--devtools
--devtools=true
but the result is the same:

C:\Users\raurosil\AppData\Local\Programs\uhk-agent>"UHK Agent.exe" --devtools=true

C:\Users\raurosil\AppData\Local\Programs\uhk-agent>
12:17:17.585 > [Electron Main] init services.
12:17:17.595 > [Electron Main] packagesDir: C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
12:17:17.696 > [Electron Main] Create new window.
12:17:17.699 > [WindowState] load settings
12:17:17.704 > [WindowState] loaded settings {
  x: 755,
  y: 145,
  width: 1024,
  height: 799,
  isMaximized: false,
  isFullScreen: false
}
12:17:17.711 > [WindowState] loaded settings is visible true
12:17:17.714 > [WindowState] return with loaded settings
12:17:17.911 > [DeviceService] init success
12:17:17.917 > [AppUpdateService] init success
12:17:17.922 > [AppService] init success
12:17:17.934 > [SudoService] App root dir:  C:\Users\raurosil\AppData\Local\Programs\uhk-agent\resources
12:17:17.996 > [DeviceService] Udev info: Ok

**Comment by ert78gb** [comment]
We have to release a new version before you can use the new command line argument

**Comment by raurosil** [comment]
ok, I'll wait to this.
Thanks for all

**Comment by mondalaci** [comment]
@raurosil Please give a try to the new [Agent 1.5.15 version](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.5.15) with the --log=all argument.

**Comment by mondalaci** [comment]
Closing due to the lack of replies. Will reopen if needed.

**Comment by raurosil** [comment]
Hi.
I think that I have the solution.... To move the Agent folder to 'C:\Users\Administrator\AppData\Local'.
I'm executing the agent without issues at this folder but if I leave it at %LocalAppData%  (where it installs by default), the Agent loads randomly but only load very few times.
I suppose that my company locks some library or command if it executes from local account folder....

**Comment by mondalaci** [comment]
Thank you for sharing the solution! We haven't ever encountered this one, so it must be due to your installation-specific environment.
