### ISSUE TITLE
How to tune trackball module scrolling speed (it's too high)?

### ISSUE THREAD

**Issue by andriysavin** [UltimateHackingKeyboard/agent#1550]
Hi, I'm finding the trackball scrolling too fast by default. And I can't find any tools in Agent to tune it. Is this still in development?

**Comment by kareltucek** [comment]
Yep. https://github.com/UltimateHackingKeyboard/firmware/issues/351

**Comment by mondalaci** [comment]
Closing this issue as a duplicate.

**Comment by andriysavin** [comment]
@kareltucek thanks!

**Comment by andriysavin** [comment]
That issue, however, seems to be representing a fundamental configuration system enhancement. Which means until that base is finished, there will be no way to change some module settings, which is very disappointing.

**Comment by kareltucek** [comment]
Not that bad actually. It requires no changes into configuration formats and Agent stuff is already implemented.

I just have to find some two or three days of time for implementing macro event initiation, and a new set command.

**Comment by andriysavin** [comment]
I (and likely many others) would appreciate publishing a ready-for-consumption recipe here.

**Comment by mondalaci** [comment]
We'll publish a blog post after we get ready with smart macros.
