### ISSUE TITLE
Removing a macro disables saving to keyboard

### ISSUE THREAD

**Issue by bhaeussermann** [UltimateHackingKeyboard/agent#1553]
1) Open Agent.
2) Select an existing macro.
3) Click the "bin" button to delete the macro.

The macro is not removed from the list in the side-bar, but when selected does say "There is no macro with id .", so it appears it is in fact deleted. All key bindings using that macro are also removed.

The major issue here is that at this stage the "Save to keyboard" option should appear, which is not happening. Further, if I make any subsequent changes, the "Save to keyboard" option still doesn't appear.

**Comment by mondalaci** [comment]
I cannot reproduce this issue. Are you using the latest 1.5.14 Agent version?

**Comment by bhaeussermann** [comment]
Yes 🤔. On Windows 10.

**Comment by bhaeussermann** [comment]
See video

![2021-07-16_09h58_24](https://user-images.githubusercontent.com/7482216/125913560-36a11514-7269-4103-b2fa-5b85ab5e6bc2.gif)

**Comment by mondalaci** [comment]
Again, are you using Agent 1.5.14? See the about screen of Agent, and please update to the latest version if needed.

**Comment by bhaeussermann** [comment]
🤷‍♂️

![2021-07-16_11h46_48](https://user-images.githubusercontent.com/7482216/125928388-f017b430-a87d-49a8-a9dc-4650501e3690.png)

**Comment by mondalaci** [comment]
Can you export and attach your configuration?

**Comment by bhaeussermann** [comment]
[Here it is.](https://www.dropbox.com/s/7swuvjepbxlvvtw/UserConfiguration.json?dl=0)

Some of the macros use Unicode characters in their names. Perhaps that might trigger the bug?

**Comment by mondalaci** [comment]
Thanks, now I can reproduce this! Unicode may be the issue. We'll look into it.
