### ISSUE TITLE
iOS/iPadOS and Android

### ISSUE THREAD

**Issue by tl87** [UltimateHackingKeyboard/agent#1560]
Would it be possible to get the agent as an app for iOS/iPadOS and Android ?

Im sure more and more people are using a keyboard and a mouse with at tablet these days and it would surely help to be able to change settings on the fly with an agent for a mobile os, like iOS/iPadOS and Android.

**Comment by mondalaci** [comment]
I'm sorry, but we don't plan to do this. This would be a monumental undertaking, especially making the UI mobile-friendly, and the demand doesn't justify allocating development resources.
