### ISSUE TITLE
New key cluster module's scroll ball doesn't work consistently

### ISSUE THREAD

**Issue by autonomousapps** [UltimateHackingKeyboard/agent#1561]
I just updated agent and flashed the most recent firmware it was bundled with (8.10.10), and I can still reproduce the issue. I got this key cluster module on Thursday, and the scroll ball often works great for about 2s before the window I'm trying to scroll just stops responding. If I use the external mouse's scroll wheel, that works, and then the cluster can scroll again (for another couple of seconds). Any ideas?

**Comment by mondalaci** [comment]
Can you reproduce this issue with another computer? If so, it's a hardware issue and we should replace your key cluster module.

**Comment by autonomousapps** [comment]
I had the issue on a new Macbook Pro. I've been using the keyboard for a couple of hours now on a laptop running Ubuntu. So far I have not repro'd the issue on the Ubuntu machine, so I think it might be specific to the mbp.

Related to the issue I mentioned, the trackpoint module's left/right lick buttons are inverted on the mbp. They have the expected orientation on the Ubuntu. (I thought this was intentional before trying on the Ubuntu and seeing the layout in Agent.)

**Comment by mondalaci** [comment]
Thanks for your feedback! Please take your time to test this and keep me updated.

**Comment by autonomousapps** [comment]
So far it looks like the modules work perfectly on Ubuntu, but not so
great on macOS. Is there anything else I can do to diagnose or try or
fix? 

On July 31, 2021, GitHub ***@***.***> wrote:
> Thanks for your feedback! Please take your time to test this and keep
> me updated.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UltimateHackingKeyboard/agent/issues/1561#issuecomment-
890479544>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PIFE6GG6KUXFFBGEQTT2UEBPANCNFSM5BKKDQ6A>.

**Comment by autonomousapps** [comment]
I can confirm that the scroll ball on the key cluster module remains very inconsistent on my macbook.

**Comment by mondalaci** [comment]
I'm quite puzzled by this issue. So are you saying that you can consistently reproduce this issue on your MacBook, and cannot reproduce it at all on your Ubuntu laptop?

**Comment by autonomousapps** [comment]
That's what I'm saying. I honestly thought it was just broken, until I
had a lovely experience using it on the Ubuntu. The only thing giving me
trouble now is the scroll ball. 

It's not just an OS thing, though. Because it's a macbook, I have to use
a USB adapter. And because it's a macbook and I have a lot of
peripherals, it actually goes through a powered USB hub. In fact, I
wasn't able to finish flashing the firmware until I plugged it directly
into the macbook (using the adapter, not the hub). 

I originally bought that powered hub on your recommendation 🙂 I was
having other issues and you suggested it would be better than an
unpowered hub. That did resolve my earlier issue. Not sure if it's
implicated here, but I wanted to mention it. 

On August 2, 2021, GitHub ***@***.***> wrote:
> I'm quite puzzled by this issue. So are you saying that you can
> consistently reproduce this issue on your MacBook, and cannot
> reproduce it at all on your Ubuntu laptop?
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UltimateHackingKeyboard/agent/issues/1561#issuecomment-
891759520>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PPXYN5ZIM7Q2AED2Y3T27FQPANCNFSM5BKKDQ6A>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.

**Comment by mondalaci** [comment]
I am really sorry for recommending the USB hub in question. Which model is it?

Can you try to reproduce this issue with your MacBook, but without the hub or with a different hub/adapter/docking station?

**Comment by autonomousapps** [comment]
I don't blame you for recommending using a powered hub. It did solve the problem I was having at the time. I use [this hub](https://www.amazon.com/Powered-BYEASY-Charging-Splitter-Notebook/dp/B07M91R8PN/ref=sr_1_4?dchild=1&keywords=byeasy+usb+hub+powered&qid=1628012389&sr=8-4).

I'll try to use the keyboard directly attached to the mbp. I really hate these things (macbooks).

**Comment by autonomousapps** [comment]
Even when it's connected directly to the mac, it doesn't behave as well as the external mouse. :-/

**Comment by mondalaci** [comment]
This may be a hardware issue. Please shoot an email to support@ultimatehackingkeyboard.com and we'll replace your key cluster module.

**Comment by Pernekhan** [comment]
I have the same issue that @autonomousapps described. 

Steps to reproduce:
1. Have Macbook Pro (not sure if it matters, but mine is macOS Big Sur. Version 11.5.1)
2. Open google docs in the chrome web browser (doesn't work on some other websites too, but google docs is a good example to reproduce)
3. Scroll using cluster key scroll ball (it should work)
4. Pause for 1-5 seconds and try to scroll again (it stops working)
5. Drag the mouse a little bit and try again scrolling (it should work)
6. Pause for 1-5 seconds and try to scroll again (it stops working)

It doesn't seem like a hardware issue. On other websites, it works perfectly fine.

**Comment by mondalaci** [comment]
@autonomousapps Can you make a screencast?

**Comment by autonomousapps** [comment]
I actually got a replacement module and the new one is giving me no trouble.
