### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyActionType' of null

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#157]
I've just tried to remove a keymap unsuccesfully (nothing seemed to happen), then reloaded Agent and got a white screen and this trace:

![untitled](https://cloud.githubusercontent.com/assets/300402/20455331/acbbf61a-ae59-11e6-9156-6e0af41fc15e.png)

Before trying to remove the keymap, I shut down webpack-dev-server which might have contributed to the issue.

**Comment by NejcZdovc** [comment]
Can you reproduce this problem without shutting down the server?

**Comment by NejcZdovc** [comment]
If you shut down the server, then you will not get anything, which is normal.

**Comment by mondalaci** [comment]
I can reproduce the issue without shutting down the server. I've just created a new keymap, renamed it, deleted it, and the error was triggered again.

**Comment by NejcZdovc** [comment]
Which keymap are you using?

**Comment by mondalaci** [comment]
Usually, I:

1. add a new keymap (VIM, or Dvorak)
2. change a key action of the new keymap
3. delete the new keymap

Possibly repeat the above several times, and then the error is triggered.

I've been able to reproduce it about a dozen of times, so I'm confident that this bug is there. I will try to provide you a more accurate reproduction soon.

**Comment by NejcZdovc** [comment]
Ok, thank you

**Comment by mondalaci** [comment]
Finally got it!

1. Clear local storage and reload Agent
2. Add a new Dvorak keymap
3. Remap the backspace key of the Mouse layer of the new Dvorak keymap to move mouse upwards
4. Delete the new Dvorak keymap
5. Boom, an error appears in the console

**Comment by NejcZdovc** [comment]
Ok, I found a very simple reproduction. Assign any action to the empty key. This will trigger an error.

**Comment by NejcZdovc** [comment]
![image](https://cloud.githubusercontent.com/assets/9574457/20461434/663b22ec-aefe-11e6-88d1-41424644bbeb.png)

There are some null values in keyActions and this is a reason for the error.
