### ISSUE TITLE
Agent does not run on CentOS 7

### ISSUE THREAD

**Issue by JalapenoGremlin** [UltimateHackingKeyboard/agent#1571]
Got the new modules, Yeah. Tried to run Agent to download latest firmware... but the AppImage requires a rather new version of libstdc++.so.6

Even setting LD_LIBRARY_PATH to a directory containing a newer version of libstdc++.so.6 does not work. The output fills with the following errors:

[DeviceService] Device connection state query error Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.JCr5AV)

**Comment by mondalaci** [comment]
@JalapenoGremlin Thanks for your report!

@ert78gb Any ideas?

**Comment by mondalaci** [comment]
Closing issue due to the lack of replies. Will reopen if needed.
