### ISSUE TITLE
Random `12345 typing and opening windows

### ISSUE THREAD

**Issue by susanacrai** [UltimateHackingKeyboard/agent#1573]
I already had this issue a while back, but it got solved with a firmware update. Now a couple days ago I got my trackpoint module, and the right/left click were switched and wasn't able to change it, so I updated my keyboard to firmware 8.10.10 and now it is happening more often than ever:

 - It randomly types `12345
 - it opens all the things pined in my taskbar (I am on Windows)

I forced another update & reset settings, but doesn't seem to help either. Is this a known issue?

**Comment by mondalaci** [comment]
The firmware shouldn't affect this issue. Please give a try to [this guide](https://ultimatehackingkeyboard.com/repair/fastening-module-steel-guide-screws).

**Comment by mondalaci** [comment]
Closing this issue due to the lack of replies. I will reopen it if needed.
