### ISSUE TITLE
White splashes during application startup

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1574]
Even when the app uses dark themes it shows white splashes during startup.

This is a very old problem which was (and still is) haunting Firefox, Chrome and many Electron apps.

Could you fix that in the Agent please?

The fix seems to be more or less simple: https://www.christianengvall.se/electron-white-screen-app-startup/

**Comment by mondalaci** [comment]
Thanks for the link! If it can be fixed, we'll fix it.
