### ISSUE TITLE
Nix formula? AppImage doesn't work on nix due to missing /lib64

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1585]
Could you create a nix formula please?

AppImage cannot be run on nix directly due to missing `/lib64` directory:

![image](https://user-images.githubusercontent.com/295225/132077630-10227de6-19f2-4176-97db-d305f437895e.png)

See also: https://github.com/AppImage/AppImageKit/issues/472

**Comment by mondalaci** [comment]
@ert78gb Let's try to solve this in the most general way possible to minimize the maintenance burden. Nix formulas sound like an OS-specific solution which we shouldn't use unless required.

**Comment by pshirshov** [comment]
Well, nix is a very special system, OS-specific solution would be the best one in this case.

**Comment by mondalaci** [comment]
It's hard enough to make Agent work on all three major OSes. I find it quite frustrating and counter-productive to spend extra effort on a single Linux distribution, and according to my memory, it's not the first NixOS-specific issue.

Would #1374 solve this one?

**Comment by pshirshov** [comment]
Probably it would, though you won't be able to distribute necessary udev rules through flatpak. At the same time it's easy to bake a proper nix formulas for both the app and the rules. 

E.g. https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/wooting-udev-rules/default.nix#L18 https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/wootility/default.nix#L38

Yes, apps misbehave on Nix because Nix is very different though it's popular enough, especially among your target audience.

**Comment by anilanar** [comment]
I've been using `nixpkgs.uhk-agent` and `hardware.keyboard.uhk.enable` which internally uses `nixpkgs.uhk-udev-rules` and they've been working fine for a while.

Today, I updated nixpkgs, which incidentally updated `uhk-agent`. 

Version `uhk-agent` v2.1.1.

It fails to open after first run because something is writing readonly files to `~/.config/uhk-agent/smart-macro-docs/UltimateHackingKeyboard/firmware/v9.2.1/`. Then it tries to delete them on subsequent runs. On subsequent runs, I get the following error: 

`[SmartMacroService] can't be started on undefined Error: EACCES: permission denied, unlink '/home/anilanar/.config/uhk-agent/smart-macro-docs/UltimateHackingKeyboard/firmware/v9.2.1/vue.esm-browser.prod.js'`

Workaround: `sudo rm -rf ~/.config/uhk-agent/smart-macro-docs/UltimateHackingKeyboard/firmware/v9.2.1` after every run.

**Comment by anilanar** [comment]
@mondalaci Nix community maintains formulas as long as the original software does not do something unconventional to make it impossible for it to work in Nix. There's already a nix package that is maintained by official nixpkgs so I'd close this issue.

Maybe create a new issue for the problem I report above?

**Comment by mondalaci** [comment]
@anilanar Thanks for reporting this issue!

@ert78gb Can you look into it?

**Comment by ert78gb** [comment]
@anilanar Node does not support `+w` syntax. Will the `0o640` sufficient?
I don't know allow this functionality on every linux or only on nix. If we allow it only on nix. How could we identify nix?
I did not find any npm package

I used the nodejs repl in nixos docker image and I got the following info
`require('os').version()` => `#1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022'` 
`require('os').platform()` => `linux`
`require('os').release()` => `5.15.49-linuxkit`
`process.env` =>
```
{
  SHELL: '/nix/store/8j360n6i7ncyl9a7c3q4v4wlpmcsgqky-bash-interactive-5.2-p15/bin/bash',
  NIX_BUILD_CORES: '5',
  configureFlags: '',
  mesonFlags: '',
  HOSTNAME: '4e8bc64b8053',
  shell: '/nix/store/mh2ga0rzccp2749ar62gmsij8bfajykj-bash-5.2-p15/bin/bash',
  depsHostHost: '',
  STRINGS: 'strings',
  depsTargetTarget: '',
  stdenv: '/nix/store/r9hic2l8zm46j98flpz3rvywvfdv26hf-stdenv-linux',
  builder: '/nix/store/mh2ga0rzccp2749ar62gmsij8bfajykj-bash-5.2-p15/bin/bash',
  NIX_CC_WRAPPER_TARGET_HOST_aarch64_unknown_linux_gnu: '1',
  PWD: '/',
  SOURCE_DATE_EPOCH: '315532800',
  NIX_ENFORCE_NO_NATIVE: '1',
  MANPATH: '/root/.nix-profile/share/man:/nix/var/nix/profiles/default/share/man',
  NIX_PATH: '/nix/var/nix/profiles/per-user/root/channels:/root/.nix-defexpr/channels',
  enableParallelInstalling: '1',
  CXX: 'g++',
  TEMPDIR: '/tmp',
  system: 'aarch64-linux',
  HOST_PATH: '/nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/bin:/nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/bin:/nix/store/6ivyyf7cqfmgy7vgrvmjfdrdxbsir113-findutils-4.9.0/bin:/nix/store/v6za4r23lpz7zxrygab6wkkzw5qjah5s-diffutils-3.9/bin:/nix/store/qx45g8112ghmc84zzjplg76d0dpfahlq-gnused-4.9/bin:/nix/store/ckj3dd75h2n72snwb80sxq4fqgcnsc4q-gnugrep-3.7/bin:/nix/store/151hagfy75fkkj1n4x6afrbnlp2y3jw7-gawk-5.2.1/bin:/nix/store/jmzx3n6pqvjs2jzprzjix203ydaczvs9-gnutar-1.34/bin:/nix/store/n45i0zq093lkbvsqd3rqjyz0pfi4bnya-gzip-1.12/bin:/nix/store/41v94y7l1iip8vxvf1djxxk5wa7ag83a-bzip2-1.0.8-bin/bin:/nix/store/yn1wpa8lg2f3krn1c9m51jhg6a7l9si4-gnumake-4.4.1/bin:/nix/store/mh2ga0rzccp2749ar62gmsij8bfajykj-bash-5.2-p15/bin:/nix/store/na7f3df22wi6p9b361y21crqijf1rsmr-patch-2.7.6/bin:/nix/store/zxmfsaiaqm6q66m5c4vzd62qcwlywqga-xz-5.4.1-bin/bin:/nix/store/1x0zlkwb1dszwxh1aph0y9n4vwqb7k7f-file-5.44/bin',
  enableParallelBuilding: '1',
  IN_NIX_SHELL: 'impure',
  doInstallCheck: '',
  buildCommandPath: '/tmp/nix-shell-91-0/.attr-0',
  HOME: '/root',
  NIX_BINTOOLS: '/nix/store/lsy2yvsz0mwih0cna3mas2lwa0r83bj9-binutils-wrapper-2.40',
  enableParallelChecking: '1',
  GIT_SSL_CAINFO: '/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt',
  depsTargetTargetPropagated: '',
  cmakeFlags: '',
  NIX_SSL_CERT_FILE: '/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt',
  outputs: 'out',
  NIX_STORE: '/nix/store',
  TMPDIR: '/tmp',
  LD: 'ld',
  READELF: 'readelf',
  doCheck: '',
  depsBuildBuild: '',
  TERM: 'xterm',
  SIZE: 'size',
  propagatedNativeBuildInputs: '',
  strictDeps: '',
  USER: 'root',
  AR: 'ar',
  AS: 'as',
  TEMP: '/tmp',
  SHLVL: '2',
  NIX_BUILD_TOP: '/tmp',
  NM: 'nm',
  NIX_CFLAGS_COMPILE: ' -frandom-seed=4h4x9zcbfj -isystem /nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/include -isystem /nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/include',
  patches: '',
  passAsFile: 'buildCommand',
  buildInputs: '/nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1',
  SSL_CERT_FILE: '/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt',
  NODE_PATH: '/nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/lib/node_modules',
  depsBuildTarget: '',
  OBJCOPY: 'objcopy',
  out: '/nix/store/4h4x9zcbfj95p74f5wsvg6dm1qf4inx3-shell',
  STRIP: 'strip',
  XDG_DATA_DIRS: '/nix/store/d4g9v30s6c8dfzw16brzjzjkp9pcl9x0-patchelf-0.15.0/share',
  TMP: '/tmp',
  OBJDUMP: 'objdump',
  PATH: '/nix/store/8j360n6i7ncyl9a7c3q4v4wlpmcsgqky-bash-interactive-5.2-p15/bin:/nix/store/d4g9v30s6c8dfzw16brzjzjkp9pcl9x0-patchelf-0.15.0/bin:/nix/store/l7dl288f0hv1ckyyh05x1v3am127pk0g-gcc-wrapper-12.2.0/bin:/nix/store/dnibkvsbrzs03av2ki2njly3svz7z3bj-gcc-12.2.0/bin:/nix/store/xx8ip67nkbdq1r5zalkgk16vim30dzxa-glibc-2.35-224-bin/bin:/nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/bin:/nix/store/lsy2yvsz0mwih0cna3mas2lwa0r83bj9-binutils-wrapper-2.40/bin:/nix/store/2m3zjclc2cxznkhf1z99771rysj1048l-binutils-2.40/bin:/nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/bin:/nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/bin:/nix/store/6ivyyf7cqfmgy7vgrvmjfdrdxbsir113-findutils-4.9.0/bin:/nix/store/v6za4r23lpz7zxrygab6wkkzw5qjah5s-diffutils-3.9/bin:/nix/store/qx45g8112ghmc84zzjplg76d0dpfahlq-gnused-4.9/bin:/nix/store/ckj3dd75h2n72snwb80sxq4fqgcnsc4q-gnugrep-3.7/bin:/nix/store/151hagfy75fkkj1n4x6afrbnlp2y3jw7-gawk-5.2.1/bin:/nix/store/jmzx3n6pqvjs2jzprzjix203ydaczvs9-gnutar-1.34/bin:/nix/store/n45i0zq093lkbvsqd3rqjyz0pfi4bnya-gzip-1.12/bin:/nix/store/41v94y7l1iip8vxvf1djxxk5wa7ag83a-bzip2-1.0.8-bin/bin:/nix/store/yn1wpa8lg2f3krn1c9m51jhg6a7l9si4-gnumake-4.4.1/bin:/nix/store/mh2ga0rzccp2749ar62gmsij8bfajykj-bash-5.2-p15/bin:/nix/store/na7f3df22wi6p9b361y21crqijf1rsmr-patch-2.7.6/bin:/nix/store/zxmfsaiaqm6q66m5c4vzd62qcwlywqga-xz-5.4.1-bin/bin:/nix/store/1x0zlkwb1dszwxh1aph0y9n4vwqb7k7f-file-5.44/bin:/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin',
  propagatedBuildInputs: '',
  CC: 'gcc',
  NIX_CC: '/nix/store/l7dl288f0hv1ckyyh05x1v3am127pk0g-gcc-wrapper-12.2.0',
  NIX_BINTOOLS_WRAPPER_TARGET_HOST_aarch64_unknown_linux_gnu: '1',
  depsBuildTargetPropagated: '',
  depsBuildBuildPropagated: '',
  CONFIG_SHELL: '/nix/store/mh2ga0rzccp2749ar62gmsij8bfajykj-bash-5.2-p15/bin/bash',
  __structuredAttrs: '',
  RANLIB: 'ranlib',
  NIX_HARDENING_ENABLE: 'fortify stackprotector pic strictoverflow format relro bindnow',
  NIX_LDFLAGS: '-rpath /nix/store/4h4x9zcbfj95p74f5wsvg6dm1qf4inx3-shell/lib ',
  nativeBuildInputs: '',
  name: 'shell',
  depsHostHostPropagated: '',
  _: '/nix/store/k9a5drkfbs9989mi9hqm6s7hfa79bivl-nodejs-16.19.1/bin/node'
}
```

The environment variables contains many promising values that start with `NIX_`. Is there one key that always exists on nixos?  The `NIX_PATH` seems obvious, but could you confirm?

**Comment by anilanar** [comment]
@ert78gb Ideally, you should avoid anything related to Nix.

I think you should focus on solving it for any Linux distro where installation directory is readonly. You can achieve that by modifying uhk-agent's directory to readonly recursively by removing write permissions. Then run `uhk-agent`, close it and run it again. It should fail on the second run.

**Comment by anilanar** [comment]
@ert78gb Try download the app image from releases, then try extract it using `AppImage` as documented [here](https://docs.appimage.org/user-guide/run-appimages.html#extract-the-contents-of-an-appimage). Make the directory recursively readonly with something like `chmod -R -w`. If you have anything in `~/.config/uhk-agent`, you should delete that before.

Then try running uhk-agent twice.

**Comment by anilanar** [comment]
@ert78gb Did you check experimental `fs.copy` with `recursive: true` option? Because this is a `fs-extra` "bug". https://nodejs.org/api/fs.html#fspromisescpsrc-dest-options That would probably solve the problem.

**Comment by ert78gb** [comment]
Agent writes the smart-macro documentation to the configuration folder of the application. 
We do it to 
- make the documentation available if the computer not connection to the Internet
- don't download the documentation everytime when the user opens the macro documentation after Agent started

As far as I know every OS supports the application config folder logic.
The only problem is the smart-macro folder is readonly when the source folder is readonly. Only nix users reported this problem so I my idea to run the `chmod` only when necessary.

I will try your AppImage installation.
I have to check `fs.copy` is available in the electron that we use or not.

**Comment by anilanar** [comment]
> The only problem is the smart-macro folder is readonly when the source folder is readonly.

That is because `fs-extra`'s `copy` has extra logic to preserve permissions. Normally, `cp` in Linux or `xcopy` in Windows do not preserve permissions. So if `uhk-agent` used anything else other than `fs-extra`, it will work for everybody.

**Comment by ert78gb** [comment]
I just know tested on mac and `fs-extra` does not preserve permissions. I am checking `fs.copy` on linux

**Comment by ert78gb** [comment]
Please ignore 
> I just know tested on mac and `fs-extra` does not preserve permissions. I am checking `fs.copy` on linux

`fs.extra` works the same way on linux and mac. Unfortunately, `fs.copy` do the same on both OS.

Looks like, run `chmod` after the copy will be the solution

**Comment by mondalaci** [comment]
Should be fixed in the latest release.
