### ISSUE TITLE
Two-action touchpad configuration?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1586]
My mouse-related firmware PR works with two configurable touchpad actions rather then one. (Specifically one-finger-tap and two-finger-tap.)

The proposal is to:
- Allow both these actions to be configured via Agent.
- Make sure that if a loaded config does not specify second touchpad action (i.e., not present in the config at all rather than set to "none"), Agent automatically sets it to right-click.

**Comment by mondalaci** [comment]
I can't think of a good way of exposing both of these actions in Agent, so I'd much rather make one-finger-tap directly configurable the usual way, and make two-finger-tap configurable via smart macros. I agree that two-finger-tap should default to right-click.

**Comment by kareltucek** [comment]
You mean just interface-wise?

That's really not a hard problem. I would much rather avoid unnecessary branching and special-case handling of keys in the firmware... On firmware level, just simply using first two actions (like any other module) and handling them like any other key works just nicely. 

Apart from that, I find configuring this via smart macros more problematic for number of reasons.

![touchpad_gestures](https://user-images.githubusercontent.com/3447497/132725875-36c5fced-6117-498b-811f-5e3f68ccfeff.png)

**Comment by mondalaci** [comment]
When it comes to the UI, I've already thought of the visualization you suggested, but I don't consider it clean, I don't think many users will use double-tapping, and we'll have to add touchpad-specific smart macros anyway.

**Comment by kareltucek** [comment]
This is more about regularity and simplicity of the entire design than actually about making it configurable.

My point is - having the two actions exist as regular actions which are part of regular keymap actually makes thing simple on firmware level. Having them both configurable via Agent then sounds as a logical way of fitting all the puzzle pieces together.

Regarding smart macros, I don't see your point. All other touchpad settings are global settings of navigation modes, while this is inherently keymap-local setting of key actions.

But let's assume that I am giving up. Does at least the second request of the original comment sound reasonable (on agent side), or should I modify the firmware config deserializer to "rewrite" the second action to right click on each touchpad keymap load? (Sounds ridiculous to me, but whatever...)

**Comment by mondalaci** [comment]
There's a touchpad-specific setting I can think of. The way I foresee it, the zoom and unzoom events will translate to ctrl+/- and cmd+/- on non-Mac vs Mac computers respectively. Maybe it'd be practical to emit both ctrl+ and cmd+ on zoom and both ctrl- and cmd- on unzoom events, but I'm not sure how well it'd work out. And there may be other module-specific settings that make practical sense that we can't think of yet.

Eventually, it may make practical sense to expose dedicated, module-specific configuration UIs via Agent, but in these early days, we can't be sure which settings make practical sense.

Using two action slots for the touchpad and defaulting the two-finger-tap slot to right-click make sense to me.

**Comment by kareltucek** [comment]
> There's a touchpad-specific setting I can think of. The way I foresee it, the zoom and unzoom events will translate to ctrl+/- and cmd+/- on non-Mac vs Mac computers respectively.  Maybe it'd be practical to emit both ctrl+ and cmd+ on zoom and both ctrl- and cmd- on unzoom events, but I'm not sure how well it'd work out. And there may be other module-specific settings that make practical sense that we can't think of yet.

The way I see this, zooming is just another navigation mode that emits ctrl +/-.

I haven't thought about Mac though. Not sure hot to deal with that, but LCtrl+LGui+<+/-> does not trigger zoom in my firefox. (Which makes sense, because Gui is generally reserved for window manager operations.)

> Using two action slots for the touchpad and defaulting the two-finger-tap slot to right-click make sense to me.

So do you prefer doing that (defaulting) on agent side, or on firmware side?

**Comment by mondalaci** [comment]
I don't think about zooming as another navigation mode. I'd make pinch to zoom default to the mentioned shortcuts regardless of the layer used because per-layer pinch to zoom navigation modes would be rather overkill and probably not very useful.

I'd default to right-click for two-finger-tap on the firmware level.

**Comment by kareltucek** [comment]
> I don't think about zooming as another navigation mode. I'd make pinch to zoom default to the mentioned shortcuts regardless of the layer used because per-layer pinch to zoom navigation modes would be rather overkill and probably not very useful.

I am not implying that it should be per-layer configurable. 

I mean that the signal-processing subsystem that we already use for navigation mode handling (including axis locking, caret mode, axis-locked scroll mode, etc) is suitable for this use too. Suffices to add a new instance of `caret_configuration_t` (which defines the two actions), and call `processModuleActions` with fixed `NavigationMode_Zoom` parameter. The feature is basically for free, and we get decent fine-tuning abilities on top totally for free.

**Comment by kareltucek** [comment]
> I'd default to right-click for two-finger-tap on the firmware level.

So this solves the ticket. Will hard code it into the config deserializer...
