### ISSUE TITLE
[Feature request] Add touchpad module support for two- finger scrolling

### ISSUE THREAD

**Issue by bonstio** [UltimateHackingKeyboard/agent#1587]
As alluded to here [https://ultimatehackingkeyboard.com/manuals/touchpad], at some point the touchpad module will support two-finger scrolling. I'm creating this issue to track this feature request

**Comment by mondalaci** [comment]
Closing this issue as a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/387
