### ISSUE TITLE
Browser-based agent with webusb?

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1588]
Actually that may be a better option than to support multiple OSes. Or a relatively simple addition to existing agents.

WebUSB allows browsers to communicate with USB devices, it's even possible to flash an Android phone through a webpage.

**Comment by mondalaci** [comment]
We're well aware of WebUSB and considered it a while back, but Agent will become an (optional) background application providing advanced features, like cross-device communication, and Electron is much better suited for this purpose than a web application running in a browser. As for mobile, the UI is desktop-optimized, and it'd take a huge work to optimize it for mobile screens. I don't want to allocate extra resources for WebUSB for the time being.
