### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by comradekingu** [UltimateHackingKeyboard/agent#1589]
Hoping to see this project offered for translation on Weblate.
hosted.weblate.org is gratis for projects with a libre license, which https://github.com/UltimateHackingKeyboard/agent/blob/master/LICENSE isn't.

Since that is a CLA that could be changed though. I don't see a reason not to use an established license, nor why it should only be used on UHK.

**Comment by mondalaci** [comment]
I'm sorry, but we don't want to spend any resources on translating Agent.
