### ISSUE TITLE
Remove "keymap" from the title

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#16]
If you check the application UI, and click on the "Factory keymap" then the editor interface's title will say
"_Factory keymap_ keymap (_FTY_)". Which is weird. For this reason I propose removing the static (non-editable) "keymap" from the title. Here are some examples without it:

- Factory keymap (FTY)
- QWERTY (QTY)
- Dvorak (DVR)
- VIM (VIM)
- Mortal Kombat X (MKX)

**Comment by csanyiarpad** [comment]
As the "Factory keymap" will be non-editable at all, which means that all the title will be static as well. As the user cannot modify the title, we can remove from it the the duplicate "keymap" keyword, and leave it everywhere else. This way the title will be more self-explanatory.

This way this issue will be a guidance for the implementation phase.

**Comment by mondalaci** [comment]
Very good point, and totally agreed, but first we should port Agent to Angular 2 because the hard-to-maintain jQuery codebase is getting larger and larger, and porting is imminent and unavoidable anyways.
