### ISSUE TITLE
Losing last console lines during firmware flashing when new Agent version message comes up

### ISSUE THREAD

**Issue by Jopie01** [UltimateHackingKeyboard/agent#1603]
Today I started the UHK agent to update the firmware on my UHK keyboard. So I go to `Firmware` and clicked on `Choose firmware file and flash it`, selected the downloaded most recent firmware and started flashing.

During flashing the message came up `A new Agent version has been released`. This message moves down the whole app and because of the size of the window, it added an extra scrollbar. So I lost the last lines of the flash console. See my screenshot.
![screenshot](https://user-images.githubusercontent.com/8482525/139529340-48750f73-c32f-4588-bb14-af8ac1a4758d.png)

**Comment by mondalaci** [comment]
@Jopie01 Thanks for reporting! We appreciate it and will fix it.
