### ISSUE TITLE
Feature request: Add a popup note for each keys

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [UltimateHackingKeyboard/agent#1608]
We can define many keymaps, and many layers could be defined for each keymap. We may create a keymap just for an application. As time goes by, we'll have a lot of shortcuts defined for different keys on different layers. Sometime I find a shortcut was defined on a key but I cannot remember what it is used for. Is it possible to add a note field when users are defining what should happen when a key get pressed. When the mouse hover over on the key, the note pops up so the user know what it is for. Imo this will make the program more useful.

**Comment by mondalaci** [comment]
Thanks for your suggestion!

This feature hasn't been requested yet, so it doesn't justify the development resources needed, but we'll reconsider if the interest is significantly higher.
