### ISSUE TITLE
Display the Remap Key button as disabled whenever input is invalid

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#161]
Currently, the key Remap Key button of the key action popover doesn't do anything when the content of the popover is incomplete which is correct. But we should also visually disable the button whenever the input is invalid.

**Comment by NejcZdovc** [comment]
As far as I can see in the code we only validate selection after you click on remap button, so we would need to change the logic to trigger validation on every click and selection, which can be very expensive and time consuming. What I would do instead is display error message when you click on remap button. 

Something like this:

![image](https://cloud.githubusercontent.com/assets/9574457/20461784/9c314a48-af08-11e6-9a90-35693994a887.png)

**Comment by mondalaci** [comment]
I'd rather stick to my proposal because I believe it's more intuitive for the user. It it's such a pain to implement then we can do it later.

**Comment by NejcZdovc** [comment]
Then I would move this task to milestone 0.9.

**Comment by mondalaci** [comment]
So be it.

**Comment by NejcZdovc** [comment]
We need to validate keypress and mouse tab.
