### ISSUE TITLE
Two different configurations are both shown as "current"

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#1612]
Updated to Agent 1.5.16.
When I went to Configuration (Device Configuration), two different configurations are both shown as "current".
That cannot be right, can it?

![image](https://user-images.githubusercontent.com/591785/140323992-4cbaf5ed-c2c7-4c66-b73d-1fbe4b03d732.png)

I am not sure if that would also have shown up on the previous Agent 1.5.15. Did not check the page before the upgrade.

**Comment by mhantsch** [comment]
After saving the configuration one more time to the UHK v1, the duplicate "Current" issue went away.

**Comment by mondalaci** [comment]
This is hardly a bug. Your older Current configuration must be the same as your latest Current configuration.

**Comment by mhantsch** [comment]
So if it's not a bug, why does it look like this today?

Same Agent on same Laptop as previously, but now connected to my other UHK... just did a FW upgrade from 8.10.11 to 8.10.12, then opened the Configuration page.

![image](https://user-images.githubusercontent.com/591785/140889606-1bcfc7db-9b02-4dfd-a902-36d4e0ab0462.png)

There must be some kind of bug, this just doesn't seem right. Not saying that it's high priority (I realise all the other stuff you are working on), but something's definitely weird.

**Comment by mhantsch** [comment]
Especially: why is the latest configuration not "Current"?

**Comment by mondalaci** [comment]
Agent reads the configuration of your UHK, and it makes a hash of it. Then it compares the computed hash with the hashes of the entries of the configuration history. If the two hashes match, Agent displays "Current".

Given the above, do you think Agent works properly?

**Comment by mhantsch** [comment]
> Given the above, do you think Agent works properly?

I see, thanks for the explaination. I now understand how it works, and it definitely works as designed.
It was confusing to me that the latest was not "current", and why would older versions be named "current".

Perhaps the simplest solution is to name them "identical to current configuration" or "same as current". That would make it clear to me.

**Comment by mondalaci** [comment]
Thanks for the suggestion! I agree with you, and we'll display "Same as current" for every current row after the first "Current" row.
