### ISSUE TITLE
Can't save a new keymap to UHK

### ISSUE THREAD

**Issue by seblovett** [UltimateHackingKeyboard/agent#1619]
When adding a fresh keymap, the option to save the configuration to the UHK isn't available. The ability is lost until Agent is restarted. 

Agent version: 1.5.16
Firmware version: 8.10.12

Steps to reproduce: 
1. Connect UHK. 
2. Open Agent
3. Click the + next to Keymaps
4. Select a keymap and click "Add keymap" button.
5. New keymap is added and is shown in the side bar. 
6. "Save to keyboard" button does not appear in the bottom right corner. 
7. Modifying existing maps doesn't cause the save button to reappear. 
8. Agent must be restarted to fix. 

Expected behaviour: should be able to save the new configuration. 

Work around: use "Duplicate keymap" from an existing keymap to make a new keymap. 

Interestingly, if you do the work around (without saving) and then add a fresh keymap, the save button doesn't disappear. Pressing save then results in an error popping up saying '"value" argument is out of bounds'. 

Thanks

**Comment by mondalaci** [comment]
I can't reproduce this issue. Please attach your configuration, and let us know which keymap you're trying to add.

**Comment by seblovett** [comment]
Hi, Thanks for looking - I will do so when I can. It was the QWERTY for PC map I was adding. I'll double check and export my starting config for you. 
Cheers,

**Comment by seblovett** [comment]
Attached is my current config. 
All I am doing is pressing the + next to keymaps, clicking "Qwerty for PC" and "Add keymap". No save button appears
Please let me know if I can get more debug out for you. Thanks!

![image](https://user-images.githubusercontent.com/3463538/141550435-ada8513a-cbc8-4704-9588-45d3a78a13d3.png)


[UserConfiguration.zip](https://github.com/UltimateHackingKeyboard/agent/files/7530742/UserConfiguration.zip)

**Comment by mondalaci** [comment]
Thank you! I could easily reproduce the bug using your configuration, and the bug also messes up the configuration page.

![image](https://user-images.githubusercontent.com/300402/141674037-d63b8d79-667f-4701-99f3-8cce02f2be3b.png)

**Comment by IzK666** [comment]
Hi.
May I ask which module has an id=5 with a single button?
If I'm not mistaken, there is only 4 different kind of modules: 0 (right keyboard), 1 (left keyboard), 2 (left module/keycluster) and 4 (right module).

**Comment by mondalaci** [comment]
@IzK666 You are referring to slots, not module ids, and I don't see how they're related to this issue. I plan to add further slots, but I don't want to make their purpose public yet.

**Comment by kareltucek** [comment]
> Hi. May I ask which module has an id=5 with a single button?

https://github.com/UltimateHackingKeyboard/firmware/issues/364

**Comment by Glutnix** [comment]
I am also suffering from the same issue described above by @seblovett.
