### ISSUE TITLE
In-place editable macro commands

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1630]
I expect users to edit quite a few macro commands, especially when experimenting with them first. Unfortunately, the UI is not well suited for such a task.

![image](https://user-images.githubusercontent.com/300402/142760010-411c8387-2d86-43d2-975f-4be8e99781e8.png)

According to the following image, the content of the inner rectangle which contains the macro commands should be in-place editable and the `cursor` style should be `text`.

![image](https://user-images.githubusercontent.com/300402/142760180-f79cbe95-701d-41cb-9a5f-4153cf3874b5.png)

**Comment by mondalaci** [comment]
Let's use the Monaco editor for this purpose instead of a textarea. Syntax highlighting and IntelliSense will be a pleasure to use.

**Comment by kareltucek** [comment]
> Let's use the Monaco editor for this purpose instead of a textarea. Syntax highlighting and IntelliSense will be a pleasure to use.

How do you plan to distribute the grammar? The way I see it, it could be either packed within a release .tar, or even might be included in the compiled firmware itself (current grammar in my informal notation currently takes 9kb, and would eat only m_text region which is big enough).

Have you yet managed to go through the Monarch definition? I am not yet sure how suitable it actually is for our purposes.

**Comment by mondalaci** [comment]
Haven't looked into the Monarch definition, but given the large number of supported languages of Visual Studio Code, it must be sufficiently powerful for our needs.

As for the exact grammar, I'd default to the grammar of the firmware bundled with Agent and use an alternative grammar fetched from GitHub according to ${forkRepo} and ${forkSmartMacroVersion} if specified according to my macro versioning proposal.

**Comment by kareltucek** [comment]
> it must be sufficiently powerful for our needs.

Not as simple as that. Will get in touch about it later (although not necessarily soon).

> fetched from GitHub according to ${forkRepo} and ${forkSmartMacroVersion}

Dtto - will get in touch about the versioning proposal soon. Quick impression - I am thinking whether using ${forkRepo} and ${tag} might be feasible and more convenient.
