### ISSUE TITLE
Linux AppImage for 1.5.17 grew by 20MB / 25% compared to 1.5.16

### ISSUE THREAD

**Issue by fastcat** [UltimateHackingKeyboard/agent#1633]
Looking at the release notes for v1.5.17, there's nothing that seems like it would explain a +20M / +25% size increase of the application. Did something go wrong in the build/release process and accidentally include excess material?

```
-rwxr-xr-x 1 x x  82498258 Nov 17 20:06 UHK.Agent-1.5.16-linux-x86_64.AppImage
-rwxr-xr-x 1 x x 103699817 Nov 24 14:06 UHK.Agent-1.5.17-linux-x86_64.AppImage
```

**Comment by mondalaci** [comment]
Good catch! Any insights, @ert78gb?

**Comment by ert78gb** [comment]
We upgraded many component for example electron from 13.2.1 to 16.0.1. The following table shows the electron size changes

| Name | Size |
| ------ | ---- |
| electron-v13.2.1-linux-x64.zip | 73.9 MB |
| electron-v16.0.1-linux-x64.zip | 94.2 MB |
