### ISSUE TITLE
Macro Mouse Action - Move Pointer

### ISSUE THREAD

**Issue by bistabil** [UltimateHackingKeyboard/agent#1634]
Moving the pointer action was never accurate for me.
I was able to get the pointer where I want to but not by using absolute coordinates on the screen.

How does this actually work and is it documented somewhere?
Is it dependant on screen size or something else?

When I am creating macros where I need to move the pointer to someplace I always work with absolute coordinates so every action becomes two actions, the first one being something like move to -3840, -2560 to make sure I would be in one of the corners on 4k display followed by second action having absolute x and y.
Getting the second one to move the pointer exactly where I want to is always a game of trial and error.

**Comment by kareltucek** [comment]
You can try adding some delay between the two mouse movement commands.

**Comment by mondalaci** [comment]
@bistabil Karel is spot on. The UHK outputs raw USB coordinates, but it's up to the OS to translate them to actual coordinates based on your OS driver and mouse settings.
