### ISSUE TITLE
Add change keymaps in macro action. [feature request]

### ISSUE THREAD

**Issue by brianhsu** [UltimateHackingKeyboard/agent#1643]
I have a KMV (Keyboard / Mouse Switch) that support keyboard shortcut switch.
Which means when I press certain key combination, it will switch my UHK between two computers.
Macro works fine after I bind those sequence to function layer, and it does work.

The only problem is that since I'm switching between PC / MacBook, and they use different keymaps in my UHK.

So if I want to switch to my MacBook, I actually need to do two steps:
1. A key combination to tell KVM switch my UHK to MacBook.
2. A key combination to tell UHK to switch to Mac keymap.

It works, but I think if there is an action in Macro that can change current UHK keymap, it will be very useful. And I could switch between my PC / MacBook efficiently with just one key combination.

**Comment by mondalaci** [comment]
Thanks for the suggestion! I plan to merge the suggested feature from https://github.com/kareltucek/firmware

**Comment by brianhsu** [comment]
Wow, thanks! I didn't noticed there is firmware fork support this feature.
It works perfectly for my use case. I will use this firmware fork until it got into main firmware / agent.
Thanks.

**Comment by brianhsu** [comment]
This is already possible using Agent 2.0.0's smart macro feature. :-)
Close this ticket.
