### ISSUE TITLE
Add empty keymap to available keymaps

### ISSUE THREAD

**Issue by kour1er** [UltimateHackingKeyboard/agent#1646]
I love the new default keymap selection in Agent - would it be possible to add a blank one? My use case being if I want to create a dedicate keymap for say just media playback and no other keys to be able to start from a blank state would be really useful.

Cheers

**Comment by mondalaci** [comment]
Thanks for the suggestion! We'll add a new "Empty" keymap at the bottom of the available keymaps list.
