### ISSUE TITLE
Large input delay after enabling caps lock

### ISSUE THREAD

**Issue by dustinpaluch** [UltimateHackingKeyboard/agent#1659]
With the versions below, and a reset device configuration, I press Mod + a to enable caps lock.

I expect the caps lock indicator light on the keyboard to light immediately and to be able to type immediately.

Instead, there is a roughly 5 second delay before the indicator lights up, and no text-creating keypresses (pressing "a" with no modifiers repeatedly) register until the 5 seconds pass and the indicator lights up. 

There is a similar experience when trying to disable caps lock.

MacOS 11.6
Agent 1.5.16
Right keyboard half firmware: 8.10.12
Left keyboard half firmware: 8.10.12
Key cluster firmware: 8.10.9

**Comment by mondalaci** [comment]
Does https://superuser.com/questions/317900/eliminate-macbook-capslock-delay/1224132 help?

**Comment by dustinpaluch** [comment]
Overnight, without restarting my computer or changing UHK config, it seem to have resolved itself.
