### ISSUE TITLE
Scroll sensitivity on key module

### ISSUE THREAD

**Issue by eletoblade** [UltimateHackingKeyboard/agent#1661]
Is there any way to change the key cluster's scroll speed? When I change the scroll speed under the "Device" section of Agent it does not seem to change the module's scroll speed. If not could a specific setting for the module be added? I'm thinking it would be good to have separate scroll speeds for when a button is pressed to scroll and when the module's scroll wheel is used.

**Comment by mondalaci** [comment]
Module speed settings will be possible via [smart macros](https://github.com/UltimateHackingKeyboard/firmware/issues/351). Please look for the next Agent and firmware release.
