### ISSUE TITLE
Difficult to use modifiers with the arrow keys

### ISSUE THREAD

**Issue by dustinpaluch** [UltimateHackingKeyboard/agent#1672]
I love that Mod + ijkl is used for the arrow keys, but I need a way to directionally switch windows in Emacs, and I'd like to use ijkl with some modifier combo to do this. The trouble is that shift + arrow keys, option + arrow keys, ctrl + arrow keys, and super + arrow keys are all already in use by macOS. 

My hope was to use a ctrl + alt + shift + arrow key binding in emacs, but holding all of those and Mod to activate the arrow key layer is not easy at all. I tried to see if I could bind a single key to ctrl + alt + shift + Mod, such that holding it and pressing ijkl would send ctrl + alt + shift + arrow keys, but I found that I can't add Mod as a "Modifier" when mapping a key to a Keypress. 

My workaround will be to turn a key into just a ctrl + alt + shift modifier, and then just use literal ctrl + alt + shift + ijkl bindings in emacs, but it remains a problem that using the arrow keys with various modifier combinations is difficult. 

I think this would be solved by #617, because then I could have one key activate a layer, and then map ijkl in that layer to ctrl + alt + shift + arrow keys and that would be great, so feel free to close this with a mention to that issue. 

Thanks!

**Comment by mondalaci** [comment]
Mod is not a modifier, but a layer switcher, and it's not received by the OS.

I'm unsure what you're trying to achieve exactly, but binding Fn+{i,j,k,l} to Ctrl+Alt+Shift+{i,j,k,l} might be a viable solution.

**Comment by dustinpaluch** [comment]
Right, but as I want my computer to receive Ctrl+Alt+Shift+arrow keys, that's three individual modifier keys I have to hold down as well as Mod to switch layers so that ijkl become the arrow keys, and my first thought was "maybe Agent has a way to activate the Mod layer _and_ one or more modifier keys with a single keypress", but it does not. Not sure if it would be wise to add that as a feature or not in the grand scheme of things, but **being able to activate a UHK layer and a modifier key with one button** seems useful to me.

Your solution would work just as well as my workaround, but I like the existing ijkl bindings on Fn, so I'll stick with my idea. 

So, I have a workaround for my specific issue, and having more custom layers from #617 would also facilitate this, so you're welcome to close this unless the bolded text above seems worthy of an open issue/feature request. 

Thanks!

**Comment by mondalaci** [comment]
Thanks for elaborating! I'm closing this issue as it's a niche feature, but take a look at [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) because it may provide what you're after.
