### ISSUE TITLE
ValidatedUserConfig from eeprom error Error: Communications error with UHK. Response code: undefined

### ISSUE THREAD

**Issue by leo-lb** [UltimateHackingKeyboard/agent#1680]
Hello!

With latest agent to date I am unable to configure my recently received keyboard, see attached log and screenshot.

Any ideas?

Thanks

![Screenshot from 2022-01-26 15-48-24](https://user-images.githubusercontent.com/44934014/151186252-b1e7d9f2-004a-4472-b3c9-3664f72757c0.png)
[uhkagent.log](https://github.com/UltimateHackingKeyboard/agent/files/7942694/uhkagent.log)

**Comment by mondalaci** [comment]
Hi there!

1. Which Agent version are you using?
2. Can you consistently reproduce this issue on multiple computers?
3. Can you reproduce this issue with [Agent 1.5.16](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.5.16)?

**Comment by mondalaci** [comment]
Closing due to the lack of replies.
