### ISSUE TITLE
[Feature request] introduce double tap

### ISSUE THREAD

**Issue by achikin** [UltimateHackingKeyboard/agent#1684]
I have some hotkeys assigned to arrows + some modifier like Ctrl and it's very inconvenient to press 3 keys instead of 2.
I think allowing to redefine double tap on the keys could help a bit. Like right arrow could be triggered by jj and so on.

**Comment by mondalaci** [comment]
The suggested solution would introduce noticeable lag on the J key when not double-tapping it.

In any case, please feel free to check out [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) which may contain such a feature.

**Comment by mondalaci** [comment]
I should also mention that we'll keep adding features from Karel's fork in the future.

**Comment by kareltucek** [comment]
> In any case, please feel free to check out [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) which may contain such a feature.

(Search for `ifShortcut`. Still, my guess is that double l and e will interfere heavily with writing.)
