### ISSUE TITLE
Communication with error with UHK. Response code: undefined

### ISSUE THREAD

**Issue by eugie512** [UltimateHackingKeyboard/agent#1685]
Running agent version 1.5.17. Whenever I make any change to the contribution and press "Save to keyboard", I:
1. See the error in the title
2. The keyboard no longer responds (I also have the trackpoint module and that stops working as well)

Unplugging and replugging the keyboard brings it back.
<img width="880" alt="Screen Shot 2022-02-01 at 07 32 39" src="https://user-images.githubusercontent.com/365340/151998855-1ce1a92c-b54c-4af5-8d64-fb74d26229cb.png">

**Comment by kareltucek** [comment]
Also, what is your *firmware* version?

**Comment by mondalaci** [comment]
Closing this issue due to the lack of replies.
