### ISSUE TITLE
Per-key colors

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1688]
### User configuration

Per-key colors will modify the user configuration, bumping its major version.

Let's add `uint8 backlightingMode` after `keyBacklightBrightness` in `UserConfiguration`. The valid enum values for this variable are `FunctionalBacklighting` and `PerKeyBacklighting`.

Following `backlightingMode`, add 8 RGB colors according to https://github.com/UltimateHackingKeyboard/firmware/blob/ff307571bcb38f54977daadbecb41455b19f642a/right/src/ledmap.c#L13-L20 and use these values as defaults. RGB colors are composed of 3 uint8 values.

Also add `ledColors[]` after `keyActions[]` in `Module`, and make it contain as many RGB values as keyActions if `backlightingMode === PerKeyBacklighting`, otherwise make its length 0.

### Settings UI

Rename the "LED brightness" page to "LED settings" including its header, filename, and side menu name.

Put the 3 sliders of the page next to each other in a 3 x 1/3 layout and add a "LED brightness" h3 header above them.

Below the sliders, add a "Backlighting mode" h3 header, and add the following radio buttons:

- Functional backlighting
- Per-key backlighting

Add a "Functional backlighting colors" h3 header below the above, list the referenced 8 color names in a 4x2 grid. Make borders around the colors, and adjust their background color according to the set colors. Set the text color of these rectangles to be the inverse of the background colors. Set the cursor style to pointer above the rectangles and open a color picker when clicking them. I like [this color picker](https://mdbootstrap.com/docs/b4/jquery/plugins/color-picker/), but others may also work.

### Color editor UI

When per-key backlighting is enabled, add a button group on the keymap page rightward of the layer button group.

Make the button group responsive, and position it under the layer button group there's not enough horizontal space available.

Display "Colors: " leftward of the button group, just as in the case of "Layers: ". Make the first 8 buttons of the button group square-shaped and make their background contain their relevant colors. Let's default to the colors of the functional backlighting, but these colors don't affect functional backlighting in any way; they're just defaults. Make these palette colors part of Agent's configuration.

Rightward of the color squares, add a font awesome plus button in the button group. When hovering on the plus button, display a tooltip for it saying "Add color to the palette.". When clicking on the plus button, invert it and display a "Click on a key to add its color to the palette." tooltip. When clicking on a key, add a new color to the palette, make the tooltip disappear, and de-invert the plus button.

When selecting a color from the palette,
1. put a font awesome check icon into it the palette color
2. animate the color of all keys of the UHK to their relevant color, and add a gray border around them
3. add a new button to the color button group displaying "Finish editing"

In color editing mode, after the plus icon, add a trash icon to the button group. When hovering over it, display the tooltip "Delete current palette color.", and make it behave accordingly.

In color editing mode, left-clicking on a key changes its color to the current palette color. The user can hold the left mouse button and paint multiple keys this way.

When clicking on the "Finish editing" button, restore the 3 changes listed above.

### Out of space UI

When backlighting mode is set to functional backlighting but the configuration contains per-key backlighting that the user has previously set, display a yellow (bootstrap warning color) "Recover LED space" button between the "Import device configuration" and "Reset device configuration" buttons. When hovering over the button, display the following tooltip "Per-key backlighting was previously active, but it's not used anymore, and per-layer LED colors still occupy {space} bytes on-board storage which you can recover.". When clicking on the button, display a confirmation popover with the "Do you want to recover {space} bytes on-board storage by deleting per-key backlighting colors?" message.

When the bottom out of space notification bar appears, instead of the "Delete some keymaps or macros to be able to save your configuration." sentence, display "[Switch to functional backlighting] and [recover per-key backlighting space], or delete some keymaps or macros to be able to save your configuration." - If per-key backlighting is active, display the first part and link it to the LED settings page. If per-key backlighting is present in the configuration, display the second part and link it to the configuration page. If only the second part is visible, don't include "and" and capitalize "recover".

**Comment by ak3io** [comment]
Szia Laci!

Loving the keyboard. If I'm understanding the concept correctly, it doesnt include an option for just changing the current layer colors with something else.

In my case, just being able to modify the existing per-layer colors and mod-key colors would be more than sufficient and would require less manual tweaks from the defaults to accomplish.

Thanks for your attention,
Andrew from Budapest

**Comment by mondalaci** [comment]
Szia Andrew, and thanks for the kind words!

The above specification contains your use case, as functional backlighting colors will be individually adjustable, too.

**Comment by Stefanoko** [comment]
I like everything I read above.

1) Can you give an ETA when this feature will be available?

2) Will I be able to switch between different color sets? I don't mean functional, but permanent color sets. The idea is to have warm colors at night and a different set for harsh daylight. Switchable by hotkey.

Thanks
Stefan

**Comment by mondalaci** [comment]
1. It should happen in a couple of months.
2. This feature won't be available out of the box, but I plan for an API that will eventually allow it via custom coding in JavaScript, for example.

**Comment by Stefanoko** [comment]
Thanks. Really looking forward to it.
Hoping it will get implemented, rather sooner than later.

**Comment by CalamitousCode** [comment]
Hello.

I am very excited to be typing this on my first UHK v2 which has arrived after a long wait. My first thought after plugging it in and downloading the agent was to customise the colours. Unfortunately, I didn't realise this feature was not available yet. I thought that 'per-key backlighting' meant each key was customisable.

I look forward to the very useful implementation of _customisable_ per-key backlighting.

Thanks!

**Comment by bseb** [comment]
Any updates on when this will be implemented

**Comment by mondalaci** [comment]
It'll probably take months. We don't have a specific ETA. We will update this issue when it happens.

**Comment by Zot1881** [comment]
Hello.

Recently got my keyboard and can't wait till this feature is implemented in stock firmware so i did fork and implemented it in very easy but still functional way. If anyone interested in it while waiting for official implementation then you can check it here [firmware with per key color via macros engine](https://github.com/Zot1881/firmware)
![UHK](https://user-images.githubusercontent.com/14919498/198612749-12fa368e-3e13-474c-a44a-cac3df290b26.JPEG)

**Comment by dEEkAy2k9** [comment]
Just to understand this. The official firmware does not have the functionality for functionalLighting nor perKeyLighting?
I could implement it myself by doing what @mondalaci said or using @Zot1881 fork but you will implement it into the official firmware "soon"?

**Comment by mondalaci** [comment]
@dEEkAy2k9 Correct.

**Comment by highend** [comment]
I hope this comes sooner than later.

Got my  UHK v2 two days ago and I've rearranged quite a bit (using my settings from my old UHK v1). It's quite annoying that hitting the FN key leads to quite a few character keys switching their light off during that time....

**Comment by Zot1881** [comment]
No easy way for now. If you really need to change color  you can try https://github.com/Zot1881/firmware

**Comment by Stefanoko** [comment]
Thanks a ton for implementing LED backlighting macros. I love it. This is fantastic, exactly what I was hoping for. 

For everyone interested in customizing their backlights for the entire keyboard, here is what works for me:
1) Create a macro named "$onInit" (to make it auto-load):
`set macroEngine.extendedCommands {extendedCommandsEnabled} boolean: 1`

2) Create additional macros for custom colors, such as:
`set backlight.constantRgb.rgb 255 192 0`

To go back to the UHK default lighting:
`set backlight.strategy functional`

Bind your custom color macros to key codes — et voilà — you can switch backlighting on the fly. I use warm colors at night, and blueish for daytime.

As an icing on the cake, it were nice to have gradients between two colors, spreading from north to south, but hey, I am not complaining, perfectly happy with the way things are now

Thank you so much for implementing this new feature!

**Comment by dEEkAy2k9** [comment]
> 1. Create a macro named "$onInit" (to make it auto-load):
>    `set macroEngine.extendedCommands {extendedCommandsEnabled} boolean: 1`

This seems to just throw an error (ERR on UHK Display)

Other commands like switching colors to constant or RGB Red (with color codes ofc) works.

**Comment by kareltucek** [comment]
It should be `set macroEngine.extendedCommands 1`

**Comment by Stefanoko** [comment]
Thanks for correcting me. And sorry for the confusion. 
Meanwhile, I deleted my $onInit macro and sure enough, it is not needed at all. I must have misread the part about extended macro commands and what belongs to it and what does not.
