### ISSUE TITLE
New macro command action button gone on origin/master?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1699]
![2022-02-18-113515_2510x986_scrot](https://user-images.githubusercontent.com/3447497/154666497-0f0ad204-44a2-4e72-98b3-9ef5d3a312df.png)

Old command actions are still shown as command actions, but the only way to create a command action is to clone a macro which already contains some.

**Comment by kareltucek** [comment]
Right, solved. 

But then... why is Agent even willing to flash a 5.0.0 userconfig (including active shift layers) onto a 4.x firmware?

**Comment by mondalaci** [comment]
Agent will enable users to flash any firmware. But it'll notify them of potential issues. The [notifications](https://github.com/UltimateHackingKeyboard/agent/issues/1682) will be implemented soon.
