### ISSUE TITLE
Per-key comments

### ISSUE THREAD

**Issue by N0K0** [UltimateHackingKeyboard/agent#1720]
Hi!

I'm currently sitter here a bit stumped when cleaning up some keymaps. What i think I'm looking at is mappings from my old I3 config. Would be nice if i was able to a small comment to the keys in the config, so that messy people like me would be able to keep their own best tool in check :sweat_smile:

**Comment by mondalaci** [comment]
Hi there!

I'm not sure this feature would be very useful since the available space per key is highly limited. How do you envision rendering your comments? Please also provide some example comments.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I have [a similar request](https://github.com/UltimateHackingKeyboard/agent/issues/1608) a few months ago. 

Considering the limited key space, maybe we could show it in a small popup like this?
![image](https://user-images.githubusercontent.com/39968/155039120-741f2486-d0c9-48b6-84d0-237d78a943a2.png)

**Comment by kareltucek** [comment]
@N0K0 @0x7FFFFFFFFFFFFFFF , you realize that macros are basically named actions, and also that every keymap has its own editable description where general comments can be placed?

(Admittedly, ergonomy of the GUI is not great in this respect, as creating a macro requires multiple context switches...)

**Comment by N0K0** [comment]
The macros solution could work, albeit a bit clunky.

![image](https://user-images.githubusercontent.com/13900053/155106023-861685e6-d330-4ca5-913d-e1774f54a231.png)
I was thinking about a small textbox over the Remap key area. It does not need to show on the actual keyboard layout as long as its visible in the config window for my part

**Comment by mondalaci** [comment]
I leave this issue open to see its demand. Anyone interested, upvote the first comment.

**Comment by mondalaci** [comment]
On second thought, I do prefer Karel's suggestion of using named macros. I don't think that this feature is really justified for the time being. Might reconsider later.
