### ISSUE TITLE
Missing git hook.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1722]
With uhk/master, I am getting `.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory` when trying to commit code. (This is after successful `npm install && npm run build`.)

This means that I effectively cannot back up any work in progress.

**Comment by mondalaci** [comment]
@ert78gb Can you help with this?

**Comment by ert78gb** [comment]
I deleted the git hooks because we did not use. Just delete the hooks folder in the git directory

**Comment by kareltucek** [comment]
I see, thanks!
