### ISSUE TITLE
Failed UserConfig import

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1723]
When trying to import config from https://github.com/UltimateHackingKeyboard/firmware/issues/453 :

```
 14:16:49.594 › [DeviceRendererService] dispatch action [user-config] Load user configuration history success
14:17:16.075 › TypeError: Cannot read properties of undefined (reading 'layers')
    at V7 (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1145643)
    at Gq (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1155591)
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1901530
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1901860
    at computeNextEntry (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1886575)
    at recomputeStates (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1886887)
    at file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1889905
    at g.U.D.pipe.state [as accumulator] (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1895273)
    at g._tryNext (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1693109)
    at g._next (file:///opt/agent/packages/uhk-agent/dist/renderer/main.a09d039d26263f96.js:1:1693010)

```

**Comment by kareltucek** [comment]
(Using today's master.)

**Comment by mondalaci** [comment]
I can't reproduce the reported issue.

@ert78gb Can you?

**Comment by ert78gb** [comment]
Can you share the user configuration?

**Comment by ert78gb** [comment]
I can't reproduce the error. Are you sure you tested with the master branch? Because the #1690 PR fixes this kind of error

**Comment by ert78gb** [comment]
Or maybe should I try with newer firmware?

**Comment by kareltucek** [comment]
> Are you sure you tested with the master branch? 

Yes.

> Or maybe should I try with newer firmware?

Please try with [uhk-firmware-9.0.0.tar.gz](https://github.com/UltimateHackingKeyboard/agent/files/8143421/uhk-firmware-9.0.0.tar.gz) .

**Comment by ert78gb** [comment]
I can't reproduce it neither on Mac or on Linux.
Angular introduced a new caching logic. I experienced Angular does not recognise well the code changes and uses old build. 
I would like to ask you to run the following steps

- `npm run clean` => this command delete `node_modules` folders and every temp and cache folders
- `npm i`
- `npm run build`
- `npm run electron`

**Comment by kareltucek** [comment]
Weird... 

```
2022-02-25 20:15:43 git clone https://github.com/UltimateHackingKeyboard/agent.git agent2
2022-02-25 20:15:58 cd agent2/
2022-02-25 20:16:10 npm run clean
2022-02-25 20:16:23 npm i && npm run build
2022-02-25 20:29:48 npm run electron
2022-02-25 20:31:17 history
 ```

Separately, I have downloaded the offending config again to avoid any confusion:

```
2022-02-25 20:30:24 cd /tmp
2022-02-25 20:30:29 mkdir uhk_cfg
2022-02-25 20:30:31 cd uhk_cfg/
2022-02-25 20:30:35 wget https://github.com/UltimateHackingKeyboard/firmware/files/8128265/UserConfiguration.json.zip
2022-02-25 20:30:40 unzip UserConfiguration.json.zip
2022-02-25 20:31:59 history
```

Still the same...

**Comment by kareltucek** [comment]
Can node version interfere? (`v16.13.1` here)

**Comment by ert78gb** [comment]
not really. I found something . I am opening a PR soon

**Comment by ert78gb** [comment]
When do you get the error? Immediately after you import the user config?

**Comment by ert78gb** [comment]
I tested with node `v16.13.1` and works fine for me.
My latest commit fixes a firmware upgrade bug. If you experienced the problem after the firmware upgrade please check the latest version

**Comment by ert78gb** [comment]
Are there any extra modules connected?

**Comment by kareltucek** [comment]
> [](https://github.com/UltimateHackingKeyboard/agent/issues/1723#issuecomment-1051266660)When do you get the error? Immediately after you import the user config?

I click 'Import device configuration`. File dialog appears. I select the file and confirm. Then the log immediately appears in terminal.

> Are there any extra modules connected?

Doesn't matter. Happens with and without modules.

> If you experienced the problem after the firmware upgrade please check the latest version

All testing is done with a freshly (re)started agent.

**Comment by kareltucek** [comment]
@ert78gb it seems that the problem is caused by the UserConfig present in UHK before the import - [UserConfiguration-Karel.json.txt](https://github.com/UltimateHackingKeyboard/agent/files/8144983/UserConfiguration-Karel.json.txt)

I get the same error if I simply try to reset UHK settings.

**Comment by kareltucek** [comment]
(Loading, editing and saving the config works fine. The problem is only if another config is imported, or reset issued.)

**Comment by mondalaci** [comment]
@kareltucek Please pull master and rebuild Agent. We can't reproduce the issue and @ert78gb's last commit may have solved your issue.

**Comment by kareltucek** [comment]
@mondalaci still the same problem.

Updated steps to reproduce:
- flash [uhk-firmware-9.0.0.tar.gz](https://github.com/UltimateHackingKeyboard/agent/files/8143421/uhk-firmware-9.0.0.tar.gz) (If you have not done so yet).
- flash [UserConfiguration-Karel.json.txt](https://github.com/UltimateHackingKeyboard/agent/files/8144983/UserConfiguration-Karel.json.txt) . 
- restart Agent. (Maybe not needed.)
- try to reset config. (At this point, error log should appear in terminal.)

**Comment by ert78gb** [comment]
The `Load user configuration history success` triggered when  Agent reads the earlier saved user-configurations from the [app data folder](https://www.electronjs.org/docs/latest/api/app#appgetpathname) `/Electron/user-configs/`

**Comment by mondalaci** [comment]
> * flash [UserConfiguration-Karel.json.txt](https://github.com/UltimateHackingKeyboard/agent/files/8144983/UserConfiguration-Karel.json.txt) .

You mean import instead of flash, right?

**Comment by kareltucek** [comment]
> You mean import instead of flash, right?

I mean import into agent and save into UHK.

**Comment by kareltucek** [comment]
> The `Load user configuration history success` triggered when Agent reads the earlier saved user-configurations from the [app data folder](https://www.electronjs.org/docs/latest/api/app#appgetpathname) `/Electron/user-configs/`

I don't understand. Please rephrase in case this requires some action from me.

**Comment by ert78gb** [comment]
I can reproduce the problem. I am working on the fix

**Comment by ert78gb** [comment]
I think I fixed.

**Comment by kareltucek** [comment]
Confirming. Thanks!

**Comment by ert78gb** [comment]
I am sorry for the inconvenience
