### ISSUE TITLE
Keypress and Layer toggling

### ISSUE THREAD

**Issue by iamFIREcracker** [UltimateHackingKeyboard/agent#1726]
Apologies if this got already answered somewhere else, but I could not find any relevant question, so here it is.

Is it by any chance possible, for a given key, to:

- Act as a modifier (e.g. `LCmd` on a Mac), when pressed
- Toggle a different layer, when double-tapped

I cannot seem to find a way to do this from the Agent: I can either do things from the "Keypress" tab, or from the "Layer" one, but not **both**.

I am not necessarily asking for this functionality to be added (if not there already), but rather trying to see if other users a) had a similar need, and b) how they got that implemented.

Thanks,
M.

**Comment by kareltucek** [comment]
Not supported by the stock firmware/agent. 

However, you can use https://github.com/kareltucek/firmware - search for `ifGesture` or `ifDoubletap`.
