### ISSUE TITLE
Dvorak only working in QWR mode

### ISSUE THREAD

**Issue by Vistaus** [UltimateHackingKeyboard/agent#1729]
I just got my UHKV2 and I already love it! However, Dvorak only works for me in QWR mode, not in DVO mode. Not a big deal, but as a Dvorak user, I would love to have DVO displayed. I have set Dvorak for PC as the default keymap.

OS: Void Linux
Agent: latest version
Firmware: latest version

**Comment by mondalaci** [comment]
Hi there, and thanks for the nice words!

This is not a bug. See https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk for the explanation.

Feel free to rename the QWR keymap to DVO if your OS layout is Dvorak.

**Comment by Vistaus** [comment]
A, I see. Thanks for the quick answer! :)
