### ISSUE TITLE
agent keeps wanting to update the firmware although I already applied the update

### ISSUE THREAD

**Issue by dcermak** [UltimateHackingKeyboard/agent#1733]
I have build the agent from the latest commit on the master branch (0a17555a929df6ca21fa637c02b9e0645bead14e as of today) and got prompted to update the firmware. I applied that update, which initially failed, but eventually applied after I plugged the UHK (v1 mind you) directly into my machine and not through a usb hub.

However, the agent is now still prompting me to update the firmware, even though it did that successfully before:
![image](https://user-images.githubusercontent.com/45594031/157819243-7bffe96f-5168-42d5-8662-2356a08a26bb.png)

This is currently preventing me from saving any settings to my UHK unfortunately.

**Comment by mondalaci** [comment]
I have yet to release firmware 9.0.0 to make this message go away. Will do it soon.

**Comment by D4N** [comment]
László Monda ***@***.***> writes:

> I have yet to release firmware 9.0.0 to make this message go away. Will do it soon.

Ok, thanks!
