### ISSUE TITLE
Allow customizing behaviour of trackball on each layer

### ISSUE THREAD

**Issue by DarwinAwardWinner** [UltimateHackingKeyboard/agent#1734]
Currently, my understanding is that the trackball is always a mouse on the base layer, scroll wheel on the Mod layer, and arrow keys on the Fn layer. I already have a mouse I like, so I would much prefer if I could use the trackball as arrow keys even on the base layer. Are there plans to make this configurable?

**Comment by mondalaci** [comment]
Yes, this will be possible to configure in the next firmware release. More info in https://github.com/UltimateHackingKeyboard/firmware/issues/351

**Comment by DarwinAwardWinner** [comment]
Excellent! Thanks for your hard work!
