### ISSUE TITLE
Unable to flash 8.10.2 from 8.9.3

### ISSUE THREAD

**Issue by emontellese** [UltimateHackingKeyboard/agent#1735]
Unable to flash 8.10.2 from 8.9.3.  Windows 10.  Latest version of agent (1.5.17)

-----
Start flashing firmware
[DeviceService] Operating system: Windows_NT 10.0.19043 x64
[DeviceService] Agent version: 1.5.17
[DeviceService] New firmware version: 8.10.12
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":1,"name":"UHK 60 v1","vendorId":"0x1D50","keyboardPid":"0x6122","bootloaderPid":"0x6120","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.9.3
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_01#a&3522e1de&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_04#a&372d572b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_02#a&21f2c5a0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_03#a&ec2a962&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6122","path":"\\\\?\\hid#vid_1d50&pid_6122&mi_00#a&4dca3cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...........................................................................................................
[UhkHidDevice] Could not find reenumerated device: Bootloader. Timeout
[DeviceService] updateFirmware error {"message":"Could not reenumerate as Bootloader","stack":"Error: Could not reenumerate as Bootloader\n    at t.UhkHidDevice.<anonymous> (C:\\Users\\publi\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1300721)\n    at Generator.next (<anonymous>)\n    at s (C:\\Users\\publi\\AppData\\Local\\Programs\\uhk-agent\\resources\\app.asar\\electron-main.js:2:1364255)"}
[UhkHidDevice] Transfer error:  TypeError: Cannot write to closed device
    at t.UhkHidDevice.<anonymous> (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298863)
    at Generator.next (<anonymous>)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
    at new Promise (<anonymous>)
    at l (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364198)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298618
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298583)
    at Generator.next (<anonymous>)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[DeviceService] Read hardware modules information failed TypeError: Cannot write to closed device
    at t.UhkHidDevice.<anonymous> (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298863)
    at Generator.next (<anonymous>)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
    at new Promise (<anonymous>)
    at l (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364198)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298618
    at new Promise (<anonymous>)
    at t.UhkHidDevice.<anonymous> (C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1298583)
    at Generator.next (<anonymous>)
    at C:\Users\publi\AppData\Local\Programs\uhk-agent\resources\app.asar\electron-main.js:2:1364453
[DeviceService] start poll UHK Device
Could not reenumerate as Bootloader

**Comment by mondalaci** [comment]
Closing this issue due to the lack of recent follow-ups. I'll address further replies regardless.
