### ISSUE TITLE
Redirect to a specific keymap / macro

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#174]
When I hit the http://localhost:8080/#/keymap or http://localhost:8080/#/macro URL a specific keymap / macro gets displayed but on the side menu nothing gets selected which is rather confusing. It'd make sense for the router to redirect to the keymap / macro in question.

We should also consider the case when no keymaps / no macros are available. Maybe we should redirect to / in such a case.

As a matter of fact, I'm wondering whether the http://localhost:8080/#/keymap and http://localhost:8080/#/macro routes make sense, given then they don't point to a specific keymap / macro.

**Comment by NejcZdovc** [comment]
What content would be on page /? Because if we have page /, then we could remove /keymap and /macro.

Current scenarios that redirects to this pages:
- initial load (keymap)
- you delete all macros (macro)

**Comment by mondalaci** [comment]
I think it'd make sense to make the `/` route redirect to to the route of the default keymap. Removing `/keymap` and `/macro` routes would be welcome, as they serve no concrete purpose. I assume this would mean that upon deleting a macro Agent would redirect to the first macro available, or to the default keymap if no macros are available.

**Comment by fjozsef** [comment]
@mondalaci Your last comment conflicts #198 in the case when there are no macros. Should it display a message or redirect to default keymap?

**Comment by mondalaci** [comment]
@fjozsef Let's rather display a message according to #198.

**Comment by fjozsef** [comment]
In the actual version when the user doesn't have any macro we'll redirect him to http://localhost:8080/#/macro which tells him "You don't have any macros. Try to add one!", but If the user do have macros and visits that url, then the message still appears. We either should change the macro not found url or redirect the user to the first macro, when he visits that page and has at least one macro.

**Comment by mondalaci** [comment]
Let's redirect to the first macro if it exists.
