### ISSUE TITLE
Macro helper

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#1750]
As you're going to include smart macros soon, I want to suggest a small helper: an english keymap.
It would be really helpful to insert special characters with macros for those of us who don't use the US layout.
It could be added into #1670

Maybe I'll explain better with an example. I use the spanish layout and my desire is to insert a simple { character.
To achieve that I have to check which keys I have to press in the keyboard. In this example, Right Alt + the key left to the enter key.
The next step is to find which symbol correspond to that key in the english layout.
And finally write the macro command: $tapKey RA-apostropheAndQuote.

Is important to remark that currently you can't check it on the keymaps tab while you write a macro.

**Comment by kareltucek** [comment]
This is not really related to smart macros. The smart macros which are to be included mean only `set` and `printStatus` commands.

As to the problem of mapping in non-US layouts, the trick is simple - first switch your OS layout to en-US, then tap the keys as if it was your spanish layout.

**Comment by mondalaci** [comment]
Thanks for your suggestion, but I agree with Karel. I plan to include visualization support into Agent for the physical keycap sets that we (are going to) provide, but it's not related to smart macros.
