### ISSUE TITLE
Keyactions

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#176]
We are currently using array with specific ID's for key actions in keymap. We need to change this to objects and move this specific ID into object of the action.

This way we can manipulate array (add, remove) without any problems.

When this is done we can revert  #162.

**Comment by mondalaci** [comment]
Hey Nejc,

I understand that from a functional programming standpoint your suggestion is the right thing to do, but there are two points that make it less than ideal:

1. Most of the keycaps will have actions associated to them, making your representation a less space efficient alternative.
2. From the perspective of the overall system architecture, it'd introduce additional complexity, especially in the firmware.

Given the above reasons, I ask you guys to keep position based key actions in place. All things considered, I think it's the best way forward, and I can't see us changing it in the future.

**Comment by fjozsef** [comment]
I more prefer @mondalaci's idea so be it then. I also think we can work with arrays without any problem, so I am closing this as won't fix.
