### ISSUE TITLE
Feature request: command view border

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1771]
Could the Monaco editor get a simple border? Either at the left side, or all around. For instance similar to the "Type text" textarea.

Current way, I feel lost and unanchored.  

This might be my professional deformation from programming - to always know where the first line begins (vertically), and where the line begins (horizontally). Current way, I am not sure whether there is an empty line at the beginning and what the indentation is...

(I thought I would get used to it, but so far, I am still getting the same feeling.)

**Comment by mondalaci** [comment]
I can totally feel you, and I've been having similar thoughts.

How about only showing the border of the current editor when the text cursor is active and blinking?

**Comment by kareltucek** [comment]
It would definitely improve the matter, and I think I would find it satisfactory.

Still, I am wondering whether having a thin gray border along just the left side of all editors might work just as well while still looking tidy and easthetically pleasing.

**Comment by mondalaci** [comment]
Why just along the left border? I'd still feel somewhat lost if I didn't see all the four borders.

**Comment by kareltucek** [comment]
I assume having borders around all editors would bring in a lot of clutter. 

Also, I assume that clearly seeing the line begin and end would give enough visual cue about the vertical dimensions.

But I am fine with all three variants, so pick however you will!

**Comment by mondalaci** [comment]
@kareltucek Ok, thanks!

@ert78gb Let's put a light gray corner around the editor when it's active. Let's also change the border of the text action textarea to the chosen light gray color. When there's off-screen content at the top of the editor, a gradient is visible at the top which I want to be removed.

**Comment by kareltucek** [comment]
Much better! Thanks!
