### ISSUE TITLE
Don't allow the deletion of the last keymap

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#178]
It makes no practical sense to have zero keymaps, so we shouldn't allow the user to delete the last one. Having no keymaps is confusing because the user wouldn't know what to expect.

I think we should simply not display the delete (trash can) icon for the last keymap.

**Comment by fjozsef** [comment]
I disagree with this. 
On a fresh start maybe you want to delete all the keymaps and start creating new ones (without clearing existing the macros, so a reset is not an option.)
I would rather show the add keymap page, when there is no keymap.

**Comment by mondalaci** [comment]
According to your suggestion Agent could have a state where no keymap is defined. That configuration could be saved to the UHK. What do you think the user would expect then?

**Comment by fjozsef** [comment]
It doesn't matter if there is no keymap or there is a keymap, but every keyaction is none. I think the working of the UHK should be equivalent in this two state.
I understand your worries, of course the keyboard will be useless, but it could be worthless even with a badly configured last keymap. It is the user's responsibility to configure the UHK.

But if you want then we could keep your idea, I just wanted you to consider my opinion before making the final decision.

**Comment by mondalaci** [comment]
Yes, by thinking logically, having no keymap should be the equivalent with a keymap full of none key actions. But still, from the standpoint of the user having no keymap may be the most confusing thing ever. Users don't necessarily think about this so deeply. They just see the lack of keymaps and have no idea what should happen.

Also, in practice, it is rare to have keymaps full of none key actions, and if the user wants to add new keymaps and delete all the rest, (s)he will be able to create the new keymaps first, and then delete the rest.

As for the implementation if this issue, it may be a better idea to always display the trash icon, but gray it out and add a label on hover that says: "The last keymap cannot be deleted."

**Comment by fjozsef** [comment]
I think we should provid an oportunity to create an empty keymap on add keymap page, but I rather create a different issue for it #180. 

I would rather suggest the idea that the favorite/default/stared keymap cannot be deleted.

**Comment by mondalaci** [comment]
Well, the last keymap is also the default one. I'd allow the deletion of the default keymap unless it's the only keymap available.
