### ISSUE TITLE
Bug: Scancode field not updated from Capture keystroke if dropdown was opened

### ISSUE THREAD

**Issue by Usoka** [UltimateHackingKeyboard/agent#1793]
When selecting a keypress for a key, if you select the dropdown (or click the text) for Scancode then Capture keystroke doesn't properly populate the Scancode field.

**Steps to reproduce**:
1. Select a key to set mapping for
2. Select "Keypress" tab
3. Click the dropdown or the text for Scancode (either option should result in dropdown menu opening)
4. (optional) click off the Scancode dropdown (but don't click off the key edit)
5. Click the "Capture keystroke" button
6. Press any key (that should be captured)
7. Observe Scancode field

**Expected result**:
Scancode field should have the input matching the key you pressed for "Capture keystroke".

**Actual result**:
Scancode field does not change.

**Additional notes**:
- After steps 1-4, you can repeat steps 5 and 6 any number of times and the input still doesn't get displayed properly.
- After completing the steps if you click the Scancode dropdown it will correctly display the key input from Capture keystroke.
- This appears to be purely visual. When you click "Remap key" it remaps it to the key pressed for Capture keystroke, even though the field for Scancode was never visually updated.

**Comment by mondalaci** [comment]
Thanks so much for the very detailed bug report! I can reproduce the issue and we'll fix it.
