### ISSUE TITLE
Allow for creation of new layers

### ISSUE THREAD

**Issue by alevani** [UltimateHackingKeyboard/agent#1797]
It would be nice to allow users to create new layers (such as the MOD or the MOUSE one).

Here is my use case:

I would like to be able to create two new layers for my `alt` and `cmd` key so that I can have specific arrow key actions dependently of which layer is used.

If the `alt` key is pressed, the arrow array would be combined to a left alt (option). if the `cmd` key is pressed, the arrow array would be combined to the cmd key. (via macros).

One other way to allow that would be to allow for toggling between different keymaps as a specific key is pressed, but it sounds like a less elegant solution.

**Comment by mondalaci** [comment]
This is already implemented by #617. We'll release a new Agent and firmware version containing this feature.
