### ISSUE TITLE
Split files to components

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#18]
Split the html, css, and js files into component libraries.

An initial list of components:
- [x] Menu
- [ ] Layout Editor
- [ ] Keymap Editor
- [ ] Macros
- [ ] Plugins
- [ ] Settings

**Comment by mondalaci** [comment]
https://www.npmjs.com/package/gulp-file-include

**Comment by csanyiarpad** [comment]
After splitting the _*.scss_ source files the `bootstrap` library would have to be switched to `bootstrap-sass` and the `_bootstrap.scss` file should be included in the beginning of the main file (`style.scss`).

**Comment by mondalaci** [comment]
So be it!

**Comment by mondalaci** [comment]
@csanyiarpad Please let's consult with @fjozsef before making this happen. It might have been partialy, or fully implemented by his webpack task.

**Comment by csanyiarpad** [comment]
I had the exact same  idea as I have seen that he's using webpack :)

**Comment by mondalaci** [comment]
This has been done.
