### ISSUE TITLE
Empty keymap on add keymap page

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#180]
The user may want to fresh start creating his own layout, where It could be annoying to remap every key, when he wants to set some of them. So we could provide adding an empty keymap at keymap add page.

**Comment by mondalaci** [comment]
This makes sense for the time being because we have a limited number of presets, but I'm not sure if it'll make sense in the long run when we will provide every major keyboard layout. I think people seldom want to start from scratch.
