### ISSUE TITLE
npm run server:web results in inoperable application

### ISSUE THREAD

**Issue by danpalmer** [UltimateHackingKeyboard/agent#1812]
Building from current HEAD of the master branch, running `npm run server:web` does not produce a working web app. The build appears to complete successfully, but when visiting the page in a browser there are errors relating to missing values imported from other packages. 

I've done some debugging to see if it was just one specific broken value being imported, but it seems to be at least anything to do with `LayerName` imported from `uhk-common`, and quite possibly any other imported values from that package or others.

It seems like something about my setup is broken, or perhaps something about the build config. Are the scripts up to date? Is this a supported way to run the application? I'm looking for a fast feedback loop for some development so felt the web build would be a better dev experience than build/run for the electron app.

I've done a clean `npm install`, although it required `--force` as there are a few incompatible dependencies. I'm on the required version of Node (v16.16.0) and NPM (v8.11.0). This is all running on macOS Ventura, although I doubt this has anything to do with the OS.

Any ideas would be greatly appreciated!

**Comment by mondalaci** [comment]
You should use `npm run electron` to run the desktop application, and it should work. The web application is only a demo.

**Comment by danpalmer** [comment]
Ah ok. I was hoping for live-reload rather than the ~1 min build and run. The feature I'm prototyping would work the same on the web demo and the app.

I'll stick with build and run for now.

**Comment by kareltucek** [comment]
... @ert78gb any input on this? ...

**Comment by mondalaci** [comment]
@kareltucek `npm run server:web` works well on my side, and the report doesn't contain enough information for us to figure out the root cause, but it must be some installation-specific issue. We can dig into this if needed, but only when having a build log.

**Comment by ert78gb** [comment]
Hi, based on the symptoms the `npm i` failed. Everything is up to date and works fine because the whole the whole build process runs successfully on the CI.
