### ISSUE TITLE
Export keys on Base and Fn layer as CDR icon file - for a maker project

### ISSUE THREAD

**Issue by llinfeng** [UltimateHackingKeyboard/agent#1819]
Please advise if there is a place to download the CDR icon files associated with all key-mappings in the Base layer? I'll also need nine keys I mapped in the Fn layer as well. Of course, this sounds quite a wild ask.

Then, can I find ways to produce the CDR icon file for one specific key, one at a time? I'll then gather the collection of CDR files for the keys I need.

----

This is for a project to replace key caps on my first UHK with wooden ones, where characters are cut to the wooden key caps one at a time. The cutter works the best with CDR files.

Many thanks!

**Comment by mondalaci** [comment]
Hi there! Please highlight the exact icons you need, and I'll try to help you.

**Comment by llinfeng** [comment]
Here is a small collection of 6 unique icons I'd like to have.
![image](https://user-images.githubusercontent.com/5890407/183501347-b8fa98d6-b223-4350-8d9c-a0091a2795fd.png)


Though, since the woodworker proposed the following set of icons, well, I'd prefer to use the original set of characters for the base-layer, if possible.

![image](https://user-images.githubusercontent.com/5890407/183501448-5e607b06-b4df-441c-aa50-9d296fded971.png)

**Comment by mondalaci** [comment]
Please see the speaker, play, and pause icons of [Font Awesome](https://fontawesome.com/v5/search).
