### ISSUE TITLE
Macro new action's "Save" button being partially obscured by "Save to keyboard" button.

### ISSUE THREAD

**Issue by bistabil** [UltimateHackingKeyboard/agent#1820]
After adding a new action to a macro "Save to keyboard" shows sticking to the bottom of the Agent's viewport.
If this button is not pressed, but you continue adding the next action, "Save" button for that new action gets behind "Save to keyboard".
![image](https://user-images.githubusercontent.com/5158508/183335163-cd578517-004a-4102-8db1-d8f61ee0f6f8.png)

**Comment by mondalaci** [comment]
@bistabil Thanks for your report! We'll fix this issue.
