### ISSUE TITLE
Unbricking procedure seems broken?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1839]
![2022-09-07-213659_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/188962365-b37e81b5-0333-44b3-8198-6f67c9b4d92f.png)

**Comment by mondalaci** [comment]
Which Agent version? I remember such a bug being fixed recently, so Agent master should work well.

**Comment by kareltucek** [comment]
Today build.

**Comment by mondalaci** [comment]
I can reproduce the issue. Thanks for reporting! We'll fix it soon.
