### ISSUE TITLE
missing fn5 layer in Keypress/Secondary role

### ISSUE THREAD

**Issue by WindChimeRan** [UltimateHackingKeyboard/agent#1840]
Hi,

I compiled the newest agent myself and flashed the released firmware. 

- What I did: add an Fn5 layer

- Something that worked as expected: I can assign a key to Fn5 in the Base layer, in the Layer page.

- **Not works as expected**: I tried to assign a key in the Keypress page, with a Major scancode and a Secondary role, but there are only Mod, Fn, Mouse, and Modifiers. No Fn5. 

I attached the screenshot below. 

 
![Screen Shot 2022-09-09 at 2 10 25 AM](https://user-images.githubusercontent.com/19507897/189283124-aafbd1c4-b572-4cda-9008-189688cd3bb9.png)

**Comment by mondalaci** [comment]
Thanks for your report! I can reproduce it, and we'll fix it soon.
