### ISSUE TITLE
Add new keymap: scrollbar not on the side of the window

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#185]
For some reason, the scrollbar is not at the right edge of the window on the add new keymap page. There's some extra space there.

![screenshot from 2016-11-22 00-02-35](https://cloud.githubusercontent.com/assets/300402/20504347/2ea21e36-b047-11e6-8d84-93239f829274.png)

**Comment by NejcZdovc** [comment]
Yes this happens, because we scroll inline window (left part of the app) not the whole window.
