### ISSUE TITLE
[] Backup Configurations to Google Drive

### ISSUE THREAD

**Issue by zilberlex** [UltimateHackingKeyboard/agent#1851]
It would be handy to have the ability to backup configuration files to Google Drive via SSO Sign in.

Proposed Backup Folder -  //Backup/UHK

**Comment by mondalaci** [comment]
We don't plan to implement this feature but rather create a dedicated UHK web service for such use cases.

In the meantime, maybe you can link the UHK configuration history folder under your Google Drive directory.
