### ISSUE TITLE
Where can I find the macro command menu?

### ISSUE THREAD

**Issue by old9** [UltimateHackingKeyboard/agent#1852]
I would like to use some [Smart macros](https://github.com/UltimateHackingKeyboard/firmware/issues/351) settings on my UHK v1, after reading a lot of the discussions on the firmware issues as well as the agent issues, I still can't figure out how to get it to work.

I have updated to the latest agent 1.5.17 and the latest firmware official version 9.0.1, reset the configuration file, reinstalled the agent, but I still can't find the **command** button mentioned in some of the posts when creating a new macro, how exactly do I use this feature? Is this even supported on a v1 device?

**Comment by mondalaci** [comment]
According to the [firmware 9.0.0 changelog](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v9.0.0), please wait for Agent 2.0.0 to be released to be able to use smart macros. We're working on it and plan to release it soon.
