### ISSUE TITLE
Remember save path

### ISSUE THREAD

**Issue by Stefanoko** [UltimateHackingKeyboard/agent#1856]
Not terribly important, but nice to have: when exporting the device configuration, I always have to navigate to my preferred folder.  Since I export/backup my config quite often, it would save time if Agent remembered the last location.

**Comment by mondalaci** [comment]
We've discussed this feature internally, and its implementation is relatively time-consuming.

How often do you save your configuration? If very often, a custom script may be a better option that copies the latest file from the configuration history directory of Agent.

**Comment by Stefanoko** [comment]
Copying from the history directory is easy enough, I like this idea. Thank you. 

I use the board on different machines (home and work). Therefore, I export twice per day, at least for now, while I am still in the beginning stages and optimizing my layers.

Just to make sure I read you correctly: 
The file I need to copy seems to be "429073955.json" and is located in  \AppData\Roaming\uhk-agent\

The "\user-configs" subdirectory probably contains incremental changes? I assume it is safe to delete old files in this folder (they pile up), provided I always retain the latest version of 429073955.json?

**Comment by mondalaci** [comment]
Yes, you're correct. Agent uses these files to populate the configuration history list of the device configuration page. Feel free to copy the latest file by date or delete them.
