### ISSUE TITLE
Flashing right-click menu gone?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1857]
I remember a right-click menu that allowed the user to flash only one selected module. 

Is it gone, or is its absence a bug?

**Comment by mondalaci** [comment]
The module recovery feature works on master, but the menu only contains the relevant modules that are not obstructed by currently attached modules. Hence, if both of your modules are attached, the pop-up menu doesn't appear upon right-clicking.

**Comment by kareltucek** [comment]
I see, thanks!
