### ISSUE TITLE
Core dump on arch linux before it starts

### ISSUE THREAD

**Issue by pmatos** [UltimateHackingKeyboard/agent#1865]
Just got my UHK. I downloaded Agent, and as soon as I run it, I get:

```
~ Downloads/UHK.Agent-1.5.17-linux-x86_64.AppImage --log all
12:58:24.194 › [Electron Main] init services.
12:58:24.196 › [Electron Main] packagesDir: /tmp/.mount_UHK.AgYJf1mD/resources
[1]    40602 trace trap (core dumped)  Downloads/UHK.Agent-1.5.17-linux-x86_64.AppImage
```

No idea what to do from here because I don't know where the core dump is. Things I can try or where  I can find the core dump would be great.

Edit: running this on sway / wayland in case it matters.

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by pmatos** [comment]
So, I actually managed to run this now but only through dev mode where I installed the proper dependencies, etc. AppImage still crashes.

I followed the steps for dev in the readme. The only thing I noticed is that electron-flags.conf is not honoured by the electron app so I had to patch `packages/uhk-agent/package.json`:
```
diff --git a/packages/uhk-agent/package.json b/packages/uhk-agent/package.json
index e693aff0..467d57d5 100644
--- a/packages/uhk-agent/package.json
+++ b/packages/uhk-agent/package.json
@@ -32,7 +32,7 @@
   "devDependencies": {
   },
   "scripts": {
-    "start": "cross-env DEBUG=kboot* electron ./dist/electron-main.js",
+    "start": "cross-env DEBUG=kboot* electron --ozone-platform-hint=auto ./dist/electron-main.js",
     "electron:spe": "electron ./dist/electron-main.js --spe",
     "build": "webpack && npm run install:build-deps && npm run download-firmware && npm run copy-to-tmp-folder",
     "clean": "rimraf ./node_modules ./dist",
```

This got it working in wayland. However, to be honest all electron apps I tried have honoured electron-flags.conf. See https://wiki.archlinux.org/title/Wayland#Configuration_file

I thought that the crash could be wayland related but passing to the AppImage `--ozone-platform-hint=auto` does not help.

**Comment by pmatos** [comment]
> So, I actually managed to run this now but only through dev mode where I installed the proper dependencies, etc. AppImage still crashes.
> 
> I followed the steps for dev in the readme. The only thing I noticed is that electron-flags.conf is not honoured by the electron app so I had to patch `packages/uhk-agent/package.json`:
> 
> ```
> diff --git a/packages/uhk-agent/package.json b/packages/uhk-agent/package.json
> index e693aff0..467d57d5 100644
> --- a/packages/uhk-agent/package.json
> +++ b/packages/uhk-agent/package.json
> @@ -32,7 +32,7 @@
>    "devDependencies": {
>    },
>    "scripts": {
> -    "start": "cross-env DEBUG=kboot* electron ./dist/electron-main.js",
> +    "start": "cross-env DEBUG=kboot* electron --ozone-platform-hint=auto ./dist/electron-main.js",
>      "electron:spe": "electron ./dist/electron-main.js --spe",
>      "build": "webpack && npm run install:build-deps && npm run download-firmware && npm run copy-to-tmp-folder",
>      "clean": "rimraf ./node_modules ./dist",
> ```
> 
> This got it working in wayland. However, to be honest all electron apps I tried have honoured electron-flags.conf. See https://wiki.archlinux.org/title/Wayland#Configuration_file But I don't know enough about electron dev to understand if this file should be always read.
> 
> I thought that the crash could be wayland related but passing to the AppImage `--ozone-platform-hint=auto` does not help.

**Comment by ert78gb** [comment]
Agent 1.5.17 contains electron 16.0.1. It is almost 1 year old release. The new release will available soon.

In the linked documentation 
>To use [electron](https://archlinux.org/packages/?name=electron)-based applications natively under Wayland, the following flags need to be added to your application exec command line (for Electron 20): --ozone-platform-hint=auto

the `--ozone-platform-hint=auto` works only with electron 20

It think you have to follow the `4.12.3 Older Electron versions` paragraph.
