### ISSUE TITLE
Macro menu - indexing bug?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1872]
_Sometimes_, Agent opens a different macro than the one which I clicked in the left pane.

Also, it seems like the left pane is _sometimes_ missing some macro.

This _sometimes_ happens after I duplicate a macro. (I clearly remember a duplicated macro not showing in the macro list. Actually, the captured sequence is bugged on a duplicated macro which (curiously) was not created during this agent session.)

This has been happening to me for some time already, unfortunately, I still have not managed to nail down the "_sometimes_". (I.e., I don't know how to reproduce it.) 

See attached mp4 (notice that name of the macro in macro editor does not correspond to the one in the left pane ): 

https://user-images.githubusercontent.com/3447497/197414394-04bada67-4d81-4812-8c27-01c429c464ce.mp4

mirror: 
[macro_bug.zip](https://github.com/UltimateHackingKeyboard/agent/files/9847394/macro_bug.zip)

(Clearly, the index sequence gets shifted by one at some point. Not sure why.)

This is at:

```
commit 4b1609abe5dc58f538e3d19ae885c57fc517b705 (HEAD, origin/master, origin/HEAD)
Author: Róbert Kiss <erT78gb@gmail.com>
Date:   Sat Oct 8 12:07:32 2022 +0200

    chore: rebuild root package-lock.json to upgrade deps of deps (#1862)
```

**Comment by mondalaci** [comment]
@kareltucek I could trigger this issue several weeks earlier, then tried to reproduce it unsuccessfully.

@ert78gb Can you fix it?

**Comment by ert78gb** [comment]
I tried to reproduce in the last 2 hours, but I can't. I need a little bit more help what did you do before the error happened?

If the macro is not visible in the left menu then 2 macro has the same macro Ii. I don't know how is it possible.

**Comment by kareltucek** [comment]
> I tried to reproduce in the last 2 hours, but I can't. I need a little bit more help what did you do before the error happened?

Well, it is always an agent which has been running for some time. I often flash UHK from terminal, so the UHK is often disconnected and later reconnected.

However, it usually exhibits after creating/deleting macros. In that case, these are usually macros with a single command action in them. (Although most of the time, the first thing I do with an Agent is to create/delete macros, so this evidence may not be relevant.)

> If the macro is not visible in the left menu then 2 macro has the same macro Ii. I don't know how it is possible.

(Well, If menu items are indexed, then missing item means messed up indexing as well.)

Either way, don't trust my memory too much. The only solid evidence is the attached video.

**Comment by kareltucek** [comment]
Also, regarding strange problems, please note this screenshot. Things to notice:

- garbled versions (this is not surprising - I encountered garbled USB communication before)
- there is no output in the log window during flashing or after. Especially the instruction to reconnect the module can be seen only in terminal, not in Agent. (I used the right-click menu to unbrick trackpoint module.)

![2022-11-12-230947_2469x864_scrot](https://user-images.githubusercontent.com/3447497/201496646-ca9f0b3b-ad34-4174-906e-117bfed7f335.png)

This may be rare issue not worth of investigation, but still seemed worth sharing...

**Comment by mondalaci** [comment]
@kareltucek I'm unsure whether the latter issues are related, and I couldn't notice them, but please keep sharing whatever you find, as we're dedicated to fixing every bug.

**Comment by kareltucek** [comment]
Hypothesis: 

This may be happening due to Agent's error handling. 

I think when an error is encountered, the left menu (or generally a part of agent) stops receiving some events, or maybe just gets unsynchronized.

I generally don't see errors in the terminal because it is long-running agent, and the errors may be due to USB communication during flashing disconnects, so when I return back to Agent, they are long gone.

Further evidence:

I have encountered the same problem with Keymap menu record. This time, there was even an error in terminal.

![2022-11-13-002900_3825x2110_scrot](https://user-images.githubusercontent.com/3447497/201545082-fdf7b7e5-44ee-4509-a87f-9cb766ffa625.png)

**Comment by ert78gb** [comment]
I have same feeling, UHK disconnect/connect could mix the macro order, but this `layer` property not found is weird for me

**Comment by mondalaci** [comment]
@kareltucek Does your UHK often disconnect? Possibly due to firmware updates? If so, do you update the firmware outside of Agent while it's running? Do you modify the configuration outside of Agent while it's running? Please try to test further accordingly if some of the mentioned possible causes make you suspicious.

**Comment by kareltucek** [comment]
> Possibly due to firmware updates?

Yes.

> If so, do you update the firmware outside of Agent while it's running? 

Yes.

> Do you modify the configuration outside of Agent while it's running? 

No.

> Please try to test further accordingly if some of the mentioned possible causes make you suspicious.

Will try.

I know that `./get-device-state.ts` produces garbled results when running while an Agent is running alongside...

Actually, I just tried:
- start `./get-device-state.ts`
- *then* start agent

![2022-11-13-224103_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/201545965-b194e6c1-88d3-431b-8e87-398cae272666.png)

**Comment by mondalaci** [comment]
As for the garbled version information, the culprit is probably that you access the UHK raw HID interface while Agent is running, causing extra back-and-forth communication of which Agent is unaware.

As for the indexing bug, the root cause may be the same. It'd be worth trying to reproduce the issue without using any USB scripts (including reflashing) vs using them heavily.

Ideally, we should avoid such issues by gaining exclusive access to the USB HID raw interface for Agent, but in practice, this doesn't seem to be viable across OSes. We'll probably end up reworking the UHK USB TypeScript library so that USB commands will be routed through Agent when it's running.

**Comment by kareltucek** [comment]
Managed to reproduce similar problem:

If I flash UHK outside of Agent, new macros and deleted macros are then not propagated into the left menu. It actually seems deterministic.

[app.log](https://github.com/UltimateHackingKeyboard/agent/files/10031061/app.log)

![2022-11-17-123953_2123x1722_scrot](https://user-images.githubusercontent.com/3447497/202436935-c90349f0-04e3-412a-b2ea-7be48f363c1d.png)

**Comment by ert78gb** [comment]
As I thought. After the device reconnects Agent reads the user config from UHK and agent rearrange the macro ids

**Comment by mondalaci** [comment]
I can easily reproduce the issue as described.
