### ISSUE TITLE
Agent 2.0.0 can't find device

### ISSUE THREAD

**Issue by mizvekov** [UltimateHackingKeyboard/agent#1880]
I just recently updated to 2.0.0 from 1.5.7.

2.0.0 can't find my device, It stays on "Searching for your UHK, Hang tight!" screen indefinitely, while 1.5.7 could.

This is a Windows 11 system.

**Comment by jesperp** [comment]
Same issue on macOS 11.6.2 after upgrading (manually). 
Also, before manually installing 2.0.0 I tried to upgrade via the app with this result:

![signal-2022-10-29-181856_002](https://user-images.githubusercontent.com/376921/198842211-3c3ca8bb-1bc7-4e42-85bf-c8dd0cb72959.png)

**Comment by amejiarosario** [comment]
I had the same issues on a Mac OS

**Comment by ochicf** [comment]
Same issue on macOS 12.6 on an M1 Pro.

**Comment by carlosflorencio** [comment]
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/1500881/198889778-90e2c1fb-665f-4ede-bb80-d2258375a40c.png">

Posting the error that's spamming the console.

**Comment by mondalaci** [comment]
The newly released Agent 2.0.1 should solve this issue.
