### ISSUE TITLE
[Feature Request] Ask the user to <put action here> prior to updating the firmware

### ISSUE THREAD

**Issue by abonhote** [UltimateHackingKeyboard/agent#1902]
I updated from 8.x to 9.x recently while my keyboard was connected via USB hub. This apparently caused the update to fail on the left half. Even after connect the UHK directly the update didn't work right away. I removed the key cluster and the touchpad, connected the two halves and then reconnected it - this made the update work.

It's maybe worth putting a few words into a dialog prior to updating. My 2 cents as developer without hardware experience ;-)

**Comment by mondalaci** [comment]
Thanks for your suggestion, but the cause of this issue is probably not your USB hub. Rather, the culprit is the electronic design of the UHK, which we will improve upon in further hardware versions.

In the meantime, #1663 should make the update more reliable and faster.
