### ISSUE TITLE
implement native double-tap as generic 3rd per key behavior as option in the agent - Feature Request

### ISSUE THREAD

**Issue by eegil** [UltimateHackingKeyboard/agent#1913]
User should have the option to select double-tap behavior to any key of his choosing.

**Comment by kareltucek** [comment]
Please, take a look at extended macro commands: https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md . 

Namely, you can use `ifDoubletap` (which does not suppress the first tap) or `ifGesture` (which does suppress the first tap).

Regarding _native_ action for that, that's a question for @mondalaci

**Comment by mondalaci** [comment]
We won't make a dedicated UI for this feature in Agent. Smart macros are the way to go, as suggested.

I'm closing this issue, but feel free to follow up.

**Comment by eegil** [comment]
thanks for the response. The idea behind the request is that also non-technical users are/might use the keyboard and smart macros documentation is hardly usable from a non-technical user perspective. Maybe some more extensive list of practical examples would help ease understanding it.

**Comment by mondalaci** [comment]
I plan to make the extended commands more accessible via examples and other ways. Thanks for the idea!

**Comment by kareltucek** [comment]
Better, more extensive and more user friendly documentation is planned by Laszlo eventually in the future, but for the moment, I am afraid you will have to stick with my technical approach. (The mentioned commands are not even officially supported at the moment.)

----

Regarding the markdown docs, I believe both the commands are satisfactorily explained in the example section of the user manual - https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md . 

If there is anything unclear or unintuitive about those examples, or the link in the first paragraph of the reference manual is hard to find, please suggest specific improvement ideas.
