### ISSUE TITLE
Secondary role for Modifier keys won't be meaningful

### ISSUE THREAD

**Issue by fr2lancer** [UltimateHackingKeyboard/agent#1915]
Agent version: 2.0.2
UltimateHackingKeyboard/firmware:9.1.4
Key cluster firmware: 8.10.12
Trackpoint firmware: 8.10.12

Hi I am first time using UHK.

when I tried to setup secondary role for ctrl key. I have the following problem.

ctrl, Alt key as modifier keys is meaningful when pressing other keys such as ctrl + a, c, z..

And the concept of 'secondary role' in UHK agent, it invokes when other key is pressed.

So, when I press ctrl + a (as an example) - it won't to be executed as primary role.

Personally I expected to have this when I saw the  'secondary role',

shot press : do primary function including modifier keys
long press:  do secondary function (even including layer switcher keys - control key can send command 'mouse' ,'fn' or 'mod' 

It can be defined better way to have those.

**Comment by mondalaci** [comment]
@kareltucek Would you please help? Sorry, but I don't clearly understand what @fr2lancer is trying to achieve.

**Comment by fr2lancer** [comment]
1) Modifier keys aren't working with concept of 'secondary role' in UHK agent,
2) To improve this, I suggest to introduce shot/long press to have different key codes

**Comment by kareltucek** [comment]
I too don't understand why current definition of secondary roles should be meaningless.

Secondary roles in UHK are defined exactly to act as a secondary role when used with another key. E.g., the control key can be bound to produce "esc" when tapped and to act as ctrl when used together with another key.

However, I guess this boils down to wanting some advanced secondary role resolution strategy - in that case, https://github.com/UltimateHackingKeyboard/firmware/issues/207 is relevant.

**Comment by fr2lancer** [comment]
How to reproduce

1. set ctrl key(firmware default was mouse key)  'secondary role' to 'Mod' in the agent.
2. open notepad and type some words in it.
3. click ctrl + a to select all words

expected : all characters are selected
actual : ask me to save the file in modal box ( c key is mapped to w in mod in default)

**Comment by kareltucek** [comment]
So you have:

- primary role: Ctrl key
- secondary role: Mod layer

?

**Comment by fr2lancer** [comment]
@kareltucek yes

**Comment by kareltucek** [comment]
Yes, then you are interested in the linked firmware#207 issue. We plan to resolve it eventually, but it is not a priority at the moment.

Unless you have more questions, please do mark this issue as closed. (I can't.)
