### ISSUE TITLE
Assignable for module behaviors

### ISSUE THREAD

**Issue by fr2lancer** [UltimateHackingKeyboard/agent#1916]
Agent version: 2.0.2
UltimateHackingKeyboard/firmware:9.1.4
Key cluster firmware: 8.10.12
Trackpoint firmware: 8.10.12

https://ultimatehackingkeyboard.com/manuals/trackball : 
```
When the Mod layer is active, the ball behaves like a scroll wheel, allowing for vertical and horizontal scrolling.

When the Fn layer is active, the ball behaves like arrow keys, allowing quick movement in text editors.
```

https://ultimatehackingkeyboard.com/product/touchpad : 
```
When the Mod layer is active, the touchpad behaves like a scroll wheel, allowing for vertical and horizontal scrolling.

When the Fn layer is active, the touchpad behaves like arrow keys, allowing quick movement in text editors.
```

https://ultimatehackingkeyboard.com/manuals/trackpoint : 

```
When the Mod layer is active, the pointing stick behaves like a scroll wheel, allowing for vertical and horizontal scrolling.

When the Fn layer is active, the pointing stick behaves like arrow keys, allowing quick movement in text editors.
```

those are pre-defined key mappings for module.

I think it would be better to have customizable mapping for those functions not fixed mapping.

**Comment by mondalaci** [comment]
These are already implemented. Upgrade to the latest Agent and firmware and see the navigation modes in the smart macro sidebar.

**Comment by fr2lancer** [comment]
Thank you @mondalaci just still I can't find it in release yet. but I am expecting to see it soon.

**Comment by kareltucek** [comment]
Please, look again.

![2022-11-20-121247_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/202898969-ffa0b3aa-c023-4ce6-8617-de04aa018f3f.png)

(And the section to rebind actions in navigation modes is right below it.)

**Comment by fr2lancer** [comment]
oh okay There wasn't $onInit by default. I have created it then I can update the key binding.
I think it would be better to specify that user also can create that macro name($onInit) in the help page.

Thank you.

**Comment by mondalaci** [comment]
We'll make a more accessible user interface for these settings in Agent eventually.
