### ISSUE TITLE
FR: load the active keymap in agent

### ISSUE THREAD

**Issue by laur89** [UltimateHackingKeyboard/agent#1917]
User has keymap `A` selected as the default/favourite/starred one, but currently keymap `B` is active.
Now user launches `agent` program.

**As-is:**
Agent interface opens, and `A` keymap is selected in the UI.

**To-be:**
Agent interface opens, and `B` keymap is selected, as it's the _currently active_ one.

--------------
IMHO this offers better UX, as user is more likely to edit the currently active keymap as opposed to the default one.
agent v `2.0.2`, behavior is consistent in both Windows and Linux clients.

**Comment by mondalaci** [comment]
It's a matter of opinion of what's right in this case.

Currently, Agent highlights the default keymap with a star, and it selects it on startup, which I believe is reasonable.

If Agent selected the current keymap, some users would perhaps also expect it to jump to the current keymap once it's changed on the UHK. I think the current behavior results in less confusion overall.
