### ISSUE TITLE
Update smart macros references to keymaps and other macros

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#1923]
As I can see on the online version of agent, when a keymap abbreviation is changed or a macro is renamed or deleted, smart macros aren't updated accordingly.
For example, smart macro A contains a command to run macro B (_exec B_). If you rename macro B to C, the command should be changed to _exec C_, as it already happens with key assignments on the keymaps.
In the case of deletion I would suggest to comment the line instead of removal.

**Comment by kareltucek** [comment]
You know, this is quite a complicated feature request.

I would love to extend Agent with an actual parser of the language for the purpose of providing an autocomplete. Assuming we had such a parser, it may be possible to implement a generic rename feature.

But even then as a user and a developer I would probably not want an automated thing going around my macros and just changing them.

Aso as far as my opinion on this goes, it is somewhere between: "no way", "would love to see a PR" and "exotic feature".

**Comment by mondalaci** [comment]
I fully agree with Karel. We can't implement this feature with reasonable effort, so it's not planned.
