### ISSUE TITLE
Response code: 6

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#1932]
Hi! I'm trying to upgrade my UHK to latest 9.1.4 version and I'm getting many response code 6 errors.
I'm using a Debian 11.5 Cinnamon live distro.
Changing firmware using agent 2.0.1 or 2.0.2 throws the error after the installing the firmware on one side. It needs to be upgraded a second time in order to upgrade the other side and the cluster module. It doesn't matter whether I upgrade or downgrade the firmware, or if I use the embedded firmware or from a file. I have to do the process twice.
Using agent 1.5.6 I'd no issues at all.

Also, I'm having issues with my configuration. It throws always a response code 6 error.
I've done a bit of research (creating different configurations with only one keymap each one and keeping the macros) and I found which keymap is the culprit, but I can't figure why. In fact, this is a very simple keymap. Also, is important to notice that it loads correctly on agent, as well on the online version.

[uhk156_update.log](https://github.com/UltimateHackingKeyboard/agent/files/10112830/uhk156_update.log)
[uhk202_update_part1.log](https://github.com/UltimateHackingKeyboard/agent/files/10112831/uhk202_update_part1.log)
[uhk202_update_part2.log](https://github.com/UltimateHackingKeyboard/agent/files/10112832/uhk202_update_part2.log)
[wrongkeymap.zip](https://github.com/UltimateHackingKeyboard/agent/files/10112833/wrongkeymap.zip)

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
The user configuration is invalid. Few module section contain only 34 key action definition. 35 is the required.

@IzK666 Have you ever modified the  user configuration manually or via a 3rd party tool?

**Comment by IzK666** [comment]
@ert78gb You're almost right. Layer base, left side has 36 key action definitions.
What it upsets the most is that is my current configuration with fw 8.10.10!
And about your last question, don't worry. The error isn't from agent.

I'll check again the update process with a correct configuration file and tell you.

**Comment by mondalaci** [comment]
@IzK666 Did you update your JSON configuration manually? We need to know because it's the second issue of its kind, and we may implement a related fix in Agent.

**Comment by IzK666** [comment]
Yes.
