### ISSUE TITLE
Macro Menu: Scancode Scrolldown Bug

### ISSUE THREAD

**Issue by Mark31415** [UltimateHackingKeyboard/agent#1936]
While creating a Macro the scrolldown menu for Scancodes seems to be broken.
I cannot even scroll down with mouse, only arrow keys are working but the choosen entry is not shown.

![Unbenannt](https://user-images.githubusercontent.com/63504055/205378950-a4082c2a-3d48-4876-972a-ecd7b08b69e9.PNG)

Agent 2.0.2

**Comment by mondalaci** [comment]
Thanks for reporting! I can easily reproduce this bug. We'll fix it soon.
