### ISSUE TITLE
Error after deleting macros

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#194]
I reset local storage, delete every macro, go to the VIM keymap, and get this:

![untitled](https://cloud.githubusercontent.com/assets/300402/20649892/a4cf0070-b4c9-11e6-871e-36f707b5b10d.png)

**Comment by fjozsef** [comment]
Possibly duplicate of #140

**Comment by mondalaci** [comment]
Good catch! Yes, it's possibly a duplicate. We should look into it.
