### ISSUE TITLE
Suggestion: refactor key/mouse macro actions

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1940]
- [ ] "Mouse action" > "Hold button" should be renamed to "Press button", as hold means a different thing in the current macro engine terminology.

- [ ] Add new actions: "Key action" > "Hold key" and "Mouse action" > "Hold button". These would correspond to a new macro subaction `MacroSubAction_Hold = 3`. This value is already supported by the firmware.

Priority: low.
Difficulty: no-brainer (I believe).

**Comment by mondalaci** [comment]
> "Mouse action" > "Hold button" should be renamed to "Press button", as hold means a different thing in the current macro engine terminology.

How so?

> Add new actions: "Key action" > "Hold key" and "Mouse action" > "Hold button". These would correspond to a new macro subaction MacroSubAction_Hold = 3. This value is already supported by the firmware.

How would Hold differ from the current key press and mouse hold button actions?

**Comment by kareltucek** [comment]
Does the following docs excerpt explain both questions?

> ### Binding keys and basic principles
> 
> 
> Key lifecycle consists of two important points:
> 
> - key press
> - key release
> 
> Various combinations of lifecycles are abstracted into following actions:
> 
> - `pressKey` - just activate the scancode
> - `releaseKey` - just deactivate it
> - `tapKey` - activate the scancode and then immediately release it
> - `holdKey` - activate the scancode and hold it for as long as the key is physically held, then release it
> - `delayUntilRelease` - will wait until the key that activated the macro is released
> 
> So if we wanted to replace a regular 'a' key with a macro, we would use:
> 
> ```
> holdKey a
> ```
> 
> Which is similar to:
> 
> ```
> pressKey a
> delayUntilRelease
> releaseKey a
> ```
> 
> If we just want to quickly produce the `a` scancode/character, we would use:
> 
> ```
> tapKey a
> ```
> 
> Which is similar to:
> ```
> pressKey a
> releaseKey a
> ```

**Comment by mondalaci** [comment]
Seems powerful, but can you provide some practical use cases?

**Comment by kareltucek** [comment]
`holdKey` or `delayUntilRelease` are just essential building blocks that are just needed to do basic stuff... such as making a macro behave as regular key. (Which is needed whenever you want to hook additional behaviour onto a key.)

For specific usecases, please, do ctrl+f for "holdKey" at https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md . Furthermore https://github.com/UltimateHackingKeyboard/firmware/issues/577 is a case of this.

This issue is not about making things more powerful. It is about making them more consistent. (So those things that can be found in the GUI match up with those available in the command interpreter.)

**Comment by mondalaci** [comment]
I'm not convinced of the widespread use of this feature.

I'm all for consistency, but once the module settings are directly accessible from Agent, I expect a small portion of users to use smart macros. I still find smart macros valuable, but I don't want to expose additional complexity to most Agent users.

The use cases I saw are quite niche. You're welcome to prove me wrong or elaborate further.

**Comment by kareltucek** [comment]
Do as you will. I find this absurd.

**Comment by mondalaci** [comment]
What do you find absurd exactly?

**Comment by kareltucek** [comment]
Honestly, I am not sure.

Partially it is that I find this to be a pretty minor and noncontroversial refactor, and can't wrap my head around the objections.

Partially it is that I had seen this argument many times before, yet the vastness of the abyss that separates our philosophical views on building things still baffles me.

Anyway, no point in dissecting this further. I don't have any argument that would move you.

**Comment by mondalaci** [comment]
As for mouse button-related macro actions, it's currently possible to tap/press/release any combination of mouse buttons. Let's say we added hold. From a user's standpoint, what'd be the difference between press and hold? How would you explain them without involving more complex concepts like the macro engine?

As for key macro actions, my question is the same.

**Comment by kareltucek** [comment]
The difference is that if you press and hold a `holdKey space` for a few seconds, you get `              ....`. If you do the same with a `pressKey space`, you get just a single space character.

**Comment by kareltucek** [comment]
As to how would I explain them without compkexity, I would use the tap key icon with a little clockface/stopwatch added.

**Comment by mondalaci** [comment]
I understand, but nobody would map space as a macro instead of a key action.

The way I see it, hold key/button is useful when it enables use cases easily without using smart macros, which would only be possible with smart macros currently. https://github.com/UltimateHackingKeyboard/firmware/issues/577 is the only scenario I can think of where my condition applies. Are there others?

**Comment by kareltucek** [comment]
I don't know. That is not the point. 

The primary point is consistency. If you don't see it or don't agree, I don't have a better argument, so feel free to either close it or reduce it to the first bullet.

**Comment by mondalaci** [comment]
Thanks for explaining. I understand that you want to make the states of the macro engine more consistent with Agent.

I'm very cautious about exposing features, and rather not expose them if I don't see substantial added value for users. I can only think of https://github.com/UltimateHackingKeyboard/firmware/issues/577 where this feature would be useful. On the flip side, it introduces complexity, making it harder for users to wrap their heads around tap/press/release/hold than without hold. 
You may not agree because, as the principal creator of the macro engine, the distinction of these states is trivial to you.

I'm still excited about further developing smart macros, and I plan to improve the sidebar documentation's structure, navigation, and content.

I'm closing this issue, but feel free to follow up.
