### ISSUE TITLE
[Bug Report] Key action scancode dropdown menu cuts off for new macro action when menu opens above (e.g. when near bottom of screen)

### ISSUE THREAD

**Issue by Usoka** [UltimateHackingKeyboard/agent#1952]
When adding an action to a macro if you select Key Action then click the scancode box, if the dropdown menu opens above the input box then it cuts off at the top of the overall box for the New Macro Action. This makes it harder for a user to input a value via the dropdown.

**Steps to reproduce:**
1. Create a macro and add a series of steps, or shrink the window down such that the next New Macro Action opens at the bottom of the page
2. Click "+ Add macro action"
3. Select "Key action"
4. Click in the Scancode input box, prompting the dropdown menu to open. It needs to open upwards above the input box to reproduce
5. Observe

**Expected result:**
Dropdown menu should open above as the top layer and not get cut off at the top of the new macro action box

**Actual result:**
Dropdown is cut off, see example image (note I have shrunk the window for recreating in this example to keep it compact, but it also occurs when fullscreen):
![image](https://user-images.githubusercontent.com/27248545/210699822-b684e9ff-4b51-4bfb-b17e-a5c3b44a0154.png)

**Comment by mondalaci** [comment]
Thanks for your report! It's already fixed in master, and I'll publish a new release soon.
