### ISSUE TITLE
[Feature Request] backlight and display inactivity shutoff timer

### ISSUE THREAD

**Issue by rchipka** [UltimateHackingKeyboard/agent#1963]
It would be nice to have the LED backlight and seven-segment display shut off after a configurable amount of input inactivity.

This would be especially helpful in instances when the computer is running with the display off, but the UHK lights remain on. In these cases I usually have to resort to unplugging the keyboard.

Ideally sleep/restore would be implemented as a quick fade in/out rather than a harsh on/off of the bright LEDs.

**Comment by mondalaci** [comment]
It's already possible via a [smart macro](https://ultimatehackingkeyboard.com/blog/2022/11/18/agent-2-next-level-uhk-and-module-configuration) variable, and it'll be more user-friendly to setup later.

**Comment by rchipka** [comment]
Perhaps we could configure both the active/inactive brightness levels separately, with main brightness and an inactive brightness setting that can be set to a low value (or off completely)

**Comment by mondalaci** [comment]
Currently, only the fully off setting is supported after a specifiable amount of time. We can implement a configurable off brightness level, but only if there's a decent demand for it.
