### ISSUE TITLE
Firmware update does not work

### ISSUE THREAD

**Issue by dischoen** [UltimateHackingKeyboard/agent#1964]
Hi,

First, the keyboard is working fine with its current firmware.

Just unpacked my new keyboard and started agent, which asked me to upgrade the firmware.
I tried several USB ports, also disconnected/reconnected. The halves are connected.
I am using Ubuntu 22.04.1 LTS.

Anything else I can try?

Dieter

Update: same behaviour with Windows.
----

Start flashing firmware
[DeviceService] Operating system: Linux 5.15.0-58-generic x64
[DeviceService] Agent version: 2.1.1
[DeviceService] New firmware version: 9.2.1
[DeviceService] New firmware user config version: 5.1.0
[DeviceService] stop poll UHK Device
[DeviceService] stopped poll UHK Device
[DeviceOperation] Read "leftHalf" version information
[DeviceService] UHK Device firmware upgrade starts: {"id":2,"name":"UHK 60 v2","vendorId":"0x1D50","keyboardPid":"0x6124","bootloaderPid":"0x6123","buspalPid":"0x6121"}
[DeviceService] Device right firmware version: 8.10.12
[UhkOperations] Start flashing right firmware
[UhkOperations] Reenumerate bootloader
[UhkHidDevice] Start reenumeration, mode: Bootloader, timeout: 5000ms
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":1,"usagePage":1,"usage":6}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":2,"usagePage":12,"usage":1}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":3,"usagePage":1,"usage":128}
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":4,"usagePage":1,"usage":2}
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":-1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting...
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Removed: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":-1}
[UhkHidDevice] Could not find reenumerated device: Bootloader. Waiting.....
[UhkHidDevice] Reenumerating devices
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
[UhkOperations] Waiting for bootloader
[UhkOperations] Flash security disable
[DeviceService] updateFirmware error {"message":"cannot open device with path /dev/hidraw0","stack":"TypeError: cannot open device with path /dev/hidraw0\n at new HID (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/node_modules/node-hid/nodehid.js:49:17)\n at ar.open (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:517805)\n at /tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:517946\n at new Promise (<anonymous>)\n at ar.sendCommand (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:517916)\n at Zt.flashSecurityDisable (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:514531)\n at Object.updateRightFirmwareWithKboot (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:630528)\n at async Gr.updateFirmware (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:531697)\n at async hr.process (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:521202)"}
[UhkHidDevice] Available devices changed.
[UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6123","path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2 Bootloader","release":2,"interface":0,"usagePage":65280,"usage":1}
[DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected at /tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:624484 at new Promise (<anonymous>) at Object.write (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:624418) at Object.getDeviceState (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:627301) at Object.waitUntilKeyboardBusy (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:636563) at Gr.getHardwareModules (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:528849) at Gr.updateFirmware (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:533716) at async hr.process (/tmp/.mount_UHK.Ag6rIEMo/resources/app.asar/electron-main.js:2:521202)
[DeviceService] start poll UHK Device
cannot open device with path /dev/hidraw0

**Comment by ert78gb** [comment]
Hi @dischoen ,

Does the firmware upgrade always fail after the `[UhkOperations] Flash security disable` step?
Please try to upgrade the firmware few times and check the error step.

**Comment by dischoen** [comment]
Hi @ert78gb ,

most of the time it's `Flash security disabled`, but I also had
once: after `UhkHidDevice Added`
and several times: Available devices unchanged.

On Windows I have
`Could not find reenumerated device: Bootloader. Waiting..................................................`
as last white message before the errors.

**Comment by mondalaci** [comment]
[This article](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys) contains several points which may help. Please give them a try.

**Comment by dischoen** [comment]
Stop the press!

While testing on window I saw that UHK was partially kidnapped by VMware.
I terminated VMware and then the firmware update worked!

This is an acceptable workaround for me.
But I am willing to execute some tests if you want to investigate further.

**Comment by mondalaci** [comment]
Ah, that explains it; thanks for the follow-up! I guess we better include relevant instruction in Agent.
