### ISSUE TITLE
Feature: Swap keys across layers

### ISSUE THREAD

**Issue by porceCodes** [UltimateHackingKeyboard/agent#1965]
Agent allows users to swap two keys by drag-then-drop of the mouse move, within the same layer. 

It also needs to support cross-layer support. There, a user may drag a key to a layer tab, which will switch the layout to the aforementioned layer, and allow to drop there. Throughout the workflow, the user should be able to continue to hold the mouse click

**Comment by mondalaci** [comment]
I'm sorry, but this is a very niche request, so we don't plan to implement it.
