### ISSUE TITLE
Feature: long press

### ISSUE THREAD

**Issue by porceCodes** [UltimateHackingKeyboard/agent#1966]
A key press "a" should show "a". A long press "a" should show "A". Even longer press (call it hold press) should show repeated keys "aaaaa..".
Shift+ hold press "a" should show "AAAA..."

The criteria to classify whether this is a short press, long press, hold press should be user configurable.

**Comment by kareltucek** [comment]
I believe https://github.com/UltimateHackingKeyboard/firmware/issues/207 can do that when it is implemented.

**Comment by kareltucek** [comment]
Also you should be able to figure out something with the extended mode of smart macros. I think `delayUntilReleaseMax` and then switching with `ifPlaytime` should be sufficient.

See https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md

**Comment by mondalaci** [comment]
Closing this issue because it's firmware related.
