### ISSUE TITLE
【bug report】no switch to super or other added layers on uhk agent 2.1.2

### ISSUE THREAD

**Issue by Ravenclawer** [UltimateHackingKeyboard/agent#2007]
I have added a new layer name super but there is no option to switch to the super layer in layer setting tab
![image](https://user-images.githubusercontent.com/73892411/233824023-44096964-1e79-465b-830e-5521a45845b8.png)

**Comment by mondalaci** [comment]
You simply have to use the relevant modifier to activate the desired modifier layer.

**Comment by Ravenclawer** [comment]
could you elaborate on the process ？

**Comment by mondalaci** [comment]
https://ultimatehackingkeyboard.com/blog/2023/03/03/how-to-use-modifier-layers

**Comment by kareltucek** [comment]
(Unlike fn2 - fn5, modifier layers are not regular layers. Actions defined in these layers override base-layer actions when modifiers (shift / ctrl / alt/ super) are pressed. If you enable fn2 - fn5 layers, you should see them in the Layer dropdowns.)
