### ISSUE TITLE
Changing the color of the active key to blue

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#201]
The idea is to change the color of the selected key to blue as soon as the popover pops up. The color should transition from the highlighted gray color of the key to our signature blue color. It should transition in the same interval it takes for the popover to animate.

Ideally, the highlighted key should not be covered by the dark overlay. Nejc briefly looked into using z-index to implement this but he didn't find a way. This should be investigated more thoroughly.

As a viable hack to impelement the highlighting of the current key, we could oversaturate the animated brightness to compensate for the dark overlay. This would not look ideal, but better than nothing.

**Comment by fjozsef** [comment]
@mondalaci What is the state of this issue? Is evertyhing covered by #290 ?

**Comment by mondalaci** [comment]
@fjozsef Good point. This has been fully resolved, indeed.
