### ISSUE TITLE
Agent error: cannot write to keyboard device

### ISSUE THREAD

**Issue by parke** [UltimateHackingKeyboard/agent#2010]
Agent is unable to communicate with my UHK.

I suspect the error is due in large part to the minimal nature of my Ubuntu 22.04 installation.  (I installed Ubuntu via `debootstrap`, not via the standard installer.  I run Xorg and the Openbox window manager, but not much else in terms of standard Linux desktop infrastructure.)

I suspect somewhere in `/dev` (or `/sys`?) on my system the permissions differ from a vanilla Ubuntu installation.  And that this difference is what is causing the error.  But I don’t know where the difference is.

For comparison, I can report that Agent runs successfully on a second system running vanilla Ubuntu (installed with the standard installer).

However, on my minimal system, the below errors are printed to the console.  The Agent window does appear, with the message: “Searching for your UHK.  Hang tight!”

```
13:17:41.850 › [DeviceService] start poll UHK Device
13:17:41.979 › [UhkHidDevice] Devices before checking permission:
13:17:41.982 › [UhkHidDevice] Available devices changed.
13:17:41.982 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
13:17:41.982 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":1,"usagePage":1,"usage":6}
13:17:41.983 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":2,"usagePage":12,"usage":1}
13:17:41.983 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw7","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":3,"usagePage":1,"usage":128}
13:17:42.045 › [UhkHidDevice] Available devices unchanged
13:17:42.105 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
13:17:47.154 › [UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at /opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589679
    at new Promise (<anonymous>)
    at Object.write (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589478)
    at Object.getDeviceState (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:592361)
    at Object.getHalvesStates (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:592144)
    at Object.getDeviceConnectionStateAsync (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589395)
    at Xr.uhkDevicePoller (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:502282)
13:17:47.155 › [UhkHidDevice] Device communication closing.
13:17:47.155 › [UhkHidDevice] Device communication closed.
13:17:47.155 › [DeviceService] Device connection state query error TypeError: Cannot write to hid device
    at /opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589679
    at new Promise (<anonymous>)
    at Object.write (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589478)
    at Object.getDeviceState (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:592361)
    at Object.getHalvesStates (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:592144)
    at Object.getDeviceConnectionStateAsync (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:589395)
    at Xr.uhkDevicePoller (/opt/uhk-2.1.2/resources/app.asar/electron-main.js:2:502282)
```
Agent version is 2.1.2.  The UHK `udev` rules are installed on both systems.

I have run `chmod 666 /dev/hidraw*`, so all the `/dev/hidraw*` devices should be writable.  (The devices were probably writable before I did this, due to the `udev` rules.)

I’ve compared strace logs on both my minimal system (with the error) and a vanilla Ubuntu system (runs successfully), but the logs are very large, and I cannot see any meaningful differences.

What devices (other than `/dev/hidraw*`) does Agent try to write to?

I will attempt to attach the complete console output of Agent to this issue report.

I also ran `find /dev /sys` both before and after plugging in the UHK, and then ran `diff` on the two outputs.  This provides a list of all the `/dev` and `/sys` entries that are created when the UHK is plugged in.  I will attempt to attach this list as well.

Here are the attachements:
*  [20230502_uhk_simple.log](https://github.com/UltimateHackingKeyboard/agent/files/11401344/20230502_uhk_simple.log)
*  [20230504_uhk_dev_diff.txt](https://github.com/UltimateHackingKeyboard/agent/files/11401352/20230504_uhk_dev_diff.txt)

**Comment by ert78gb** [comment]
The error occurred when Agent tried to connect to the hidraw device. The `[UhkHidDevice] Used device:` shows which device exactly. Agent always try to connect to the device which `interface` property `0`.

You mentioned the `udev` rules were set. We use the following udev rules, but I think it is not perfect in your setup
```
SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
```

I don't see the `[UhkHidDevice] hasPermission` line in the logs, so looks like Agent can open the device, but can't write any message.
Please run Agent with the `--log=all` command line argument? I would like to check will it when write the first byte or later.

If you start Agent as root then do you still get the error? I just would like to be sure it is an access issue instead of a dependency missing. Agent could query the list of the usb devices so, my assumption is every dependency were installed.

> What devices (other than /dev/hidraw*) does Agent try to write to?

Agent uses only `hidraw` devices

**Comment by parke** [comment]
> Agent always try to connect to the device which `interface` property `0`.

How do I locate or read the `interface` property?

> You mentioned the `udev` rules were set. We use the following udev rules, but I think it is not perfect in your setup
> 
> ```
> SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"
> SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
> KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
> ```

Here are my `udev` rules:
```
SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
```

If you are wondering why the `udev` rules appeared in the log, that could be because the log was generated from inside a container.  The rules file is present in the host, not in the container.  (See more details about containers below.)

> I don't see the `[UhkHidDevice] hasPermission` line in the logs, so looks like Agent can open the device, but can't write any message. Please run Agent with the `--log=all` command line argument? I would like to check will it when write the first byte or later.

    $ ./AppRun --log=all
    ./AppRun: line 45: /uhk-agent: No such file or directory

The above error may be due to the fact that I am running Agent as an extracted AppDir, not as an AppImage.  The following works:

    $ export APPDIR=$PWD
    $ ./AppRun --log=all

* [20230505_minimal_log_all.txt](https://github.com/UltimateHackingKeyboard/agent/files/11409383/20230505_minimal_log_all.txt)

I do not see any difference in the `--log=all` log.  I did `export DEBUG=1` so I could confirm that `./AppRun` is passing `--log=all` to `uhk-agent`.  `--log=all` is being passed.

I will attempt to generate the same log on the full Ubuntu system later today, so you can see what is in it.

(I use AppDir because the suid-bit is ignored inside the container.  Consequently, FUSE mounts are not possible inside the container.)

> If you start Agent as root then do you still get the error?

I'm unwilling to run Agent as root on my main system.  So to do that test, I'd need to install my minimal OS on another system for that test.  I can do this, but it will take time and it may be several weeks before I have the time to try it.

I actually run Agent inside a container.  This worked on Ubuntu 20.04 (which was probably installed with the standard Ubuntu installer, as I don't think I had written my custom installer yet).

Inside the container is a full OS install.  Specifically, I am using the Linux Mint live ISO environment.  So I have four environments I can run in:

1)  Minimal OS host, inside a container
2)  Minimal OS host, plain (no container)
3)  Standard Ubuntu, inside a container
4)  Standard Ubuntu, plain (no container)

1 and 2 behave identically (write error).  3 and 4 behave identically (success).

As far as I know, the only difference is between 1 and 3 is that:

In 1, `/dev` and `/sys` (and `/proc`) are provided by my minimal OS (via bind mount).

In 3, `/dev` and `/sys` (and `/proc`) are provided by standard Ubuntu.

All other files in 1 and 3 are provided from the Linux Mint live ISO filesystem.squashfs file.

The container is based on an unprivileged Linux user namespace.  Consequently, permission "skew" may occur.  However, Agent runs fine in exactly the same container on the standard Ubuntu host.

Thank you for your assistance.

**Comment by ert78gb** [comment]
> How do I locate or read the interface property?

The interface number is part of the usb descriptor. As far as I know you could reference for it as `ATTR{bInterfaceNumber}=="0"`

> I do not see any difference in the --log=all log. I did export DEBUG=1 so I could confirm that ./AppRun is passing --log=all to uhk-agent.  --log=all is being passed.

Agent did not get the command line argument because the first line of the log does not contain it
`11:57:21.273 › [Electron Main] command line arguments {}`
it should be `[Electron Main] command line arguments { log: 'all' }`

As I see your linux knowledge is much stronger than mine. I would like to help to you but I think I just can learn from your.
I am very excited what will the solution so I would like ask if you will find it please share it here.

**Comment by parke** [comment]
> > I do not see any difference in the --log=all log. I did export DEBUG=1 so I could confirm that ./AppRun is passing --log=all to uhk-agent.  --log=all is being passed.
>
> Agent did not get the command line argument because the first line of the log does not contain it `11:57:21.273 › [Electron Main] command line arguments {}` it should be `[Electron Main] command line arguments { log: 'all' }`

Very strange.  Here is an excerpt of the output with `export DEBUG=1`.  The command I ran was `./AppRun --log=all`.

```
+ trap atexit EXIT
+ isEulaAccepted=1
+ '[' -z '' ']'
+ APPIMAGE=/opt/uhk/uhk-2.1.2/AppRun
+ atexit
+ '[' 1 == 1 ']'
+ '[' 1 -eq 0 ']'
+ exec /opt/uhk/uhk-2.1.2/uhk-agent --log=all
17:04:07.805 › [Electron Main] command line arguments {}
17:04:07.809 › [Electron Main] init services.
17:04:07.809 › [Electron Main] packagesDir: /opt/uhk/uhk-2.1.2/resources
```

Note the line:  **`+ exec /opt/uhk/uhk-2.1.2/uhk-agent --log=all`**

Here is the full output:  [20230505_minimal_log_all_2.txt](https://github.com/UltimateHackingKeyboard/agent/files/11410769/20230505_minimal_log_all_2.txt)

> As I see your linux knowledge is much stronger than mine. I would like to help to you but I think I just can learn from your. I am very excited what will the solution so I would like ask if you will find it please share it here.

Okay...

I did a `git clone` and followed the build instructions.

When I run `npm run electron`, I get the following error (same as before).

```
17:24:09.063 › [UhkHidDevice] Available devices unchanged
17:24:09.121 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6122","path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v1","release":258,"interface":0,"usagePage":65280,"usage":1}
17:24:14.221 › [UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at /home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:594229
    at new Promise (<anonymous>)
    at Object.write (/home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:594028)
    at Object.getDeviceState (/home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:596911)
    at Object.getHalvesStates (/home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:596694)
    at Object.getDeviceConnectionStateAsync (/home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:593945)
    at en.uhkDevicePoller (/home/parke/2023_agent/agent/packages/uhk-agent/dist/electron-main.js:2:506837)
```

Is there some way to build Agent without compressing (minifying?) the entire application to a single line of Javascript?

I'd like to get a human readable stack trace, with meaningful line numbers that point to human readable source code files.  Is this possible?

Also, I'm puzzled by some of the logic in `uhk-hid-device.ts`

[Line 93](https://github.com/UltimateHackingKeyboard/agent/blob/4ecc3ef795e8d13b2ef2acead9066899f087b5c3/packages/uhk-usb/src/uhk-hid-device.ts#L93):

            const dev = devs.find((x: Device) => isUhkZeroInterface(x) || isBootloader(x));

            if (!dev) {
                return true;
            }

Why `return true`?  I'd naively expect `return false`.  (This may not matter, as the result is only used on line 148.)

**Comment by parke** [comment]
I'm starting to suspect this is not an issue with Agent, but rather with the Node uid libraries.

There error is probably coming from here:
[HID.cc line 407](https://github.com/node-hid/node-hid/blob/711311ad3113a761113abc44c492115b24694fc8/src/HID.cc#L407)

After examining my `strace` log, I filtered it as follows: `grep 'pid   304' strace.log | grep write`

Here is the relevant excerpt:

```
[pid   304] write(1, "12:07:50.666 \342\200\272 [UhkHidDevice] "..., 6812:07:50.666 › [UhkHidDevice] Devices before checking permission:
[pid   304] write(30, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   304] write(95, "[2023-05-03 12:07:50.666] [info]"..., 85) = 85
[pid   304] write(1, "12:07:50.747 \342\200\272 [UhkHidDevice] "..., 59 <unfinished ...>
[pid   304] <... write resumed>)        = 59
[pid   304] write(93, "[2023-05-03 12:07:50.747] [info]"..., 76 <unfinished ...>
[pid   304] <... write resumed>)        = 76
[pid   304] write(1, "12:07:50.748 \342\200\272 [UhkHidDevice] "..., 246 <unfinished ...>
[pid   304] <... write resumed>)        = 246
[pid   304] write(93, "[2023-05-03 12:07:50.748] [info]"..., 263 <unfinished ...>
[pid   304] <... write resumed>)        = 263
[pid   304] write(1, "12:07:50.749 \342\200\272 [UhkHidDevice] "..., 242 <unfinished ...>
[pid   304] <... write resumed>)        = 242
[pid   304] write(93, "[2023-05-03 12:07:50.749] [info]"..., 259 <unfinished ...>
[pid   304] <... write resumed>)        = 259
[pid   304] write(1, "12:07:50.749 \342\200\272 [UhkHidDevice] "..., 243 <unfinished ...>
[pid   304] <... write resumed>)        = 243
[pid   304] write(93, "[2023-05-03 12:07:50.749] [info]"..., 260 <unfinished ...>
[pid   304] <... write resumed>)        = 260
[pid   304] write(1, "12:07:50.750 \342\200\272 [UhkHidDevice] "..., 244 <unfinished ...>
[pid   304] <... write resumed>)        = 244
[pid   304] write(93, "[2023-05-03 12:07:50.750] [info]"..., 261 <unfinished ...>
[pid   304] <... write resumed>)        = 261
[pid   304] write(1, "12:07:50.967 \342\200\272 [UhkHidDevice] "..., 60 <unfinished ...>
[pid   304] <... write resumed>)        = 60
[pid   304] write(93, "[2023-05-03 12:07:50.967] [info]"..., 77 <unfinished ...>
[pid   304] <... write resumed>)        = 77
[pid   304] write(1, "12:07:51.025 \342\200\272 [UhkHidDevice] "..., 252 <unfinished ...>
[pid   304] <... write resumed>)        = 252
[pid   304] write(95, "[2023-05-03 12:07:51.025] [info]"..., 269 <unfinished ...>
[pid   304] <... write resumed>)        = 269
[pid   304] write(93, "\0\t", 2 <unfinished ...>
[pid   304] <... write resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid   304] write(2, "12:07:56.178 \342\200\272 [UhkHidDevice] "..., 68812:07:56.178 › [UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
```

So it appears to be a timeout error, but I have yet to figure out the number of the file descriptor that is timing out.  I'm not an expert at reading `strace` logs.

**Comment by ert78gb** [comment]
Some reason agent still doesn't get the command line arg. The correct exec command
```diff
-exec /opt/uhk/uhk-2.1.2/uhk-agent --log=all
+exec /opt/uhk/uhk-2.1.2/uhk-agent . --log=all
```

In the `packages/agent` folder you could run the `node --require source-map-support/register ../../node_modules/electron/cli.js ./dist/electron-main.js` command to get better call stack.

Line 93 returns with true because the devices list does not contain any UHK keyboard so we can't test permission. Other part of the code test the existence of a connected keyboard.

Agent periodically tries to detect and connect to the connected keyboard. I think this is the `clock` event in the strace log.

I wrote the following script to debug more simple way. Just extract and copy the following file into the root directory of the agent repo and run `node uhk-usb-test.js`.

[uhk-usb-test.js.zip](https://github.com/UltimateHackingKeyboard/agent/files/11411965/uhk-usb-test.js.zip)

Another thing came to my mind. Your minimal ubuntu install is very strict environment. Is it possible the OS exclusively lock the hidraw device to prevent access for other program? Or is there any other program that already connected to the hidraw device?

**Comment by parke** [comment]
> Some reason agent still doesn't get the command line arg. The correct exec command
> 
> ```diff
> -exec /opt/uhk/uhk-2.1.2/uhk-agent --log=all
> +exec /opt/uhk/uhk-2.1.2/uhk-agent . --log=all
> ```

Thanks.  I should be able to edit the `AppRun` script to adjust the `exec` command.  When I do, I'll let you know what the result is.

> In the `packages/agent` folder you could run the `node --require source-map-support/register ../../node_modules/electron/cli.js ./dist/electron-main.js` command to get better call stack.

Thanks.  Happily, I was able to interpret the original (single line) stack trace.  It helps that there is only one call to `write()` in `getDeviceState()`.

The failing call to `write()` is on [line 291](https://github.com/UltimateHackingKeyboard/agent/blob/master/packages/uhk-usb/src/uhk-hid-device.ts#L291).

I verified this by putting calls to `this.logService.error()` before and after that call to `write()`.  The one before was logged.  The one after never was.

> I wrote the following script to debug more simple way. Just extract and copy the following file into the root directory of the agent repo and run `node uhk-usb-test.js`.
> 
> [uhk-usb-test.js.zip](https://github.com/UltimateHackingKeyboard/agent/files/11411965/uhk-usb-test.js.zip)

Thanks.  At present, I am working on setting up a minimal Arch Linux system.  I want to find a minimal-ish system on which Agent runs successfully.  Arch seemed like a good way to try to do this.

There are too many differences between my minimal Ubuntu system and a standard Ubuntu system.  I don't want to try to hunt through all those differences to find the problem.

> Another thing came to my mind. Your minimal ubuntu install is very strict environment.

>  Is it possible the OS exclusively lock the hidraw device to prevent access for other program?

Seems unlikely.  What would create the lock?  My system has far fewer programs and daemons installed on it than standard Ubuntu.

> Or is there any other program that already connected to the hidraw device?

I don't know of any such program.  Would a first program connecting to the `hidraw` device cause a second program to timeout when writing?  Because the error is caused by a write timing-out.

Also, the GUI of Agent is freezing during the write.  Each freeze lasts for about 2 seconds (or maybe more than 2 seconds, I'd have to measure it).  So when Agent works (on standard Ubuntu), the call `write()` returns very quickly.  Whereas on my minimal Ubuntu system, the call to `write()` is blocking, and then timing-out and returning `-1`.

**Comment by parke** [comment]
> Or is there any other program that already connected to the hidraw device?

Here is a possible theory:  Something about my system is causing Agent itself to open the `hidraw` device twice (instead of just once).  And this is causing `write()` to block and timeout.

**Comment by ert78gb** [comment]
> Seems unlikely. What would create the lock? My system has far fewer programs and daemons installed on it than standard Ubuntu.

I don't know I just shared my thoughts.

> Here is a possible theory: Something about my system is causing Agent itself to open the hidraw device twice (instead of just once). And this is causing write() to block and timeout.

Agent pays attention keep open only 1 connection to the keyboard. Closing the connection and opening a new within few millisecond is part of the "normal" process, that works. No one reported it as a problem.
If the quick reconnection cause any issue in your system then my assumption is it caused on kernel/driver level because the os does not release the connection enough fast.

**Comment by parke** [comment]
I'm happy to report that I identified the problem.  I was looking in **entirely** the wrong place.

I realized that I had not recreated the error on a separate system.  I had my main system (with the error), and a test system (no error).  However, I had not reproduced the error on the test system.

I installed my minimal OS on the test system, and... Agent worked!

So this meant that, most probably, the problem was something to do with the **hardware** of my main system.  At this point, I quickly identified the problem.

My mouse and keyboard were connected as follows:

*  computer
*  (low quality?) 10(?) foot USB 2.0 cable
*  unpowered Amazon Basics USB 2.0 hub
*  (low quality?) 6(?) foot USB 2.0 cable
*  UHK provided USB cable
*  the UHK itself

So I tried ...
*  computer
* (high quality?) 10 foot USB 3.0 cable
*  UHK provided USB cable
*  the UHK itself

... and Agent worked!  Agent still works even if I insert the Amazon USB hub between the "high quality" USB 3.0 cable and the UHK USB cable.

So perhaps the write command sent to the UHK causes the UHK to draw more power than my series of USB cables could provide.  And the UHK fails silently, which causes a timeout.

Of course, I feel silly for not trying a different USB port much sooner.  The "high quality" USB 3.0 cable lives on my desk (direct, with no hub) precisely to put a high quality USB port within easy reach.  (The computer is located a few feet away from my desk.)

I was also misled because previously (a year or two ago) I used Agent on this system, with **almost** exactly the same setup, and everything worked fine.  However, as I think back, there was one difference.  At that time, I was using a cheap-but-powered USB 2.0 hub instead of the unpowered Amazon Basics USB hub.  That cheap, powered hub failed some months ago, and I decided to replace it with the unpowered Amazon Basics hub.  And this is the first time the equipment change has caused me any problems.  Live and learn, I guess.

**Comment by kopsis** [comment]
I just wanted to offer a quick "thanks" for documenting this. I've been beating my head against a wall trying to figure out why Agent could no longer connect to my keyboard. Your final comment made me realize I now had a KVM in the loop that wasn't there the last time Agent worked. Bypassed the KVM and "presto!" Successful Agent connection.
