### ISSUE TITLE
How to use runtime macro recording.

### ISSUE THREAD

**Issue by yan0lovesha** [UltimateHackingKeyboard/agent#2011]
There is a release note from 11/18/2022 said runtime macro recording is supported. I didn't find any detailed introduction for this feature. So, I am requesting some documents about where is it, what is it and how to use it. If it is already existing, please help to post the link here.

**Comment by mondalaci** [comment]
See https://ultimatehackingkeyboard.com/knowledgebase/how-can-i-use-smart-macros
