### ISSUE TITLE
Support for microphone mute

### ISSUE THREAD

**Issue by jpyllman** [UltimateHackingKeyboard/agent#2012]
I do not know if this is in any specification for HID yet. But some new laptops have specific microphone mute buttons. If it is available in standard HID it would be nice to have in the agent.

**Comment by mondalaci** [comment]
See the Media -> Mute scancode.

**Comment by mondalaci** [comment]
Sorry, I didn't read your issue thoroughly. I think there's a relevant scancode.

**Comment by mondalaci** [comment]
On page 34 of https://usb.org/sites/default/files/hut1_4.pdf , the 0xA9 scancode belongs to "System Microphone Mute", but when using Agent's [arbitrary scancode feature](https://github.com/UltimateHackingKeyboard/agent/issues/857) and entering B169, the mapped scancode doesn't do anything on neither of the three OSes, which makes me believe that this scancode is not implemented via USB.

**Comment by jpyllman** [comment]
But for me it is unclear how to get this work. It would be really nice to have the 'scancode' that is in the same range that the mute speaker. I will look in the UHK code to see if I can get some feeling how the scancode could look like. F20 is working on the linux x11 system where F20 is mapped to micmute.

**Comment by mondalaci** [comment]
Great finding regarding F20! I can confirm that it mutes the mic on Linux, but it doesn't work on other OSes, which is the reason why I don't want to get it added to the scancode dropdown, suggesting that it's an OS-independent scancode.

**Comment by benedekkupper** [comment]
The microphone mute functionality is first introduced in the HID telephony usage page, and only got more attention post-COVID - which meant that new usages and functionality was put into specification, but the rollout of this spec into OSes and gadgets will take a lot more years. If we want backwards compatibility with existing systems, we need to modify the UHK firmware so it supports sending HID telephony page scancodes.

**Comment by mondalaci** [comment]
@benedekkupper Thanks for the insight! I'm fine with adding support, but it's a very low-priority issue.

**Comment by jpyllman** [comment]
I understand, it is just today with all the meetings in teams/zoom/jabber/etc, it is nice to have a 'quick' way to mute. And new laptops come with functions like that. So, nice to have feature. :.-)
