### ISSUE TITLE
Caps Lock does not work for some keys

### ISSUE THREAD

**Issue by 3nigm4** [UltimateHackingKeyboard/agent#2013]
Steps to reproduce:

Activate Caps Lock: (for me) MOD + A
Type , . or - they will not be translated to ; : or _ which is what I would expect.

Firmware: 9.2.2
Agent: 2.1.2

**Comment by mondalaci** [comment]
Caps Lock is not meant to alter the mentioned symbols. It should merely translate letters to their capitalized version.

**Comment by 3nigm4** [comment]
Ah I did not know that, because the behaviour is different on [french and german keyboards](https://en.wikipedia.org/wiki/Caps_Lock). However I was wrong about the UHK behavior. The UHK does the right thing when caps lock is enabled. The - key is just not a key, that is also caps locked on german layouts. Sorry for the hastle.
