### ISSUE TITLE
Num Lock is deactivated on first windows login

### ISSUE THREAD

**Issue by provinzio** [UltimateHackingKeyboard/agent#2015]
Is it possible to add a command to `$onInit` so that the numpad is initally always active?

I realized that on the first windows login, the numpad is disabled. Therefore I have to enable the numpad before I can use the numpad numbers to type in a password with numbers.

If this does not work, I'll think about switching to "normal" numbers instead of numpad numbers.

**Comment by mondalaci** [comment]
The numpad scancode doesn't enable/disable the numpad state but toggles it. The other problem is that the `$onInit` macro gets called whenever the UHK is connected via USB and upon saving the configuration in Agent.

Correct me if I'm wrong, but given the above, I don't think the suggested solution would work for you.

**Comment by provinzio** [comment]
Fair point, I'll remove the numpad numbers from my layout and use normal numbers or perhaps alt codes.
