### ISSUE TITLE
where/how do I fix the trackpoint drift

### ISSUE THREAD

**Issue by G2G2G2G** [UltimateHackingKeyboard/agent#2016]
I found this:
https://github.com/UltimateHackingKeyboard/firmware/issues/382
which lead me to this
https://github.com/UltimateHackingKeyboard/firmware/pull/510
which reading the source code https://github.com/UltimateHackingKeyboard/firmware/commit/1bedf12c4aca70a665c3daa6579edba5219211f9 lets me see that the command is `resetTrackpoint` I guess?
and googling that command with ultimate hacking keyboard leads me to one of your many hidden mysterious pages: https://ultimatehackingkeyboard.com/repair/module-issue-solutions
and that page leads me to this page: https://ultimatehackingkeyboard.com/blog/2022/11/18/agent-2-next-level-uhk-and-module-configuration

then your smart macros... are.. just a command box so a "smart macro" just runs your script you put in it? The whole tutorial there seems to emphasize the name of the macro more than the actual command box but I assume the name is irrelevant in this case..

Ok so what do I do, write `set resetTrackpoint` in the command box? or just `resetTrackpoint` or what?

**Comment by G2G2G2G** [comment]
ok I saw this on the web page:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/50514477/4b0154a1-ae7c-4ef3-9f02-1548252316ff)

on 4k screens it is extremely tiny way over to the side of UHK program and I didn't even see it.
In there somewhere it says the command so I assume it's just `resetTrackpoint` guess I'll wait for drifting and tell.. anyway it'd be nice to have it in a dropdown somewhere
thanks

**Comment by mondalaci** [comment]
Admittedly, the current way of invoking features like this via smart macros is not very intuitive, and Agent should provide an easier way.

After implementing #1921, we'll look into the possibilities, but I believe a new tab in the key action popover would work well for this purpose. The name of the tab could be "Special", and it could be placed leftward of the "None" tab.

**Comment by G2G2G2G** [comment]
Yea I agree on the new tab, I did read through the entire list of everything on those before trying to google for it... I thought it would be there.
I remember reading those github threads like 2+ years ago so I was just waiting for them to fix my trackpoint, obviously I wasn't super eager because I am a year late to do it lol

& yea the special on the left (2nd to last) option sounds like a perfect placement. Plenty of room there to add tabs and such too.
