### ISSUE TITLE
Smart Macro (leds.Timeout) does not work

### ISSUE THREAD

**Issue by tl87** [UltimateHackingKeyboard/agent#2020]
I am runnging the lastest UHK agent 2.1.2 and have the Keyboard updated to 9.2.2.

Im following this guide, which can be found on https://ultimatehackingkeyboard.com/blog/2023/02/10/setting-led-fade-timeout and yes LED brightness is turned on.

The issue is that after waiting 10 seconds, which is the timeout set in the smart macro, nothing happens, the LEDS does not dim down and turn off.

I've tried unplugging and plugging in the keyboard multiple times, even did a few reboots, with the keyboard plugged in and without being plugged in at boot - still the same.

A screenshot of my macro:

![smartmacro](https://github.com/UltimateHackingKeyboard/agent/assets/5989314/28978c89-f5d6-4a4c-8818-980ab21b677f)

Does any one expirence the same issue or am i doing something wrong?

**Comment by kareltucek** [comment]
The parameter is minutes, not seconds.

**Comment by mondalaci** [comment]
Should we perhaps move to seconds?

**Comment by kareltucek** [comment]
I don't have a strong opinion on this. I would find seconds more intuitive, but it is not a big deal, and breaking people's setups definitely has some penalty...

**Comment by mondalaci** [comment]
I'm not keen on breaking existing setups either, but I'd still switch to seconds because sub-minute values make practical sense.

**Comment by kareltucek** [comment]
All right, feel free to make a relevant firmware ticket!

(Also, I think this one can be closed, but don't have permissions to do it.)

**Comment by mondalaci** [comment]
[Ticket](https://github.com/UltimateHackingKeyboard/firmware/issues/618) created.

Closing this issue.
