### ISSUE TITLE
Per-key-RGB refactor

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#2021]
@ert78gb, please, refactor per key RGB so that information whether RGB values are included is separate from backlight mode.

I.e., serialized config should contain two values. Corresponding C snippet is:

```
        PerKeyDataPresent = ReadBool(buffer);
        BacklightingMode = ReadUInt8(buffer);
```

Corresponding firmware BacklightingMode enum now reads:

```
    typedef enum {
        BacklightingMode_Functional,
        BacklightingMode_PerKeyRgb,
        BacklightingMode_ConstantRGB,
    } backlighting_mode_t;
```

(Constant RGB can be ignored in agent.)

This is to match https://github.com/UltimateHackingKeyboard/firmware/pull/625

**Comment by ert78gb** [comment]
> (Constant RGB can be ignored in agent.)

What does it mean exactly? The firmware will never provide this information or if firmware will provide then how should the Agent behave, like `Functional` backlighting?
