### ISSUE TITLE
Per-key coloring configuration problems.

### ISSUE THREAD

**Issue by Zot1881** [UltimateHackingKeyboard/agent#2031]
This is great new functionality but currently there are some problems:
1) if too many colors are configured there is no possibility to remove them. And also it does not correctly fit in the screen.
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/16753b80-651c-4199-a888-fd05184d0e45)
2) There is no edit button for color once it is added.
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/a88d57a9-257a-4ede-9715-d818e04197c5)
3) It would be great to have add button on color selection window instead of relying that color will be added automatically.
4) As i understand colors in 
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/5ab88f15-7e6a-41cb-8f76-c7f9d2964c75)
are not saved in config so restore config does not work for this list. So it's not possible to switch to old colors config?
5) Not able to configure "black color" to disable coloring of unused keys.
6) Color is reset after key remap.

**Comment by Zot1881** [comment]
Currently I'm stuck cause added too many colors and can't edit\remove them.

**Comment by mondalaci** [comment]
Thanks for your report!

1. We'll add a horizontal scrollbar if the colors don't fit in their own row. In the meantime, make the Agent window unmaximized and keep dragging its right or left edge until you make the window so large that the delete color icon is accessible. Use the title bar of the window to drag it after resizing it.
2. We'll make the colors editable by right-clicking them.
3. We'll add an "Add color" button to the color selection dialog. Clicking outside of the dialog will not add any color.
4. I don't think storing the palette in the UHK configuration would be right. How about being able to add key colors to the palette by dragging them to the palette?
5. I was able to add the black color to the palette, but it doesn't work consistently. We'll look into it.
6. Key colors will be preserved after key remapping.

**Comment by Zot1881** [comment]
Great, thank you.

**Comment by Zot1881** [comment]
> I don't think storing the palette in the UHK configuration would be right. How about being able to add key colors to the palette by dragging them to the palette?

Can palette be populated with colors from configuration? In this scenario during config restore valid palette will be rebuilt. At least for now i don't see reason in palette colors that are not in config and vice versa.

**Comment by Zot1881** [comment]
Also one thing related to per-key color. For some reason in this mode keyboards is drawn in white which looks not the best.
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/be17d697-4525-4c84-965d-bebdeca47fe7)
Can it be drawn with default color or at least something close to it?

**Comment by mondalaci** [comment]
We can store the palette in the UHK config, but I'm unsure if most users would prefer this behavior. I'd rather wait to see more opinions on this.

In dark mode, the white color of the keyboard case hurts the eyes, indeed. Maybe we should render the case with the same color as in functional backlighting mode. I'd love to see the opinions of other users about this, too.

**Comment by Zot1881** [comment]
> We can store the palette in the UHK config, but I'm unsure if most users would prefer this behavior. I'd rather wait to see more opinions on this.

Mostly agree cause palette is virtual and does not have hard connection to configured keys color. But what about populating palette colors from config itself? Normally palette from config must be same as palette in agent. Only during restore config they potentially may differ.

**Comment by mondalaci** [comment]
> > We can store the palette in the UHK config, but I'm unsure if most users would prefer this behavior. I'd rather wait to see more opinions on this.
> 
> Mostly agree cause palette is virtual and does not have hard connection to configured keys color. 

My exact thoughts and perfectly articulated.

> But what about populating palette colors from config itself? Normally palette from config must be same as palette in agent. Only during restore config they potentially may differ.

This feature makes sense, and we can make it happen, although the palette can get very large if there are many colors used across layers/keymaps. But this is a problem for the user who created the config, and we should probably not worry about it.

**Comment by Zot1881** [comment]
> > But what about populating palette colors from config itself? Normally palette from config must be same as palette in agent. Only during restore config they potentially may differ.
> 
> This feature makes sense, and we can make it happen, although the palette can get very large if there are many colors used across layers/keymaps. But this is a problem for the user who created the config, and we should probably not worry about it.

Fully agree. And in current and proposed variants problem of big palette will be really the same, so no change from this perspective.

**Comment by mondalaci** [comment]
We've implemented the above points, which'll be included in the next Agent release.
