### ISSUE TITLE
Backlighting switches itself off after a couple of seconds

### ISSUE THREAD

**Issue by on3iro** [UltimateHackingKeyboard/agent#2032]
I just updated to the newest agent version and firmware.

Greate stuff so far. However I played around a bit with per-key rgb and somehow my rgb's turn off every couple of seconds. I then have to press a button on the right half of the keyboard to turn them on again.
I switched back to functional backlighting, but the issue persists.

My LED-timeout inside the settings is set to 0.
I also have an `$onInit`-macro with the following contents (which worked fine up to now)

```
set macroEngine.extendedCommands 1
set leds.fadeTimeout 10
```

(Do I still need this macro or is this effectively the same option I can configure inside the LED-Settings?)

**Comment by on3iro** [comment]
I removed the `onInit`-part and it seems to work now - I'll keep an eye on it and report back :)

**Comment by mondalaci** [comment]
That must have been a problem. Closing the issue, but feel free to follow up.
