### ISSUE TITLE
Bug: Navigation mode cannot be changed for modifier layers (shift, ctrl, super)

### ISSUE THREAD

**Issue by provinzio** [UltimateHackingKeyboard/agent#2033]
I upaded to the latest release.

My previously fine working `$onInit` results now in an error.

It looks changing the navigationMode on `shift`, `ctrl`, `super` result in an error, even though the setting is adjusted and e.g. the key cluster is a cursor in the shift layer.
Please see the three lines below which throw errors in my `$onInit` macro.

```
$set module.keycluster.navigationMode.mod cursor
$set module.keycluster.navigationMode.fn scroll
$set module.keycluster.navigationMode.mouse scroll
$set module.keycluster.navigationMode.fn2 scroll
$set module.keycluster.navigationMode.fn3 scroll
$set module.keycluster.navigationMode.fn4 scroll
$set module.keycluster.navigationMode.fn5 scroll
$set module.keycluster.navigationMode.shift cursor # ERROR $onInitÖ 0Ö 0Ö Navigation mode cannot be changed for modifier lazers!
$set module.keycluster.navigationMode.ctrl scroll # ERROR $onInitÖ 0Ö 1Ö Navigation mode cannot be changed for modifier lazers!
$set module.keycluster.navigationMode.super scroll # ERROR $onInitÖ 0Ö 2Ö Navigation mode cannot be changed for modifier lazers!
$set module.keycluster.swapAxes 1

$set module.trackpoint.navigationMode.mod scroll
$set module.trackpoint.navigationMode.fn cursor
$set module.trackpoint.navigationMode.mouse cursor
```

**Comment by kareltucek** [comment]
Yes, that's intentional. See https://github.com/UltimateHackingKeyboard/firmware/issues/586 for more details.

**Comment by provinzio** [comment]
I tried to understand the "intention" behind it by reading though the linked issues, but I can't...

I tested (on the latest version) that I am unable to use scrolling with the trackpoint on shift. I get an error for that, ok...

But why do I get an error for changing the keycluster navigationMode setting on shift? I do not have any problems using the keycluster as whatever I want on shift. The error I get is meaningless in my case. Do I have some kind of edgecase or where does the error come from?

Btw the smart macro reference still allows me to change the navigationMode for the trackpoint in e.g. shift. As the trackpoint cannot be updates for shift, ctrl, super it should be hidden from the smart macro reference.

**Comment by provinzio** [comment]
Me again, I realized, that my keycluster shift navigationMode is fixed to cursor mode for some reason and the firmware forbids me to change this back.

So I still have my old settings in the keycluster saved(?). Even restarting the keyboard does not reset the keycluster navigationMode setting for shift and i am not able to change it via macros because its denying that.

I removed the `set module.keycluster.navigationMode.shift cursor` from my config for now, to avoid the error (as this line of code does nothing after the firmware change).

I am currently fine with using shift cursor on it, so I don't want to reset it right now; but just in case. How could I change it back to "normal"? Do I have to install an older firmware to change the config or is there any other way?

**Comment by provinzio** [comment]
Sorry, that I write alot.. I am still trying to understand the core issue.

I think that I am not really effected by the stated problems in the other issue, because I use `$holdLayer shift` to change to modifier layers. This seems to be not acting like a real shift click, therefore I have no problems using whatever navigationMode I want.

The composing antipattern seems to only appear, when the real modifier button is clicked.

Therefore the restriction implemented by the last firmware is kind of a step back for me. Could their be any good trade off so I can still adjust the navigationModes of my modifier layers without staying on an old firmware version?

**Comment by kareltucek** [comment]
Well, the point is that no one can agree on whether by definition the modifier should or should not apply when navigationMode is changed in modifier layer, so it was decided that such a niche usecase will not be supported.

> I am currently fine with using shift cursor on it, so I don't want to reset it right now; but just in case. How could I change it back to "normal"? Do I have to install an older firmware to change the config or is there any other way?

Actually, this is a bug. -> https://github.com/UltimateHackingKeyboard/firmware/pull/636

> BTW The Smart macro reference still offers to change the navigationModes for Keycluster/Trackpoint on the modifier layers. This should be removed, as the settings throw errors. (which as stated above I do not recommend, as I don't think that this limitation is meaningful)

This is also a bug. -> https://github.com/UltimateHackingKeyboard/agent/issues/2034

Furthermore, they are listed in the reference-manual.md. Originally that was intentional, because I did not want to hinder the readability of the grammar, but I see it is likely to generate more misunderstandings in future, so I will fix it shortly too.

> Therefore the restriction implemented by the last firmware is kind of a step back for me. Could their be any good trade off so I can still adjust the navigationModes of my modifier layers without staying on an old firmware version?

- Rethink your workflow so that you don't need to configure them.
- Feel free to build custom firmware. (Searching codebase for the error text and disabling that check should be easy enough edit.)
- Or try to persuade me and Laszlo that it is a reasonable usecase and figure out a way to get rid of the confusion of whether such a setting should or should not apply the modifier of the layer. 
- Do some hacking. E.g., you could hook the `$onLayerChange shift` macro event and and change the base layer navigation mode from there, as base layer navigation mode should be used in modifier layers

> [1] my usecase for using $holdLayer shift is, so that I can setup my UHK so that clicking both shifts activates capslock. 
 
You can also do that using smart macros. E.g., with `ifGesture` in https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md . Or with some simple register signaling.

For instance on the left shift:
```
pressKey iLS
ifGesture 27 tapKey capsLock
```
on the right shift:

```
pressKey iRS
ifGesture 85 tapKey capsLock
```

**Comment by provinzio** [comment]
> Well, the point is that no one can agree on whether by definition the modifier should or should not apply when navigationMode is changed in modifier layer, so it was decided that such a niche usecase will not be supported.

As I am using the holdLayer macro to change to the shift layer, I would say that it should not compose. And it does not. 
How does the UHK handle the "normal" Shift key? Are every button clicks automatically composed with shift? If yes, I would argue that also the navigationMode should compose by default as ever other thing gets composed too. Other keys might have the option to change the composition (?), But the nacigationModes currently do not offer that functionality. I would argue in that case, that this is a feature request and not a bug. Therefore wouldn't restrict it. 

It might be an option to add more navigationModes for the said feature request of having navigationModes which do not compose with the modifier layer. Besides the scroll and cursor, something like scrollUncomposed could be added . 

Even when I think that more people would like to be able to change a Ctrl+cursor to just a scroll and
not everyone might require the current composing functionality, I think it's a bummer to deny such an option and even more restrict the people which want the functionality or come along good enough with the bug as there is currently no other option to change the navigationMode on the modifier layer.

**Comment by kareltucek** [comment]
> as there is currently no other option to change the navigationMode on the modifier layer.

> - Do some hacking. E.g., you could hook the $onLayerChange shift macro event and and change the base layer navigation mode from there, as base layer navigation mode is (will be after above bug is fixed) used in shift layers

**Comment by provinzio** [comment]
> > as there is currently no other option to change the navigationMode on the modifier layer.
> 
> > * Do some hacking. E.g., you could hook the $onLayerChange shift macro event and and change the base layer navigation mode from there, as base layer navigation mode is (will be after above bug is fixed) used in shift layers
> 
> (Untrue, unless I have missed something.)

Mhh ok, I might have thought of this wrong. I'll dig deeper into your referenced macro commands when I am back at my UHK
