### ISSUE TITLE
Smart macro reference allows to change modifier modes

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#2034]
![2023-07-13-223517_1382x1639_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/b5d0ffc2-f3ca-4ddc-8f7b-549e777f4d17)

Changing modifier layer navigation modes was prohibited in the last firmware update, but they are still listed in Agent's smart macro reference.

**Comment by mondalaci** [comment]
Done by 9767d77fe9af8be6cbc6c33d8ad2186ddd0a888a
