### ISSUE TITLE
I can't start User Agent on my Mac book pro

### ISSUE THREAD

**Issue by takaotsu811** [UltimateHackingKeyboard/agent#2039]
Hi UHK support,

As I said earlier I have a problem with user Agent on my mac book pro .(13inch,2017)
The OS is Ventura13.4.1, and I have the App version3.0.
If you look at the top left of screenshot, it seems like working but the interface won't come up.

![スクリーンショット 2023-07-14 11 14 37](https://github.com/UltimateHackingKeyboard/agent/assets/139594679/3cbb854a-d736-4ca7-bb7e-341deb666cb3)

**Comment by mondalaci** [comment]
@ert78gb Please look into this.

**Comment by ert78gb** [comment]
I use the same OS version and it works for me.
@takaotsu811 please run `/Applications/UHK\ Agent.app/Contents/MacOS/UHK\ Agent > agent-log.txt` in command line and attach or send to me the `agent-log.txt` file. thx

**Comment by takaotsu811** [comment]
Thank you for quick response.
Here's what I got from may command.

MacBook-Pro:~ ◆◆my ID◆◆$ /Applications/UHK\ Agent.app/Contents/MacOS/UHK\ Agent
21:43:03.588 › [Electron Main] command line arguments {}
21:43:03.593 › [Electron Main] init services.
21:43:03.593 › [Electron Main] packagesDir: /Applications/UHK Agent.app/Contents/Resources
MacBook-Pro:~ takamichi811$ agent-log.txt
-bash: agent-log.txt: command not found

**Comment by ert78gb** [comment]
Looks like the `>` character was not copied to the terminal and the `/Applications/UHK\ Agent.app/Contents/MacOS/UHK\ Agent > agent-log.txt` command executed as 2 separate instructions.

Based on the terminal logs Agent already runs in the background. Please
- open the Activity monitor. Just press `command + space` and type `Activity Monitor`
- type the `uhk` into search input control of the `Activity Monitor`
- you will see multiple Agent related processes. 
- Please select `UHK Agent` and click on the `Stop` icon in the toolbar of the `Activity Monitor`
- Select the Quit option in the dialog window. If it does not terminate the Agent processes then click again on the `Stop` icon and select the `Force quit` command.
- If you don't see the `UHK Agent` process, just terminate`UHK Agent helper ...`
- start the Agent

Maybe more simple and faster just to restart the mac.

**Comment by takaotsu811** [comment]
I tried the process for few times,  but it didn't work.
The situation is still the same.
I was able to use UHK Agent at my wife's Macbook so I'm not in that much trouble any more, but I'd be happy to find another solution.

**Comment by ert78gb** [comment]
Agent stores the configs in the ` ~/Library/Application Support/uhk-agent` folder. Maybe worth to delete it and reinstall Agent.

**Comment by takaotsu811** [comment]
I just deleted all data of UHK Agent and reinstalled the app, but same thing happened. I can use the app at my wife's mac and I'm fine with this.
Thank you for your support, please close this issue.

**Comment by mondalaci** [comment]
Thanks for your kind words and support!

I'm closing this issue, but feel free to get back to us at any time.
