### ISSUE TITLE
AltGr vs. Alt+Ctrl - make clearer in Agent

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/agent#2044]
On Windows some programs do not recognize Alt+Ctrl instead of the "true" AltGr-key. Example: with the US international keyboard layout active, Outlook does not output the letter ß when a UHK key is assigned to Alt+Ctrl+s.

That is important to take care of in Agent. One should assign only RAlt (without Ctrl) to achieve the AltGr-function. To make that clear I suggest to change the name from RAlt to RAlt(Gr) and possibly add a note in the relevant tooltip.

Suggestion:
> RAlt acts as AltGr for all language layouts which make use of AltGr, such as for example German or US international.

**Comment by mondalaci** [comment]
@ert78gb Let's replace the "RAlt" toggle button of the key action popover and macro editor with "RAlt(Gr)".

(We won't touch the tooltips for now because it'd likely get ignored by users anyway.)

**Comment by rpnfan** [comment]
Great, that will be helpful for some! :-)
