### ISSUE TITLE
Macro tab select not working properly

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#205]
1. Given the inital config.
2. Add new macro with name "aaa".
3. Try to assign the macro to any key. On the macro-tab when you select the first macro (aaa) it will select the last and vica versa.

**Comment by mondalaci** [comment]
Let me correct your phrasing (in case Nejc fixes this) because it wasn't apparent to me.

3. Try to assign the macro to any key. On the macro-tab when you select the first macro (aaa) it will **display the macro actions of** the last and vica versa.

**Comment by fjozsef** [comment]
It <b>selects</b> the last. I checked the value is coming from the `Select2Component`. It doesn't matter you've clicked on the first, the last will be selected.

Selection includes the displaying of the macro actions, but @mondalaci there is no problem with the displaying, that's why is used the word <i>select</i>.

**Comment by mondalaci** [comment]
@fjozsef You're right, I stand corrected :)
