### ISSUE TITLE
Increase select2 heights

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#2056]
Increase the secondary role select2 height so that its items fit in it without scrolling.

Increase the height of the keymap and macro select2 heights as much as possible, just as for the scancode select2.

When opening the scancode select2, it momentarily opens downward, then upward. I can remember that there's a dependency issue involved. What component should we upgrade to avoid the momentary downward opening?

**Comment by ert78gb** [comment]
> When opening the scancode select2, it momentarily opens downward, then upward. I can remember that there's a dependency issue involved. What component should we upgrade to avoid the momentary downward opening?

We use the https://github.com/ng-select/ng-select component. If we would like to prevent the mentioned behaviour we have to open a feature request or PR with the expected functionality.

The PR that increase the height of the dropdowns #2237. I decreased the timeout of the dropdown rendering from 10 ms to 1 ms. maybe it make more smooth repositioning

**Comment by ert78gb** [comment]
The flashing part story #2241
