### ISSUE TITLE
Case color is not same for PerKey and Functional backlightning

### ISSUE THREAD

**Issue by Zot1881** [UltimateHackingKeyboard/agent#2059]
According to https://github.com/UltimateHackingKeyboard/agent/pull/2048 case color must be same for per key and for functional lightning. But it's not the same
per key coloring:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/becfe4d0-48f5-43c1-b283-b597ca7fbf5d)
functional:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14919498/fef61f6d-3333-4448-be5e-d769d3f15cf9)

**Comment by mondalaci** [comment]
That was the original idea, but the current behavior is intentional.

**Comment by Zot1881** [comment]
Understand. Thank you.
