### ISSUE TITLE
Multiple Modifiers with Second Role

### ISSUE THREAD

**Issue by pogopaule** [UltimateHackingKeyboard/agent#2063]
I'd like to set my hyper key (four modifier keys) to my space key as the second role

It does not seem to be possible to do that. Is that correct? If so, could this be implemented?

**Comment by kareltucek** [comment]
You can do it with macros. This should do the trick:

```
ifSecondary final holdKey LCAGS
holdKey space
```

**Comment by mondalaci** [comment]
I'm closing this issue, but feel free to follow up.
