### ISSUE TITLE
Not able to update UHK Agent

### ISSUE THREAD

**Issue by Joklisawesome** [UltimateHackingKeyboard/agent#2067]
# What do I want to do?

I want to change my keyboard configuration on my Win10 laptop.

# Error description

As soon as I connect my keyboard to my Win10 laptop the agent software tells me that I have to update before being able to use the agent.  As you can see below I get an error "ENOENT: no such file or directory, rename ...'. The problem is that I am not able to see the full path, so I did not try to actually rename something. Maybe renaming a subfolder below 'uhk-agent-updater' folder would already solve the issue but I am not sure which one. The error is cut off no matter how wide the agent window is.

![error1](https://github.com/UltimateHackingKeyboard/agent/assets/19578289/4807fb0a-d7b0-4309-9e7e-750c5e8d4f4d)

After you close the error message and wait for a while a new window pops up which shows a javascript error 'in the main process' (see image below).

![error2](https://github.com/UltimateHackingKeyboard/agent/assets/19578289/454b9fc2-670f-419c-a882-60135dc3a604)

# Background Info

I use different computers (Linux, MAC, Windows 10) and I have to switch between those devices on regular basis. Before the error occured I had been using my MAC book to change the configuration. I already did this in the past and it hadn't been a problem then but now the switch from MAC to Win10 resulted in the above mentioned error.

Any help would really be appreciated since I need to use the configuration possibility on different devices.

Kind regards,
Johannes

**Comment by mondalaci** [comment]
@ert78gb Would you look into this?

**Comment by ert78gb** [comment]
It looks like electron updater issue. The electron updater does not work perfectly on windows. I am still waiting the fix of #2008 too. 
The manual update is the workaround currently :( Download the new version and install it

**Comment by mondalaci** [comment]
Thanks!

I'm closing this issue, but feel free to follow up, @Joklisawesome.
