### ISSUE TITLE
Keymap switch animation

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#207]
Right now, when clicking on a different keymap than the current one in the side menu, some keys animate as if they're being remapped. According to Jozsi this is a side-effect of the current component. We should not do this because it's misleading.

Even though we shouldn't animate keys, we could use some animation. I'm thinking about quickly fading out the previous keyboard and fading in the new keyboard when switching to another keymap. I mean the whole keyboard including its case and keys, not the keys individually.

**Comment by mondalaci** [comment]
Continuing the discussion of #210 according to @fjozsef's suggestion.

Any way to try the parallel animation? I'd like to see it myself.

**Comment by fjozsef** [comment]
The side effect should be fixed with 5e7e0c49337c6922e5ce61cedf9fc6a87a38b2bc. 
The implementation of the parallel animation would take too much time now, the sequential is available in #210.
@mondalaci Do you want the fading animation later or can this can issue be closed?

**Comment by mondalaci** [comment]
@fjozsef There is way too much shit going on right now, and I have doubts whether the fading animation is useful, so let me close this one altogether. :)
