### ISSUE TITLE
Per layer functional backlighting setting

### ISSUE THREAD

**Issue by syl20bnr** [UltimateHackingKeyboard/agent#2074]
First of all great work on the per-key backlighting, that's awesome ! 😍 

Would it be possible to have functional backlighting to be the default and then be able to override at the layer level the mode to switch to per-key backlighting.

Use case:
- I want to keep functional backlighting per default
- I create dedicated Keymaps for professional software and games with dedicated layers, only those layers would be in per-key backlighting mode

**Comment by kareltucek** [comment]
You can use macro events for this purpose.

For instance:

Macro named `$onLayer any`:
```
set backlight.strategy functional
```
Macro named `$onKeymapLayer QWR fn2`:
```
set backlight.strategy perKeyRgb
```

For more information, see https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md and https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md

**Comment by syl20bnr** [comment]
Awesome ! Looking into it.

**Comment by syl20bnr** [comment]
Works great, I'm using:

```
$onKeymapChange <KEYMAPID>
```

To set the mode for the keymap.

Then I reassigned all the switch layer keys to use a macro instead to force the functional backlighting. For instance for `fn` layer:

```
set backlight.strategy functional
holdLayer fn
```
