### ISSUE TITLE
Error panel

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#2076]
[error state](https://github.com/UltimateHackingKeyboard/firmware/blob/66a2bef451b32d8caf4ca7ae5d3a155cf9bdcc04/right/src/usb_commands/usb_command_get_device_state.c#L38) has been added recently. If a smart macro error or warning is detected, it's nonzero, in which case, make a bottom error panel visible in Agent. The error panel must be resizable, just like the smart macro sidebar. 

Use [UsbCommand_GetVariable(UsbVariable_StatusBuffer=5)](https://github.com/UltimateHackingKeyboard/firmware/blob/master/right/src/usb_commands/usb_command_get_variable.c#L28) to fetch the status buffer.

The `UsbCommand_GetKeyboardState()` payload will be refactored, and its length will be decreased. To prepare for this change, only watch the last bit of `SetUsbTxBufferUint8(1, IsEepromBusy)` and `SetUsbTxBufferUint8(2, MERGE_SENSOR_IS_MERGED)`, not the whole bytes.

**Comment by mondalaci** [comment]
@kareltucek This issue is being implemented. The question now arises: Since the whole configuration is validated upon saving, at which point the status buffer is filled, does it make sense for the firmware to append to the status buffer upon running faulty macros? Maybe Agent shouldn't watch `UsbCommand_GetKeyboardState` for this feature and only display the status buffer upon connecting to the UHK and after saves.

**Comment by kareltucek** [comment]
Macro validation checks just basic syntax. It should catch most basic typos and other oversights, but there still are semantic errors that can arise only during runtime. 

For instance, using an undefined macro name, or jumping to a label that does not exist. 

So I think it makes sense.
