### ISSUE TITLE
Generic USB command for testing.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#2080]
I am repeatedly running into pains regarding testing of firmware USB-related PRs...

Could I have a new script in `packages/usb/test-command.ts` that would take a list of (8bit) integers, which it would simply take and just send to the keyboard, and then print a list of results on two lines - once as a list of numbers, seconds time as a string (only valid characters so that a strings in reply are not terminated prematurely due to zero bytes)?

E.g.:
```
$ ./test-command.ts 0 8 2
foo
0 102 111 111
```

Or is there another way already established for this kind of testing?

**Comment by mondalaci** [comment]
@kareltucek Totally fair request!

@ert78gb Please create this script.
