### ISSUE TITLE
UX: Drag and drop icon should be clearly separated from the rest of the row

### ISSUE THREAD

**Issue by krokofant** [UltimateHackingKeyboard/agent#2089]
![image](https://github.com/UltimateHackingKeyboard/agent/assets/5908498/4b475097-5e85-4851-8658-55e6ff3874d0)

It's not clear that the `||` icon is for dragging, and the interactable area could be increased.
The icon could be a tiny bit larger, perhaps a little less opacity and be more left-adjusted in the row.
More like this
![image](https://github.com/UltimateHackingKeyboard/agent/assets/5908498/c6f0a4f8-db30-4866-8b3f-7c536ddea585)

Perhaps this last feedback is more subjective than the rest but I find the first icon, of these below, to be more recognizable as a drag icon
![image](https://github.com/UltimateHackingKeyboard/agent/assets/5908498/be6e0b4e-0d3e-4983-830a-6cbfce8bc1dd)

**Comment by mondalaci** [comment]
Thanks for your feedback! Little details like this make a difference, and we'll implement your suggestion.
