### ISSUE TITLE
Macro Folder [feature-request]

### ISSUE THREAD

**Issue by katherinespiess** [UltimateHackingKeyboard/agent#2106]
In order to better organize large amounts of macros, it'd be desirable to be able to create colapsable 'folders' it the macro menu.

In my usecase I have a somewhat large amoutn of macros, and it can get a bit hard to find a macro if I want to edit it.
Currently, I'm prepending the macro names with identifiers so that the alphabetical sort display them grouped, but a nice feature would be to have distinct folders that I could colapse so it's more organized.

**Comment by mondalaci** [comment]
Duplicate of https://github.com/UltimateHackingKeyboard/agent/issues/1845 which we plan to implement.
