### ISSUE TITLE
Secondary role is triggered to often, when not ment to.

### ISSUE THREAD

**Issue by tl87** [UltimateHackingKeyboard/agent#2108]
Let's say that primary role for a key could be 'g' and seconday role could be 'shift-key'.

When you press they key once, it will type the letter 'g' and when you hold down they key for longer it will trigger 'shift'.

I have both the UHK60 v1 and v2,  and the problem occours for both of them, which is secondary role is triggered randomly even when tapping fast on a button, so it seems that secondary role could be triggered if a click is longer then a few miliseconds.

This could be solved by letting the user set a custom timer in seconds, which will determin when secondary role i triggered. Example would be, that the user has set a timer for 2 seconds before seconday role is triggered. Click once, and the letter 'g' is triggered, hold key for 2 seconds (or more) and 'shift-key' is triggered.

This would also be an awesome feature for accessibility.

Would that we possible?

**Comment by kareltucek** [comment]
Please see https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md and search for "secondary". 

The problem is that you are using the default resolution strategy which is not suitable to be used on alphanumeric keys...

**Comment by tl87** [comment]
Is it even possible  to use secondary role on alphanumeric keys?

My layout is as following:

![keys](https://github.com/UltimateHackingKeyboard/agent/assets/5989314/4175f879-0dd1-4501-a5c4-d7d3985bccca)

**Comment by kareltucek** [comment]
Yes, why wouldn't it be?

**Comment by tl87** [comment]
My issue is that, when I press one of the keys with a secondary role attached, it will randomly activate the secondary role, so it would be nice to be able to set a custom delay in seconds, for how long a key needs be pressed in order to activate secondary role. Would that be possible?

**Comment by kareltucek** [comment]
You mean that it will randomly activate without there being another key that activates it?

**Comment by tl87** [comment]
I'm sorry, if I'm not being very descriptive, English is not my native language and this is hard for me to explain.

I'm 100% sure that it is not a hardware issue, but let me try to explain it in more detail.

If I press a key with a secondary role and then quick another key, like you do when typing, it will sometimes activate secondary role. An example would be that I'm typing away and hit the T key, which has a secondary role to activate the mod-layer, then mod-layer will be activated and what ever key I press afterwards will be on from the mod-layer. This is very frustrating when you get randomly interupted when typing.

So a customer timer to separate primary click and when secondary role is activated, would be much appreciated :-)

**Comment by kareltucek** [comment]
Yep. Please see https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md and search for "secondary" and "advanced strategy". (It will tell you how to configure your keyboard so that it does exactly what you are asking for.)

**Comment by kareltucek** [comment]
(Still feel free to follow up with questions etc.. Laszlo has closed the issue because it does not substitute an Agent development task...)

**Comment by tl87** [comment]
Thank you for all the help.

I'm not 100% sure on how to write a macro, that will have primary role to write the letter 'f' and secondary role 'left shift key':

```js
$onInit
set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 800
set secondaryRole.advanced.timeoutAction secondary
ifPrimary write f
break
ifSecondary holdkey shift left
```

**Comment by kareltucek** [comment]
Your `$onInit` macro:

```
set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 800
set secondaryRole.advanced.timeoutAction secondary
```

Your f key macro:
```
ifPrimary final tapKey f
holdKey LS
```

**Comment by tl87** [comment]
@kareltucek IT WORKED !! THANKS :-)

LS and LC must be short for left shift and ctrl, and if i replace L with R, it will be right shift and ctrl. My question is, do you know what shortcut to use for mod and mouse key?

**Comment by kareltucek** [comment]
Mod and mouse are not "keys" in the sense of scancodes. They are layers, and as such, they need a different command, which is `holdLayer mod`. 

Still, you don't need to do that via macros. You can bind these via the key popover, and the `$onInit` config will take care of the rest.

**Comment by tl87** [comment]
Thanks 👍🏻

**Comment by tl87** [comment]
@kareltucek I'm still having a few issues, now that I have been using secondary role for a while.

There is a macro with $onInit, that looks like this:

``ìni
set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 2000
set secondaryRole.advanced.timeoutAction secondary
```

My keyboard layout looks like this:

![Keyboard](https://github.com/UltimateHackingKeyboard/agent/assets/5989314/b46da5d5-80ee-45b4-869f-22d6181f1400)

F, G, H and J have similar macros and the **tapKey** and **holdKey** is just different depending on the layout above:

``ìni
ifPrimary final tapKey j
holdKey LC
```

R and T also has similar macros, but holdLayer is different depending on key:

```ini
ifPrimary final tapKey t
holdLayer mod
```

```ini
ifPrimary final tapKey t
holdLayer mouse
```

My problem is, when I'm typing a text and click on R or T (even for a short and quick click) and then press another button right after, the input is registered as me trying to use the mod or mouse layer, even though I'm simply trying to the primary role. Is **set secondaryRole.advanced.timeout 2000** not suppose to set a timer for 2 seconds of me holding down R or T key, before mod/mouse layer is activated?

I really hope you know the answer? Maybe it's just a missing line of code in my macro or sometIng else?

All help is much appreciated :)

**Comment by kareltucek** [comment]
You have not disabled triggering by release order. That is on by default... So if you press dual role key, press another key, release that another key, (while dual role key is still held), secondary role kicks in.

For me, this weems to work just as you wish:

![2023-10-17-095107_2360x302_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/5a094622-6309-4254-bcfc-77f467b7795c)
![2023-10-17-095340_1889x895_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/15999b04-9cae-4d3e-a1e6-1829d6256157)

Another way could be increasing safetyMargin, which skews the resolution towards primary roles when increased.

**Comment by tl87** [comment]
Thanks, I will try it out :-)
