### ISSUE TITLE
Agent 3.1.0 - Per-key backlighting UI glitch

### ISSUE THREAD

**Issue by abonhote** [UltimateHackingKeyboard/agent#2109]
Reproducable, Win 7 here:

- Device > LED Settings
  - Backlighting mode: "Per-key backlighting"
- Edit Keymap
  - Add a new color `[+]`, right click it to set it
  - Double click on the color code `#000000`
 
The keyboard layout will scroll out to the right side ;-)

Easter egg? Don't think so.

**Comment by mondalaci** [comment]
Great catch! Will fix it :)
