### ISSUE TITLE
[DeviceOperation] ValidatedUserConfig from eeprom error

### ISSUE THREAD

**Issue by strowk** [UltimateHackingKeyboard/agent#2118]
Just installed latest version of agent and it had stuck at this point:
<img width="500" alt="image" src="https://github.com/UltimateHackingKeyboard/agent/assets/25692644/b5941928-fc42-4aa5-96dd-4c66444182bc">

Before that I tried to update from the agent (it asked that, saying that keyboard has too new configurations) and I had another error: 
> uhk Error: EPERM: operation not permitted, open C:\...\AppData\Local\uhk-agent-updater\pending

I am on windows 11, so agent is pretty much down here completely, no idea what to do. Before that I have updated firmware from another machine (with Ubuntu 20).

This error shortly goes away if I remove agent and install it again, but eventually appears once more.

**Comment by mondalaci** [comment]
Closing because this is likely related to #2120.
