### ISSUE TITLE
Communications error with UHK. Response code: undefined

### ISSUE THREAD

**Issue by strowk** [UltimateHackingKeyboard/agent#2119]
I receive this whenever I try to hit "Save to keyboard" button. This started to happen after I have installed Agent 3.1.0 . The firmware 10.3.0 was installed before from another Ubuntu machine. I have managed to upload configs to keyboard once with version 3.1.0 and occasionally it works, but most of the time I receive that error above.

**Comment by mondalaci** [comment]
Closing because this is likely related to #2120.
