### ISSUE TITLE
Agent 3.2.0 - Screen goes black after a few seconds

### ISSUE THREAD

**Issue by Zetaphor** [UltimateHackingKeyboard/agent#2123]
I'm running the AppImage on Fedora 39 with Wayland. When I open the Agent everything appears to load, but then after a couple seconds the entire window goes black:

![image](https://github.com/UltimateHackingKeyboard/agent/assets/3112763/e8c97a2c-a4ee-46a9-927e-0486396a33fb)

This issue does not appear with Agent 3.1.0

**Comment by Zetaphor** [comment]
https://github.com/UltimateHackingKeyboard/agent/assets/3112763/5cd35d8c-172b-4d2e-8bb9-5d3dfa9c1769

**Comment by mondalaci** [comment]
Thanks for reporting! Please also provide the Agent application log.

**Comment by Zetaphor** [comment]
> Thanks for reporting! Please also provide the Agent application log.

Where would I locate that for the AppImage?

**Comment by ert78gb** [comment]
@Zetaphor the log file  `~/.config/uhk-agent/uhk-agent.log`

**Comment by be7b5** [comment]
Also happens on Arch with X11.
[uhk-agent.log](https://github.com/UltimateHackingKeyboard/agent/files/13358371/uhk-agent.log)

**Comment by Zetaphor** [comment]
[uhk-agent.log](https://github.com/UltimateHackingKeyboard/agent/files/13358702/uhk-agent.log)

**Comment by ert78gb** [comment]
Thx for the logs. I think the https://github.com/electron/electron/issues/2357 happened. I will upgrade the electron today and build a tmp version for you.

**Comment by ert78gb** [comment]
I created a [new version](https://drive.google.com/file/d/1UTPYldpl6V_nI2mSqUOFYNWiIbAhmzjI/view?usp=sharing) with electron 27 . 
@Zetaphor @be7b5 Could you test it. If it upgrade solve the issue then we will officially release too. THX

**Comment by ert78gb** [comment]
If it does not solve the issue could you share some info about your window system.

**Comment by Zetaphor** [comment]
> I created a [new version](https://drive.google.com/file/d/1UTPYldpl6V_nI2mSqUOFYNWiIbAhmzjI/view?usp=sharing) with electron 27 . @Zetaphor @be7b5 Could you test it. If it upgrade solve the issue then we will officially release too. THX

That's fixed it for me. Thank you!

**Comment by be7b5** [comment]
> I created a [new version](https://drive.google.com/file/d/1UTPYldpl6V_nI2mSqUOFYNWiIbAhmzjI/view?usp=sharing) with electron 27 . @Zetaphor @be7b5 Could you test it. If it upgrade solve the issue then we will officially release too. THX

All good here as well. Thank you.

**Comment by mondalaci** [comment]
Thanks, guys! Looks like this has been resolved. The new Agent 3.2.1 will be released real soon, incorporating this fix.
