### ISSUE TITLE
how can i remove the uhk keyboard mapping so my default built in macbook germany keyboard is using its default layout again

### ISSUE THREAD

**Issue by mtin79** [UltimateHackingKeyboard/agent#2128]
hi uhk agents,
after i configured a keyboard mapping with uhk agent for the ultimate hacking keyboard (trying to map a german mac keyboard layout) i took my laptop on the road again. unfortunately now the built in keyboard map is mapped wrongly and i can't find any way to remove the keyboard mapping that was done by the uhk agent.
what can i do? really urgent as i can't get the "at" symbol any longer and couple of other characters ...

**Comment by kareltucek** [comment]
This is somewhat confused. 

Do I understand correctly that the problem you are having is with your built-in laptop keyboard and not with the UHK itself? Agent makes no changes to the OS layout, so you must have done them (like mapping different OS language layout), and so you should also know how to revert them?

**Comment by mtin79** [comment]
Hello,
and thanks for getting back to me!
No i didn't change anything in the mac os system.
I only used the UHK Agent and now my default keymap seems to be scrambled afterwards!
I'd be grateful for some guidance how to rever it back to how it was before!!!

**Comment by kareltucek** [comment]
> I'd be grateful for some guidance how to rever it back to how it was before!!!

I do believe that, but as far as I know, Agent really does nothing to your OS, so the best I can do is to give you some generic google results. E.g., setting input method according to this article? https://support.apple.com/guide/mac-help/write-in-another-language-on-mac-mchlp1406/mac

**Comment by mtin79** [comment]
the main keys seem to work, but keys with modifiers are scrambled.
so if i hit "alt"+"L" should create a "@" symbol. but it creates the following character "˛"
so all keys i hit with "alt" + seem not right any longer ..

i already chose the input source as it is by default:
<img width="734" alt="Screenshot 2023-11-17 at 18 58 15" src="https://github.com/UltimateHackingKeyboard/agent/assets/46390/c4ae1507-6949-4d63-a040-dd90455d33b2">

**Comment by mtin79** [comment]
hi @kareltucek and thank your for getting back to me.
i eventually saw that there were indeed different german keyboard layouts.
especially two appeared as German standard layouts.
after trying for a while i could see that while pressing the "alt" key, what they layout map was for this was:

<img width="643" alt="Screenshot 2023-11-17 at 19 41 08" src="https://github.com/UltimateHackingKeyboard/agent/assets/46390/b2447327-dba4-4dbd-b6d5-65887b6edaf9">
<img width="643" alt="Screenshot 2023-11-17 at 19 40 51" src="https://github.com/UltimateHackingKeyboard/agent/assets/46390/fe99227b-c98f-41ab-81b2-3b0e4daa5304">
