### ISSUE TITLE
Why UHK agent needs networking?

### ISSUE THREAD

**Issue by porceCodes** [UltimateHackingKeyboard/agent#2129]
This must have been there for a while.

On my macOS, System Settings -> Network -> Firewall -> Options show UHK agent receives incoming network connection from outside. Since I have never configured such a thing, I wonder if this is done automatically at the time of UHK agent installation.

Why does UHK agent need an incoming network connection?

<img width="518" alt="image" src="https://github.com/UltimateHackingKeyboard/agent/assets/1392931/ae91245a-48a0-46cd-998a-841121a285e7">

**Comment by ert78gb** [comment]
The reason is the 2nd option `Automatically allow downloaded signed software to receive incoming connections` is on. 
That means 
> Allow downloaded apps and services that are signed by a valid certificate authority to be automatically added to the list of allowed apps, without your authorisation.

source https://support.apple.com/en-gb/guide/mac-help/mh11783/mac

**Comment by ert78gb** [comment]
I mean Agent does not receive/accept any incoming request. Only outgoing connection needed for auto update, but it is optional.

Agent signed with valid Apple certificate, this is why automatically allowed to accept incoming connections.

The following image contains my settings and Agent works perfectly:
<img width="480" alt="Screenshot 2023-11-18 at 14 10 11" src="https://github.com/UltimateHackingKeyboard/agent/assets/496775/6ce22dcf-5021-4af5-be19-064e9685cdd4">

**Comment by mondalaci** [comment]
I think the provided explanation is adequate. I'm closing this issue, but feel free to follow up if you have further questions.
