### ISSUE TITLE
Transfer the actual layer, keymap, config to the UHK over USB

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#213]
Ctrl+u should make Agent transfer the binary configuration of the current layer to the UHK over USB. This calls for Electron and node-usb.

Ctrl+i should make Agent transfer the current keymap
Ctrl+o should make Agent transfer the whole configuration

No visual indication is necessary for the time being but console.logging what's being done would be useful.

@algernon is about to start with the configuration parser of the firmware soon, and this feature is very much necessary for him to rock and roll.

**Comment by mondalaci** [comment]
I'll be writing the the application logic for this feature, which is the USB transfer part.

I'd like the following to be impelemented:
* Make Agent work inside of Electron
* Include node-usb. We don't have to do this webpack. Let's just get this working first somehow.
* Make Ctrl+u invoke an empty function, which I will implement. Pass the binary serialized configuration of the current layer as a Buffer to the function.

**Comment by mondalaci** [comment]
I'm not sure whether I'll be ready with the USB transfer part by the weekend, but regardless there needs to be a way to test whether the rest is working, so I was thinking about having a function invoked by Ctrl+u that actually does something. In specific, it should:

* console.log() the content of the Buffer representing the current layer
* contain the code of `/usb/blink-test-led.js` which would toggle the test LEDs upon every invocation

**Comment by algernon** [comment]
On the other end, I can soon start working on the parser in the firmware. Initially, I can hardcode a serialized buffer, and parse that. We can test most parts this way, without having the Agent->UHK USB transfer part ready.

**Comment by mondalaci** [comment]
@algernon I can see that this would work, but testing would be so much easier if Agent was capable of sending the config to the UHK.

@NejcZdovc Reassigning this issue to @fjozsef, so that he can make the base work happen.

**Comment by mondalaci** [comment]
@fjozsef As the very first step, it'd be useful to have the Buffer of the layer console.logged. The first commit should contain just this change.

Then @algernon would copy-paste the content of the buffer and integrate it into C, and get things going. This is not efficient on the long term but a great way to test things short term, so let's proceed this way.

**Comment by fjozsef** [comment]
@mondalaci How and why do you want a binary representation console.logged?

**Comment by algernon** [comment]
A hex dump is fine. I just need some reasonably easy way to get a dump of the keymap (or layer), to start working on the parser in the firmware. Emphasis on reasonably easy :)

**Comment by fjozsef** [comment]
It would be more convenient to write a node.js application which (like the test serializer) writes the binary into a file.

**Comment by algernon** [comment]
That's also fine for me. As long as I have some blob I can drive a parser with, I'm good.

**Comment by mondalaci** [comment]
Saving the Buffer as a file with https://github.com/eligrey/FileSaver.js/ should also cut it for the first stab. I'm concerned it'll be hard to make node-usb or node work, and would like to have something useful first, and then iterate further.

**Comment by fjozsef** [comment]
Those are still overkill and I don't want to add test code to the agent, at least not on the master branch. In node.js it's like no time with few lines. Is the basic configuration okay or you want it to be modifiable via agent?

**Comment by algernon** [comment]
A static configuration is fine. If it could contain a number of different things (mouse keys, keys with modifiers held, layer switchers, etc), that would be super useful. But a simple static dump with only basic keys is good enough for a little while, too.

**Comment by fjozsef** [comment]
Please look at this 8f719b06906d987b44661aff2bdce2578ed8e8ef

**Comment by mondalaci** [comment]
@fjozsef Looks like a good first step to me. You're welcome to proceed further with USB.

**Comment by fjozsef** [comment]
@algernon Please checkout the [playground](https://github.com/UltimateHackingKeyboard/agent/commit/1eed900aa485e826534fc827e8ffe566d6ec6e5a) branch. You should see a download icon on the keymap page next to the duplicate keymap icon. Clicking on the icon you can download the selected layer in binary.

**Comment by algernon** [comment]
Thanks, this will last me a while! Much appreciated!

**Comment by mondalaci** [comment]
I have yet to write a script that will transfer the saved configuration to the UHK. I'm rather overloaded right now, but chances are I'll wrap it up this week.

**Comment by mondalaci** [comment]
Just uploaded usb/upload-config.js to the playground branch which expects the filename of the binary configuration and uploads it to the UHK. Tested it and works like a charm. Right now, the firmware expects only a single layer but the script transfers any payload to the UHK.

For the time being, the configuration only gets written to the RAM, but persisting it to the EEPROM shouldn't be a big deal, and I'll be doing it soon.

@fjozsef Now that every dependency is in place, I'd like to make this a priority. When do you expect to wrap this up?

Mad props go to @algernon for writing the configuration parser!

Everything is coming together. I'm so excited, guys!

**Comment by fjozsef** [comment]
@mondalaci According to the current milestone this is the next task. I don't know when it will be ready, but it is the next issue for me which I will work on.

**Comment by mondalaci** [comment]
@fjozsef Ok, thanks for the update.

I almost forgot that the user should be able to transfer the current layer, the current keymap, or the whole configuration. Given the upcoming developments of the firmware, all of these options will be needed. I don't really care how we expose these 3 features (via shortcuts, or dedicated buttons, etc) but they should be available.

**Comment by fjozsef** [comment]
@mondalaci According to the description of this issue, sending of the current layer will be accessible with ctrl + u. For the other use cases please create different issue or modify this one. 
However, this issue is under implementation right now, so changes in the description is avoidable, but if needed, then I will do the changes in the code accordingly.

**Comment by mondalaci** [comment]
@fjozsef Just updated the description to include the suggested shortcuts. Thank you!
