### ISSUE TITLE
Cosmetics: text foreground in Firmware section

### ISSUE THREAD

**Issue by dxps** [UltimateHackingKeyboard/agent#2149]
Hi UHK team,

Here is a small - cosmetics related - issue:
- using Agent version 3.2.2
- in the Firmware section these entries needs a brighter text when using Dark theme
- OS: Pop!_OS Linux 21.04 w/ Gnome DE

![image](https://github.com/UltimateHackingKeyboard/agent/assets/14140226/4dd1f527-e86b-420a-b9d2-1961a094fe7e)

<br/>

Most probably that color is static, since it looks the same when using the Light theme:

![image](https://github.com/UltimateHackingKeyboard/agent/assets/14140226/09af3125-ed9e-4120-820f-06117e7a3552)

**Comment by mondalaci** [comment]
Thanks for your report! We'll fix it.
