### ISSUE TITLE
Cosmetics: custom color text foreground when choosing a custom color

### ISSUE THREAD

**Issue by dxps** [UltimateHackingKeyboard/agent#2150]
Hi UHK team,

Here is a small - cosmetics related - issue:
- using Agent ver. 3.2.2
- the text foreground when choosing a custom color needs to be lighter when using Dark theme
- OS: Pop!_OS Linux, ver. 21.04 w/ Gnome DE

![image](https://github.com/UltimateHackingKeyboard/agent/assets/14140226/f4fb5e25-c1dd-4489-97f4-291a51182379)

**Comment by mondalaci** [comment]
Thanks for your report! We'll fix it.
