### ISSUE TITLE
Agent 3.2.2 does not detect UHK 60 v2

### ISSUE THREAD

**Issue by dharkness** [UltimateHackingKeyboard/agent#2152]
I received a new UHK to replace my version from the initial Kickstarter run this week. It was detected by Agent 3.2.1, but after upgrading to 3.2.2, it was no longer detected. I downgraded to 3.2.1, and it was detected again. I flashed the latest firmware in 3.2.1 and upgraded again. Again, it would not detect the device. I downgraded one last time, and it was once again detected.

See [this thread](https://forum.ultimatehackingkeyboard.com/t/cannot-detect-new-v6-uhk-after-agent-upgrade/733/5) for more background and the complete steps I followed.

**Comment by mondalaci** [comment]
@ert78gb Can you look into this?

**Comment by ert78gb** [comment]
Hi @dharkness,

From `3.2.1` to `3.2.2` we upgraded the hid-raw library that responsible for the USB communication. Can you send me the Agent logs? You can find them in

- on Linux: `~/.config/uhk-agent/uhk-agent.log`
- on macOS: `~/Library/Logs/uhk-agent/uhk-agent.log`
- on Windows: `%USERPROFILE%\AppData\Roaming\uhk-agent/uhk-agent.log`

**Comment by dharkness** [comment]
I'm on Ubuntu 20.04. Here's the log file in `/home/david/.config/uhk-agent/logs`:

[uhk-agent.log](https://github.com/UltimateHackingKeyboard/agent/files/13852892/uhk-agent.log)

**Comment by ert78gb** [comment]
The error is "version `GLIBC_2.33' not found". What is your operation system?

Our users experience GLIBC issue when they use older OS.

**Comment by ert78gb** [comment]
Sorry I just know read you use Ubuntu 20.04.

**Comment by ert78gb** [comment]
I opened a PR that uses Ubuntu 20.04 as build runner.
@dharkness please download and test the Appimage artifact from the https://github.com/UltimateHackingKeyboard/agent/actions/runs/7438188763?pr=2157. If it solves your problem we will merge the PR and release a new version.

**Comment by dharkness** [comment]
I get the same error. Looks like my system has Glibc v2.31.

```
/lib/x86_64-linux-gnu/libc.so.6 -> libc-2.31.so
```

Is that determine by the linux kernel or Ubuntu? I ask because I had to downgrade my kernel because the newer version failed to boot. I'm not against upgrading to 22.04--just have been putting it off with no immediate need to do so. Can the agent work with Glibc 2.31?

**Comment by ert78gb** [comment]
As far as I know the OS determine the GLIBC. Possible to use different GLIBC than the OS provides but not recommended. So if you need newer GLIBC recommended to upgrade the OS.

I have to investigate what happened with `node-hib`. They use new build process to compile the library. I have to investigate why it is needed newer glibc. I will collect and share this information within the next few days.

**Comment by in-sachen-it** [comment]
Same on Debian 11/bullseye which is supported until August and by that, not that old.

**Comment by ert78gb** [comment]
@in-sachen-it @dharkness  I upgraded the `node-hid` package. Could you test the new [version](https://github.com/UltimateHackingKeyboard/agent/actions/runs/7519543868?pr=2162)? Thx

**Comment by ert78gb** [comment]
I modified the build. If you have time please test the https://github.com/UltimateHackingKeyboard/agent/actions/runs/7533700761?pr=2162

**Comment by dharkness** [comment]
@ert78gb The most recent build works, thanks!

**Comment by mw75** [comment]
Can’t test because the linked artifact is not available anymore. The version on https://ultimatehackingkeyboard.com/agent is still not fixed.
