### ISSUE TITLE
Enable layer-switching action to base layer from other layers

### ISSUE THREAD

**Issue by da11an** [UltimateHackingKeyboard/agent#2164]
I'd like to see a layer-switching action (available from **_non-base layers_**) that returns the keyboard to the base layer. This would be useful when you're possibly toggled to another layer (but you don't remember for sure) and want to get back to the base layer without first looking down to check.

I'd assign this layer action to a key on the alternate layer that was fairly benign on the base layer, like `shift`, `ctrl`, or `escape`. Then, with a single press of `right-shift` (for example), you'd know you're on the base layer. And if you already had been on the base layer, no harm done.

See related [Escape to base layer request](https://github.com/UltimateHackingKeyboard/agent/issues/1043).

**Comment by kareltucek** [comment]
This is now possible via smart macros. See https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md for more details.

**Comment by da11an** [comment]
Awesome, this did it:

![image](https://github.com/UltimateHackingKeyboard/agent/assets/49221299/9fea301d-e1d3-47cf-ab0e-3bb9f653afe8)
