### ISSUE TITLE
Recover LED space tooltip blocks warning popup

### ISSUE THREAD

**Issue by Siebjee** [UltimateHackingKeyboard/agent#2173]
On the 3.3.0 agent, I noticed the "Recover LED space" tooltip (on hover) is blocking the popup when you click the button. You have to press `ESC` to see the warning popup, see attached screenshots.
<img width="858" alt="Screenshot 2024-02-09 at 09 50 30" src="https://github.com/UltimateHackingKeyboard/agent/assets/7149591/04089908-06db-4038-a587-4f235e1c0e43">
<img width="850" alt="Screenshot 2024-02-09 at 09 50 42" src="https://github.com/UltimateHackingKeyboard/agent/assets/7149591/2c704abc-23e3-427c-971a-29daba5c9d02">

**Comment by mondalaci** [comment]
Thanks for the report! We'll make the tooltip always oriented upward.
