### ISSUE TITLE
Add F13-F24 to the list of scancodes

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#218]
Just got an inquiry whether the UHK supports extended function keys, so there's a demand for them, and given how easy they're to add to the scancode list of the key action popover, let's do it.

See page 56 of [The USB HID Usage Table](http://www.usb.org/developers/hidpage/Hut1_12v2.pdf) for the relevant scancode values.

**Comment by noutritenou** [comment]
Please also add scan code for the Menu key aka application key present on standard keyboards
https://en.wikipedia.org/wiki/Menu_key
https://en.wikipedia.org/wiki/QWERTY#United_States
In the USB HID Usage Table it is called Keyboard Application and has Usage Id 65 hex.

**Comment by fjozsef** [comment]
Menu key should work (see Qwerty keymap, mod layer), however it seems it is not selectable on the keypress tab, i've created #221 for solving that.
