### ISSUE TITLE
Free storage saveState relying on environments config

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#219]
Currently our storage reloads (JSON parsing, model building, etc) the UhkConfiguration when we save the state.
The problems with this approach;

- Performance issues, parsing should be done ideally only once
- LocalStorage could be deleted since the app start, so there will be no config to use
- Blocks #212. More detail there.

The application state should store the whole config, which should be used in the serialization.

**Comment by NejcZdovc** [comment]
With parsing you mean what exactly? I am not sure that I understand this problem, so can you please explain how would you like to solve this problem?

**Comment by fjozsef** [comment]
We should load the whole config not only the keymaps and macros when we are createing the initital state. So when we want to save the config, then we will not have to read it again and update those fields.
