### ISSUE TITLE
Put layer switcher action into the tab bar

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#22]
Currently the layer switcher action is under the Keypress tab. This has to be put on it's separate tab as it will have more functionality.

The changes for the new functionality are the followings:
1. The "None" action will disappear as it have its own tab
2. Other then the currently remaining options a new option will appear as a bootstrap-checkbox saying "Toggle layer". It also would have an information bubble with some further explanation.

**Comment by mondalaci** [comment]
Could you proceed with this one, @csanyiarpad? Jozsi is about to start to put application logic behind the key action editor, and he's blocked by this issue.
