### ISSUE TITLE
Allow diagonal mouse movement and scrolling

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#220]
To my surprise, [there is need](https://github.com/UltimateHackingKeyboard/firmware/pull/24#discussion_r92458825) for diagonal mouse movement and scrolling, so let's make them happen.

It'd be worth to tweak the binary representation of `MouseActionParam` as follows:
* Let's split the `MouseActionParam` to 2 nibbles (4-bit groups)
* The first nibble would represent the major mouse action, that is move, scroll, click, or speed.
* The second nibble would represent the minor mouse action which is dependent on the major mouse action as seen under the Mouse tab of the key action popover.
* Regarding the value of the minor mouse action, for move and scroll actions it'd be worth to represent them as bitfields. For example 0b0001 upwards, 0b0010 rightwards, 0b0100 downwards, and 0b1000 leftwards. This way the implementation of the firmware would be easier, and on the TypeScript level this only involves assigning specific values to enums.

**Comment by mondalaci** [comment]
I'm rather closing this for the time being, and possibly resurrect it when a couple of users confirmed that there's a significant need regarding this feature. I'd like us to focus on more pressing issues.

**Comment by NickDaly** [comment]
I've subscribed to this issue, in case you ever come back to it.  Diagonal scrolling keys would work much better with my own conception of keyboard-mouse movement, trained over many hours of vi.

**Comment by mondalaci** [comment]
@NickDaly I'm sorry, but this is not planned anymore.
