### ISSUE TITLE
Latest agent not working

### ISSUE THREAD

**Issue by Vistaus** [UltimateHackingKeyboard/agent#2203]
I opened UHK Agent 3.3.0 and it updated itself to 4.0.1, but now it's not working anymore.

```
╭─vistaus@localhost /home/vistaus/Apps  ‹system›
╰─$ ./UHK.Agent-4.0.1-linux-x86_64.AppImage                                                                             ↵ 127
Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
open dir error: No such file or directory
╭─vistaus@localhost /home/vistaus/Apps  ‹system›
╰─$   
```

**Comment by mondalaci** [comment]
Does [Agent 4.0.0](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v4.0.0) work for you?

**Comment by Vistaus** [comment]
That was fast! :D 

Yes, 4.0.0 seems to launch just fine.

Sorry btw, I forgot to give a brief overview of my system.

OS: openSUSE Tumbleweed
DE: KDE 5.27.10

**Comment by Vistaus** [comment]
Hmm, I downloaded 4.0.1 manually and now it does launch fine. So it seems to be a bug in the updater.

**Comment by mondalaci** [comment]
Thanks! This seems like a one-off, so I'm closing this issue. Will reopen if it reoccurs for someone.
