### ISSUE TITLE
Left Keyboard Half Cannot Unbrick

### ISSUE THREAD

**Issue by maxywb** [UltimateHackingKeyboard/agent#2204]
I was updating my firmware from 8.2 to 11.0.0 and the left keyboard half bricked. I followed the unbrick instructions to unplug/replug that half during firmware flashing and that did not work. I have attached the logs from the agent as instructed.

[uhk_log.txt](https://github.com/UltimateHackingKeyboard/agent/files/14484994/uhk_log.txt)

**Comment by mondalaci** [comment]
Please follow [these instructions](https://ultimatehackingkeyboard.com/knowledgebase?q=unbrick).

If they don't work, please [contact us here](https://ultimatehackingkeyboard.com/contact-us).
