### ISSUE TITLE
Tooltip amends: module configuration

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#2213]
Please change the Keystroke delay tooltip as follows:

> Keystroke delay defines minimum delay between two consecutive usb reports, thus slowing down keyboard output in case of fast bursts (e.g., from the macro engine).
> 
> This improves compatibility as many programs (especially RDP clients) have problems accepting too fast input. On the flip side, this limits caret navigation mode sensitivity and introduces (possibly undesired) delays.

**Comment by mondalaci** [comment]
Already done and part of the new release.

https://github.com/UltimateHackingKeyboard/agent/commit/dd5c2226e43f71063a2ec167413f368ec047841c
