### ISSUE TITLE
Mouse speed diagram

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#2214]
May I ask Róbert, was there any problem with fitting the https://raw.githubusercontent.com/UltimateHackingKeyboard/firmware/master/doc-dev/resources/mouse_speeds.svg diagram into the speed section tooltip(s)? 

If there is no problem with it, it would be really nice to include it.

**Comment by ert78gb** [comment]
I don't have any problem with the diagram. @mondalaci removed it in 8add146 commit.

**Comment by kareltucek** [comment]
Well, maybe because of this?

![2024-03-22-103337_3840x2160_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/c0d5a2f2-1517-4728-90ed-4144a3f4780f)

If I remember correctly, the image did not work before laszlo removed it, just as it does not work when I simply add it. 

(I have added back the `<img src="/assets/images/acceleration-graph.svg" alt="acceleration graph">` and copied the graph to `agent/packages/uhk-web/src/assets/images/acceleration-graph.svg`.)

**Comment by kareltucek** [comment]
Actually, it works in web agent, but does not work in electron.

**Comment by kareltucek** [comment]
Found a fix, will post a PR shortly.
