### ISSUE TITLE
Agent ver 4.0.2 - Low contrast on keys borders

### ISSUE THREAD

**Issue by dxps** [UltimateHackingKeyboard/agent#2216]
Dear UHK team & community,

With the latest version - `4.0.2` at the time of this writing - of the Agent, the layout misses some contrast on keys borders.

In Agent ver `4.0.0` it looked like this:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14140226/ec118400-eb56-41f2-b24f-ae1706ab6547)

And now, in Agent ver `4.0.2` it looks like this:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/14140226/56ef5fe9-897b-4c71-ae0e-01ca9adff9b2)

I'm using:
- Pop!_OS 22.04 LTS (up-to-date)
- GNOME Desktop 42.9

Thanks!

**Comment by mondalaci** [comment]
Hi there!

If you use functional backlighting instead of per-key backlighting, Agent 4 will render your UHK just as it's rendered by Agent 3, according to your last screenshot.

When per-key backlighting is enabled, you're right that the keys should have a visible border, as featured in your first screenshot. We'll fix this issue.

**Comment by dxps** [comment]
Hi László!

Understood.
I am using `Per-key backlighting` option.
Even with this, I still believe that a darker color for the case is better than white, imho.

As always, thanks for the quick feedback!
And thanks for the satisfaction of owning and using 3 UHK toys. :blush:

**Comment by mondalaci** [comment]
Thanks for your huge support, Marius!

The ideal case color is not obvious when per-key backlighting is enabled. A very dim case color doesn't match well if all your keys are bright. Originally, the case color was chosen based on the average of the key colors, but it didn't look good. There's no perfect solution, and I think the current color choice is reasonable for most.

**Comment by dxps** [comment]
I know this is a pure cosmetics topic and I don't want to insist on it.
To me, as a user, I would prefer to choose that case color as well.
And I would immediately choose that dark brown that looks good on black.

**Comment by mondalaci** [comment]
Got it, and I appreciate your suggestion. If there's a larger demand, we can implement such a feature.

**Comment by kareltucek** [comment]
(I can also sign that I find the current case color unsatisfactory. I have no specific ideas on improvement though.)
