### ISSUE TITLE
Pinch to zoom on trackpad - weird key codes (Win)

### ISSUE THREAD

**Issue by abonhote** [UltimateHackingKeyboard/agent#2218]
Agent 4.0.2, Windows 10 here, Swiss German keyboard layout. As the trackpad pinch to zoom didn't really work, I played around with the settings. Now it's set to PC mode. When I try to zoom out right here inside the github form, I get some backticks (````). Zooming out results gives me single quotes (''''). [JavaScript says](https://www.toptal.com/developers/keycode) says 221 and 219, if that helps.

Couldn't we rather have somtething similar to the keyboard assignment dialog for these gestures?

![image](https://github.com/UltimateHackingKeyboard/agent/assets/264473/66ed4143-69a8-40e5-9403-e594658aea24)

Cheers

André

**Comment by kareltucek** [comment]
Well, the zoom mode only produces Ctrl+- / Ctrl+= scancodes (not characters: https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk), so you using the swiss german layout may easily be the problem.

As to remapping the zoom mode, it is possible via smart macros. Search https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md for "navigationModeAction".

**Comment by mondalaci** [comment]
Closing this as https://github.com/UltimateHackingKeyboard/firmware/issues/591 is supposed the be the solution.

Feel free to follow up regardless.
