### ISSUE TITLE
error while saving new configuration

### ISSUE THREAD

**Issue by RonaldEC** [UltimateHackingKeyboard/agent#2224]
After altering a key and trying to save to keyboard, I get error messages (see the picture, the message below was the first try). After that, the keyboard can not be used untill I disconnect en reconnect again.

It used to work perfectly, but now it does not anymore. What can i do?
![Schermafbeelding 2024-03-30 160438](https://github.com/UltimateHackingKeyboard/agent/assets/142705586/e61d1740-fade-4c01-b8db-91c4bd20d8fb)

**Comment by ert78gb** [comment]
Hi @RonaldEC ,

please attach the logs.
You can find them in
- on Linux: `~/.config/uhk-agent/uhk-agent.log`
- on macOS: `~/Library/Logs/uhk-agent/uhk-agent.log`
- on Windows: `%USERPROFILE%\AppData\Roaming\uhk-agent/uhk-agent.log`

Does the keyboard directly connected to the computer or do you use any usb hub or other devices?

**Comment by RonaldEC** [comment]
[uhk-agent.log](https://github.com/UltimateHackingKeyboard/agent/files/14848601/uhk-agent.log)

**Comment by ert78gb** [comment]
Based on the logs I don't know what is the problem. 
What is the modification that you would like to apply?

**Comment by RonaldEC** [comment]
just altering the function of a key, but the same problem arises when I want to change the speed of the trackpiont or something like that

**Comment by ert78gb** [comment]
can you share your user config? if you share please remove any sensitive information from the macros.
but before share please check the latest firmware release https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v11.0.2 maybe it fixes a bug that prevent the savings of the userconfig.

**Comment by RonaldEC** [comment]
The firmware update solved it, tnx!

**Comment by RonaldEC** [comment]
solved
