### ISSUE TITLE
Make it easy to swap keys

### ISSUE THREAD

**Issue by warsaw** [UltimateHackingKeyboard/agent#223]
The agent (the browser version) is looking awesome.  IWBNI it were easier to swap keys, maybe through a copy and paste mechanism?  E.g. If all you want to do is swap Alt and Fn, or Mouse and Ctrl, it would be great if you didn't have to go through every options, potentially missing something important.  Having an easy way to swap two keys would be a huge timesaver.

**Comment by mondalaci** [comment]
Thanks for the nice words regarding Agent!

We could optimize the UX of Agent for key swapping, but I doubt whether it's a usual use case. It's surely useful once in a while, but once you configure your keymap I doubt it is.

How often would you use key swapping and in what cases?

**Comment by warsaw** [comment]
@mondalaci I think you're right that I'd only use it a few times, especially at the beginning as I'm configuring my keyboard to my own personal choices.  Maybe it would be more common if switching desktops, e.g. from Gnome shell to Unity7, etc.

But TBH, I'm pretty sure I'd use agent to customize the keyboard a lot at the beginning and it would tail off pretty quickly (perhaps, modulo moving the keyboard to other systems or OSes).  I definitely want to be able to save configurations so e.g. if I move from Linux to OS X, I can call up a configuration for that platform.

FWIW, some OSes are easier than others to do the keyboard switching in the OS software layer, but of course it's better done in the keyboard/hardware :)

I always swap keys since I'm an old school Emacs user, so CapsLock<->Ctrl is a common one, but often I have to swap around Alt/Super and others.

Another thought that might work and not be so specialized to keyboard switching.  If I can open a window that summarizes all the settings for a key, and open multiple of those windows (e.g. I want to compare how the Alt key and J key are set at the same time), that might be enough.  Then I can do the manual swapping and be sure that I've got all the settings moved over before I close the window.

In any case, I cannot wait until I get my UHK!

**Comment by mondalaci** [comment]
@warsaw Thanks for elaborating further!

On one hand, I can see the use of opening multiple windows, but on the other hand, key actions are pretty simple in nature, so it's rather easy to remember them and change them even across layers.

Another reason I feel uneasy about this feature is that it makes the UI/UX significantly more complex from the standpoint of the user. Currently, when a key action gets edited the modal popover appears, forcing the user to interact with it and close it before doing anything else. Multiple windows would surely change this and make the interaction pattern less trivial.

Given that these are fairly rare use cases, I'd rather close this issue. Our policy is to enable users as much as possible, but also keep the UI/UX as minimalistic and simple as possible. This way, we end up with a simpler and more trivial to use application that is also easier to maintain. I hope you understand.

Lastly, thank you so much for supporting us! We're working on delivering your UHK as soon as possible.

**Comment by warsaw** [comment]
@mondalaci Thanks for the consideration!
