### ISSUE TITLE
Allow position change of Fn, Mod, Super, Alt, Ctrl

### ISSUE THREAD

**Issue by leifmadsen** [UltimateHackingKeyboard/agent#226]
Not sure if I just missed it, but it seems like you can't modify the position of the Fn, Mod, Super, Alt, and Ctrl keys?

I prefer a setup similar to my das keyboard, and would like to move the keycaps around and then adjust the  map to account for this. My preferred layout would be:

Ctrl, Fn, Super, Alt

Thanks!

**Comment by mondalaci** [comment]
Hey there, @leifmadsen!

Please take a look at [Agent](http://ultimatehackingkeyboard.github.io/agent/) and click on any key of any layer of any keymap. As you can see, it's possible to remap the UHK as you desire.

Given the above I'm closing this ticket.

**Comment by leifmadsen** [comment]
Oops! You're a 100% correct. It's a little different than what I was originally trying, but looking again, it's much more obvious. Thanks!
