### ISSUE TITLE
"back to keymap" (from module reached via puzzle piece) reverts to base layer

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#2277]
Agent 4.1.0.
Start with a UHK with at least one extra module connected.

1. look at the base keymap
2. select a different layer (e.g. mod or mouse)
3. click the puzzle icon on a module
4. click "back to ... keymap"

You end up on the base layer. Not sure if that was intended. I feel like it should actually return to the layer that was previously active.

**Comment by mondalaci** [comment]
I agree that most users expect the suggested behavior. Thanks for reporting it; we'll fix it.
