### ISSUE TITLE
FR: Make UHK Agent AppImage updateable

### ISSUE THREAD

**Issue by jay7x** [UltimateHackingKeyboard/agent#2312]
It'd be nice if UHK Agent would support the AppImageUpdate technology: https://github.com/AppImageCommunity/AppImageUpdate. That'd make Agent update process a bit easier.

P.S. Also it'd be nice to have a flatpak, but it's another story (#1374).

**Comment by mondalaci** [comment]
@ert78gb How does AppImageUpdate differ from our current update mechanism?

In any case, I'm reluctant to use it at this point:

> This is beta-level code. It works, and most features available work fine. However, in this state, there is not much real world experience with the application. Please report any issues on the bug tracker.

**Comment by ert78gb** [comment]
If I understand well the documentation there are 2 differences
- the referenced method supports differencial download, so it can save bandwith
- there is a service on the users computer that periodically  checks for update and if it available then download it in the background. Currently the user has to start the app and the app checks for update.

**Comment by ert78gb** [comment]
I think when [electron-builder](https://www.electron.build) will support this method we can consider the use of it.

**Comment by mondalaci** [comment]
I'm closing this issue because we don't use beta libraries. We'll keep checking electon-builder; if this feature is available, we'll consider using it.
