### ISSUE TITLE
Sync layers across keymaps [Feature Request]

### ISSUE THREAD

**Issue by eegil** [UltimateHackingKeyboard/agent#2313]
Curent user context:
- 4 keymaps with 3+ layers maintained. Usually only MAIN layer is different across the keymaps. 

Issue: 
- for one change on the extra layers needs to be made, then the corresponding layers from the other keymaps must also be updated in order to have usability consistency. Long time this is unsustainable. 

Proposed solution: 
Agent should provide the means to actively sync/mirror changes from one layer to its corresponding layers from the other keymaps.  
Option should allow user: 
- Select the layers to be synced. 
- Manage the direction of the sync. 

Benefits: 
- improved user experience, usability, consistency of actions, elimination of various errors, time saving. 
- improved keymap management
- eliminate the need to use external unapproved tools

**Comment by mondalaci** [comment]
For related commands, please see the "Layer/Keymap loading manipulation / shared layers" section of the [reference manual](https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md).

We won't implement the suggested feature as specified, but these commands allow you to achieve it.
