### ISSUE TITLE
Keymap reloads twice after enabling it and at random times. 

### ISSUE THREAD

**Issue by eegil** [UltimateHackingKeyboard/agent#2314]
I noticed that keymap keeps reloading after activating it or maybe power resets. 
attaching the user configuration for analysis. 
[UserConfiguration-jul-8.json](https://github.com/user-attachments/files/16123994/UserConfiguration-jul-8.json)

**Comment by mondalaci** [comment]
Please describe exactly what's happening and what your expectation is.

**Comment by eegil** [comment]
###  What is happening: 
## Current set up: 
- keymap has a set setLedTxt message to display whenever is being loaded/reloaded. This stays on $onKeymapChange xxx macro. 
- this message seems to be displayed from time to time at random intervals, indicating that $onKeymapChange xxx keeps being called, although there is absolutely no change regarding loading or reloading of the keymap. 

### Expectation
- Analyze and decide if there is a bug, the message should be displayed once.

**Comment by eegil** [comment]
actually this appears to happen more often than the display shows. Sometimes keyboard has delays making typing a bad experience.

**Comment by mondalaci** [comment]
Please take some photos of the missing screws and any physical/mechanical issues you noticed. We haven't encountered such an issue yet.

**Comment by mondalaci** [comment]
Please contact us at https://ultimatehackingkeyboard.com/contact-us as this looks like a hardware issue.

**Comment by eegil** [comment]
> Please take some photos of the missing screws and any physical/mechanical issues you noticed. We haven't encountered such an issue yet.

I was mistaken. I opened up and realized that is as per design. On other keyboards there are spacers between board and the steel plate, while here there is a spring that ensures proper tensioning distance. This was a bit confusing when removing switches, because in some cases when removing switches board has some vertical play. 

But is there something special with key corresponding to B (keyid 91)? it appears that on that area I am noticing the issue.  Il check the switch and the cables, maybe there is an issue with them.

**Comment by mondalaci** [comment]
> On other keyboards there are spacers between board and the steel plate

In my experience, this is generally not true, but some keyboards may have spacers.

> while here there is a spring that ensures proper tensioning distance.

In the UHK, one spring per half connects the PCB ground plane to the metal plate for shielding purposes. This spring has no mechanical purpose.

> This was a bit confusing when removing switches, because in some cases when removing switches board has some vertical play.

When assembled properly, the switches act as spacers, and we haven't received reports about spacing-related issues yet.

> But is there something special with key corresponding to B (keyid 91)? it appears that on that area I am noticing the issue. Il check the switch and the cables, maybe there is an issue with them.

Please swap the switch mentioned with another one. It may be broken, or its pin doesn't connect properly.

**Comment by kareltucek** [comment]
Check i2c stability. Keymap reload is needed on module reconnections.
