### ISSUE TITLE
html links in keymap description can lead Agent astray

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#2335]
Add some funky html in the keymap description:

![image](https://github.com/user-attachments/assets/f03b21f0-49a2-4594-88a7-5c3fb447269d)

See that it looks awesome:

![image](https://github.com/user-attachments/assets/7ce9355b-d407-4a64-bf9d-e121e594639a)

Click on the github link, and watch Agent turn into a new web page:

![image](https://github.com/user-attachments/assets/dffeae31-af5a-4486-9808-1e54a831e01f)

No way to get back to Agent 😏 You have to close the window and restart Agent.

You could filter out all html content, but it's kind of nice that I can do tables and bold emphasis etc...

**Comment by mhantsch** [comment]
And yes, of course I can add `target="_blank"` to the link and it will open in a new window and leave Agent intact.

**Comment by mondalaci** [comment]
Thanks for the report! From a security standpoint, I think Agent should escape all HTML.

**Comment by mhantsch** [comment]
> From a security standpoint, I think Agent should escape all HTML.

There goes my table... 😔😉

Unfortunately, I agree to the security reasoning.

**Comment by ert78gb** [comment]
The #2352 PR sanitize the full HTML content but I maybe would better UX to define which HTML elements are allowed and open URLs in the external browser. But do it in other issue if there is user need.

**Comment by mhantsch** [comment]
*snif*

![image](https://github.com/user-attachments/assets/dd9bca4d-7aa8-4dee-bd2f-1dd556b1ea69)

Can confirm this is now working as intended. Table, emphasis and links are now gone.
