### ISSUE TITLE
weird behaviour when configuring Typing behaviour -> Trigger safety margin

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#2343]
1. Start Agent.
2. Configuration -> Reset device configuration -> Yes
3. Close Agent and start fresh, so that everything starts from a clean slate.
4. Start Agent again.
5. configure Typing behavior -> Resolution strategy -> Advanced
6. go to Configuration and note that your Export and Import and Reset buttons look fine:

![image](https://github.com/user-attachments/assets/d817c6f6-0372-4316-ab97-ae9a592d652c)

7. configure Typing behavior -> Trigger safety margin -> -5 (any negative number will do)
8. go to Configuration and note that the buttons look wrong, the configuration memory bar is empty, and all the Configuration history is blank:

![image](https://github.com/user-attachments/assets/fd60ba0f-c753-4479-9d6e-73690f2ac51d)

9. configure Typing behavior -> Trigger safety margin -> 0
10. go to Configuration and note that everything looks normal again.
11. go back to Typing behaviour and note that the Trigger safety margin now shows -100 ms.
12. write a Github Issue for Agent because all of this is very weird.

In addition, sometimes changing values in the Typing behaviour section do not pop up the "Save to keyboard" button

Agent version: 4.2.0
Firmware version: 11.1.1

**Comment by mondalaci** [comment]
Thanks for your report! I can simply reproduce this issue by setting trigger safety margin to 0 or less.

**Comment by mhantsch** [comment]
I reset the configuration just because I wanted to make sure it's not a side effect of my quite large configuration.

**Comment by ert78gb** [comment]
it has been fixed by the #2319 PR, but has not been released
