### ISSUE TITLE
Error running Agent AppImage on Ubuntu 24.04

### ISSUE THREAD

**Issue by dm319** [UltimateHackingKeyboard/agent#2344]
My current system:

OS: Ubuntu MATE 24.04.1 LTS x86_64
Host: 20UF000RUK ThinkPad X13 Gen 1
Kernel: 6.8.0-41-generic
CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics (16) @ 1.700GHz

When running 4.2.0 as such:

`./UHK.Agent-4.2.0-linux-x86_64.AppImage`

I get this error:

```
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[364269:0906/155815.725288:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap
```

It is resolved by running

`./UHK.Agent-4.2.0-linux-x86_64.AppImage --no-sandbox`

In which case Agent opens normally.

**Comment by ert78gb** [comment]
@dm319 Do you run Agent as a `root` user?
Do you use app armor or something like that?

**Comment by dm319** [comment]
No, not run as root.  I don't use apparmor either as far as I know.

**Comment by ert78gb** [comment]
Sorry for the late response.

It is an electron and ubuntu 24.04 compatibility issue. https://github.com/electron/electron/issues/42510
Pleas, check the  https://github.com/electron/electron/issues/42510#issuecomment-2171583086 and let me know is it helped or not

**Comment by dm319** [comment]
Hi there,

Yes that appears to work.

I.e. running this:

`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`

beforehand allows you to run the software without the `--no-sandbox` flag.

D

**Comment by ert78gb** [comment]
thx for the feedback. I am keeping my eyes on the linked thread. I hope app image will work with the default settings of the Ubuntu 24.04
