### ISSUE TITLE
Agent hangs, when trying to color specific keys / layer

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/agent#2347]
I have a strange bug in Agent 4.2.0, which can be reproduced on different computers (Win 11).

I want to color some keys (assign green LED to some keys), but that kills Agent and it does not respond correctly any longer. 

Steps to reproduce. Download my config. Go the the following page and try to color the J-key or others close to it and Agent will stop working (for the most part). Coloring keys on the left side does not seem to cause any problems.

![image](https://github.com/user-attachments/assets/6699baaa-0843-4fa3-ba9c-164378139fbe)

[paintbugUserConfiguration.json](https://github.com/user-attachments/files/17196001/paintbugUserConfiguration.json)

**Comment by mondalaci** [comment]
I can reproduce this issue and Agent throws:

```
23:36:48.902 › TypeError: Cannot set properties of undefined (setting 'b')
    at file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1422675
    at Array.map (<anonymous>)
    at file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1422508
    at Array.map (<anonymous>)
    at file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1422451
    at Array.map (<anonymous>)
    at mZe (file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1422358)
    at file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1283429
    at file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:1283719
    at ote (file:///tmp/.mount_UHK.Ag4A7BvH/resources/app.asar/renderer/main.f5b33b14cb223c01.js:1:2002004)
```
