### ISSUE TITLE
Application loads with white screen

### ISSUE THREAD

**Issue by gschiess** [UltimateHackingKeyboard/agent#2348]
Running Ubuntu 24.04
I don't have anything fancy like apparmor installed

First off when I try to run just the AppImage alone it gives this error>

"
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[13505:1001/173149.620288:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
"

When in terminal with sudo i get this error

command - "sudo ./UHK.Agent-4.2.0-linux-x86_64.AppImage"
[1001/173339.269325:FATAL:electron_main_delegate.cc(295)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap

the output.txt file is when the application finally loads but it loads with a white screen. I can mouse over stuff but I can't see anything.

command - "sudo ./UHK.Agent-4.2.0-linux-x86_64.AppImage --no-sandbox 2>&1 | tee output.txt"

[output.txt](https://github.com/user-attachments/files/17217733/output.txt)

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
it is an electron and ubuntu 24.04 compatibility issue. https://github.com/electron/electron/issues/42510

The https://github.com/electron/electron/issues/42510#issuecomment-2171583086 contains the solution/workaround. 
Could you try it?

**Comment by ert78gb** [comment]
I will try to upgrade electron to the latest version but based on the comments, not guaranteed to will solve the problem.

**Comment by ert78gb** [comment]
https://www.reddit.com/r/linux4noobs/comments/lu1plx/hi_i_get_this_authorization_required_but_no/ also talks about this problem

**Comment by gschiess** [comment]
The Fix from https://github.com/electron/electron/issues/42510#issuecomment-2171583086
works thanks for the quick response
