### ISSUE TITLE
Agent 4.2.0, doesn't detect my V1 UHK

### ISSUE THREAD

**Issue by perssondan** [UltimateHackingKeyboard/agent#2349]
The latest version of the Agent doesn't detect my V1 UHK.
See attached log file.
[uhk-agent-submitted.txt.log](https://github.com/user-attachments/files/17242911/uhk-agent-submitted.txt.log)

**Comment by mondalaci** [comment]
@ert78gb Please look into this.

**Comment by ert78gb** [comment]
Hi @perssondan ,

Sorry for my late response.

Please follow the https://github.com/UltimateHackingKeyboard/agent/issues/2273#issuecomment-2115211212 instructions.

Please let me know is it helped or not.

**Comment by perssondan** [comment]
Hi @ert78gb ,
Thanks for the reply. I followed the instructions that was in the comments of #2273 , however, I'm not able to run that typescript file on my machine. For you information I'm using windows. I downloaded the ts-node npm package to be able to run typescript file but can't get it to work properly. The typescript gods ain't with me at the moment ;). If you've any further recommendations, it would be very appreciated. One idea I'm thinking of, is to install an older version of the agent, but I'm not sure of what version of the firmware I've on my keyboard at the moment...

**Comment by ert78gb** [comment]
Older Agent would solve the ts-node issue. Just stay on the master/edge :)

The following commands work in a cmd terminal

If your keyboard has LED backlight
`node_modules\.bin\tsx.cmd packages\usb\update-device-firmware.ts tmp\packages\firmware\devices\uhk60v2-right\firmware.hex --log=all`

If the keyboard does not have LED backlight
`node_modules\.bin\tsx.cmd packages\usb\update-device-firmware.ts tmp\packages\firmware\devices\uhk60-right\firmware.hex --log=all`

**Comment by perssondan** [comment]
Ok, so ran the command you suggested, first time over it failed, but the second time it worked. After I disconnect the keyboard and reconnect it. It works. Yay!

I then started the UHK Agent 4.2.0 and it says there's an issue with my keyboard and it displays a button to fix it, which I press (of course :D ). The agent though, are not able to fix it. Instead I need to go back to the use command you sent me to make it work. Even if I just start the agent, this seems to lock the keyboard and I need to power-cycle the keyboard to make it work again. Any ideas?
[uhk-agent-github.txt](https://github.com/user-attachments/files/17323278/uhk-agent-github.txt)

**Comment by mondalaci** [comment]
@perssondan Please [contact us](https://ultimatehackingkeyboard.com/contact-us), and we'll recall and fix your UHK. We're sorry for the inconvenience!

Please also attach your user configuration. It'd be useful for fixing the core issue.
