### ISSUE TITLE
Latest agent won't run on Ubuntu 24.04

### ISSUE THREAD

**Issue by mattgodbolt** [UltimateHackingKeyboard/agent#2362]
It seems some sandboxing changes have caused the uhk agent to not run on new Ubuntu. Downloading, chmod-ing and trying to execute:
```
$ mv ~/Downloads/UHK.Agent-4.2.1-linux-x86_64.AppImage ~/bin/uhk-agent
$ chmod +x ~/bin/uhk-agent
$ uhk-agent 
[1419073:1201/115356.023518:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_uhk-agj8I2es/chrome-sandbox is owned by root and has mode 4755.
fish: Job 1, 'uhk-agent' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

Same issue as things like: https://github.com/getcursor/cursor/issues/1683

Seems a workaround is to run with `--no-sandbox` or to take one of the steps mentioned in the bug above, though then the app can't seemingly talk to the keyboard at all.

**Comment by mattgodbolt** [comment]
Setting the `sysctl` to let it run still has permissions issues. I tried the "Set up permissions" but that also did not work.

**Comment by mondalaci** [comment]
@ert78gb Please help with this issue.

**Comment by ert78gb** [comment]
Please check https://github.com/UltimateHackingKeyboard/agent/issues/2344#issuecomment-2396039105

**Comment by mattgodbolt** [comment]
Thanks all! Sorry I didn't search closed issues! This seems to work: thank you!
