### ISSUE TITLE
Create default configuration dynamically

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#237]
Currently we parse the uhk-config.json to create the default/initial configuration. This means that keymaps used in the default configuration are duplicated since they are both stored in uhk-config.json and preset-keymaps.json.

Proposal A:
Remove uhk-config.json and build up the default configuration completly dynamically from code.

Proposal B:
Remove the keymaps from the uhk-config.json and use a string array which would enumerate those keymaps' abbrevation which should be included into the default configuration.

**Comment by mondalaci** [comment]
Ultimately, only a relatively small subset of presets will be included into the default configuration. Also, the default configuration includes some macros for demonstration purposes and those macros won't be included into the presets.

Given the above, I'd rather leave it as it is.

**Comment by fjozsef** [comment]
In the final version they shouldn't include any macro action, or if they do then we shouldn't call them QWERTY, VIM, etc. since they wouldn't be identical with the keymaps could added from add keymap page.
I would suggest to create a demo keymap for demonstration purposes, which would not be visible on add keymap page.

**Comment by mondalaci** [comment]
Having some macros in the default configuration is quite useful because the user can explore and customize them without having to create new macros from scratch. I don't consider it to be a problem that the macros are present beyond the preset content of the keymaps.

**Comment by fjozsef** [comment]
Okay, then what if there would be 2 cases:
If a keymap includes a PlayMacroAction then it can be stored in the configuration, but it cannot be in the preset. 
If a keymap doesn't include a PlayMacroAction, then if we would want it to be available both at add keymap page and in the default configuration, then in the uhk-config.json in the keymaps array instead of the keymap object only the abbrevation would be stored so it could be replaced with the preset object in the serializer.
With this we could resolve the redundance.

**Comment by mondalaci** [comment]
> If a keymap includes a PlayMacroAction then it can be stored in the configuration, but it cannot be in the preset.

I intend to bind at least one macro to every default keymap for demonstration purposes, and the above suggestion would make storing these keymaps both in the preset and in the default configuration which wouldn't reduce redundancy.

I also dislike redundancy, but I don't think this issue can be resolved without introducing some arbitrary policy, so I'd much rather have it now, and deal with more pressing issues.

**Comment by fjozsef** [comment]
I am not sure if I understand you correctly,  but preset keymaps can't have PlayMacroActions, it is by design. 

I haven't specified a milestone when this issue should be solved, but I have come across this issue regarding to fixing a critical one and I have to make redundant work because of this and it is quite annoying.

**Comment by mondalaci** [comment]
Let's talk about this on Hangouts.
