### ISSUE TITLE
Remove unused images

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#241]
Let's remove the unused images inside of the images and examples directories. It'd make sense to completely remove the examples directory.

**Comment by fjozsef** [comment]
While #138 is not ready I wouldn't remove the examples directory.

**Comment by mondalaci** [comment]
Sure thing. We can leave the examples directory as it is until #138 gets finished.

**Comment by mondalaci** [comment]
Just moved the the relevant images of the examples directory to #138 and removed the examples directory.
