### ISSUE TITLE
UHK Agent quits unexpectedly when closing the application

### ISSUE THREAD

**Issue by rogermeletta** [UltimateHackingKeyboard/agent#2430]
## Environment
**Agent:** [feat-uhk80-user-config](https://github.com/UltimateHackingKeyboard/agent80/actions/runs/11393823280)
**macOS:** Sequoia 15.0.1 (24A348)

(I encountered this issue using the latest available Agent build, as the master build has expired and is no longer downloadable. I've also tested with earlier Agent builds that I had previously downloaded, all of which produced the same outcome.)

## Description
When the UHK keyboard is connected via USB and dongle simultaneously, the Agent enters a "searching" state:

![Agent in searching state](https://github.com/user-attachments/assets/b9bf0483-d16c-4b17-a700-827710ee5438)

In this state, the UHK Agent application crashes when attempting to quit it normally.
This triggers a system dialog with the following message:

<img width="407" alt="UHK Agent quit unexpectedly dialog" src="https://github.com/user-attachments/assets/bece38b8-d3d1-4320-a362-2407f835756c">

## Steps to Reproduce
1. Open UHK Agent application
2. Connect the UHK keyboard via USB cable
3. Also connect the UHK keyboard via wireless dongle
4. Observe that the Agent enters a "searching" state
5. Attempt to close the application (through normal means, e.g., clicking the close button or using CMD+Q)
6. Observe the unexpected quit and error message

**Comment by ert78gb** [comment]
I think we could close it as duplication of 2354
