### ISSUE TITLE
Agent ignores the git sha for the right half upon updates

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#2435]
Agent doesn't even try to update to #b88eb0f for the right half when I choose a firmware file.

![image](https://github.com/user-attachments/assets/298be5b8-9383-4303-a6ff-7aed7e09a6d8)

**Comment by ert78gb** [comment]
I think it has been addressed in the https://github.com/UltimateHackingKeyboard/agent/pull/2365. In this PR we switched to checksum check instead of version check in Dongle and right half devices

**Comment by kareltucek** [comment]
Well, at minimum, please disable the check when current version or checksum is zero - in such cases, please always flash (ideally everything).

**Comment by ert78gb** [comment]
we have the `ignore-firmware-checksums` command line argument. Is it not sufficient?

**Comment by kareltucek** [comment]
Ah. Yes then, it is sufficient!
