### ISSUE TITLE
Function keys on macOS to control built-in Mac features

### ISSUE THREAD

**Issue by mjio** [UltimateHackingKeyboard/agent#2440]
Hi, does the UHK Agent support function keys on macOS to control built-in Mac features? I'm talking about the keys to control the display brightness, Mission Control, Spotlight, and Dictation as shown here: https://support.apple.com/en-us/102439

Thank you

**Comment by mondalaci** [comment]
Please see https://ultimatehackingkeyboard.com/knowledgebase/how-can-i-map-the-fn-key-of-my-laptop-to-the-uhk

I'm closing this issue, but feel free to follow up.
