### ISSUE TITLE
UHK Agent Core Dump. Keyboard broken

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/agent#2466]
I started flashing new firmware to keyboard (as was requested by agent, before I updated agent using notification in app itself). Agent became broken (core dump, run it from console), keyboard too (no my settings, looks like works like qwerty).

Downloaded agent from site and run it. It hangs - loads configuration forever.
![Screenshot From 2024-12-19 16-51-07](https://github.com/user-attachments/assets/17431243-fcff-4e3b-a2f6-9f07cf9968a8)

**Comment by likern** [comment]
And since I had custom layout I would say this is highly critical error.

**Comment by ert78gb** [comment]
If you start the agent from terminal do you see any error message?

you can also find the logs

on Linux: ~/.config/uhk-agent/uhk-agent.log
on macOS: ~/Library/Logs/uhk-agent/uhk-agent.log
on Windows: %USERPROFILE%\AppData\Roaming\uhk-agent/uhk-agent.log

Unfortunately from this screenshot I don't know what is the error

**Comment by likern** [comment]
> If you start the agent from terminal do you see any error message?
> 
> you can also find the logs
> 
> on Linux: ~/.config/uhk-agent/uhk-agent.log on macOS: ~/Library/Logs/uhk-agent/uhk-agent.log on Windows: %USERPROFILE%\AppData\Roaming\uhk-agent/uhk-agent.log
> 
> Unfortunately from this screenshot I don't know what is the error

The was a core dump (in terminal), while agent was dirung flashing firmware - I don't know what that means - as far far as I remember agent gui continued to working - might be this was some native subcomponent - and I saw logging to console?

No, don't see any errors.
[console.log](https://github.com/user-attachments/files/18203020/console.log)

**Comment by likern** [comment]
```bash
ls: cannot access '/home/vm/.config/uhk-agent/uhk-agent.log': No such file or directory
```

**Comment by likern** [comment]
Tried to run old UHK agent - no device found.
![Screenshot From 2024-12-19 23-47-28](https://github.com/user-attachments/assets/dee2d208-c29c-4a86-8759-72e8961550fb)

**Comment by ert78gb** [comment]
The old Agent not able to detect the keyboard with the latest firmware.

No error in the console.log so maybe there is an unexpected error in the renderer process.

After you started the Agent please open the electron developer tools with the CTRL + SHIFT + I. Do you see any error?

**Comment by ert78gb** [comment]
The log shows need to setup the udev rules. I am investigating why Agent does not show this information.

**Comment by likern** [comment]
I see only one warning
![Screenshot From 2024-12-20 00-00-53](https://github.com/user-attachments/assets/1fd0a346-72a4-4a6d-8b54-fbc54fc7cc68)

**Comment by ert78gb** [comment]
While I am fixing the bug.

You could set the udev rule manually. You can find the rules in https://github.com/UltimateHackingKeyboard/agent/blob/master/rules/50-uhk60.rules

Please update the `/etc/udev/rules.d/50-uhk60.rules` files and after run the following commands with sudo

```
udevadm control --reload-rules
udevadm trigger
udevadm settle
```

**Comment by likern** [comment]
> The log shows need to setup the udev rules. I am investigating why Agent does not show this information.

I saw this in log when tried to run old agent (probably). And already tried this. Do I need to do something besides physically reconnecting UHK from PC? Is this udev rules are correct?
[60-uhk.rules.txt](https://github.com/user-attachments/files/18203242/60-uhk.rules.txt)

**Comment by likern** [comment]
Worked (your file)! At least I see device. I was able to firmware again forcefully (to be sure). But all my settings are gone - custom layouts and macroses. Can I restore them?

**Comment by likern** [comment]
![Screenshot From 2024-12-20 00-15-49](https://github.com/user-attachments/assets/d05a258f-9033-4a9d-990d-d1373cc0c545)

**Comment by ert78gb** [comment]
You can see the archived user configuration on the Configuration page. You can restore to earlier user config

**Comment by likern** [comment]
Amazing! I was expecting a much worse outcome and experience. Thank you very much! Now it becomes fully functional. Close the issue.

**Comment by ert78gb** [comment]
Sorry for the inconvenience. It should be much smoother.
I would like to find what caused the issue.

Could you write the Agent and firmware upgrade process from the start if you still remember.
- Your keyboard was connected to the keyboard. 
- Did you started Agent 4 and it suggested new version available or did you manually download the new version?
- If the Auto updater updated the Agent then after you started the firmware upgrade? Is it failed or was success just Agent not recognised the keyboard?

Or anything else that come into your mind.
