### ISSUE TITLE
Faulty firmware information display

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#2469]
Consider this firmware build:
[uhk-firmware-12.0.1-20e8b5cf.tar.gz](https://github.com/user-attachments/files/18212745/uhk-firmware-12.0.1-20e8b5cf.tar.gz)

Agent displays the following:
![image](https://github.com/user-attachments/assets/3b73b157-5426-466f-920d-d0fc34a7f12d)

**Comment by ert78gb** [comment]
The firmware returns with only the 2 byte of the informations

I tried to "bisec" by the CI builds. 
The https://github.com/UltimateHackingKeyboard/firmware/commit/56ba94d8af9326e502c730026428cdd3a6b05d07 works properly

failed CI

https://github.com/UltimateHackingKeyboard/firmware/actions/runs/12410092553/job/34644998289 => issue occur here

My assumption is the https://github.com/UltimateHackingKeyboard/firmware/pull/1038  cause the issue.
I recognised this PR added the python version of `scripts/generate-versions.mjs` and `scripts/generate-versions-util.mjs`
I did not check the python version is the correct implementation or not. Or is it cause the issue or not, but I just would like to mention not lucky to maintain the same code in 2 languages especially when both usage are run the script as an executable.

The CI uses the `scripts/make-release.mjs --allowSha` to generate the release. 

The python script called without any argument `COMMAND ${Python3_EXECUTABLE} "${PROJECT_SOURCE_DIR}/scripts/generate_versions.py"` maybe it cause the issue.

**Comment by ert78gb** [comment]
the USB commands for easier debuging
- git tag `./packages/usb/send-command.ts --log=usb 0 6`
- git repo `./packages/usb/send-command.ts --log=usb 0 7`

**Comment by mondalaci** [comment]
@ert78gb Thanks for looking into this!

@benedekkupper What was the rationale for porting genrate_versions from node to Python? Besides introducing this bug, our team is more familiar with node.

**Comment by ert78gb** [comment]
Other note. The release generation has 2 mode
- for git tag. These are official releases
- for git sha. These are mostly used for internal testing.
