### ISSUE TITLE
UHK80 with Windows is in disconnected state after waking up from sleep

### ISSUE THREAD

**Issue by n0rbertg** [UltimateHackingKeyboard/agent#2474]
Hi,

Keyboard: UHK 80
FW version: 12.1.0
Connected via USB
OS: Windows11

When Windows wakes up from sleep the keyboard is in a disconnected state. After reconnecting the USB cable, it works again.

**Comment by n0rbertg** [comment]
Sorry, wrong repo, please delete from here.

**Comment by mondalaci** [comment]
Should I reopen and transfer this issue to the firmware repo?

**Comment by n0rbertg** [comment]
> Should I reopen and transfer this issue to the firmware repo?

Only if it's not redundant (I've seen similar issues there, if any covers this, then please just delete)

**Comment by mondalaci** [comment]
@kareltucek I leave it up to you whether to reopen and transfer this issue.

**Comment by kareltucek** [comment]
Please do. So far we have a forum thread and (closed!) agent ticket. Not ideal.
