### ISSUE TITLE
Implement Sticky Keys in Firmware

### ISSUE THREAD

**Issue by TorC8** [UltimateHackingKeyboard/agent#249]
In order for the sticky keys accessibility feature[0] to work with non-standard layouts that split the default punctuation or other pairs of characters, the feature must be implemented within the UHK or else the shifted characters will be misinterpreted by the host OS.  E.g. Programmer Dvorak has on the qwerty 2 key open square bracket without shift, but numeral seven with shift.  Sticky keys implemented in host OS with US layout would emit open curly brace instead of numeral seven.

This won't matter until after #248 is implemented.

[0] Sticky keys allows modifiers such as shift and ctrl to be used as sequences rather than as chords (e.g. ctrl then a instead of ctrl+a simultaniously).

**Comment by mondalaci** [comment]
Just tagged this as an exotic feature. We will consider implementing these later.

**Comment by fjozsef** [comment]
I would rather close this issue, since it is firmware related, so it should be tracked at [UltimateHackingKeyboard/firmware](https://github.com/UltimateHackingKeyboard/firmware)

**Comment by mondalaci** [comment]
It's fine by me, although these features cover both the firmware and Agent. Probably it's more firmware-related, though.
