### ISSUE TITLE
Agent doesn't work in Firefox

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#251]
Agent shows a blank page in Firefox and the Firefox JavaScript console contains the following:

![screenshot from 2017-01-03 22-52-26](https://cloud.githubusercontent.com/assets/300402/21624472/7a1e0e1a-d207-11e6-82e2-57abb8ad1247.png)

I'm using Firefox 50.1.0

Let's not handle this issue as a priority at least until Electron + node + USB works well.

**Comment by TorC8** [comment]
It also fails for me in FF 45.6.0 with the same (or very similar) ReferenceError.  Agent 1.0.0A1.  Only one JS warning for me:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
bootstrap.min.css:5:115557
```
There is also a host of CSS warnings.
