### ISSUE TITLE
UHK privilege screen

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#259]
After detecting the UHK according to #258, Agent should check whether it can access it.

Right after detection succeds, Agent should read the hardware configuration area, then the user configuration area. Upon starting to read the hardware configuration area, Agent will immediately hit a privilege issue if it can't access the UHK. Right at that point, it should display a screen similar to the detection screen but containing the following:

> Header: Cannot talk to your UHK
> Body: Your UHK has been detected, but its permissions are not set up yet, so Agent can't talk to it.
> 
> ["Set up permissions" button]

The "Set up permissions" button will behave in an OS-specific manner. Relevant OS-specific issues will be created later.

**Comment by mondalaci** [comment]
@fjozsef I've just noticed that you have written privilige instead of privilege all over the place. It's not a big deal, but it'd be nice to fix it.

**Comment by fjozsef** [comment]
@mondalaci Thanks, it should be fixed now.
