### ISSUE TITLE
Windows set up permission button 

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#261]
I'm not sure how much work it takes to set up Windows USB permissions with a click of a button. This should be researched. Worst case scenario, we'll just display the following for the first try:

In order to setup UHK permissions, download [Zadig](http://zadig.akeo.ie/) and use it to install the WinUsb driver for "Ultimate Hacking Keyboard (Interface 0)". (The rest of the interfaces should default to HidUsb.)

**Comment by fjozsef** [comment]
https://msdn.microsoft.com/en-us/library/windows/hardware/ff540174.aspx

**Comment by mondalaci** [comment]
For the first implementation, let's implement a regular setup without the special Windows descriptors. We have to deal with this case anyways, and right now I don't have time to implement the descriptors. Should the descriptors make the USB setup process completely automatic? If so, I assume you won't have to deal with them, and I should be able to test them as I complete them.

**Comment by fjozsef** [comment]
@mondalaci I don't know, I just found this feature, which could be helpful for us. But I don't know how the descriptors work, you should read the article yourself.

**Comment by mondalaci** [comment]
Ok then. Let's not deal with WinUsb descriptors in this issue. I'll implement them in the firmware, test them myself, and let you know if there's anything to do regarding Agent.

**Comment by mondalaci** [comment]
This isn't an issue anymore because hidapi doesn't require privilege escalation on Windows.
