### ISSUE TITLE
OSX set up permission button

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#262]
I'm absolutely clueless about whether it's necessary, and if so, how to set up UHK USB permissions on OSX, so we'll be relying on the ultimate wisdom of Mr. @NejcZdovc.

Related issues are #259, #260, #261.

**Comment by ert78gb** [comment]
#314

**Comment by ert78gb** [comment]
To fix #314 issue we have to solve it.

**Comment by mondalaci** [comment]
hidapi has just been integrated in #300 which should resolve this issue. No privilege escalation is required for Agent on OSX.
