### ISSUE TITLE
Option to use JIT/AOT build modes

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#280]
Currently only building in JIT mode is available, we should make it possible to use AOT (and switch between those two transparently) since it has a lot of benefits (e.g. smaller and faster code).

Probably we will use: https://www.npmjs.com/package/@ngtools/webpack

**Comment by fjozsef** [comment]
Blocked since `@ngtools/webpack` is unable to process symbolic links.

**Comment by attilacsanyi** [comment]
Would be great to use [angular-cli](https://github.com/angular/angular-cli/wiki) which is use **AOT by default**.
_Electron part might be an issue in this case._
Angular-cli has [eject](https://github.com/angular/angular-cli/wiki/eject) command, which can be used for comparison to the current agent webpack config.

**Comment by mondalaci** [comment]
@attilacsanyi I'd like to see angular-cli introduced, although chances are AOT won't work right now due to the issue mentioned by @fjozsef.

**Comment by mondalaci** [comment]
How about this one, @ert78gb? According to my knowledge AOT is not used yet due to circular dependencies. How long would it take to make it happen?

**Comment by ert78gb** [comment]
I will check it on next week and I will give a response.
