### ISSUE TITLE
Platform specific bundles

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#283]
See [Electron packager](https://github.com/electron-userland/electron-packager) and [Electron builder](https://github.com/electron-userland/electron-builder)
- [x] Windows 32 bit
- [x] Windows 64 bit
- [ ] Linux x86
- [x] Linux x86_64
- [x] OS X

**Comment by fjozsef** [comment]
Relates to #250

**Comment by mondalaci** [comment]
This has been done.
