### ISSUE TITLE
Polishing QWERTY keymap

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#285]
- [ ] Presets
- [ ] Default

- [ ] @mondalaci Remove unwanted keyactions (From user perspective)
- [x] @fjozsef Remove unwanted keyactions (from technical perspective)

**Comment by fjozsef** [comment]
@mondalaci Done from my side.

**Comment by mondalaci** [comment]
Done by e99fb08cc2d5aa1b640322dbc9b84bc34254a4bd.
