### ISSUE TITLE
Add menu to the electron app

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/agent#295]
The electron app is not contains any menu by default. The task is create a new menu structure same as the default menu:

On Mac:
- Agent  
  - About Agent
  - Quit Agent (CMD + Q)
- View
  - Reload (CMD + R)
  - Force Reload (CMD + SHIFT + R)
  - Toogle Developer Tool (ALT + CMD + I)
  - Separator
  - Actual Size (CMD + 0)
  - Zoom In  (CMD + +)
  - Zoom Out (CMD + -)
  - Enter Full Screen (CTRL + CMD + F)

Win:
- TBD

Linux: TBD

**Comment by fjozsef** [comment]
Actually it has had a menu and it was there for a long time, but was removed after @mondalaci asked it. 
Hidden by https://github.com/UltimateHackingKeyboard/agent/blob/master/electron/src/electron-main.ts#L19

**Comment by mondalaci** [comment]
Correct, @fjozsef.

@ert78gb I believe we shouldn't feature a traditional menu just because most applications have menus. I'd much rather integrate features into the side menu than revealing the top menu. I'm closing this issue, but feel free to open it if you think there's something else to it.
