### ISSUE TITLE
Implement every class of the configuration to be serialized

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#30]
First of all, thank you very much for offering your help regarding this, @srang!

I've just finished putting together a [Google Sheet](https://docs.google.com/spreadsheets/d/1qsUgSyPOcEI3zLLjTlvH4Mo4pbCBCTjxk9LQE_vRWJw/edit#gid=0) that describes the individual classes and properties of the configuration in fair detail.

The [documentation](https://github.com/UltimateHackingKeyboard/agent/blob/master/config-serializer/README.md) that I've written up on the configuration serializer should also help.

I think it'd be a good strategy to move upwards in the tree step by step, starting from the currently implemented KeyActions class. If so, the next one would be Module, then Modules, then Layer, Layers, Keymap, Keymaps, and finally UhkConfiguration. Then you could implement ModuleConfigurations, and finally the Macros tree.

Please let me know if anything is unclear and let's discuss things here, so that everybody can see the conversation as it unfolds.

Thanks a ton!

**Comment by srang** [comment]
Would you prefer a single pr with all of the serialization functionality that we review periodically or split it over multiple prs?

**Comment by mondalaci** [comment]
I certainly vote for multiple PRs because that way code gets committed in regular intervals. Also gives a better sense of progress.

**Comment by srang** [comment]
Sounds good I'll have Module and Modules up soon

**Comment by srang** [comment]
Is pointerRoles supposed to be a single pointerRole enum or an array of pointerRole enums? In the semantics, the first module has it as a single and the description supports that but in the second and third modules, its an array, and it could make sense for a pointer module to be able to scroll and point. Additionally the name is plural so I figured it was worth checking.

**Comment by mondalaci** [comment]
Good point! `pointerRole` is supposed to be a single enum, not an array. Originally, it was an array but I figured that we may never use multiple pointers per module, so an array would be overkill. Looks like I already updated `uhk-config.json`, but I forgot to update the spreadsheet, so I've just fixed it.

**Comment by srang** [comment]
So I've come across an interesting bug while working on this. I've got the serializer working with a single module, however what I'm seeing is that when there are multiple items in a `ClassArray` of the same type (eg `Serializable<Module>`) the previous items in the array get overwritten with the properties of the new pushed element. For example:
```
                    "modules": [
                        {
                            "moduleId": 0,
                            "pointerRole": "move",
                            "keyActions": []
                        },
                        {
                            "moduleId": 1,
                            "pointerRole": "scroll",
                            "keyActions": []
                        },
                        {
                            "moduleId": 2,
                            "pointerRole": "none",
                            "keyActions": []
                        }
                      ]
```
and print out the elements array as it get populated by the `_fromJsObject` function in `ClassArray` I see something like this: 
```
Elements: <Module moduleId="0" role="1">
Elements: <Module moduleId="1" role="2">,<Module moduleId="1" role="2">
Elements: <Module moduleId="2" role="0">,<Module moduleId="2" role="0">,<Module moduleId="2" role="0">
```
I assumed this had to do with how I implemented Module and Modules, however on a hunch I tried adding a second keyaction of the same type and the same thing happened where the second element of the same type forced its properties onto the other element.  I've started looking around online for explanations but I'm still getting the hang of typescript in general and figured maybe a second set of eyes might know what's going on. My suspicions are currently on how typescript handles pushing to typed arrays.

**Comment by mondalaci** [comment]
This is pretty interesting, indeed, and I'm not sure what's going on.

I've just checked out your repo, and couldn't reproduce this issue right off the bat. Can you please commit to your repo, so that I can reproduce this by executing `test-serializer.js`?

**Comment by srang** [comment]
Sure thing. One moment.

**Comment by mondalaci** [comment]
@srang I've noticed that the dump was pretty hard to read beacuse I didn't account for deeper object hierarchies, like the one you're working with. So I've just committed 97c025d19bb5774217922fc8c976a7e2f8bb59bc to make the dump significantly more readable.

This bug has yet to fixed, but given the increased usability of the improved dump I thought that it's the best use of my time long-term. I'd be happy to look into the exact problem tomorrow, but I don't have any more time today. You're welcome to merge master and take another look at the improved dump in the meantime.

**Comment by srang** [comment]
@mondalaci Awesome that is way easier to read! I'll let you know if I figure out what is going on. Were you at least able to replicate the problem?

**Comment by mondalaci** [comment]
@srang Glad it's easier to read! I could see that the test failed, but I haven't looked into it yet. But I will look into it today.

**Comment by mondalaci** [comment]
I've managed to reproduce the problem, and I think that your suspicion is correct. According to the dump the JavaScript objects get correctly converted to TypeScript objects, but then they don't get correctly saved into the array, and upon reading the array back the problem surfaces.

I don't understand the cause of the problem either, and plan to dig deeper. It'd be a good idea to reduce the problematic code as much as possible and write a little script out of it. That way, we could focus on the core issue and understand it in its entirety.

Two little things: Could you please use the tslint visual studio code extension? That way you could see every warning right off the bat. I think it'd also be a good idea to always use full names, such as `pointerRole` instead of `role`. By being more explicit it's easier for the mind to associate concepts, and helps avoiding bugs.

Good job on your analysis regarding duplicate objects! This is quite a weird behaviour. Let's figure it out!

**Comment by srang** [comment]
Yep I can add tslint and update that variable name. Were you okay with changing module.id to module.moduleId? I changed it while I was debugging but because we are going to have many classes with an id field I thought making it more explicit made sense.

**Comment by mondalaci** [comment]
I agree, let's be explicit.

**Comment by mondalaci** [comment]
On second thought, `id` could be an exception. It should be clear that it's the unique identifier of a given object / class, like the primary key of relational database tables.

**Comment by srang** [comment]
That makes sense, I can switch it back

**Comment by mondalaci** [comment]
Thank you!

**Comment by mondalaci** [comment]
The `@assert*` decorators seem to be the culprit. Try to remove the assert for the module id for example, and then it gets serialized correctly.

The implementation of these decorators contains some JavaScript magic, like moving the values of these properties into a closure. The current implementation is elegant in the sense that no assertion code has to be injected into the classes to be serialized, but given the above problems this approach might not be feasible.

For the time being, you're welcome to comment out the assert decorators and see whether the comparison check succeeds.

I'll be looking into this, and try to find the best solution that actually works.

**Comment by mondalaci** [comment]
Please make sure that you comment out the assert decorators instead of removing them. If I manage to fix them then they'll be back.

**Comment by srang** [comment]
Good find and okay I'll update that and put up the pr (after making sure everything else works) and get started on the next part!

**Comment by srang** [comment]
Naming convention question with respect to Layer and Layers. There is an enum in SwitchLayerAction. This causes a naming collision if we wanted to call the class above modules "Layer". I'd propose changing the enum name over the class name to something like KeyLayer. but that begs the question, do we change every (Layer|layer) to (KeyLayer|keyLayer) in Switch(Key?)LayerAction or just the formal enum and leave everything else the same. Nit picky I know, but I appreciate attention to detail.

**Comment by mondalaci** [comment]
I think it'd make sense to change the current `Layer` enum to `LayerName`. I believe we shouldn't change the name of `SwitchLayerAction` because layer action and layer are different concepts.

Nitpicking is always welcome - let's care about the details.

**Comment by srang** [comment]
In the uhk-config.json the first keymap has fields that aren't in the second keymap. I'm guessing that the first one is what to code off of and that those fields are **not** optional, but wasn't sure. I feel like the actual mapping of keys are a vital part of a key map :wink:

**Comment by mondalaci** [comment]
Good point! The key actions are actually not required (the array must be there, but it can be empty) given that the pointerRole is not None. That's because one can create a module that is a pointer without any keys, like a touchpad. So the last module example is not valid.

**Comment by srang** [comment]
Okay that is very good to know! Maybe we should open an issue to add additional validation beyond the type assertion annotations? Obviously we'd need all the classes implemented first... but after that. Also that didn't exactly answer my question about the keymap configuration. I was looking at this one 
```
        {
            "id": 1,
            "name": "Dvorak"
        }
```
compared to 
```
        {
            "id": 0,
            "isDefault": true,
            "abbreviation": "QTY",
            "name": "QWERTY",
            "layers": [
                ... omitted for clarity ...
            ]
        }
```

**Comment by mondalaci** [comment]
I totally agree that we should implement additional semantic validation. I was already thinking about this but didn't want to overwhelm you with it yet. Beyond the case that you brought up, we should also check whether Play Macro Actions reference valid macro ids, and whether Keymap Switch Actions reference valid keymaps. I think it'd be more productive to implement these checks after the basics have been done, and validate them in a second pass. Actually, not only it'd be more productive but some of the validations need the whole tree to be constructed beforehand.

Sorry for forgetting to answer your question about the keymap configuration. You're right that these fields are all necessary. You're welcome to add some valid content there.

**Comment by mondalaci** [comment]
I've been thinking about whether we should squeeze bits together to maximize the use of the EEPROM as much as possible, and I concluded that we shouldn't do it because it's not a good tradeoff at this point.

Currently, we do this for `SwitchLayerAction`, and `Macro`, and we do indeed save a byte per object but in an average configuration there will only be about one or two dozen such objects. On the other hand, this practice does introduce complexity, not only in Agent, but also on the firmware side, which will also have to deserialize the binary configuration.

Given how many stuff can potentially break, and the combined complexity of Agent and the firmware, I think we should aim for simplicity and robustness for our first release, and not complicate things even the slightest bit.

Once people all around the world (and a fair number or Martians) will use Agent, and share configurations we'll be able to make statistics and see what (if anything) needs to be optimized. Maybe we conclude that 32K is much more than people generally use, so let's rather not optimize potentially prematurely.

In light of the above, would you please simplify the relevant classes, Sam?

**Comment by srang** [comment]
Yep I think that makes a whole lot of sense. So I'll pull `toggle` out into its own byte in SwitchLayerAction, `isDefault` out in KeyMap, and leave the two bools separate from the id in Macro. Or would you like each one in its own byte? It occurred to me while I was eating breakfast that this kind of thing would make things ugly for the firmware so I totally agree with the move.

**Comment by mondalaci** [comment]
I'm glad you agree with this decision. Yes, I think we can make the bools separate. It's a bit wasteful, but I don't foresee people using so many macros. Let's aim for simplicity first.

**Comment by srang** [comment]
Question on ModuleConfiguration. In the comment on id you say that each module has a unique id and that we should create enums for each one, I think it makes sense then to change the json representation to use a string form of the enum like we're doing in SwitchLayerAction. Unless I misunderstood where the enum is supposed to go.

**Comment by mondalaci** [comment]
Very good point, but this is sort of a special case. It'll be possible for anyone to take our hardware dev kit and create a custom module. For that, the developer should pick an unused module ID to uniquely identify his/her module. That ID will be used to build the firmware of the module, which the module will communicate to Agent. At that point, Agent won't be able to associate a related enum value for that new integer value.

That's why I'd rather stick to numeric IDs for the time being. The module enumeration protocol and payloads are yet to be designed, so let's keep it basic for now.

Maybe we should postpone the creation of these enums because tslint would complain that they're unused.

**Comment by srang** [comment]
Ah that makes a lot more sense then. Okay so for now I'll hold off on the enums and leave the id as a uint8 (that will actually make this last bit more straight forward)

**Comment by srang** [comment]
With [4195028](https://github.com/UltimateHackingKeyboard/agent/commit/4a950283b3d8e0d0f5d329aeef71a9ce36e2f8b9) I think we can mark this issue as completed/closed. I'll give you a chance to take a look at the final implementation though

**Comment by mondalaci** [comment]
Boom shakalaka! This was a very impressive sprint, Sam. I agree that this issue is pretty much closed. Please let me open a new one in a sec.

Awesome job, keep it up! :+1:
