### ISSUE TITLE
Support setting Unicode character for keypress

### ISSUE THREAD

**Issue by EgillAntonsson** [UltimateHackingKeyboard/agent#312]
Proposed solution:
have a textfield where you can enter the unicode Number for the character
Example:
Type in _00E1_ into a Unicode labeled textfield which would result that appropriate unicode character **á** would display in the Scancode textfield (and would be saved on Remap Key press).

**Comment by mondalaci** [comment]
USB keyboards don't send unicode characters to the host. They send scancodes (0-255). Then the scancode gets converted by the operating system according to the active language keymap.

The only way is use Alt codes, or OS-specific equivalents on non-Windows platforms implemented by macros.
