### ISSUE TITLE
Convert the Base, Mod, Fn, Mouse buttons to a button group

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#315]
Convert the Base, Mod, Fn, Mouse buttons above the keyboard to a bootstrap button group of the same size.

**Comment by attilacsanyi** [comment]
PR is ready. Screenshot about the change:
![image](https://user-images.githubusercontent.com/2144794/27391626-b4a6aaf2-56a4-11e7-8c99-c0bbec94ade1.png)

**Comment by mondalaci** [comment]
Closed by #317.
