### ISSUE TITLE
Undo deletion box

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#318]
Let's use the following box upon deleting keymaps and macros:

![undo-delete](https://user-images.githubusercontent.com/300402/27520465-89a2ec60-5a0c-11e7-9c91-74c92bc3d8ec.png)

* The box should slide in from the right and slide back, out of screen upon undoing the deletion or pressing X.
* The "keymap" part of the text should be "macro" for macros.
* When navigating to another page and coming back the box shouldn't be visible anymore.
* The style of the box largely utilizes the [dismissible bootstrap warning alert](http://getbootstrap.com/components/#alerts) with some tweaks. Please make it look like on the picture.
* Edge case: When deleting the last macro the empty macro page will be shown. The box should be visible in this case, too.
* Unlike [displaying errors](#319), the point here is not to cover any UI elements and to seamlessly disappear when not acted upon and moving to another page.

Please check whether we can use use anything from #126. If neither this issue nor #319 can utilize #126 then close #126 and #74.

**Comment by ert78gb** [comment]
I created the base functionality

**Comment by mondalaci** [comment]
@ert78gb It seems to me that your first suggestion is not generic because the last keymap event is specific to keymaps. Your second suggestion however seems generic and simple. Is it so?

**Comment by mondalaci** [comment]
I tried to test this but nothing seems to happen when clicking the delete icon.
