### ISSUE TITLE
Remove excess space above the UHK

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#323]
Please consider the following screenshot:

![screenshot from 2017-06-27 22-29-24](https://user-images.githubusercontent.com/300402/27608633-745a2f80-5b88-11e7-96ee-0e37f22ae004.png)

The narrower the window gets, the larger the space above the UHK becomes. This space should be constant.

Please use a general approach that will work even if we use the SVGs of other keyboard models in the future.

**Comment by attilacsanyi** [comment]
Do we still need something here @mondalaci ? I assumed it is done ;-)

**Comment by mondalaci** [comment]
Yep, all good!
