### ISSUE TITLE
The Electron build of Agent remembers the configuration

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#325]
But it clearly shouldn't. Only the web build should remember the configuration. The weird thing is that I can't see where it stores the config. Local storage seems to be empty.

**Comment by ert78gb** [comment]
It should remember.
https://github.com/UltimateHackingKeyboard/agent/blob/master/electron/src/services/electron-datastorage-repository.service.ts

**Comment by mondalaci** [comment]
It shouldn't. Agent-electron should always read the configuration from the UHK over USB which will be implemented later. For the time being, the default configuration would be preferred.

**Comment by ert78gb** [comment]
ok, I understand.
The solution is https://github.com/UltimateHackingKeyboard/agent/blob/master/electron/src/services/electron-datastorage-repository.service.ts#L22 return null.
I will fix it
