### ISSUE TITLE
Linux privilege escalation problem

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#326]
Just after Agent escalates privilege on Linux, I hit a strange screen:

![screenshot from 2017-06-28 20-51-02](https://user-images.githubusercontent.com/300402/27654875-af3b9fd8-5c43-11e7-90ca-719ed7d8813c.png)

First, I was totally clueless about what I saw, then opened the dev tools of Agent, dug into the HTML structure, and realized that I'm looking the ngrx/store Log Monitor.

This is the console log:

![untitled](https://user-images.githubusercontent.com/300402/27655090-6db954d2-5c44-11e7-8f1b-59cbf0676738.png)

Luckily, the privilege escalation itself gets executed properly and if I restart Agent it can access the UHK over USB and doesn't display the privilege escalation screen anymore, but this error is definitely confusing.

It would be nice to get this fixed, and I'm especially interested about why the ngrx/store Log Monitor gets opened. We should always display the relevant errors to the user instead of displaying a developer tool.

**Comment by attilacsanyi** [comment]
Perhaps not related, but why are we using the separate `log-monitor` from @ngrx.
Just `@ngrx/devtools` should be enough with **Redux devtools chrome extension** described [here](https://github.com/ngrx/store-devtools)

**Comment by mondalaci** [comment]
@attilacsanyi I don't have the slightest idea. Chances are Mr. @NejcZdovc pulled it in along with ngrx/store. Maybe he knows the answer.

**Comment by attilacsanyi** [comment]
I also used log-monitor sooner, but with extension it is better to show redux debugger only if the extension is present.

our code has this `<ngrx-store-log-monitor toggleCommand="alt-t"></ngrx-store-log-monitor>`
so `alt+t` is the key combo to show or hide the monitor.

**Comment by mondalaci** [comment]
@attilacsanyi You're welcome to ditch the log monitor if the chrome extension alternative is a suitable replacement.

**Comment by mondalaci** [comment]
@attilacsanyi Would you also kill the dead space on the top of the page? I guess that it might be related to log monitor, but in any case, I'd rather not open a separate issue just for this.

![screenshot from 2017-07-02 22-45-35](https://user-images.githubusercontent.com/300402/27773373-909cdf1e-5f78-11e7-83c1-ea4442db3aa0.png)

**Comment by NejcZdovc** [comment]
Sorry for a late response. Yeah if chrome extension is working correctly I am down for it, because we want to ship smallest bundle possible.

**Comment by attilacsanyi** [comment]
Sure, I love to do it ;-)

**Comment by mondalaci** [comment]
Please hold on with this as https://github.com/UltimateHackingKeyboard/agent/pull/378 might just fix it.
