### ISSUE TITLE
Use bootstrap tooltip

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#329]
Right now, we only have a single tooltip which you can see by hovering over the question mark icon located rightwards of the long press action of the keypress tab of the key action popover.

Please use [bootstrap tooltip](http://getbootstrap.com/javascript/#tooltips) instead, and make use of its HTML feature because I'd like to add HTML content to this tooltip soon.

I'd also like to experiment with styles, and have no idea about where to override Bootstrap tooltip styles, so please create a file for it and increase the padding a bit, so that we can check that it's working and I'll be able to tweak it further.

**Comment by attilacsanyi** [comment]
basic bootstrap tooltip works with examples next to the question-mark icon. @mondalaci
_run `npm i` needed_

**Comment by mondalaci** [comment]
@attilacsanyi It's not working and I don't understand how it is supposed to work because I cannot see any relevant PRs or commits.

**Comment by attilacsanyi** [comment]
No PR yet as the custom tooltip is not working yet as an example. Please checkout `issue-329` branch please and run `npm i` before run the dev server. I hope it helps.

**Comment by mondalaci** [comment]
Ah, gotcha! Unfortunately, I still cannot see the bootstrap tooltip in the branch when hovering over the question mark icon. Please open a PR when this is supposed to be fully functional. That way, we'll avoid any misunderstanding. Thank you!

**Comment by attilacsanyi** [comment]
Hmm, strange it should be functional, never want to ask for testing code which is not working or no extra functionality were added. Could you provide me the problem @mondalaci

You can see the new code and logic pushed to `issue-329` branch.

Follow these steps:

0. Ensure that you remove `package-lock.json` _(in case of `node` > 8.0 )_
1. Checkout `issue-329` branch _(Green in Travis)_
2. `npm prune`
3. `npm i`
4. `npm run server:web`
5. Explore the tooltip like this:
![image](https://user-images.githubusercontent.com/2144794/27853911-fa6e476e-6164-11e7-9d39-eb0230b221c7.png)

**Comment by mondalaci** [comment]
Thanks for the insructions! For some reason, this time it worked by simply building the electron version as usual.

What are your remaining evil plans for this issue? Remove the "(title missing, default, topdefault, )" test text and add custom styles? I prefer the downwards pointing tooltip version.

**Comment by attilacsanyi** [comment]
Awesome, if its enough for now I can stop here by removing the examples and set **default tooltip position to bottom**.
_If we need more customised tooltip, you can request it in another issue is it convenient @mondalaci ?_

**Comment by mondalaci** [comment]
Yep, please do as you suggested. On top of that, I'd just like to ask for a dedicated style file into which I can put my bootstrap tooltip styles to override the defualt ones. Please override the background color of the tooltip with gray color for example. Then I'll experiment with tooltip styles myself.

**Comment by attilacsanyi** [comment]
@mondalaci ready for check again. Applied a custom tooltip with externalised styles. Hopefully it will be suitable for you, PR also green.
