### ISSUE TITLE
Remove libusb

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#330]
After testing hidapi on Linux-64, Linux-32, Windows-64, Windows-32 and OSX, please remvove libusb and remove the extra abstraction layer that calls hidapi vs libusb.

Please also remove zadig, zadic, and generally speaking all the Windows specific privilege escalation code that has been obsoleted.

**Comment by mondalaci** [comment]
I'm reopening this issue because it looks like [libusb is still needed](https://github.com/UltimateHackingKeyboard/agent/issues/393#issuecomment-325024773) for building Agent which shouldn't be the case. I'd like this to be reinvestigated and all the libusb-specific code to be removed.

**Comment by ert78gb** [comment]
it is duplicate of #380 Only the usb package use the libusb.

**Comment by mondalaci** [comment]
Ah, I see! Sorry for the misunderstanding. Closing this issue.
