### ISSUE TITLE
Agent throws errors when removing all macros

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#339]
If I delete every macro, I get the following error:

![error1](https://user-images.githubusercontent.com/300402/27983852-565cc910-63c7-11e7-8a66-e520262ffa89.png)

Then if I hit ctrl+o to transfer the whole configuration to the UHK, I get the following error:

![error2](https://user-images.githubusercontent.com/300402/27983858-8dd99422-63c7-11e7-9fc3-fd8836a88229.png)

This one is quite critical and a blocker because Eric, our firmware development cannot proceed due to this bug, so please fix it ASAP.

**Comment by fjozsef** [comment]
It only happens in electron and you don't need to delete all of the macros, just the second one. It seems the array has become readonly somehow.

**Comment by mondalaci** [comment]
@fjozsef Thanks for the further info! Not sure why you removed the blocked tag. Eric has implemented the configuration parser without the macro parser, and he can't test it due to this issue, so this is effectively blocking him.

**Comment by fjozsef** [comment]
@mondalaci The issue itself is not blocked.

**Comment by eltang** [comment]
@mondalaci I appreciate the gesture, but @fjozsef is right here. My development is blocked by this issue, not the other way around.

**Comment by mondalaci** [comment]
You're totally right guys. I won't misinterpret this tag the next time.
