### ISSUE TITLE
Get rid of jQuery

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#346]
In another discussion regarding bootstrap tooltips you guys have suggested that we should get rid of jQuery which I'm very open to.

The first question is that what parts of Agent utilize jQuery. The second is how hard would it be to replace them.

**Comment by attilacsanyi** [comment]
It is currently used only in the following 2 cases:

1. ng2-select2 options
1. bootstrap tooltip

So far I could not found any similar like ng2-select2 groupped select, but the following two libs are rich enough to use and can replace lots of existing UI elements in the agent:

1. [bootstrap](https://ng-bootstrap.github.io/#/components)
1. [primeng](https://www.primefaces.org/primeng/#/) . _(custom theming support)_

**Comment by mondalaci** [comment]
* I'm fine with replacing bootstrap with ng-bootstrap given that the bundle size won't increase significantly.
* We could possibly replace JS select2 with ng-select2.
* I'd rather not use Prime at this point because it's a different UI toolkit and it wouldn't gel well with Bootstrap.

**Comment by attilacsanyi** [comment]
Prime has Themes dropdown with Bootstrap style, really close, you just need to define custom colours, so not a problem at all to use it but you can get much more components flexibility.

**Comment by ert78gb** [comment]
I tried to use the datepicker and select components of primeng in prev project but I did not really liked the themeing and databinding implementations.

**Comment by mondalaci** [comment]
My major concern is that Prime is a fully-fledged UI framework and as such, it'll likely pull extra dependencies. I'm much more comfortable with standalone non-Bootstrap components.

**Comment by attilacsanyi** [comment]
Thats true @mondalaci Primeng use jQuery inside and jquery-ui :), but definitely the most richest angular lib out there for free. My personal favourite is material 2.

**Comment by ert78gb** [comment]
I used material 2 one years ago but it was very alpha many components was not implemented or worked with low functionality, but I love the material base concept.
Bootstrap and material 2 has 2 different outfit :)

**Comment by mondalaci** [comment]
The presence of jQuery shouldn't be a big deal after all. Closing this ticket.
