### ISSUE TITLE
Don't display the add-on modules by default

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#351]
The add-on modules will only be implemented later until which point we shouldn't display them in the menu. Please hide them by default and only show them when the `--addons` command line argument is present.

**Comment by ert78gb** [comment]
What about the web build? Would you like to see the add-on menu group?

**Comment by ert78gb** [comment]
Depend from PR #338 , because I moved the app reducer from the electron module to the shared module. And I would like to add the 'visibleAddon' property to the app state.
