### ISSUE TITLE
Make SwitchKeymapAction store the target keymapId instead of keymapAbbreviation

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#357]
Currently, we're storing the abbreviation of the target keymaps in switch keymap actions. We should rather store the index of the target keymap. This will make the configuration parser easier to implement and consume fewer resources which is important given the resource-constrained nature of microcontrollers. This is also consistent with the way we store macros.

This issue blocks https://github.com/UltimateHackingKeyboard/firmware/issues/52

**Comment by fjozsef** [comment]
Macros have ids, that ids are stored, not the indices. The ids of the keymaps are the abbrevations.

**Comment by mondalaci** [comment]
Apparently, you're totally right. In any case, we should identify both keymaps and macros by their indexes. I'd be much easier to handle them on the firmware side, we'd save memory and EEPROM storage space.

**Comment by ert78gb** [comment]
I am working on #338 and I create a current and previous state of the user configuration. Could you wait with the development until I finish it? I plan to finish it today.

**Comment by mondalaci** [comment]
I'd like to get this implemented ASAP given the blocking nature of the issue. How would this affect #338?

**Comment by ert78gb** [comment]
if need ASAP do it.

**Comment by ert78gb** [comment]
I finished the development and I chose other solution. I hope the conflict will be minimal or 0

**Comment by ert78gb** [comment]
@fjozsef Laci said it is an important issue. Could I help anything to faster solving?
