### ISSUE TITLE
Add tooltips to action icons

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#364]
Currently, the delete and duplicate icons of keymaps and macros have tooltips. Please also make sure that the tooltips of the download keymap and the default keymap (star) icons look the same.

Note that the star icon has enabled and disabled state and it's also present in the side menu. All of these 3 icons must have tooltips.

Make sure that every tooltip points downwards, not upwards which is currently the case.

I'd also like to get the style of the tooltip changed, so that it has the current dark gray outline but white background and black text.

**Comment by ert78gb** [comment]
What are the text of tooltips?

**Comment by ert78gb** [comment]
Delete
Duplicate
Default ?

**Comment by mondalaci** [comment]
The icons already have Alt text. You can see them if you hover over them. These Alt texts should be put into the respective tooltips.
