### ISSUE TITLE
Impossible to reassign any key using middle click on FF

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#367]
That's the behaviour:
When you middle click a key appears on top the record key.
Any key pressed after that do nothing.
When you middle click the key again, the record symbol dissapears.

If the user middle clicks two keys, both will have on top a record key.
![redkeys](https://user-images.githubusercontent.com/2158443/28416324-d47619ce-6d53-11e7-9385-03271c459e60.gif)

I've tested the issue on v39 (32bit), but also on the newests versions: v54 (32bit) and v54 (64bit).
Same issue.

**Comment by IzK666** [comment]
You should reopen this issue.
I can't still reassign any key using the middle click, but now it doesn't show the record symbol.

**Comment by IzK666** [comment]
Note: The record symbol doesn't appear on FF v39 (an old version).
On latest version the record symbol appears, but still no key is recorded.

**Comment by ert78gb** [comment]
What is your "latest version"? I tested FF v55 and it works correctly

@laxu Who fixed the bug wrote in the PR
> Only Firefox v52+ support focusout event so this will still not work correctly on older FF versions than that.

**Comment by IzK666** [comment]
As I was using v52 esr it didn't update automatically to regular versions (even the button on FF website) :laughing: 
So I have updated manually to v54 and wasn't working either. After that I tried with the newest v55b12 with no results.

I don't know what to say. It's a bit strange.
Keep this issue closed and don't bother if no one else complains about.

**Comment by ert78gb** [comment]
What is your OS?

**Comment by IzK666** [comment]
Windows 7 64bit

**Comment by laxu** [comment]
Tested this on FF v54 on both MacOS Sierra and Win10 64-bit. Works fine for me. Maybe a cache issue?
