### ISSUE TITLE
Save to keyboard button

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#377]
Whenever the user updates hid/her configuration, a button should slide in from the bottom and show up in the right bottom corner:

![untitled](https://user-images.githubusercontent.com/300402/28756817-308c99f2-7576-11e7-9d8e-dce5b95977d4.png)

Upon pressing the button it should trigger the same transfer that is now triggered when pressing ctrl+o and update its content to display "[animated progress spinner] Saving", and when completing the transfer it should slide out downwards.

When changing the content of the button, don't change its size of and always center align its content.

Please unbind ctrl+u, ctrl+i and ctrl+o and clean up related unused code.

I've also observed that when I transfer the config using ctrl+o, then make another keymap default, the configuration automatically transferred. Please make sure that the config never gets automatically transferred.

**Comment by ert78gb** [comment]
> When changing the content of the button, don't change its size

What is the maximum with of the button?

**Comment by mondalaci** [comment]
The maximum width of the button is the width that is necessary to hold the "Save to keyboard" text. The "[spinner] Saving" text will be narrower than that, so the button should keep its width.
