### ISSUE TITLE
Automatic testing of the serializer

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#38]
It'd make a lot of sense to implement automated testing for the serializer. I was thinking about using Travis CI for this purpose. `test-serializer.js` is supposed to be executed without any errors on every commit.

Similarly, `test-assertions.ts` could also be created to check every assertion for valid and invalid values. The script should return with success if every valid value is accepted, and if exceptions are thrown for every invalid value.

**Comment by fjozsef** [comment]
@mondalaci Please check [this](https://travis-ci.org/UltimateHackingKeyboard/agent) and close this issue if it satisfies your needs.

**Comment by mondalaci** [comment]
@fjozsef Yep, looks good to me. Thanks for the great work!
