### ISSUE TITLE
Change the wording of macro key actions

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#385]
Eric, as a native English speaker told me that the verbs that we use for macro key actions are rather ambiguous. His suggestions are:

* "hold" should be renamed to "press"
* "press" should be renamed to "tap"
* (release remains unchanged)

These changes should be carried out across the codebase (class names, JSON properties, etc.) and the macro UI.

**Comment by ert78gb** [comment]
I am waiting with this issue until merge #462 SecondaryRoleAction PR

**Comment by eltang** [comment]
I just realized that the mouse macro action also has a hold action which should be renamed to press as well.
