### ISSUE TITLE
Device node

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#388]
I'd like to have a top-level device node in the side menu:

![agent-usb](https://user-images.githubusercontent.com/300402/29363297-b9297192-828f-11e7-9f2a-bf46d3d3eae0.png)

Agent will eventually be able to handle multiple devices and display top-level device nodes accordingly, but this is only a static node for the time being.

Clicking on the gear icon of the device node should jump to a device-specific settings page that should contain some standard "Device settings..." content for now.

I've just added the `images/icons/0401-usb-stick.svg` icons to the master branch which should be used for the device node. The icon is oriented upwards by default so please rotate it 90 degrees clockwise the Font Awesome way.

**Comment by attilacsanyi** [comment]
Hi @fjozsef @ert78gb . Any idea how to reference a custom svg under root `/images/icons` in font awesome (this icon needed for both web and electron)?

So far I had no luck with that, imho `uhk-web` can just reference `url(...)`s from scss which is under `packages/uhk-web/assets` based on the cli, right?.

Thanks for any guide.

**Comment by ert78gb** [comment]
move /images/icons -> uhh-web/src/svgs
`npm run sprites` generate a sprite from `uhh-web/src/svgs` -> `uhh-web/src/app/assets/compiled_sprite.svg`
 currently generate only the svg sprite but you could configure to generate css or scss file check https://github.com/jkphl/svg-sprite

**Comment by attilacsanyi** [comment]
Thanks @ert78gb so after generating the new sprites I can reference in `scss` like this:
`...url(/assets/compiled_sprite.svg#<icon-name>)` ?

No option for using from font awesome, right?

**Comment by ert78gb** [comment]
you could use url(/assets/compiled_sprite.svg#<icon-name>) , but not lucky because the new sprite generation maybe overwrite the sprite position. svg-sprite could generate scss file same as font-awsome 

font-awsome configured and used in the project search "fa fa-" in the project. The usb icon in font-awesome different then Laci suggests, but 2 of you should discuss it :)

**Comment by mondalaci** [comment]
I insist to the icon I provided. :)

If it's not possible to make it work with our generated SVG sprite then let's reference it separately for the time being.

**Comment by attilacsanyi** [comment]
Just use as a separate icon under `uhk-web/assets` for now, prepare PR soon @mondalaci

**Comment by mondalaci** [comment]
Done in #397.
