### ISSUE TITLE
Out of screen empty undo notification

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#391]
I've noticed that the horizontal scrollbar is present, so I scrolled rightwards, then noticed that there's an empty undo notification there.

![untitled](https://user-images.githubusercontent.com/300402/29495447-bef1805a-85bf-11e7-89e8-9dfedbc69c07.png)

**Comment by ert78gb** [comment]
Do you know the reason what is the big space under the keyboard image ?

**Comment by mondalaci** [comment]
Yes, that's because when a bottom key is clicked, the key action popover gets opened which needs the extra space. The macro tab of the popover consumes the most space vertically. We investigated a couple of solutions and all things considered this was the best of all.
