### ISSUE TITLE
Error when trying to build Agent on Fedora 26

### ISSUE THREAD

**Issue by viktormadarasz** [UltimateHackingKeyboard/agent#393]
trying to do npm run build:electron 

[npm-debug.zip](https://github.com/UltimateHackingKeyboard/agent/files/1252511/npm-debug.zip)
gives me error: ( added the log file mentioned on the end of the message)

https://paste.fedoraproject.org/paste/VIIiroray~r7H4N-RAZmkw

on Fedora 26. my -sysinfo is below:

https://paste.fedoraproject.org/paste/qZrDBHhnagcTVfG87-viwg

**Comment by ert78gb** [comment]
try to build with node >= 8.3.0 version

**Comment by viktormadarasz** [comment]
Thanks

nodejs 8.3 is at the moment not on the f26 stream let me try in rawhide ( it does show up in f27)

**Comment by ert78gb** [comment]
I am not familiar with Fedora, but why do not you use https://github.com/creationix/nvm

**Comment by viktormadarasz** [comment]
I learn something new everyday let me try it

**Comment by viktormadarasz** [comment]
using nvm and activating version 8.4.0 getting these errors now ( attached the new logfile)

https://paste.fedoraproject.org/paste/NAKtSNWuUBmWyYKWRXV8Uw

[2017-08-25T19_50_01_054Z-debug.zip](https://github.com/UltimateHackingKeyboard/agent/files/1252864/2017-08-25T19_50_01_054Z-debug.zip)

**Comment by ert78gb** [comment]
NVM installed and activated the 8.4.0 node version.
You used 6.x node version earlier when install application dependencies with npm i. The application dependencies contains a special native binaries thats not compatibles with the node 8.x version
Follow the following steps
- npm run clean // delete all node_modules and other temporary folders
- npm i // install dependencies for node 8.4
- npm run build:electron // build the electron version
- npm run electron // start the electron app

**Comment by viktormadarasz** [comment]
ert78gb:

npm run clean - completes Ok, 

running npm i  gives me the below error

https://paste.fedoraproject.org/paste/~T3xj9clS5jf36he~nEVrg
[2017-08-25T20_07_48_252Z-debug.zip](https://github.com/UltimateHackingKeyboard/agent/files/1252901/2017-08-25T20_07_48_252Z-debug.zip)

**Comment by ert78gb** [comment]
:) The libusb dev dependencies missing from your machine try: `dnf install libusb-devel`

**Comment by viktormadarasz** [comment]
still failing... i will get back to it tomorrow with a fresh mind i guess..

**Comment by viktormadarasz** [comment]
deleted all the cloned agent folder and npm and node too , reinstalled it all.. still fails ( even tried as root)

**Comment by mondalaci** [comment]
@viktormadarasz Please always specify the exact error, otherwise we're unable to help you. What's the error now?

**Comment by viktormadarasz** [comment]
Hi @mondalaci 

this is what i get with npm install

https://paste.fedoraproject.org/paste/wgSxBgffw5veOZ7wHJwdlA
[2017-08-26T11_23_36_581Z-debug.zip](https://github.com/UltimateHackingKeyboard/agent/files/1253622/2017-08-26T11_23_36_581Z-debug.zip)

**Comment by mondalaci** [comment]
Thanks! This seems to be the culprit:

```
fatal error: libudev.h: No such file or directory\n #include <libudev.h>
```

Please install the `libudev-dev` package (might be differently named on Fedora) and retry.

**Comment by viktormadarasz** [comment]
@mondalaci 
Thanks. It builds and works now

its the systemd-devel package on fedora

Hope this tread can serve as some common issues other users can come across while building the tool on Fedora

Regards

Viktor
