### ISSUE TITLE
Resolve circular dependencies

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#396]
Although it's not a show-stopper, it'd be nice to eventually resolve the circular dependency build warnings.

**Comment by attilacsanyi** [comment]
That was my first try to resolve, but it seems trickier than I thought :) Will do another try later @mondalaci

**Comment by mondalaci** [comment]
When rebuilding Agent, I can't see any circular dependency warnings anymore. Have any of you fixed this issue in the meantime, guys? I'd like to confirm that it's fixed and shouldn't resurface anymore. If so, I'll close the issue.

**Comment by ert78gb** [comment]
I did nothing, but will check I got or not warnings

**Comment by mondalaci** [comment]
@ert78gb I cannot see any circular dependency related warnings during the build process. Can you confirm it?

**Comment by ert78gb** [comment]
I still see warnings

**Comment by mondalaci** [comment]
Ah, never mind. Let's take care of it later.
