### ISSUE TITLE
Lock package-lock.json files

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#406]
So that they won't keep changing, and it'll make sure that our build won't break due to changed external dependencies.

**Comment by ert78gb** [comment]
Solved in #378

**Comment by ert78gb** [comment]
related to: https://github.com/lerna/lerna/issues/913

**Comment by mondalaci** [comment]
Related issues:
* https://github.com/npm/npm/issues/17722
* https://github.com/npm/npm/issues/18202
* https://github.com/yarnpkg/yarn/issues/2437

**Comment by mondalaci** [comment]
This cannot be fixed yet due to OS-specific packages. Let's revisit it later when resolved by npm or yarn.

**Comment by mondalaci** [comment]
Looks like this has been resolved by the recent npm update.

**Comment by mondalaci** [comment]
Unfortunately, the issue regarding OS-specific packages still stands.

**Comment by ert78gb** [comment]
did you upgraded your npm to 5.6.0?

**Comment by mondalaci** [comment]
I haven't encountered with this for a while, so I think that a recent npm upgrade solved this.
