### ISSUE TITLE
Build fails with or without libusb-dev

### ISSUE THREAD

**Issue by TorC8** [UltimateHackingKeyboard/agent#407]
Very similar to #405.  Initial view looks the same to me.

Attached is error with libusb-dev installed.

[170906-2install.txt](https://github.com/UltimateHackingKeyboard/agent/files/1282525/170906-2install.txt)

**Comment by mondalaci** [comment]
Yep, you're right. Even though now we're using hidapi instead of libusb, hidapi apparently uses libusb on Linux, so it's still needed. Please `apt-get install libusb-dev` and retry.

**Comment by TorC8** [comment]
Still missing something.  I had already tried installing libusb-dev.
Based on what you said about using hidapi, I installed libhidapi-dev,
and got the same fatal error at the same "../hidai/libusb/hid.c:42:20"

**Comment by mondalaci** [comment]
Please always include the whole build log, including this case. Only then I can help you.

**Comment by TorC8** [comment]
Sorry.  Here it is.  
[170906-3install.txt](https://github.com/UltimateHackingKeyboard/agent/files/1282790/170906-3install.txt)

**Comment by mondalaci** [comment]
Thanks! This seems to be the culprit:

```
lerna ERR! execute ../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
lerna ERR! execute  #include <libusb.h>
```

This still seems like a libusb-dev related error. You said that you tried to install libusb-dev. Did you actually install it? If not, what was the exact problem?

**Comment by TorC8** [comment]
Yes, installed without apparent error:

$ aptitude show libusb-dev 
Package: libusb-dev                      
Version: 2:0.1.12-30
State: installed
Automatically installed: no
Priority: optional
Section: libdevel
Maintainer: Aurelien Jarno <aurel32@debian.org>
Architecture: amd64
Uncompressed Size: 232 k
Depends: libusb-0.1-4 (= 2:0.1.12-30), libc6-dev | libc-dev
Description: userspace USB programming library development files
 Library for programming USB applications without the knowledge of Linux kernel internals. 
 
 This package contains what you need for compiling sources that use this library in your own code.
Homepage: http://www.linux-usb.org/
Tags: devel::library, role::devel-lib

**Comment by mondalaci** [comment]
Well, this is a tricky one then. Is the `libusb.h` header file present on your system? For example, I have it at `/usr/include/libusb-1.0/libusb.h`. Please search for it and let me know where it is. If it's not available then `libusb-dev` isn't properly installed on your system.

**Comment by TorC8** [comment]
Thinking out loud here if I post this...
libusb.h is missing...
libusb-dev version is 2:0.1.12-30
There also exists the package libusb-1.0-0-dev
OK, install libusb-1.0-0-dev
Now I have libusb.h, and I get a new build failure.  At least now we're getting somewhere.

Looks like you may need to add libusb-1.0-0-dev to the at least Debian Stretch dependencies.
[170906-4install.txt](https://github.com/UltimateHackingKeyboard/agent/files/1283059/170906-4install.txt)

**Comment by mondalaci** [comment]
```
g++: Command not found
```

I think you need to `apt-get install g++` or some related package.

**Comment by TorC8** [comment]
Well, I missed that error, even after looking again before you got to it.  That was the issue there.  Installed (apparently) fine, then the "npm run build:electron" appeared to work with only some deprecated warnings.  Failed at "npm run electron".

Tried again with a clean clone of agent; got similar warnings and a failed build.  Error indicated missing libudev-dev.  Installed libudev-dev and tried again with a clean build.

This time it worked, and I get a helpful window for Agent that tells me it can't find my UHK and to please plug it in.  No apparent options to say that, no I don't have one yet, and to please let me play with Agent anyway.

Known dependencies from this issue that are not (AFAICT so far) in a default install for Debian Stretch:
libusb-1.0-0-dev
g++
libudev-dev

I'll attach or email you the deprecated warnings I got from the successful install if they are useful to you.

**Comment by mondalaci** [comment]
Thanks for the package list! I've updated the readme accordingly.

The build warnings are only relevant to us if they're directly caused by Agent and not external libraries. In the former case, they're most welcome.

If you want to play around with Agent please use the web build. The "plug in your UHK" opening screen of the electron build is very much intentional and it should work great usability-wise, so we don't plan to change it.

**Comment by TorC8** [comment]
Glad I could provide some help here.  I should note that I'm not clear whether libhidapi-dev was needed or not, so I didn't include it in the list.  Maybe later I'll try a clean install in a VM and nail down the dependency list.

Looks like all the warnings are related to HID.cc

Nice work!

**Comment by TorC8** [comment]
P.S. My first thought is that if Agent can save layouts to files, an option to say "I know there isn't a UHK here; open anyway" would be worthwhile, however I reserve judgement until actually getting to use it in action.

**Comment by mondalaci** [comment]
Thanks for the idea! We'll think about it.
