### ISSUE TITLE
Fix save config and add UI for it

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#416]
On the "Device settings..." page:
* Instead of the "Device settings..." title write "Device settings" (without the "...").
* Add button titled "Save device JSON configuration" and assign the functionality of Alt+j
* Add button titled "Save device binary configuration" and assign the functionality of Alt+b
* Remove the Alt+j and Alt+b bindings.

**Comment by mondalaci** [comment]
@ert78gb Please note that I've edited this issue and made it much simpler.

**Comment by ert78gb** [comment]
What will be the button style?

**Comment by mondalaci** [comment]
Regular bootstrap buttons.
