### ISSUE TITLE
Layer switcher key behavior on non-base layers

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#419]
I'd like Agent to behave according to the following:

1. If a layer-switcher key gets assigned on the base layer (layer switcher keys can only be assigned on the base layer) then also assign the layer switcher key on its own layer. For example, the user maps a key on a base layer to Mod. Then the same key on the Mod layer should also be assigned to Mod.

2. Don't allow the user to reassign layer switcher keys on non-base layers. According to the above example, don't allow the reassignment of the Mod key on the Mod layer. Make the popover only contain the "Reassignment of a layer switcher key is not possible on its own layer. You can only change it on the base layer." text and a Close button.

3. When changing a layer switcher key (which can only happen on the base layer) to a non-layer switcher key, make the key on its own layer unassigned.

**Comment by ert78gb** [comment]
Thats mean if any key action assigned on non base layer and the user create a layer switch action then the key action will override without any notification on the non base layer. Am I right?

**Comment by mondalaci** [comment]
The key action should only overwrite the base layer and its own layer (without any notification). For example, let's say that you map scancode "A" to Mod. then Mod gets assigned to the base layer and to the Mod layer. The other layers are unchanged.

It's an special case when a layer switcher key is changed to another layer switcher key. For example let's say that Mod gets changed to Fn. In this case, the base layer changes from Mod to Fn, the key on the Mod layer gets unassigned, the key on the Fn layer gets assigned to Fn.
