### ISSUE TITLE
Migrate font icons to SVG.

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#42]
Font Awesome uses font icons whose quality is [not great](https://css-tricks.com/icon-fonts-vs-svg/).

We purchased the [IcoMoon Ultimate Font Pack](https://icomoon.io/preview-ultimate.html) and we're about to migrate to it and remove Font Awesome from the project. Going forward, Font Awesome should not be used.

According to our license, we're not permitted to upload every IcoMoon Ultimate font to the repo but we can upload the icons that are needed. Contributors, please let us know which IcoMoon Ultimate font you need and we'll add it to the repo.

Here's a non-complete list of font icons to be migrated:
- [ ] layer
- [ ] none action
- [ ] trash
- [ ] pencil (macro edit action)
- [ ] star
- [ ] cog

In the meantime, we've also purchased Font Awesome 5 Pro, so let's wait until it's released and then migrate to it.

**Comment by NejcZdovc** [comment]
@mondalaci this is still something that need's to be done right?

**Comment by mondalaci** [comment]
@NejcZdovc Correct.

**Comment by mondalaci** [comment]
Replace the current Font Awesome 4 font icons with Font Awesome 5 SVG icons according to the following rules:

1. Almost always, the icon name stays the same. Use the solid version of the icons.
2. Remove the `-o` part when the icon name ends in it. Please note that for the star icon, the solid icon version must be used for enabled state and the regular version for disabled state.
3. The following icons must be renamed:

* gear -> cog
* sliders -> sliders-h
* files-o -> copy

4. Replace glyphicons with the following Font Awesome 5 SVG icons:

* glyphicon-trash -> trash
* glyphicon-option-vertical -> grip-vertical
* glyphicon-pencil -> pen
