### ISSUE TITLE
Macro list not visible after adding new macro action

### ISSUE THREAD

**Issue by attilacsanyi** [UltimateHackingKeyboard/agent#425]
Try to add new macro action, the you can expect that the existing macro list is going to be hidden by something.

I tried to solve this in several ways, but no luck. Reverted back the last 21 changes and the error is still exists. I remember that it was working when I was implemented the macro validation feature.

Please look into this @ert78gb perhaps you have a better idea what cause this wrong behaviour.
This is a blocker for my issue 324.

Could you please test this @mondalaci, thanks.

Thanks in advance.

**Comment by mondalaci** [comment]
I can confirm the issue, and have no idea what is causing it. If the fix is not trivial, it would be worth to `git bisect` this to figure out when it went wrong.

@attilacsanyi You meant macro actions, not macros. I edited the issue accordingly.

**Comment by attilacsanyi** [comment]
Something related to `npm` locked dependencies in the `package.lock.json`. Removing it and re-run install solved the issue. Continue the investigation.

**Comment by mondalaci** [comment]
Resolved by #426
