### ISSUE TITLE
Add userConfigurationLength field

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#428]
Add a uint16 `userConfigurationLength` field to the UserConfiguration item right after the dataModelVersion field. `userConfigurationLength` should contain the actual length of the user configuration, including this field, and `dataModelVersion`.

This will require a firmware change which I'll implement.

**Comment by ert78gb** [comment]
Could you describe more specified spec? Example message of the 100 byte data
- [0] =  8 - upload user config command
- [1] = 0  -
- [2] = 100 - length of the data.
- [3] ... [103] - data
- [104][105] - CRC value

**Comment by mondalaci** [comment]
Let's say that the user configuration is 1000 bytes long.

Then prefix the user configuration with the length, which takes 2 bytes.

And postfix the user configuration with the CRC value with takes another 2 bytes.

The resulting user configuration is 1004 bytes long. Then you have to transfer this 1004 bytes long user configuration in chunks with the upload user config USB command.

**Comment by mondalaci** [comment]
Please note that I've changed this issue. No need to postfix the user configuration with the CRC, just prefix it with its length.

**Comment by mondalaci** [comment]
I have changed this issue yet another time. No further changes are expected. I think.

**Comment by mondalaci** [comment]
Done by #486.
