### ISSUE TITLE
Routing animation fixes

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#432]
1. When starting up Agent-electron without the UHK plugged in, it first momentarily displays the main application screen with the keyboard, then transitions to the "UHK not found" screen. Please don't show the main application screen in this case, not even for a moment. Always show the relevant screen immediately.

2. Animations are used when switching routes. For example, when switching from a macro to to a keymap the keyboard slides in from the left slide. Let's not use animations in such cases at all.

**Comment by ert78gb** [comment]
@mondalaci I think the 1. issue is solved earlier. Could you test it is still an issue or not?
Would you like to remove the routing animation at the app start too?

**Comment by mondalaci** [comment]
Yes, I believe that first issue is solved, indeed.

Yes, please remove the routing animation at the app start, too.
