### ISSUE TITLE
Macro UI fix

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#438]
When editing a macro often times the macro actions totally collapse. It seems like there are no macro actions in a macro that clearly contains macro actions. Please try to edit a macro to reproduce it. If necessary, I can write steps to reproduce.

**Comment by ert78gb** [comment]
Could you write reproduce steps?

**Comment by mondalaci** [comment]
1. Add a new macro.
2. Add a new macro action for the new macro. Let's make it a text action with the text "asdf".
3. Save the new macro action.
4. At this point, the macro looks empty.
