### ISSUE TITLE
Display/hide left keyboard half and merged/unmerged state according to keyboard state

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#450]
First of all, please check out the usb/read-keyboard-state.js script to see how to query the relevant states. This state should be queried 4 times per second for a smooth user experience. Please only query this state when not writing or reading the user configuration.

Let's display the actual merged/split state of the keyboard and animate it accordingly.

Let's also fade/unfade the left keyboard half depending on whether it's connected.

**Comment by ert78gb** [comment]
I could not find ` usb/read-keyboard-state.js` do you think to `packages/usb/get-device-state.js`?

**Comment by mondalaci** [comment]
@ert78gb Yes, exactly. Sorry about that.
