### ISSUE TITLE
Add mouse speed page

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#458]
Create a new page titled "Mouse speed". Use the fa-slider icon before its title, and redirect to it upon clicking the Device -> Mouse speed menu item.

This page features a lot of sliders. Please use [ng2-nouislider](http://tb.github.io/ng2-nouislider/) for all the sliders. Make the slider tooltip always show. If possible, show the unit of the value (for example px/s²) in the tooltip, for example "8 px/s²". If it's not possible easily, then just display the unit as described below, for example "Acceleration (px/s²): above the individual sliders". Make the sliders occupy the whole width available. Make the range show below every slider.

The page should contain the following content:

> The following options affect the speed of the mouse when being controlled by mouse keys.
>
> Mouse pointer speed
>
> Initial speed (px/s):
> [slider]
> Acceleration (px/s²):
> [slider]
> Decelerated speed (px/s):
> [slider]
> Base speed (px/s):
> [slider]
> Accelerated speed (px/s):
> [slider]
>
> Mouse scroll speed
>
> Initial speed (pulse/s):
> [slider]
> Acceleration (pulse/s²):
> [slider]
> Decelerated speed (pulse/s):
> [slider]
> Base speed (pulse/s):
> [slider]
> Accelerated speed (pulse/s):
> [slider]

The actual values of the user configuration are uint8 types, and each value can be 1-255. (0 is not allowed.)

Use a 25x multiplier for displaying move ranges, so they should show 25 as the minimum and 6375 as the maximum.

Use a 1x multiplier for displaying scroll ranges, so they should show 1 as the minimum and 255 as the maximum.

Use the following properties of UserConfiguration:

* mouseMoveInitialSpeed
* mouseMoveAcceleration
* mouseMoveDeceleratedSpeed
* mouseMoveBaseSpeed
* mouseMoveAcceleratedSpeed

* mouseScrollInitialSpeed
* mouseScrollAcceleration
* mouseScrollDeceleratedSpeed
* mouseScrollBaseSpeed
* mouseScrollAcceleratedSpeed

**Comment by richrd** [comment]
Hi! I'm curious to why `ng2-nouislider` should specifically be used? Not against it but just wondering, since html5 already has input `type="range`.

Another question: are there any issues that I could volunteer to work on?
As I've ordered a UHK and I have Angular 2/4 experience this would be a fun project to contribute to.

Thanks!

**Comment by mondalaci** [comment]
@richrd Hi there! I think `ng2-nouislider` has some beneficial features usability-wise, such as the tooltips, and pips. Being Angular-compatible is also a benefit.

What I don't like about it is its bulkiness. I'm wondering how hard it is to customize it visually. I much better like the aesthetics of http://simeydotme.github.io/jQuery-ui-Slider-Pips/ and it seems to offer the same features.

This issue would be an excellent place to start. Thank you so much for your support, and for considering to contribute!

**Comment by mondalaci** [comment]
To reiterate, I think it'd make sense to use `ng2-nouislider` due to its features and native Angular support, and my hope is that we'll be able to easily tweak its look to better resemble `jQuery-ui-Slider-Pips`.

**Comment by mondalaci** [comment]
@richrd As things are standing now, I'm not sure if this issue is the best place to start because @laxu is making heavy progress with #520 which is extremely similar to this issue. It'd be worth to wait until he finishes with that one, and either chooses to do this too, or simply use his work as a basis to create this.

Luckily, alternative issues are plentiful. For example, #483 is probably an easy one to start with, but I really don't have a strong preference. It's probably a better strategy to pick whichever is most interesting to you.

**Comment by laxu** [comment]
Yeah I can do at least the UI for the mouse speed page pretty quickly when I get the LED brightness done.

**Comment by mondalaci** [comment]
So glad to hear! Actually, I'd be fine if you implemented this one in #520, too. They're awfully similar both from a frontend and backend standpoint.

**Comment by laxu** [comment]
I made the Mouse speed page with mostly copy paste from the LED brightness page. Looks like this:
![uhk-mousespeedpage](https://user-images.githubusercontent.com/987972/34364194-20ae79d4-ea8c-11e7-9818-8fdaccc6e3c0.PNG)

I got a question though. Should the values for mouse _move_ coming from the configuration be multiplied by 25 and when saved back to configuration divided by the same number? Just want to make sure I understood the task correctly.

**Comment by mondalaci** [comment]
@laxu Wow, you're on a roll!

The answer to your question is yes.

Based on your screenshot, almost evereything is spot on, except for the unit of mouse scroll initial speed which should be pulse/s.

**Comment by laxu** [comment]
Thanks for the reply! I think the settings available on this page are pretty hard to understand so could you add some short descriptions that could be added in a question mark tooltip next to the label? For example at what point the different accelerations and decelerations apply. Also maybe either a "reset to default" button or just listing the default value would be useful if someone goes messing with these and wants to return back to the stock options.

**Comment by mondalaci** [comment]
Excellent ideas!

Can you add a "Reset mouse speeds" button to the bottom of the page and make it set [the default values](https://github.com/UltimateHackingKeyboard/agent/blob/master/packages/uhk-web/src/app/services/user-config.json#L10-L19)?

Tooltip descriptions:

Initial speed: When mouse {movement/scrolling} begins, this is the starting speed.
Acceleration: The rate of acceleration from the initial {movement/scrolling} speed to the base speed.
Decelerated speed: This speed is used while {moving/scrolling} with the decelerate key pressed.
Base speed: This speed is reached after the initial {moving/scrolling} speed sufficiently ramps up.
Accelerated speed: This speed is used while {moving/scrolling} with the accelerate key pressed.

**Comment by mondalaci** [comment]
Resolved by #537.
