### ISSUE TITLE
Revamp the Add new keymap page

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#459]
Please implement the following mockup:

![untitled](https://user-images.githubusercontent.com/300402/31729852-8d2d3db2-b430-11e7-831b-c43f45ca129a.png)

Upon clicking on the add keymap (+) button, make the inner side menu slide in. (By default, don't select an available keymap.) Make the empty state of the page "Select an available keymap to view it."

When selecting a keymap of the available keymaps, display it as shown on the mockup. Don't allow to edit the key actions, only display them upon hover in a tooltip, just as they behave on the Add Keymap UI now. The top "Add keymap" button should add the keymap to the user configuration, then redirect to it, and close the inner side menu.

When clicking on a menu item of the outer side menu, close (slide back) the inner side menu. In this case, the Add Keymap operation gets cancelled.

The background color of the inner side menu is intentionally #fafafa (instead of the background color of the outer side menu which is #f5f5f5).

Use the keymaps of the default configuration as presets to be added.

**Comment by IzK666** [comment]
I've made a small website to create blank keymaps and copy layers.
You can [run here](https://izk666.github.io/UHK-Viewer/) or view the [code on github](https://github.com/IzK666/UHK-Viewer)

**Comment by mondalaci** [comment]
@IzK666 Thank you so much! I've just tested your webapp, and it's very well done.
