### ISSUE TITLE
JSON Schema for uhk config file

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#46]
The UHK configuration can be represented as a JSON. Despite the fact that this configuration file will be edited by the agent and it will generate correct syntax we could validate it via [JSON Schema](http://json-schema.org/).

JSON Schema is also supported by Visual Studio Code so it would also helpful having it when we would like to manually create our configuration.

[Very initial version](https://github.com/UltimateHackingKeyboard/agent/commit/a5b477155cec7515e3de09c51672797fadcff301)

**Comment by NejcZdovc** [comment]
@fjozsef what is the status on this issue?

**Comment by fjozsef** [comment]
We only have an initial schema, it was on low priority for me.

**Comment by mondalaci** [comment]
@fjozsef Do you actually see a use of this issue? If your answer is no, I'd rather delete this issue and the out-of-date schema file. (Is our schema file actually out of date?)

I think that manual editing is so rare that the long-term mainteance of the schema is not justified. It's another story if we actually use it for programmatic validation. Although I believe feeding the json to the serializer should be sufficient programmatic validation.

**Comment by fjozsef** [comment]
It is hard to tell. It would be definitely be useful if it would be ready, but because of the low priority the main developer(s) will never focus on this. However it could be still created by a contributor who wants to help.

**Comment by mondalaci** [comment]
Thanks for your reply! Given your answer, and the fact that the ongoing maintenance of the schema would be laborious, I'm gonna remove the schema and close this issue.
