### ISSUE TITLE
Reset configuration only temporarily resets config in Agent-web

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#476]
Instead of persisting it to local storage.

**Comment by ert78gb** [comment]
@mondalaci Would you like the store in the web module or would you like to apply the reseted user config to the device is running the electron agent? Same #447

**Comment by mondalaci** [comment]
I'd like both Agent-electron and Agent-web to implement both issues. Eventually, we'll implement WebUSB support, so Agent-web will be a useful application, not just a demo.
