### ISSUE TITLE
Macro UI tweaks

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#478]
For macro key actions, currently "Tap/Press/Release key: S leftShift leftGui" is displayed in the title of the macro action.
* Display the modifiers first.
* Put " + " strings between them.
* According to #442, display Command, Windows, or Super depending on the OS instead of leftGui/rightGui. Also display Command and Return instead of Alt and Enter respectively for Mac.
* Display LShift instead of leftShift, and so on.
* So the above example should look: "LShift + LSuper + S" on Linux.

I've noticed another minor issue. On the "Move pointer" and "Scroll" panes, When I click on the "X:" and "Y:" labels,  the mouse correctly jump to the relevant input field except for scroll X. The pointer icon is also different for this than for the rest. Please fix this, too.

**Comment by owlstead** [comment]
Just browsing through the issues, it seems to me that as #442 is closed this issue should not be blocked anymore.
