### ISSUE TITLE
Popover mouse tab speed action 

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#49]
Use large icons and show text "accelerate" "decelerate" below them in smaller font.

Always show a help text below the button group saying something:

> Press this key along with mouse movement/scrolling to accelerate/decelerate the speed of the action.
> You can set the multiplier in [link_to_settings].

**Comment by csanyiarpad** [comment]
[-] Decelerate | [+] Accelerate
button group solution

**Comment by NejcZdovc** [comment]
@mondalaci is this still relevant?

**Comment by mondalaci** [comment]
@NejcZdovc Yes, it is. It'd be worth to change the text to:

Press this key along with mouse movement/scrolling to adjust speed.
You can set the speed multiplier in [settings].

Settings should be linked properly.

The Accelerate / Decelerate texts should be added to the buttons.

**Comment by NejcZdovc** [comment]
What would be a link to the settings? You mean http://localhost:8080/#/settings ?

**Comment by mondalaci** [comment]
@NejcZdovc Yes, exactly.
