### ISSUE TITLE
Keyboard USB interface not working on Windows 7 when Agent is running

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#494]
I've been testing the UHK on Windows 7 Ultimate, Service Pack 1, 32 bit, and have some findings.

When Agent is **not** running, and I plug in the UHK, both the keyboard and mouse functionality works as expected.

Unfortunately, when Agent is running and I plug in the UHK, the keyboard + mouse functionality very rarely works. Most of the time, I can mouse with the UHK, but the keyboard doesn't work. Rarely, only the keyboard functionality works, but mouse doesn't. Sometimes, neither the mouse nor the keyboard works. Very rarely, it actually works.

@ert78gb Can you try to reproduce this? It'd be great to test it on both Windows 7 and Windows 10, and also on OSX.

**Comment by ert78gb** [comment]
Every time works fine on Mac. I will try it on Win 7

**Comment by mondalaci** [comment]
This is likely caused by https://github.com/UltimateHackingKeyboard/firmware/issues/68

When using older firmwares this issue totally blocked keyboard input, but starting from firmware 5.0.1 it only blocks mouse actions.

**Comment by mondalaci** [comment]
Retested this with firmware 8.0.0 and Windows {7,8,10} and only Windows 7 seems to be affected. When Agent is running on Windows 7 only the mouse interface of the UHK works.

**Comment by mondalaci** [comment]
This looks like a firmware issue, so closing this one in favor of https://github.com/UltimateHackingKeyboard/firmware/issues/73
