### ISSUE TITLE
PostCSS migration

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#5]
First up, we should figure out which [PostCSS plugins](https://github.com/postcss/postcss/blob/master/docs/plugins.md) to use. We definitely need nesting and variables, preferably in a future-proof manner. I've heard that CSS is supposed to support variables natively in the future, but I'm not sure about nesting.

**Comment by mondalaci** [comment]
Imports would also come handy. We could include every stylesheet from a single main file that way.

**Comment by csanyiarpad** [comment]
Reopened this issues as this was closed by mistake by a fault commit message.

**Comment by mondalaci** [comment]
Just looked into the PostCSS plugins and concluded that we may be better off using LESS for the time being. Let's talk about this sometime.

**Comment by csanyiarpad** [comment]
I wanted to recommend some other solution than PostCSS, but before I could do so I wanted to look after PostCSS, as I never used it, and I want to see the pros and cons to choose the best. But if you are considering LESS, then I'm suggesting to talk about LESS vs SASS vs Stylus.
(_With the previous two I'm having deeper experience, and at the moment I'm having a project with Stylus._)

**Comment by csanyiarpad** [comment]
As we have discussed earlier, we will use SASS with the SCSS syntax (as Bootstrap is using that syntax as well, and we want to keep things easy and consistent across the project).

**Comment by csanyiarpad** [comment]
cb1f61b6b655d700389d82930cf6b1c0386d9b74 mainly resolves this issue, but I'll want to make some refactoring on the app.scss file, before marking this issues fixed.
