### ISSUE TITLE
Make Serializable interface more consistent

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#51]
Currently, the signature of `Serializable._fromJsObject(jsObject: any): T` and `Serializable._fromBinary(buffer: UhkBuffer): T` are consistent as they both expect the source of the operation and return the result.

This is unlike `Serializable._toJsObject(): any` and `_toBinary(buffer: UhkBuffer): void`. Ideally, `_toBinary` should also return a `UhkBuffer` which would make the API more consistent.

Instead of this:

``` typescript
    _fromBinary(buffer: UhkBuffer): UhkConfiguration {
        this.signature = buffer.readString();
        this.dataModelVersion = buffer.readUInt8();
        this.prologue = buffer.readUInt32();
        this.hardwareId = buffer.readUInt8();
        this.brandId = buffer.readUInt8();
        this.moduleConfigurations = new ModuleConfigurations().fromBinary(buffer);
        this.keyMaps = new KeyMaps().fromBinary(buffer);
        this.macros = new Macros().fromBinary(buffer);
        this.epilogue = buffer.readUInt32();
        return this;
    }
```

I am proposing this:

``` typescript
    _fromUhkBuffer(buffer: UhkBuffer): UhkConfiguration {
        this.signature = String.fromUhkBuffer(buffer);
        this.dataModelVersion = UInt8.fromUhkBuffer(buffer);
        this.prologue = UInt32.fromUhkBuffer(buffer);
        this.hardwareId = UInt8.fromUhkBuffer(buffer);
        this.brandId = UInt8.fromUhkBuffer(buffer);
        this.moduleConfigurations = new ModuleConfigurations().fromUhkBuffer(buffer);
        this.keyMaps = new KeyMaps().fromUhkBuffer(buffer);
        this.macros = new Macros().fromUhkBuffer(buffer);
        this.epilogue = UInt32.fromUhkBuffer(buffer);
        return this;
    }
```

Using `fromBuffer()` calls everywhere should increase consistency. Unlike for compound classes, classes for primitive classes should not be `new`'ed, but static methods should be used.

And instead of this:

``` typescript
    _toBinary(buffer: UhkBuffer): void {
        buffer.writeString(this.signature);
        buffer.writeUInt8(this.dataModelVersion);
        buffer.writeUInt32(this.prologue);
        buffer.writeUInt8(this.hardwareId);
        buffer.writeUInt8(this.brandId);
        this.moduleConfigurations.toBinary(buffer);
        this.keyMaps.toBinary(buffer);
        this.macros.toBinary(buffer);
        buffer.writeUInt32(this.epilogue);
    }
```

I am proposing this:

``` typescript
    _toUhkBuffer(): UhkBuffer {
        return new UhkBuffer([
            String.toUhkBuffer(this.signature),
            UInt8.toUhkBuffer(this.dataModelVersion),
            UInt32.toUhkBuffer(this.prologue),
            UInt8.toUhkBuffer(this.hardwareId),
            UInt8.toUhkBuffer(this.brandId),
            this.moduleConfigurations.toUhkBuffer(),
            this.keyMaps.toUhkBuffer(),
            this.macros.toUhkBuffer(),
            UInt32.toUhkBuffer(this.epilogue)
        ]);
    }
```

The new `UhkBuffer` constructor is supposed to concatenate the specified buffers to a larger buffer.

**Comment by mondalaci** [comment]
I think it's a definite improvement but I'm interested in your opinion, Sam. No other major refactorings are expected beyond this one.

**Comment by srang** [comment]
I think this makes sense. One of the nice things about having all of the read commands in UhkBuffer was that it keeps things centralized. Based on you're idea, I'll create a `primitive-items` folder which will have the classes with the static primitive `fromUhkBuffer` functions, and rename `config-items` to `compound-items`. We will also need a UhkBuffer that takes an array of UhkBuffers argument.
We also talked a while back about how UhkBuffer doesn't have a constructor that takes a Buffer as an argument which makes it difficult to load a UhkBuffer from file. Any more thoughts on this since I'll be taking a look at that code anyways?

**Comment by mondalaci** [comment]
Good point on the UhkBuffer constructor! Just talked about Jozsi, and we ultimately agreed that we should use polimorph constructors. You can implement them [in various ways](http://stackoverflow.com/a/28328719/1449117) by using the `|` operator or declaring multiple signatures, then use `typeof` in the implementation. 

It might make more sense to keep the `UhkBuffer` constructor as simple as possible by accepting an array of `UhkBuffer`s, and rather make the `UhkConfiguration` constructor polymorph, because it is what the outside world will use. We could make the `UhkConfiguration` constructor accept a vanilla JS object tree, a JSON string, and node.js Buffer to support a wide variety of source types.

It'd also make sense to make `UhkBuffer.offset` private and provide a public `UhkBuffer.rewind()` method that sets the `offset` to `0`.

I agree that it's nice to keep the `read*` and `write*` methods centralized in `UhkBuffer`, but on the other hand I think that the consistent `toUhkBuffer`, `fromUhkBuffer` calls make the code as a whole significantly easier to read.

**Comment by NejcZdovc** [comment]
@mondalaci what is the status of this issue?

**Comment by fjozsef** [comment]
@NejcZdovc This is still something needs to be done, but it has a low priority.
