### ISSUE TITLE
Volume up and down keys produce too rapid changes

### ISSUE THREAD

**Issue by laxu** [UltimateHackingKeyboard/agent#517]
Compared to another programmable keyboard I have, the Volume Up and Volume Down keys cause way too big changes to volume with a single keypress. On my other keyboard (GH60, EasyAVR firmware) pressing volume up or down once changes volume by only two units, which allows for very precise volume control. On the UHK it seems almosts random, with one keypress I may get anything from 30-50 units of change on the volume control.

Mute also toggles rapidly when pressed, e.g. I can see it mute and unmute the sound and it may end up in the initial state instead of toggling between muted and unmuted. I think there is something wrong with how the media keys work. I tried an online key tester and it reports that the media keycode is sent multiple times on a single keypress.

These issues happen with both the stock QWR and a custom keymap.

**Comment by laxu** [comment]
Windows 10 64-bit. I can check if it does something different on OSX tomorrow.

**Comment by mondalaci** [comment]
I could reproduce this issue. It's easy to fix for Windows 10 and harder to implement a general fix that works on every OS. I'll try to fix this soon. Thanks again for the report!

**Comment by laxu** [comment]
Works correctly on latest OSX so seems to be an issue only on Windows.

**Comment by mondalaci** [comment]
Being a firmware issue, I'm closing this in favor of https://github.com/UltimateHackingKeyboard/firmware/issues/72
