### ISSUE TITLE
Finish config-schema.json

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#52]
Jozsi created an incomplete `config-schema.json` that has proven to be very useful for editing `uhk-config.json` because JSON Schema is apparently supported by Visual Studio Code. It'd be worthwile to extend it to include every configuration item type.

Jozsi is not sure at all whether he made the simplest possible JSON Schema but it does work. It'd be useful to look into the JSON Schema specification and simplify the structure of the file if possible.

**Comment by fjozsef** [comment]
What about #46 ?

**Comment by mondalaci** [comment]
Geez, you're right! I better look into all of our issues before creating a new one next time. :)

Let me close this redundant one. Good catch!
