### ISSUE TITLE
Agent crash during auto update on Mac

### ISSUE THREAD

**Issue by attilacsanyi** [UltimateHackingKeyboard/agent#522]
I am on Mac OS High Sierra. After I installed version 1.0.0 it went smoothly. I saw 1.0.1 came out, so I started my Agent to see how the autoupdate process is working, but I received the following popup (the UHK was not plugged in, this might be also important):

![image](https://user-images.githubusercontent.com/2144794/34289574-70e5f45a-e6f3-11e7-9036-6cbc953cd206.png)

It seem that its related to the autoupdate.

After plugged in the UHK the Agent detect it properly, but no update happened.
Once I quit and restart the Agent I received the crash popup again:
![image](https://user-images.githubusercontent.com/2144794/34289826-9913b5a6-e6f4-11e7-982a-0f993c81457c.png)

Thanks guys for the hard work to make Agent running smooth ;-)

**Comment by mondalaci** [comment]
Thanks for your report! Actually, I'm not sure if autoupdate is supposed to work at this point despite of being displayed on the UI.

**Comment by dsalychev** [comment]
I can confirm that updater doesn't work on my macOS High Sierra 10.13.3, just want it to be a reminder.

**Comment by ert78gb** [comment]
Auto update works as soon as we sign the app
