### ISSUE TITLE
Revert #516

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#525]
The relevant bug has been fixed, so there's no need for #516 anymore.

**Comment by ert78gb** [comment]
@mondalaci Would you like I revert the whole code? Or just not process the `auto-write-config` command line argument. I think this function maybe need in the future.

**Comment by mondalaci** [comment]
I'd like the whole code to be reverted. I don't think we'll ever use it again. This wasn't a bug of Agent, but a bug of my USB hub.
