### ISSUE TITLE
Checking firmware version on keyboard

### ISSUE THREAD

**Issue by laxu** [UltimateHackingKeyboard/agent#527]
Right now the firmware page does not seem to report what firmware is currently on the keyboard. This would be good as well as some indicator if the firmware bundled with Agent is newer than current one or if your firmware is up to date.

**Comment by mondalaci** [comment]
Yes, this would be very useful. It'd be worth to display the firmware version on the firmware page.

I've just written `packages/usb/get-right-firmware-version.js`. It should be queried when Agent detects the UHK and queries its properties. I'm happy to help with this if you choose to implement it.

Eventually, we'll also query the firmware version of the left half, too.

**Comment by mondalaci** [comment]
Let's display the following below the title of the firmware page:

Firmware a.b.c is running on the left keyboard half.
Firmware d.e.f is running on the right keyboard half.

Please query the above version numbers after connecting to the UHK. See packages/usb/get-{left,right}-firmware-version.js for how to retrieve these values.

**Comment by ert78gb** [comment]
@mondalaci If the left module not connected to the right what is the "left firmware version"?

**Comment by mondalaci** [comment]
@ert78gb It should display "unknown".

**Comment by mondalaci** [comment]
@ert78gb Forget what I said. This is good for now. We'll improve it later. Great job!
