### ISSUE TITLE
Add development instructions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by richrd** [UltimateHackingKeyboard/agent#528]
I finally got the project setup after a few issues with libusb and electron. I then proceeded to run `npm run electron` but noticed that for it to actually do anything I need an actual UHK. Then I found `npm run server:web` in the package.json which seems to be the correct command for development (?).

Maybe my first PR could be adding that command and some extra info to the contribution instructions. What do you think?

I'm still looking around and checking out the code, but at least the following info could be added:
- The frontend code is located in `packages/uhk-web/`
- Run the project locally with `npm run server:web`
- View the app at `http://localhost:8080`
- The app will automatically reload when you make changes

**Comment by mondalaci** [comment]
Excellent suggestion! Yes, `npm run server:web` should be used for developing the web build, indeed. Just added your suggestion to the readme, and also included a description about the difference of the electron vs the web application. If you feel that I missed anything, definitely feel free to send a PR.
