### ISSUE TITLE
Key title animation when remapped

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#53]
When a key is being remapped, a flash like animation should play on the key:
1. the whole key goes white quickly (optionally immediately)
2. the white background fades back to the original one (dark grey), revealing the new (white) label on the key.

**Comment by NejcZdovc** [comment]
@mondalaci is this still relevant?

**Comment by fjozsef** [comment]
@NejcZdovc As far as I know, yes.

**Comment by mondalaci** [comment]
Yes, it is, although it will only be truly relevant after positioning the key action popover correctly.

**Comment by NejcZdovc** [comment]
blocked by #56
