### ISSUE TITLE
Import keymap

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#531]
Agent can export keymaps, but can't import them yet.

Let's implement #459 first on which this issue is based.

Then add a white button above the "Available keymaps" title, make the button text "Import keymap", make it pop up the file selector window filtered with .json files, and import the chosen keymap file.

**Comment by snaggen** [comment]
Any progess on this? I have an UHK expected to arrive in a few weeks. To be able to use the uhk with the us layout, but adding the swedish ÅÄÖ to some mod keys, I expect to run a Swedish keymap on the desktop (to get access to the åäö keys) then remap my uhk so the keycaps and keycodes align again. So I expect to do quite some remapping, and I have 2 keyboards coming (one for the home office, and one for the real office). So I was hoping to do this re-mapping once, then export and import it to the other keyboard.

**Comment by mondalaci** [comment]
You can already do what you're looking for with Agent's configuration import/export feature. This issue pertains to keymaps which are part of the whole configuration. Also make sure to read https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

**Comment by owlstead** [comment]
Beware that this feature request may require some interaction on the Macro functionality as well. I'm not sure if there is other information in the keymap that is not being send to the keyboard, but that would be affected as well; you cannot import what is not there.

**Comment by vinipsmaker** [comment]
This will be excellent in combination with #916

**Comment by mondalaci** [comment]
I'm closing this, and respecify it later to work via the cloud.
