### ISSUE TITLE
Factory keymap title

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#55]
This keymap is an exception:

- [ ] it is non-editable at all (title, short name, mapping)
- [ ] in the menu it should show: `Factory keymap`, and this should be the first item.
- [ ] in the title line of the edition interface (which is a viewer interface in this case): `Factory keymap (FTY)` (star icon after it)

Other keymaps should look like on the mockups. `[Editable title] keymap ([editable 3 letter name])` as the main title of the editor interface, and only the "Editable title" part of it is shown in the left menu (ofc not editable from there).

**Comment by NejcZdovc** [comment]
@mondalaci as we already talked about this (we will not show Factory keymap), this can be closed.
