### ISSUE TITLE
Fix My UHK menu item hover background color

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#552]
Right now, when hovering over the My UHK menu item, its background color changes. Please make the background color unchanged when hovered.

![screenshot from 2018-01-09 18-41-25](https://user-images.githubusercontent.com/300402/34734704-05db9ff6-f56d-11e7-8e8e-9d1f65cbda7f.png)

**Comment by Eja26** [comment]
If you are referring to just the text input's background being darker than the rest of the menu item, try changing the background-color from 'inherit' to 'transparent'.

**Comment by mondalaci** [comment]
@Eja26 Indeed! Thanks, very much appreciated.
