### ISSUE TITLE
Save to keyboard button doesn't appear

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#560]
Please see the attached configuration. When I start up Agent and delete "New macro (1)" the "Save to keyboard" button doesn't appear.

[UserConfiguration.json.zip](https://github.com/UltimateHackingKeyboard/agent/files/1631645/UserConfiguration.json.zip)

**Comment by ert78gb** [comment]
`New macro (1)` is assigned to the `QWERTY for PC` keymap `MOD` layer. If the macro is deleted, the keyAction binding will not be deleted and the serialization tries to find the macro but it cannot and crashes.

I think the system should delete the keyAction binding, am I right? If not pls advise.

**Comment by mondalaci** [comment]
Yes, we should definitely set the MacroActions to NoneActions for macros which get deleted at the moment they are deleted.
