### ISSUE TITLE
Menu key doesn't work

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#563]
Maybe it has an invalid scancode.

**Comment by borje** [comment]
I tried to scan the key with an other (non-UHK) keyboard that was connected and then Agent recognized Menu at least. But it didn't work anyway.

**Comment by mondalaci** [comment]
@Lauszus Please take a look at this to see what's happening on the USB level. This may not be a firmware related issue. We may simply use an incorrect scancode.

**Comment by Lauszus** [comment]
Changing ```HID_KEYBOARD_SC_MENU``` to ```HID_KEYBOARD_SC_APPLICATION``` solves this issue on Windows 7. Please see the following PR: https://github.com/UltimateHackingKeyboard/firmware/pull/95.
