### ISSUE TITLE
Show markers for home row index finger keys (F & J with QWERT*)

### ISSUE THREAD

**Issue by tuxlifan** [UltimateHackingKeyboard/agent#580]
Please add markers for the keys on the home row index finger positions
(F & J with QWERT* layouts).
Together with #418 this will help greatly with visual orientation on layers other than Base.

Attached are modified base-layer....svg as examples (.txt extension added to work around github file type restrictions).
If it would be easier to implement, just adding a colored (and dashed?) bottom border could also work fine.

[base-layer--blank-with-knobs.svg.txt](https://github.com/UltimateHackingKeyboard/agent/files/1730373/base-layer--blank-with-knobs.svg.txt)
[base-layer-with-knobs.svg.txt](https://github.com/UltimateHackingKeyboard/agent/files/1730374/base-layer-with-knobs.svg.txt)

**Comment by tuxlifan** [comment]
mockup for border color (.txt extension added since github apparently really doesn't like any .png or .jpg today :o)

[border-bottom-keymarker.ppm.txt](https://github.com/UltimateHackingKeyboard/agent/files/1730416/border-bottom-keymarker.ppm.txt)

**Comment by mondalaci** [comment]
Thanks for the idea! We should definitely make key orientation easier to see but I'd much rather prefer to implement #418 and #450. I think they'll be much easier to see for most users. I'm closing this issue, but feel free to follow up.
