### ISSUE TITLE
Add the scancodes of the Korean Han/Yeong and Hanja keys

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#587]
I ordered a Korean keyboard from eBay and sent it to @Lauszus who will capture the scancodes of the Han/Yeong and Hanja keys, and we'll add them to Agent.

**Comment by Lauszus** [comment]
The Han/Yeong key has a scancode of ```0x90``` and the Hanja key has a scancode of ```0x91```. I'll send a PR in a bit.

**Comment by mondalaci** [comment]
Fixed by e3330220439c380fe183ddf8dd95a7f751695030.
