### ISSUE TITLE
Add a layer for Ctrl

### ISSUE THREAD

**Issue by Jos512** [UltimateHackingKeyboard/agent#592]
I was reading today about non-QWERTY keyboard layouts. One person who designed an alternative keyboard layout remarked [here](http://nikolay.rocks/2016-06-26-we-were-wrong):

>All those layout optimizations projects. We all been doing it wrong. From the very beginning we tried to save as many standard control combinations letters in original places as possible. 

> But the truth is, our brains don't think of the control combos as *letters*. Those are just muscle memory things. *do this and file will be saved, press that and you paste from the memory*. And we can move those into a separate layer, (...).

And so the idea is that when someone presses Ctrl, the QWERTY layout becomes active and we can use key combinations at the same location as we otherwise do. But without Ctrl held down, the customised keymap is active.

I think this is a great idea and it think it makes switching to a different keyboard layout that much easier. Because it doesn't force us to re-learn the keyboard combinations we've used thousands of times (`Ctrl + V`, `Ctrl + C`, `Ctrl - S`, and so on).

But I noticed in the Agent that there is a layer for Base, Mod, and Fn. Should we also add one for Ctrl?

**Comment by mondalaci** [comment]
Thanks for the idea! This use case makes sense to me, and it's not the first request of its kind. We may implement it eventually, but I'm not sure yet when and exactly how.

If we do it, we'll do it in a general manner that allows any modifier to alter scancodes on a per-key basis via a UI that is very intuitive and unobtrusive.

For now, I'm closing this, and labelling it as an exotic feature. Such features will be reconsidered after implementing the features that have been part of the original vision.

Thanks again, and feel free to follow up.
