### ISSUE TITLE
Update the firmware versions after firmware updates

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#595]
Currently, the displayed current firmware versions don't get updated right after firmware updates. One has to restart Agent to see the updated firmware versions.

After the firmware update procedure finishes (regardless of whether the update succeeds or fails), please query the firmware versions via USB and update them on the firmware page.

Please also remove the OK button at the bottom of the page. I don't think anybody uses it, and it's confusing.

Lastly, please add a standard looking copy to clipboard UI element, so that users can copy the update log.

**Comment by ert78gb** [comment]
@mondalaci The `OK` button starts the device poller. If I remove the button the app should start the poller after the success/failed firmware update. Is it ok?

**Comment by mondalaci** [comment]
Yes, sounds great.

**Comment by ert78gb** [comment]
I think it is closable. I forgot write the close keyword in the related PR.
