### ISSUE TITLE
No icon is displayed for Agent in the Alt-Tab dialog

### ISSUE THREAD

**Issue by eltang** [UltimateHackingKeyboard/agent#598]
This is happening on a Fedora 27 system.

**Comment by mondalaci** [comment]
According to my experience, the icon is not displayed when starting the AppImage for the first time, or when starting the development build of Agent. What if you start the AppImage the second time?

**Comment by mondalaci** [comment]
This is weird, because on Linux Mint 18.3 it works as expected after the AppImage is installed.

This doesn't seem as trivial as expected. The "appimage no icon" Google search yields plenty of results.

@ert78gb Where do we load the icon?

**Comment by ert78gb** [comment]
maybe the solution is electron-userland/electron-builder#2269
I checked the agent code and we set icon for the window
```typescript
win = new BrowserWindow({
        title: 'UHK Agent',
        width: 1024,
        height: 768,
        webPreferences: {
            nodeIntegration: true
        },
        icon: 'assets/images/agent-icon.png' // <-- wrong path the "renderer/" missing
    });
```

I will fix it on this weekend

**Comment by eltang** [comment]
It appears that this issue still has not been fully resolved for me. Whenever there is a dialog window open, such as that for choosing a firmware file to flash, the icon disappears again.

**Comment by mondalaci** [comment]
@eltang I cannot reproduce this on any OS. Which OS and which Agent version exactly? You should use the most recent Agent release.

**Comment by eltang** [comment]
I am running Agent 1.1.5 on Fedora 27. You must use Alt-Tab while the window for selecting the firmware file is open.

**Comment by eltang** [comment]
This is happening with GNOME. I actually tried whether this would happen with Firefox when a dialog window for uploading files is open, and I did not encounter the same issue.

**Comment by mondalaci** [comment]
Does the icon disappear for the time the dialog is open, or stays that way after you close the dialog?

**Comment by eltang** [comment]
It returns after I close the dialog, yes.

**Comment by mondalaci** [comment]
Sorry, but I cannot reproduce this on Linux Mint with Cinnamon. Unfortunately, I think chances are good that Electron implements this behavior and we have no control over it.
