### ISSUE TITLE
Translation for Agent

### ISSUE THREAD

**Issue by iprok** [UltimateHackingKeyboard/agent#60]
Hello!

I will be glad to make subj if you can give me some instruction about how to translate it in general.

WBR.

**Comment by iprok** [comment]
I use linux.

**Comment by mondalaci** [comment]
Thank you very much for offering your contribution, @iprok! Currently Agent is not localized, so please let us look into it.

@fjozsef, is there a standard way to localize Angular 2 applications?

**Comment by fjozsef** [comment]
@mondalaci There will be internationalization support in the final release of the Angular 2, but I think now it's only partially supported.

**Comment by mondalaci** [comment]
In this case, I think it'd be worth to postpone the implementation of localization in Agent until the Angular API stabilizes and the feature set works properly in order to avoid later refactoring. Agreed?

**Comment by fjozsef** [comment]
I have similar thoughts. It is blocked, we should finish the migration to angular 2 in the first place. Hopefully a stable i18n API will released until then, so we can discuss this issue again.

**Comment by mondalaci** [comment]
Sounds good to me! In light of the above, please let us follow up later about this, @iprok.

**Comment by libook** [comment]
I can help for Chinese translation~
Angular 2 support i18n natively.You can try https://angular.io/docs/ts/latest/cookbook/i18n.html and https://scotch.io/tutorials/simple-language-translation-in-angular-2-part-1 .
And maybe the translation could run as another parallel thread.

I love VUE2 and ES6\ES7, actually. :-P

**Comment by mondalaci** [comment]
Thanks you for offering your help, @libook! Currently, this issue is not a priority, but we'll let you guys know as soon as we start working on it.

**Comment by mondalaci** [comment]
I've been thinking about this issue lately.

Agent already takes huge resources to develop and maintain, and this issue would potentially add a lot of burden in the long run. I can foresee people adding new languages from time to time which would result in a lot of overhead. Even worse, as we'd add new strings to Agent, those would have to be translated one by one.

Given that the vast majority of our customers speak English, this issue would add little value. I'd much rather pursue other issues that actually add value. I'm sorry, but I'm closing this issue.

**Comment by KovalevArtem** [comment]
I propose to return to this issue again!
I am ready to help in the translation into Russian.
I suggest using Weblate. It is completely free for open source projects. But greatly simplifies the localization process!

**Comment by mondalaci** [comment]
@KovalevArtem I'm sorry, but the translation process would be a constant burden according to the above, no matter the tooling. Thank you for your help, but we'll spend resources on other efforts.
