### ISSUE TITLE
Sanity-check firmware files before updates

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#608]
Right now, the user can specify any file, and Agent will try to update the firmware with it. This deletes the  firmware of the right keyboard half, and times out the update process.

Agent should sanity-check the firmware image. The sanity check should be done before running the update process both for user provided firmware images and the bundled firmware image.

The sanity check should do the following:
1. Extract the tarball.
2. Read package.json
3. Check if the files described by `devices[*].source` exist.
4. Check if the files described by `modules[*].source` exist.

If the sanity check fails, pop up the "Invalid firmware file provided." error message.

**Comment by mondalaci** [comment]
Let me modify the specification. Instead of 3 and 4, only check if the devices and modules directories exist. No additional checks are needed.

**Comment by ert78gb** [comment]
Implemented the new requests in 1123 PR
