### ISSUE TITLE
Side menu

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#63]
I would like to start work on side menu. I have a couple of questions before I can start.

- Can I move all content from HTML cutouts to one big div and angular to another, because now we can't toggle only content anymore, we need to toggle the whole page? I would personally suggest to split content into two html files at this point. Index.html for angular and Demo.html for static content.
- Main app need change. I suggest moving content from the current main app to new "master" keymap component and introduce new main app with only sidemenu, router and outline.
- I would suggest to start using router v3, so we need to update project to rc2 and all necessary dependencies. This is [documentation ](https://angular.io/docs/ts/latest/guide/router.html)for it.
- Is first keymap default page (home page) of the agent or will there be welcome screen / other home page?

@fjozsef and @mondalaci what do you think?

**Comment by fjozsef** [comment]
- I thought we could have 3 htmls, one for the angular2, one for the keymap and one for the macro editor. I would wrap the jQuery codes into an angular2 component which would contain only an iframe. What do you think?
- Yes, we definitily need a new main app. I think you should rename the current one and create a new one. Maybe you should move some of the logic (like selecting the keymap) from the current main app to the new one, but I am sure you will see what should be moved.
- router v3: +1. I really hope that it's stable enough. I had a bad experience with the previous ones when I tried to migrate to v2 unsuccessfully.
- For now the first keymap should be the home page, but in the future maybe we'll have authentication services, who knows.

**Comment by NejcZdovc** [comment]
- Which jquery code are you referring too and which iframe?
- Ok
- Same here, fingers crossed.
- Ok

I would suggest to do this in three phases. 
1) Split HTML files
2) Reorganize main app without router
3) Add router

This way we can merge PR (phases) to the master branch faster, so there will not be a lot of conflicts. @fjozsef What do you think?

**Comment by mondalaci** [comment]
@NejcZdovc: Regarding the iframes, @fjozsef meant to extract to code of the legacy keymaps, and the code of macros into separate files, and loading those files within the iframe of a separate LegacyKeymap, and a Macro Angular 2 component. That way, Angular could supervise the whole DOM, and we would nicely separate (and eventually port) the legacy code. Makes sense?

Your roadmap looks good to me, but I'm interested about @fjozsef's opinion, too.

Thank you!

**Comment by fjozsef** [comment]
@NejcZdovc Yes, exactly as @mondalaci described.
