### ISSUE TITLE
Modifier keys before action key for remote sessions

### ISSUE THREAD

**Issue by piratk** [UltimateHackingKeyboard/agent#631]
When using remote sessions such as with Citrix or NoMachine, the modifier key needs to be pressed well ahead of the action key. For instance, sending "Alt+Tab" without any delay between alt and tab may not work. 

This could be an option per keyboard short-cut, or just remodel the keyboard short-cuts as macros with advanced key press and release characteristics.

**Comment by mondalaci** [comment]
Thanks for reporting this! It's quite an edge case, and I'm not sure yet how should we best handle it.

How much delay must be inserted exactly at least?

**Comment by piratk** [comment]
I can't say, but it might be good to have it configurable.

**Comment by mondalaci** [comment]
What is your host OS on which you can experience this issue?

**Comment by mondalaci** [comment]
This issue is likely due to https://github.com/UltimateHackingKeyboard/firmware/issues/185 assuming that your host OS is Linux or Windows. Closing this issue assuming this is the case. If it turns out not to be the case, I'll reopen it.
