### ISSUE TITLE
Changing to base layer, releases any pressed modifier key like Ctrl or Shift

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#633]
I'll explain much better with an example:
**Ctrl+**: Press control
**Shift+**: Press shift
**Mod+**: Press mod
**L**: Press L (Key Right arrow). It selects next word.
**Mod-**: Release Mod. but in fact releases Shift and Control too.
**Shift-**: Release shift (In fact, does nothing)
**C**: Press C (for copy into clipboard). In fact, replaces text with a 'c'.

**Comment by mondalaci** [comment]
Thanks has already been fixed in https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.2.1

Please upgrade.
