### ISSUE TITLE
Weird Macro Bug

### ISSUE THREAD

**Issue by sad2project** [UltimateHackingKeyboard/agent#636]
I've written and assigned my first macro. The macro does a Super+E, Space, Enter, Space. Nothing all that special. Then I assign the macro, and whenever I activate it, instead of doing the thing it's supposed to do, it switches keymaps to whatever is at the top of the list.

**Comment by mondalaci** [comment]
Being a frimware bug, I'm closing this issue. You're welcome to watch the firmware issue if you're interested.

**Comment by sad2project** [comment]
Was kind if surprised you didn't close it earlier honestly
