### ISSUE TITLE
Super + Mod + i,j,k,l don't work for window positioning on Windows

### ISSUE THREAD

**Issue by alexandrnikitin** [UltimateHackingKeyboard/agent#637]
Basically, the title. I use Windows key + arrows hotkeys to align, minimize, expand a current window on Windows OS. They don't work with UHK.

**Comment by mondalaci** [comment]
Just checked this, and Super + Mod + {i,j,k,l} works flawlessly for me on Windows Vista. Please attach a picture of your keyboard (to see how your keys are labelled), and another picture of the Mod layer of your default keymap that is visible in Agent.

**Comment by alexandrnikitin** [comment]
Ops, I'm sorry, my bad. The problem was that I removed Super from Mod layer. (I remapped the bottom row of the default layer to `Ctr-Fn-Super-Alt-Mod`, reflected that on Mod layer, but accidentally removed Super key so that it was `Ctrl-None-None-Alt-Mod`. Thank you.

**Comment by mondalaci** [comment]
Cool, glad it works for you! Cheers!

**Comment by IzK666** [comment]
Maybe could be a good enhancement to implement a checkbox in remapping keys screen that allows to assign the same key in all layers in one step.

**Comment by mondalaci** [comment]
@IzK666 See https://github.com/UltimateHackingKeyboard/agent/issues/618
