### ISSUE TITLE
Agent shows "skipping update" message on ALL runs not just first

### ISSUE THREAD

**Issue by sergeyhush** [UltimateHackingKeyboard/agent#639]
I keep getting this message "[AppUpdateService] Application update is skipping at first run." on all the runs, not just the first one.
<img width="1281" alt="screen shot 2018-05-16 at 10 32 09 am" src="https://user-images.githubusercontent.com/64040/40133469-bc86c970-58f4-11e8-971b-4e6fdd297c1c.png">

**Comment by mondalaci** [comment]
@sergeyhush Thanks for the report!

@ert78gb Can you disable these messages and hide the whole auto-update UI? It'd be the best solution, because I can't see when the auto updater will work, and in the meantime it just causes confusion and user reports.

**Comment by mondalaci** [comment]
@ert78gb Thanks for the quick fix! I don't insist to hiding the auto update UI, especially if it's working. Let me test it soon. I'm closing this issue.
