### ISSUE TITLE
UHK unable to load configuration

### ISSUE THREAD

**Issue by joelp1** [UltimateHackingKeyboard/agent#646]
After updating to the latest version of the agent and flashing the keyboard with the included firmware, my keyboard shows "FTY" as the configuration.  Agent hangs on the Loading keyboard configuration screen with the error "Cannot read property 'uniqueId' of null'.  My default configuration is not loading and I cannot switch to any other configuration besides "FTY" which I'm unfamiliar with.

I'm running on mac.

**Comment by mondalaci** [comment]
You probably hit https://github.com/UltimateHackingKeyboard/firmware/issues/67

Please unplug, then replug your keyboard over USB. Does it help?

**Comment by mondalaci** [comment]
Please let us look into this. We're considering this as the highest priority issue, and will get back to you ASAP.

**Comment by eltang** [comment]
@joelp1 Is it correct that your hub has its own power adapter? If so, you may need to unplug both that and the USB cable connecting your hub to your computer. Alternatively, you can unplug the USB cable connecting your UHK to your hub. The display should turn off if you are successful in fully power cycling your UHK.

**Comment by joelp1** [comment]
When I unplugged the keyboard from the powered hub, the problem was
resolved.  Thanks!

Joel Ponder

joelponder@gmail.com
3930 N. Pine Grove Ave. # 3109
Chicago, IL 60613
(312) 970-9194

**Comment by mondalaci** [comment]
So glad to hear, @joelp1! Thanks for the help, @eltang!
