### ISSUE TITLE
Launch Calculator opens multiple instances of the calculator

### ISSUE THREAD

**Issue by cassull** [UltimateHackingKeyboard/agent#654]
When using the Launch Calculator shortcut, it opens multiple copies of the default calculator. The number of copies seems random, I have seen it open anywhere between 4 to 22 copies of the calculator. This is on a Win10 using the QWERTY for PC map

**Comment by mondalaci** [comment]
Thanks for reporting! This is caused by https://github.com/UltimateHackingKeyboard/firmware/issues/72 . Being a duplicate issue, I'm closing this one.
