### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by MattKunze** [UltimateHackingKeyboard/agent#659]
I have a pretty big monitor (3440x1440) and when starting the agent app it automatically expands to fill the screen (OSX, haven't tried it anywhere else). Having a more reasonable initial size, and potentially remembering the previous layout, would be a lot less jarring

**Comment by mondalaci** [comment]
I agree that Agent should always remember the previous window size and state (maximized vs unmaximized).

As for the initial window size, it's less trivial given the wide range of possible resolutions. Any suggestions about the latter?

**Comment by mondalaci** [comment]
Good points, thanks! We'll think about this before implementing it.

**Comment by mondalaci** [comment]
Given that Agent looks right on most monitors when maximized, it will start as such by default, but then it'll remember and restore its last window size setting upon startup. We'll only implement this for now.
