### ISSUE TITLE
unused "keymap/add" and KeymapAddComponent

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/agent#663]
When I developed the #658 I found unused code base that not used in the app. 
@mondalaci What do we do whit these codes?

**Comment by mondalaci** [comment]
I hid that part of Agent because [the final implementation](https://github.com/UltimateHackingKeyboard/agent/issues/459) will differ very much.

I think we should leave it as it is, and change it later. What do you think?

**Comment by ert78gb** [comment]
ok leave it
