### ISSUE TITLE
Feature request: Visual Indicator when Secondary Role is used

### ISSUE THREAD

**Issue by StitiS** [UltimateHackingKeyboard/agent#664]
Hey Team,

Would you mind creating a visual indicator on a key if the Secondary Role is used, similar to how you show the modifiers (if used)?

![image](https://user-images.githubusercontent.com/9129183/40898565-1a37e118-6777-11e8-8a84-b84feb3d8346.png)

**Comment by mondalaci** [comment]
Hi there! Yes, this is a duplicate of #138.
