### ISSUE TITLE
Make --layer-double-tap=true default

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#665]
Eventually, `npm run electron -- -- -- --layer-double-tap=true`, will have to be used by default, and this option will have to be removed. I'll prioritize this issue after fixing the freeze bug.

**Comment by mondalaci** [comment]
Some of the UHK users have come to grow dissatisfied due to unwanted double tap locks. If you don't want to wait for this feature to be merged, then flash the latest pre-released firmware, update to the latest Agent, and start it with `./UHK.Agent-1.2.7-linux-x86_64.AppImage -- --layer-double-tap=true`.

Then you'll be able to enable/disable the double tap to lock feature on a per key basis with the following checkbox:

![untitled](https://user-images.githubusercontent.com/300402/44298822-8f002b00-a2ea-11e8-9e5a-f3e5ce5f7bb7.png)

**Comment by rpbaptist** [comment]
On my system layer locking doesn't work at all anymore going from 2.4 to 2.7. (Linux) Starting agent with this flag displays the option, but it doesn't do anything whether I enable it or not.

**Comment by mondalaci** [comment]
@rpbaptist What are the 2.4 and 2.7 version numbers? I don't think they belong to Agent or the UHK firmware?

**Comment by rpbaptist** [comment]
Sorry, I forgot a 1 there. 1.2.4 to  1.2.7 for the agent. Version numbers of firmware are which were included in those releases.

**Comment by mondalaci** [comment]
Please flash firmware 8.4.4 and retry. Firmware versions starting from 8.3.3 and ending with 8.4.2 contained a bug that made the double tap to lock layer feature work only when tapping very quickly. That's why I explicitly wrote before to update to the **latest pre-released firmware**, not to the bundled firmware of Agent.

**Comment by mondalaci** [comment]
@ert78gb The `-- --layer-double-tap=true` arguments don't seem to be working on Windows. Any ideas how to make it work?

**Comment by mondalaci** [comment]
@ert78gb Sorry, it works perfectly.

**Comment by mondalaci** [comment]
Closing in favor of #822.
