### ISSUE TITLE
<base> tag breaking assets on gh-pages

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#67]
The demo site is served as github pages from the *gh-pages* branch at the URL http://ultimatehackingkeyboard.github.io/agent/.

If haveing the asset `build/uhk.js` on this branch, then it can be used in the *index.html* file with a relative URL `<script src="build/uhk.js"...` and this get's resolved to "http://ultimatehackingkeyboard.github.io/agent/build/uhk.js" correctly.

**The issue**
When having the the `<base href="/">` tag in the header all the relative URLs after it will be based on the value of the `href` attribute. (see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).

**The fix**
Removing the `<base>` tag resolves the issue. This has been already done on the *gh-pages* branch. (see: c718e06)

**To be discussed**
The `<base>` tag has been added to the *index.html* in this commit: 036c2d0a.
@NejcZdovc do we need this tag for the app (on the *master* branch)?
Anyway I'm curious what do you use this tag for, as I never used it before (barely knew about the existence of it).

**Comment by mondalaci** [comment]
Just to clear things up, the main culprit was likely that gh-pages hasn't been updated for some reason. Please let's investigate on the HTTP protocol level first when resolving bugs like this in the future. Regardless, please let's talk about the base tag in this issue as Arpi suggested.

**Comment by fjozsef** [comment]
https://angular.io/docs/ts/latest/guide/router.html#!#base-href

**Comment by csanyiarpad** [comment]
Ok, got it, I'll propose a solution here.

**Comment by mondalaci** [comment]
@csanyiarpad Please restore the base tag temporarily on gh-pages and let's see for certain whether it breaks the app. I'm not sure at all it does.

**Comment by csanyiarpad** [comment]
Oh yes, that's the first step for sure.

1. Find the solution manually.
2. Automate the deployment of the gh-pages (or more likely the build process, as we are pushing the changes manually).

**Comment by fjozsef** [comment]
Since we are using HashLocationStrategy thus the base tag can be removed (it is only needed for the PathLocationStrategy which uses the HTML5 History PushState API).

I will remove the base tag in an upcoming commit.
