### ISSUE TITLE
Modifier keys lose their "pressed" state if you press Fn or MOD

### ISSUE THREAD

**Issue by CalmDownMonkey** [UltimateHackingKeyboard/agent#676]
I notice if you are holding a modifier like LShift, it will lose its pressed state if you use Fn or MOD. You have to release the LShift key and press it down again for it to register.

I came across this when I was working with selecting text using the MOD+cursor keys and replacing it with different text, and I kept getting stuff from the "lowercase" layer when I wanted a character from the "uppercase" layer. I thought I was screwing up and not holding shift properly, but then I noticed the bug using http://keyboardchecker.com/ 

Steps to replicate on that online tool: 
1. Hold LShift
2. Tap MOD or Fn, but don't let go of LShift

Expected: LShift to still be pressed
Actual: LShift becomes unpressed 

This doesn't seem to happen on my laptops' Fn buttons so I think it might be a small firmware bug.

**Comment by mondalaci** [comment]
I cannot reproduce this issue. According to keyboardchecker.com, LShift stays pressed while tapping Mod or Fn.

Would you please reset UHK your configuration, use the default keymap, and retry?

If this issue still persists, please provide your exact OS and firmware versions.

**Comment by CalmDownMonkey** [comment]
I've reset the keyboard including all my personal settings and tried on a different machine - it seems to behave the same on my Windows 7 laptop and Windows 10 PC (all kept up to date), regardless of the keymap.

My firmware is 8.1.5.

On the keyboardchecker, when you hold shift, it should go grey, and stay grey. However, mine goes green when I tap MOD or Fn.

Is there anything else I could give you to help replicate it? All I can think of is filming it happening =D

**Comment by mondalaci** [comment]
Please flash [firmware 8.2.5](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.2.5) with Agent and retry. Let's see if you can reproduce with this firmware version.

**Comment by CalmDownMonkey** [comment]
Ah that seems to have fixed it =) Case closed, my apologies!

**Comment by mondalaci** [comment]
Awesome, glad it's working for you! *Our* apologies, actually. Agent will always update to the latest firmware, but we're not there yet.
