### ISSUE TITLE
Make the timeout of dual role keys configurable

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#679]
User configures a key to send a scancode as the primary action.
User configures the same key as a layer switch as the secondary action.
User presses that key with the intention to switch layers (f.x. to get to cursor key movements) and keeps it held down for a while. But user does not press another key for a while (f.x. because they are still reading the page, and are not yet ready to scroll). User then decides they do not need the secondary layer and let go of the key. UHK now sends the primary scancode. Instead, I want UHK to not send anything once a certain timeout has elapsed. (Maybe that timeout can be the same as the "double-tap to lock layers".)

Here is my use case: I have configured the Colemak "backspace" (which is on the standard CapsLock key) to send Backspace as the primary scancode, and use it to switch to the Mod layer (for cursor movements etc.) as a secondary action. I now sometimes find myself holding down that Backspace (CapsLock) key with my left pinky because I probably intend to scroll the page I am reading, but then after a while, figure that I am not going to scroll, because I found maybe an interesting link I want to click on; so I let go of the key and I get a Backspace scancode, which in turn sends Firefox back in history and I lose the web page I was looking at. If the primary action had a timeout, then that would not happen. 

My intended behaviour: Quickly pressing and releasing the key would give primary; pressing in combination with some other key would give secondary; pressing, holding it for a while, then releasing would not do anything.

**Comment by mhantsch** [comment]
Actually, this request might be better placed in "firmware". Is there a way to move it?

**Comment by mondalaci** [comment]
Thanks for reporting! This feature makes sense to me.

No need to move this to the firmware repo because it's both a firmware and an Agent issue, given that this timeout will be configurable via Agent. The firmware part will be done when we get there.

**Comment by mondalaci** [comment]
Blocked by #562.

**Comment by mhantsch** [comment]
Okay if you want to keep it in Agent, although I guess a general timeout for primary actions could be implemented in the firmware alone without any change in Agent. Configurability through Agent could come at a later stage. 

Just slicing the implementation into smaller pieces that can be implemented separately and incrementally, producing little bits of valuable features step by step. Can't help it, I work as an Agile coach in my main line of business ;-)

**Comment by mondalaci** [comment]
We think the same way! Agent and the firmware is developed in an agile fashion! :)

A reasonable timeout could be choosen and made the default, but I'm worried that some people prefer the current behavior. That's why this time I'd rather stick to the configurable approach without any intermediate steps, even if it takes more time.

**Comment by mhantsch** [comment]
I honestly do not see much sense in holding down a key for a long time, and then release it just to produce a single keystroke ;-) I'd just set it to a long timeout, f.x. 4 times the double-tap-to-lock time. It's your call though, you are the "product owner"!

And BTW, I'd be happy to test beta firmware for my use cases.

**Comment by mondalaci** [comment]
Closed in favor of #792.
