### ISSUE TITLE
UHK Agent will not initialise when connected through a Dell D3100 dock

### ISSUE THREAD

**Issue by Swissola** [UltimateHackingKeyboard/agent#683]
I have a Dell XPS 13 9360. Agent works fine when plugged in directly to the laptop. I also have a Dell D3100 dock that I use with two monitors while at work.

Problem occurs when I try to connect the keyboard via the Dell D3100 dock. Agent application hangs (with what looks like the main screen displayed and a secondary, child window overlayed.

Give me some instructions if you'd like me to help you troubleshoot the issue with you all :)

**Comment by mondalaci** [comment]
Unfortunately, there's hardly anything that can be done besides using another hub or docking station. The UHK exposes a standard but complicated USB device that is composed of multiple USB interfaces and a fair number of hubs can't deal with it and exhibit all sorts of weird behavior.

We're sorry about it. This is clearly not ideal, but we can't fix the bugs of third party devices. Maybe you can contact Dell, although manufacturers typically don't care about such issues.

I'm closing this, but feel free to follow up.
