### ISSUE TITLE
Agent LED on UHK doesn't light up when connected?

### ISSUE THREAD

**Issue by kevlar1818** [UltimateHackingKeyboard/agent#685]
The agent LED on my UHK doesn't illuminate when I have Agent running and connected to my UHK. Is this normal behavior? I was under the impression it would light up.

**Comment by mondalaci** [comment]
It should, and it will. Now we have an issue for it. :)

**Comment by kevlar1818** [comment]
@mondalaci So this is a known issue, and not one unique to my UHK?

**Comment by mondalaci** [comment]
Yes, this is a known issue and has yet to be implemented.

Actually, this is a firmware issue. Closing this issue in favor of the newly opened https://github.com/UltimateHackingKeyboard/firmware/issues/126

**Comment by kevlar1818** [comment]
@mondalaci Thanks for the quick response! Please know that this doesn't taint my first impression of the UHK. So far I'm very pleased with the keyboard. Thanks for all of your work!

**Comment by mondalaci** [comment]
@kevlar1818 Thank you! So glad you're satisfied!
