### ISSUE TITLE
Import braces spaces

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#69]
We may should add extra spaces where it is missing to the import.

Change these: 
```typescript
import {Component, OnInit} from '@angular/core';
```
To these: 
```typescript
import { Component, OnInit } from '@angular/core';
```

Like [here](https://github.com/ReactiveX/rxjs/issues/1868).

@mondalaci What do you prefer? I can see both version in angular and rxjs code.

**Comment by mondalaci** [comment]
I personally prefer the shorter version, but I don't insist to them badly.

**Comment by fjozsef** [comment]
@NejcZdovc You?

**Comment by NejcZdovc** [comment]
I prefer spaces, but only in imports. I hate spaces in functions or loops like this:
`foo ( arg1, arg2 )` or `for ( var i=0; ....; i++ )`

**Comment by fjozsef** [comment]
On the typescript's official [site](https://www.typescriptlang.org/docs/handbook/modules.html) they are using spaces, so I think we should, too. @NejcZdovc do you know any tslint rule or lib how could we check this in travis?
