### ISSUE TITLE
Possible to create corrupted configuration

### ISSUE THREAD

**Issue by syl20bnr** [UltimateHackingKeyboard/agent#690]
When assigning a key to switch keymaps, the current keymap is not a valid choice. The agent does a good job to remove this choice from the combo box. In the screenshot below it is not possible to choose the current keymap  `000 - MAC` from the list:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1243537/41814054-d3d3203a-7710-11e8-8933-2056a732d0ff.png">

However we can trick the agent by going to another layer and assign the keymap `000 - MAC` and selecting `Remap on all keymaps`:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/1243537/41814087-77770f4e-7711-11e8-8961-b8cae8bcfa7f.png">

We can flash it or save it to a file. If we try to import the saved configuration, we've got an error `corrupted configuration`.

To fix this we can go to each keymap and and remove the key with the current keymap assign. We can also see an artifact of the bug, the keymap image appears as a broken link.

**Comment by mondalaci** [comment]
@syl20bnr Thank you for the report! I can confirm this bug.

@ert78gb When remapping a switch keymap action on all keymaps, please make sure that Agent doesn't change the keymap which the switch keymap action refers to.
