### ISSUE TITLE
Display error message on OSX when encountering with buggy USB hubs / docking stations

### ISSUE THREAD

**Issue by aki009** [UltimateHackingKeyboard/agent#708]
I just received my UHK and Agent 1.2.5 on a MacBookPro running High Sierra (10.13.5) I get the message "Agent wasn't able to set up permissions via PolicyKit. This is most likely because the polkit package is not installed on your system." This is followed by commands that are clearly intended for a Linux based system and not a Mac.

This issue seems similar to #634.

**Comment by mondalaci** [comment]
@aki009 This is rather strange. Would you also give it a try to Agent 1.2.1 - 1.2.4 and let me know which works (if any)?

**Comment by aki009** [comment]
Here is the console output

[logout2.txt](https://github.com/UltimateHackingKeyboard/agent/files/2151229/logout2.txt)

**Comment by mondalaci** [comment]
Please unplug every one of your USB devices, connect your UHK directly to your MacBook and retry Agent 1.2.5

**Comment by aki009** [comment]
I haven't tried any permutations of this, but bringing the keyboard closer to USB root might have something to do with this. I had all of my HID devices plugged into a USB3 hub built into my monitor, that was attached to a USB-C hub that has its own USB root port via Thunderbolt (the USB hub then went into a USB-C port on the Mac). By plugging the keyboard directly into the hub it's correctly detected by the Agent software.

Note that even though Agent didn't detect the keyboard, it seemed to work fine, except for the command button.

Things that made no difference:
- version of the software (I tried 1.2.5-1.2.3)
- if other keyboards were plugged in (I also had a Mac keyboard plugged in at first)
- other devices on the same hub (removing them made no difference)

**Comment by mondalaci** [comment]
@aki009 Thanks for the detailed description! Appreciate it a lot. USB hubs cause a lot of issues when it comes to firmware updates, and apparently they are also responsible for issues like this.

@ert78gb Please make Agent detect this scenario on OSX and display the permission setup screen without the "Set up permissions" button and "What will this do?" link. Change the "Your UHK has been detected ..." text to:

> Your UHK has been detected, but Agent can't talk to it. Your USB hub or docking station is probably the culprit. Please plug your UHK directly to your computer or use another USB hub.

Then automatically read the configuration whenever Agent can communicate with the UHK.

@aki009 You're welcome to suggest a better phrasing instead of mine.

**Comment by aki009** [comment]
That wording would work.

FWIW, I looked at your code and I didn't see any reason why it shouldn't pick up the keyboard when connected via the hub.

I have attached the output of util.inspect(HID.devices()) for both cases, the "direct" and "monitor", where the latter is through the hub in my monitor. In the former case the agent works in every case, and in the latter it never does.

For good measure I captured the settings twice. My node-foo is lacking so I didn't try to debug things further.

[direct1.txt](https://github.com/UltimateHackingKeyboard/agent/files/2157290/direct1.txt)
[direct2.txt](https://github.com/UltimateHackingKeyboard/agent/files/2157291/direct2.txt)
[monitor1.txt](https://github.com/UltimateHackingKeyboard/agent/files/2157292/monitor1.txt)
[monitor2.txt](https://github.com/UltimateHackingKeyboard/agent/files/2157293/monitor2.txt)

**Comment by mondalaci** [comment]
I think there's a difference between listing the devices and actually talking to them. The latter seems to be problematic.

Can you flash https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.3.3 via Agent and retry via your monitor hub? Please let me know how it works.

Don't forget to install the bundled firmware version in Agent afterwards, as firmware 8.3.3 is not stable according to my testing.

**Comment by aki009** [comment]
It did not improve the situation. I have attached node-HID output in case it helps.
[monitor3.txt](https://github.com/UltimateHackingKeyboard/agent/files/2160451/monitor3.txt)

**Comment by mondalaci** [comment]
I've taken a look at your log. We can't fix this one, merely display a warning message which we will do.

According to my experience, USB hubs range from mediocre to terrible and often don't properly handle sophisticated compound USB devices like the UHK.

**Comment by mondalaci** [comment]
@creeonix This is a good point, although the mentioned devices hardly expose as many interfaces as the UHK. We'll take another look at the USB descriptors.

**Comment by borgel** [comment]
I had the same problem, and moving my UHK closer to the root fixed it as well.
