### ISSUE TITLE
Agent doesn't start on Ubuntu 18.04

### ISSUE THREAD

**Issue by andreybratukhin** [UltimateHackingKeyboard/agent#709]
The latest version 1.2.5 of Agent doesn't start on Ubuntu 18.04. I installed required packages: `apt-get install libusb-dev libudev-dev g++` but it returns following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libusb-1.0.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/snap/uhk-agent/x1/resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/snap/uhk-agent/x1/resources/app.asar/node_modules/node-hid/nodehid.js:5:34)
```

**Comment by mondalaci** [comment]
Can you check if libusb is installed, and which version? It should depend on libusb-dev, but I'm not sure.

**Comment by andreybratukhin** [comment]
Here is output of `sudo apt show libusb-1.0`:

```
Package: libusb-1.0-0
Version: 2:1.0.21-2
Priority: standard
Section: libs
Source: libusb-1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Aurelien Jarno <aurel32@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 127 kB
Depends: libc6 (>= 2.17), libudev1 (>= 183)
Homepage: http://www.libusb.info
Task: standard
Supported: 5y
Download-Size: 43.3 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
Description: userspace USB programming library
 Library for programming USB applications without the knowledge
 of Linux kernel internals.
 .
 This package contains what you need to run programs that use this
 library.

Package: libusb-1.0-0-dev
Version: 2:1.0.21-2
Priority: optional
Section: libdevel
Source: libusb-1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Aurelien Jarno <aurel32@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 285 kB
Depends: libusb-1.0-0 (= 2:1.0.21-2)
Recommends: libusb-1.0-doc
Homepage: http://www.libusb.info
Supported: 5y
Download-Size: 60.5 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
Description: userspace USB programming library development files
 Library for programming USB applications without the knowledge
 of Linux kernel internals.
 .
 This package contains what you need for compiling sources that
 use this library in your own code.

Package: libusb-1.0-doc
Version: 2:1.0.21-2
Priority: optional
Section: doc
Source: libusb-1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Aurelien Jarno <aurel32@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,489 kB
Conflicts: libusb-1.0-0-dev (<< 1.0.16)
Replaces: libusb-1.0-0-dev (<< 1.0.16)
Homepage: http://www.libusb.info
Supported: 5y
Download-Size: 170 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
Description: documentation for userspace USB programming
 Library for programming USB applications without the knowledge
 of Linux kernel internals.
 .
 This package contains the libusb 1.0 API reference manual in HTML format.

```

**Comment by mondalaci** [comment]
This looks like an installation-specific issue of some sort. According to https://packages.ubuntu.com/bionic/amd64/libusb-1.0-0/filelist the libusb-1.0.so.0 file should be present on your system, but according to the output of Agent it's not, or can't be accessed by the linker. Can you check?

**Comment by DDzwiedziu** [comment]
I do have the exactly same problem.
 ```
# find /lib /usr/lib -name '*libusb*'
/lib/firmware/carl9170fw/extra/libusb-zeropacket.diff
/lib/i386-linux-gnu/libusb-1.0.so.0
/lib/i386-linux-gnu/libusb-1.0.so.0.1.0
/lib/x86_64-linux-gnu/libusb-1.0.so.0
/lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
/usr/lib/calibre/calibre/plugins/libusb.so
/usr/lib/x86_64-linux-gnu/freerdp/urbdrc-client-libusb.so
/usr/lib/x86_64-linux-gnu/libusbmuxd.so.4
/usr/lib/x86_64-linux-gnu/libusbmuxd.so.4.0.0```

**Comment by mondalaci** [comment]
Looks like you guys have libusb installed, but it doesn't mean that the linker can see it. Please run `ldconfig -v` and attach its output.

@DDzwiedziu Which Linux version exactly?

**Comment by DDzwiedziu** [comment]
@mondalaci almost same as OP: Kubuntu 18.04

ldconfig -v output: https://pastebin.com/XJNTjLH1

**Comment by mondalaci** [comment]
@DDzwiedziu What if you explicitly specify the linker path on the command line?

```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu ./UHK.Agent-x.y.z-linux-x86_64.AppImage
```

**Comment by DDzwiedziu** [comment]
It works, as far as the permission setup screen goes.

**Comment by mondalaci** [comment]
@DDzwiedziu

1. Does Agent work beyond the setup screen? Please give Agent a thorough try and let me know.
2. Please list the content of `/etc/ld.so.conf` and the content of every (recursively) included file. I want to get to the bottom of this.
3. Did you make a clean install of Kubuntu, or upgraded from a previous release? In the latter case, did the update process offered to update `/etc/ld.so.conf` or the content of `/etc/ld.so.conf.d/` which you rejected?

**Comment by DDzwiedziu** [comment]
Ad 1: Agent works. I was able to setup a new keymap, upload it, switch to it, confirm changes working, and back.
But, also the AppImage version works without explicitly setting LD_LIBRARY_PATH

Ad 2:
```
# for each in $(ls /etc/ld.so.conf /etc/ld.so.conf.d/*); do echo -e "\t$each"; cat $each; done
        /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

        /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf
/usr/lib/x86_64-linux-gnu/libfakeroot
        /etc/ld.so.conf.d/i386-linux-gnu.conf
# Multiarch support
/usr/local/lib/i386-linux-gnu
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/usr/local/lib/i686-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu
        /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib
        /etc/ld.so.conf.d/x86_64-linux-gnu.conf
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
        /etc/ld.so.conf.d/zz_i386-biarch-compat.conf
# Legacy biarch compatibility support
/lib32
/usr/lib32

# for each in $(ls /etc/ld.so.conf /etc/ld.so.conf.d/*); do grep -Hni '^/lib/x86_64-linux-gnu' $each; done
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:3:/lib/x86_64-linux-gnu
```

Add 3: It was an upgrade, but no files suggesting any upgrade conflicts were left. So I can't be certain, but would I answer the latter with "no".

**Comment by DDzwiedziu** [comment]
I've installed the snap. The OP has missed this, and I've did not notice, but the initial message is from trying to run the snap from the commandline. To the why I've chosen the snap it's probably that I've glanced at the release page looking for debs, and not seeing any I've went for the first known option. Kind of missed the connection from the big, fat "AppImage" on the last page of the onboarding guide to the smaller "AppImage" in the release files list.
Are the links on the last page of the onboarding guide suppose to link to the latest releases page (https://github.com/UltimateHackingKeyboard/agent/releases/latest) instead of the individual files?

**Comment by mondalaci** [comment]
Thanks for the useful feedback! The snap clearly seems to be broken. I believe it doesn't add any value over AppImage, merely causes support burden, so I'll remove them from releases, and we'll make electron builder not build snaps for future Agent releases.

The last page of the onboarding guide is not meant to link to the GitHub releases page for several reasons. First, to avoid issues like this. Second, to make downloading easier and more direct. Third, we'll move to a CDN that is way faster than GitHub and directly link it.

**Comment by mondalaci** [comment]
@andreybratukhin Please confirm that the AppImage works for you, too.

**Comment by mondalaci** [comment]
#719 makes sure that no snaps will be built in the future, and I manually removed the snaps of previous releases. I consider this issue to be resolved. Feel free to follow up if there's anything left.

**Comment by andreybratukhin** [comment]
I can confirm snap doesn't work but AppImage works fine.

**Comment by mondalaci** [comment]
Thanks, glad to hear!
