### ISSUE TITLE
Keep current selected layer when changing keymap

### ISSUE THREAD

**Issue by syl20bnr** [UltimateHackingKeyboard/agent#713]
Currently selecting a new keymap reset the selected layer to `Base`. It makes it tedious to compare same layer between keymaps. I believe this is a frequent use case where users want to configure a given layer across multiple keymaps (not necessarily all the keymaps) or just comparing them to see if they are in sync.

**Comment by mondalaci** [comment]
Although this has been suggested before, I feel a bit uneasy about it because I'm not sure about the expectations of most users. We can give it a try and see how users will react.

**Comment by syl20bnr** [comment]
Maybe another explanation why it may be a better solution is that resetting the layer is an implicit action that the user did not made so it may feel less natural. Obviously if the UI guessed it wrong it can be frustrating and feels more to be in the way than helpful.
Also it breaks some kind of symmetry where clicking on a layer just changes one thing but clicking on a keymap changes two things. It can be confusing in multiple ways as the new displayed layout is not only from a new keymap but also from a different layer at the same time.

That's great you consider to test it 👍

**Comment by mondalaci** [comment]
Thanks for articulating the advantages of your proposal. It makes sense to me and gives me confidence. Let's implement it and see what users say. I think chances are good that it's an improvement over the current behavior.
