### ISSUE TITLE
[Mac] Checking for update shows toast that it is disabled

### ISSUE THREAD

**Issue by jbcpollak** [UltimateHackingKeyboard/agent#723]
On my Mac when I click 'Settings->Check for update' I see a toast that reads:

> [AppUpdateService] Application update is skipped at first run.

This happens all the time, after I've restarted the agent, when I click the link multiple times, etc.

**Comment by jwr** [comment]
I can confirm that. It's always been like this for me, so I always updated the agent manually.

**Comment by mondalaci** [comment]
Thanks guys! Admittedly, the auto update is not working yet. We'll make it happen eventually.

**Comment by mondalaci** [comment]
This shouldn't be an issue anymore, but auto-update is broken nevertheless, so feel free to subscribe to #1148.
