### ISSUE TITLE
More mouse acceleration controls.

### ISSUE THREAD

**Issue by josh-hernandez-exe** [UltimateHackingKeyboard/agent#724]
I'm finding using the mouse with multiple (3 in my case) to be a bit cumbersome at times. The defaults work great on one monitor, but it takes quite a bit of time to move the mouse between multiple monitors. When I increase the top speeds and acceleration of the mouse settings, then I find that I over shoot my target when the target is close by but far enough that I instinctively use the accelerate mouse modifier right away.

Personally I would like a second accelerate mode for the mouse to zoom between monitors, and then use the normal setup with normal mouse movement within that monitor.

Though I have no current use for it, I don't see why you couldn't extend this feature to also allow an extra decelerate mode as well.

**Comment by mondalaci** [comment]
Implementing multiple acceleration / deceleration profiles would be rather overkill, but I'm quite confident that you'll be able to solve this with macros. We plan to implement macro support in the upcoming firmware release. Then you should be able to zoom between monitors easily with a touch of a keystroke.
