### ISSUE TITLE
The status of Scroll Lock

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#744]
It should be some way to indicate whether the scroll lock is on or off.

**Comment by luteijn** [comment]
Would be nice if there were more options to control the status leds and display, e.g. via the macro engine, so one could decide for themselves what to use them for.

**Comment by mondalaci** [comment]
@IzK666 Sorry, but I can't see a way of doing this properly given the lack of dedicated LEDs on the display.

@IzK666 @luteijn #660 will allow you to hack the content of the display.

**Comment by luteijn** [comment]
Something like this https://keyboard-leds.com/ could come in handy in the mean time. Another option could be to have Agent indicate some state in e.g. titlebar or notification area.

**Comment by kareltucek** [comment]
Also, one nasty workaround might be having multiple keymaps dedicated for different combinations of locking keys - then the abbreviation could be used to indicate possibly all three states (scroll, caps, num). 

The only problem is that macros currently don't have bindings for keymap switching. Which however is a reasonable general request. ( @mondalaci  Yeah, I know, another exotic feature :-).)
