### ISSUE TITLE
Give secondary role to layer switching option

### ISSUE THREAD

**Issue by iprok** [UltimateHackingKeyboard/agent#745]
We have secondary role for key only for general keypress. Can you allow using secondary role when layer switching? 
It will be great for example to bind "Toggle Mouse layer" to main role of "Mouse" button and "Activate Mouse layer" to its secondary role.

**Comment by mondalaci** [comment]
This is not planned, but tagging it as an exotic feature for future reconsideration and closing it in the meantime.
