### ISSUE TITLE
Data layer

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#75]
## Problem
For our UHK config I have something like this in mind. So we need to save, edit and delete key maps, macros, etc. Our data can come from two places. For web app user can upload their config file or we load default config file for them (if local storage is empty). For electron app we load file directly from the keyboard.

So to handle this efficiently we need to have a helper that will handle all events the same way and only at the last stage decide where to save the data. For webapp we will be using local storage (user can download JSON anytime) and for electron we will be saving data directly to keyboard.

I would use [ngrx/store](https://github.com/ngrx/store) for our configuration manipulation.

Why I would like to use store:
- we need to update state in multiple components at once
- we have state in one place
- we have logic for manipulating state in one place
- simplicity

## Implementation

I would create reducers for main parts (keymap, macro, addons). There would also be a file with all possible actions from all reducers.

### Actions
_action.ts_
```
// Keymap
export const KEYMAP_DEFAULT= 'KEYMAP_DEFAULT';
export const KEYMAP_TITLE = 'KEYMAP_TITLE';
.....

// Macro
export const MACRO_TITLE = 'MACRO_TITLE ';
export const MACRO_DELETE = 'MACRO_DELETE ';
.....

and so on
```
### Reducers
We need to avoid mutation within reducers. That's why we are creating new objects.

_keymap.reducer.ts_
```
export const keymaps:  Reducer<Keymap[]> = (state: Keymap[] = [], action: Action) => {
    switch(action.type) {
        case 'KEYMAP_DEFAULT':
            return state.map((keymap: Keymap) => {
                if(keymap.id == action.payload.id) {
                    keymap.isDefault = true;
                } else {
                    keymap.isDefault = false;
                }
                
                return Object.assign({}, state, keymap);
            });
        default:
            return state;
    }
};
```
### Model
Reducers would be then joined into one model that would then be used all over the application. 
```
this.model = Observable.combineLatest(
    _store.select('keymaps')
     _store.select('macros')
     _store.select('addons')
)
```

### Usage
Usage of the KEYMAP_DEFAULT action:
_keymap.component.ts_
```
defaultKeymap(id: string): void {
    this._store.dispatch({type: KEYMAP_DEFAULT, payload: {id: id}});
}
```

_keymap.component.html_
```
<i class="fa fa-star-o fa-star" (click)="defaultKeymap(keymap.id)"></i>
```

### Saving data
Every time the state is changed data helper for saving data will be triggered and data will be saved to the correct place (local storage or keyboard).

### Updating config file
There is also the possibility that user has old config file on their keyboard and he is using the latest version of our Agent with new config structure. In this case we have scripts for updating that will be inside the data helper and will handle update processes, so that user will have his config file updated automatically when he starts the Agent. Notification will be displayed to him while we are updating the configuration for him.

## Thoughts
What are your thoughts about this flow for data manipulation? You can read more about it [here](https://gist.github.com/btroncone/a6e4347326749f938510).
@mondalaci @fjozsef

**Comment by mondalaci** [comment]
Thanks for the detailed description, Nejc!

I have doubts whether the use of ngrx/store is justified in this case.

As for the saving of configuration data, do we truly need ngrx/store to detect when the model changes? Looks like it's a quite basic callback. Is there a native Angular 2 API for this purpose?

As for the loading of configuration data, it happens very rarely so it doesn't have to be optimized. Is there a native Angular 2 way for explicitly updating the view based on the changed model? Or does it happen automatically by Angular 2?

As you can see above, I'd like to see whether ngrx/store is truly necessary. It looks like a sophisticated API that significantly adds to the complexity of the project. I'd like to minimize complexity to keep the project easy to maintain.

**Comment by NejcZdovc** [comment]
@fjozsef I talked about this with @mondalaci on call and all things were cleared out. What do you thing about this approach?

**Comment by fjozsef** [comment]
Until now everything I wanted to solve could be done with data binding, using Input/Output (and OnChanges lifecycle hook) or with calling a service, so purely with Angular 2. 

I have watched [this](https://egghead.io/lessons/angular-2-ngrx-store-in-10-minutes) video about ngrx/store and I think I have understood in which cases would that be useful. My problem is that I can't decide now that we really need this sophisticated libary to solve our (future) problems.
@NejcZdovc Maybe if you could to clear me up with a use case in the agent, where ngrx/store would help a lot and it could not be done (or could be done, but only in ugly way) a feature in angular, then it would help me. The default keymap is not something we need across the application, besides it could be queried anytime from a service.

My first thoughts was that I would start implement it purely with angular 2 with service(s) and data binding and if we find a use case when it will be too complicated to implement it natively then we should consider the using of ngrx/store.

(But if you guys talked about it and both of you think that it would be useful to use, then I am not against it, because it seems promising.)

**Comment by mondalaci** [comment]
Personally, I'm not able to make an informed decision because I'm not sufficiently knowledgable about Angular, so I'm relying on you, guys. On principle, I agree that we should only use ngrx/store if it's truly needed and makes our life easier.

**Comment by NejcZdovc** [comment]
@fjozsef Like you said everything can be done with services, input/output one way or another, but it's not optimal. Yes you add dependency, but you get simplicity and order.

Regarding use case. I think that most typical use case is communication between side menu and main content. Basically when you edit key map title, save default, add new one, delete one all this actions needs to be represented in side menu. Same goes for macros. With store you automatically get observers so side menu just observes stores key map and macro. When something changes in the main app side menu is updated automatically. And yes this can be done with service, but you would need to prepare some more code and it's not that straightforward as is with store.

One use case that is more important for me and I found it when I was porting notifications to the app. In notification we have Undo button. Handling undo action is something else. If you check [this video](https://youtu.be/mhA7zZ23Odw?t=17m48s) you can see that store have already something in store for us for this :smiley:.

I like approach that store is giving us, because is simple, easy to control and straightforward. I know that it was created with more complex applications in mind that our is, but still I don't see why that should stop us from using it.

**Comment by fjozsef** [comment]
Then I would suggest to use ngrx/store in the first place and if it turns out that it's overkill, then we still can refactor our code.

**Comment by NejcZdovc** [comment]
Ok, as soon as I finish "add key map" page will start working on connecting whole page to the store.

**Comment by fjozsef** [comment]
@NejcZdovc Can we close this after #117 lands in the master?

**Comment by NejcZdovc** [comment]
Yes we can
