### ISSUE TITLE
Decouple Import Configuration from Save To Keyboard

### ISSUE THREAD

**Issue by eltang** [UltimateHackingKeyboard/agent#761]
I think Agent should pop up a dialog box to ask whether the user wishes to do this, or better yet allow the user to make changes to it before saving it to the keyboard manually.

**Comment by mondalaci** [comment]
Agreed. Agent will pop up a window saying:

> You are about to overwrite your configuration with the imported configuration.
> white [Cancel] button, red [Overwrite] button

**Comment by mondalaci** [comment]
Actually, I'm not sure at all if it's necessary. Users who use this feature have already exported their configuration, so they should have an idea what it's about. I'd rather implement this upon receiving complaints.

**Comment by IzK666** [comment]
I think you should split the functions import and save.
Maybe I want only to see a keymap that I downloaded from the internet and then decide if I want it or only watch to modify mine. (there are a few on github, but nothing useful)

Another reason is because is inconsistent with the export feature behaviour. You aren't forced to save it before you export it.

**Comment by mondalaci** [comment]
The recently implemented Configuration History feature allows users to restore previous configurations with two clicks each which should suffice for the time being.

As for the future, we'll eventually implement the UHK cloud via which sharing any part of UHK configurations will be a breeze.

**Comment by mondalaci** [comment]
Just a few minutes ago, @ert78gb contacted me saying that he thinks this should be implemented as it'd improve consistency as suggested, and he can implement it in no time. And so, I shall reopen this issue. Thanks for pushing it, guys!

**Comment by IzK666** [comment]
Thanks @ert78gb  :+1:
