### ISSUE TITLE
Node segfaults on get-variable.js and set-variable.js

### ISSUE THREAD

**Issue by iprok** [UltimateHackingKeyboard/agent#762]
I wanna try to do things mentioned here: https://github.com/UltimateHackingKeyboard/firmware/issues/128#issuecomment-407593713 .

Seems that I can set and get variables but node segfaults after doing this. 
~/work/agent/packages/usb $ ./set-variable.js debounceTimeRelease 40
node: /tmp/portage/dev-libs/libusb-1.0.21/work/libusb-1.0.21/libusb/io.c:2115: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.

~/work/agent/packages/usb $ LANG=C ./get-variable.js debounceTimeRelease 40
40
node: /tmp/portage/dev-libs/libusb-1.0.21/work/libusb-1.0.21/libusb/io.c:2115: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.

In dmesg:
[Пн авг 27 12:22:01 2018] node[8030]: segfault at 200 ip 00007f662b2a324b sp 00007f662a66ddc0 error 4 in libusb-1.0.so.0.1.0[7f662b299000+17000]
[Пн авг 27 12:23:58 2018] node[8112]: segfault at 200 ip 00007f6b7a9de24b sp 00007f6b79da8dc0 error 4 in libusb-1.0.so.0.1.0[7f6b7a9d4000+17000]

$ node --version
v8.11.3
libusb-1.0.21

gentoo linux amd64.

Agent was freshly cloned. Tried from user and root.

**Comment by mondalaci** [comment]
libusb / node-hid segfaults on some systems. We'll update it which will hopefully fix it.

On an unrelated note, please don't decrease the timeouts as they will only make chatter worse. Please leave it on 50-50 and rather try the suggested physical fix.
