### ISSUE TITLE
Alt+Tab triggers "Remap on all layers"

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#770]
When Alt is held during the opening of the key action popover, the "Remap on all layers" checkbox gets checked. This is correct behavior.

Interestingly, when Alt+Tab is used to switch to the Agent window, Agent behaves as if Alt was held. Alt stays virtually held until tapping Alt.

**Comment by mhantsch** [comment]
To clarify, the wrong behaviour occurs only if Alt-Tab is used first to switch AWAY from Agent. It does not matter how you switch windows back to Agent (you can use mouse clicks to focus Agent again, for example).

**Comment by mondalaci** [comment]
@mhantsch Thanks for the clarification! I wasn't aware of it, and I can confirm it.

I also noticed that when Alt is checked, and I open the popover the second time, it's not checked anymore, but this behavior works on a per layer, per key basis.

So when I use Alt+Tab to switch from Agent, go back, open the popover, then "remap on all layers" checkbox is checked, I open the popover for the same key, it's not checked anymore, open the popover for a different key or on a different layer then it's checked again.
