### ISSUE TITLE
Assigning a secondary role to a key without a primary role

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/agent#774]
Could be that possible?
Practical use: I'm using the fn layer (custom numpad on the right) and I need the arrows, which are on the mod layer. I want to use the small clicky keys (which I use in normal layer as mod keys) to do that without assigning them any other function when pressed/released (primary role).

Example:
![remapkey](https://user-images.githubusercontent.com/2158443/45391893-1e1c0c80-b625-11e8-9ec5-b210a91bfdef.png)

**Comment by mondalaci** [comment]
Sorry, but this isn't possible. You have to release the Fn layer, then switch to the Mod layer to access it.

We'll actually explicitly disallow this in the future to avoid misunderstandings by displaying:

"You can't use a secondary role without a primary role."

below the secondary role option and make the Remap Key button inactive when a secondary role is selected without a primary role.

**Comment by luteijn** [comment]
Actually, I think this is a bug. Not complaining, as I personally don't mind that this is possible and would prefer direct layer switching between non-default layers via primary functions to be possible anyway, but the layer switching assignments should probably not be available as secondary options on non-default layers, as far as I understand the current way of thinking/preference of the team.

FW 8.4.0: Remap a key on the FN layer to be primary shift + none, secondary MOD layer, then hold or lock keyboard to FN layer, hold down the remapped key and another key, e.g. the one mapped to caps-lock in the MOD layer.
MOD-led and CAPSLOCK-led go on, FN-led off. Release remapped key and FN replaces MOD led again.

**Comment by mondalaci** [comment]
@IzK666 The Remap Key is already inactive when no primary role is specified, indeed.

@luteijn I agree that layer switchers shouldn't be available as secondary options on non-base layers. We'll fix this. The mentioned case shouldn't be possible.

**Comment by luteijn** [comment]
"That's not a feature, it's a bug". Not sure if I should be happy for a bug to be squashed, or sad for losing a feature, as as you know I am in the "prefer no layer to be more equal than the others"-camp. :)
