### ISSUE TITLE
agent v1.2.9 doesn't have firmware 8.4.5 (like status report claims)

### ISSUE THREAD

**Issue by jheidemann** [UltimateHackingKeyboard/agent#777]
The monthly status report on 2018-09-13 says "If you’re reading this and already have your UHK, please upgrade to the latest 8.4.5 firmware in Agent!" and later that the latest version of agent is 1.2.9.

When I pull agent, checkout tag v1.2.9, I only get firmware 8.2.5, not 8.4.5.  That seems inconsistent with the report that implies the current firmware is in the current agent.

How does one get 8.4.5 firmware?  Shouldn't it come with a git pull and build of the v1.2.9 agent?

**Comment by mondalaci** [comment]
Firmware 8.4.5 is linked from the monthly status update. Please click on it, download it, and flash it via Agent.

**Comment by jheidemann** [comment]
You might want to change "flash it via Agent" to "flash it by selecting the .tar.bz2 file from the "choose firmware and flash it" option in Agent > Firmware.

(It is not obvious if you need to uncompress it, or rebuild the agent, or what...)

**Comment by mondalaci** [comment]
Great idea! Just updated our blog post as suggested. I'll try my best to be more explicit in the future.
