### ISSUE TITLE
Highlight the "Save to keyboard" button the first time it appears

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#782]
I've seen that [users sometimes don't notice](https://www.youtube.com/watch?v=VoBgLJGRKiM&t=5m03s) the "Save to keyboard" button, so let's show an animation that highlights it the first time it appears.

Use an SVG arrow that is easy to see and has the same color as the "Save to keyboard" button. Make the angle of the arrow so that it points exactly towards the button. Move the arrow from the center of the Agent window to the "Save the keyboard" button.

Make the arrow disappear when the user clicks in Agent. Make Agent only show this the first time, and don't ever show it again.

**Comment by mondalaci** [comment]
@mhantsch The "Save to keyboard" button should always appear in the right bottom corner of the Agent window regardless of the length of the macro actions of a macro. Can you still reproduce this with the latest Agent?

**Comment by mondalaci** [comment]
@dgyimesi You showed me a fancy animation a while back regarding this feature. Can you put the relevant code into a new branch? You're also welcome to upload the video. @ert78gb will take this over.

**Comment by dgyimesi** [comment]
Partial solution pushed to https://github.com/UltimateHackingKeyboard/agent/tree/feat/782-highlight-save-to-keyboard

**Comment by ert78gb** [comment]
@dgyimesi The referenced branch is empty. Could you look after? Maybe I didn't recognize something.
thx
