### ISSUE TITLE
Feature Request: Ability to send ESC when Ctrl+[ is pressed

### ISSUE THREAD

**Issue by asgeo1** [UltimateHackingKeyboard/agent#786]
Hi there,

I have a request which I think would be awesome.  If we had the ability to create special mappings for certain key combinations, that could send a totally different key code when pressed.

A good example is sending `ESC` when `Ctrl+[` is pressed.

That probably sounds a little random, but it's not for Vim users. If you're a Vim user, you probably know that pressing `Ctrl+[` in Vim actually is the same as pressing `Esc`.   And a lot of Vim users prefer this key combination, rather than pressing the real ESC key.  Especially, if you remap capslock to Ctrl, then it makes even more sense. (I've always done this).

Anyway, I figure I would like to use `Ctr+[` for ESC everywhere, not just in Vim! Given that it's already in my muscle-memory, it will be easy for me and seems an improvement over pressing `Mod+~`, which is the current default for ESC. (given no dedicated ESC in the base layout).

What do you think?

**Comment by mondalaci** [comment]
Hey there!

I think this is a great idea. So much so that we've already created #617 which will enable it. No ETA yet, but we'll make it happen eventually.

Closing this issue as a duplicate.

**Comment by asgeo1** [comment]
Thanks, that's awesome, I can't wait!
