### ISSUE TITLE
Exchanging key actions via drag and drop

### ISSUE THREAD

**Issue by lukasz-zaroda** [UltimateHackingKeyboard/agent#791]
It would be nice if we could just switch functions of two keys.

**Comment by mondalaci** [comment]
Like using drag and drop to exchange the source key with the destination key?

**Comment by lukasz-zaroda** [comment]
Yep, exactly. My use case is that I'm often writing in Polish, so I need an easy access to the right alt key to write Polish letters, so I decided to switch Fn and Alt on the right side, for easier access to the alt. It would be nice if I could just drag and drop keys configurations to switch them. :)

**Comment by mondalaci** [comment]
I like the idea, and this is not the first time I'm considering it. As for the actual implementation, I'm fairly confident that the Right Thing to do would be to exchange only the keys actions of the current layer of the current keymap, except for modifiers in which case they should be exchanged on ALL layers of the current keymap. Anything else to add?

**Comment by lukasz-zaroda** [comment]
I think it would be great if it would simply ask if we want to switch keys functions on the current layer or on all layers, or even some other things, but either way it would be great. I imagine that's one of the most common operations on the keymap, so having it as intuitive and simple as that, would be great. It's these simple things that make great user experience :) . BTW. Kayboard is amazing, thank you for all your work :) .

**Comment by mondalaci** [comment]
@ert78gb In Chrome 81, the mouse pointer changes over draggable elements:

![image](https://user-images.githubusercontent.com/300402/82843181-a1a28d80-9edc-11ea-875d-bd2289878ae1.png)

This would be very confusing for Agent keys. Is it possible to use the normal mouse icon over the keys?

**Comment by mondalaci** [comment]
* Exchange *modifier* key actions on *all layers* of the current keymap.
* Exchange non-modifier* key actions *only on the current layer* of the current keymap.
* If Shift is held when releasing the mouse button upon finishing dragging, exchange key actions on all layers of the current keymap regardless of the key action type.

**Comment by ert78gb** [comment]
The CSS defines default pointer types, but the rendering depends on the browser and OS.
Can define custom images as a pointer if the default is not good. In this case, the outfit will same on all OS.

**Comment by gnutix** [comment]
Awesome! I just received my new keyboard and spend quite a few hours these last few days in the Agent, and this is definitely a feature I thought would be awesome when one is still "figuring it out" and moving things around a lot. Glad to see it just moved into the Priority issues. :+1:
