### ISSUE TITLE
Macros: right mouse click and middle mouse click are swapped

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#794]
When I use right mouse click in a macro, the application seems to receive a middle mouse click.
When I use middle mouse click in the macor, then the application receives a right mouse click.

**Comment by mondalaci** [comment]
Thanks for reporting! The fix will be included into the upcoming Agent release.

**Comment by mhantsch** [comment]
Will I have to modify my current macro, and re-save my keyboard configuration, or is this simply an incorrect display string in Agent (which will be corrected in the next Agent release)?

**Comment by mondalaci** [comment]
The latter.
