### ISSUE TITLE
Make Right click, Esc set the key action to none

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#798]
Currently, there is number of ways how to map a key quickly via right mouse, however I do not see any way to unmap a key quickly. I personally need to unmap keys slightly more often than I need to map them.

Ctrl + click seems unused at the moment so that might be used?

**Comment by mondalaci** [comment]
Ctrl and Alt are already utilized, even for right click. See the help screen of recent Agent versions. Other modifiers can't be used in a cross-platform manner (we tried). I can't see a way to make this happen, so I'm closing this issue, but feel free to follow up.

**Comment by mondalaci** [comment]
I can't remember the details, but the bottom line is that Super and Ctrl can't be used in a cross-platform manner in Electron.

I think your suggested behavior is the most intuitive one. We'll make right-click, then Esc set the relevant key action to None.

**Comment by luteijn** [comment]
Although I've been remapping escape a lot the last few days, trying out some alternatives, in general I would agree. Middle click might be an alternative, although currently it seems to do the same as right click? 
Related to this, maybe at the same time of addding the escape as a way to clear assignment, make it also possible to unmap a key by selecting none as the scan code, no modifiers and no secondary role?

**Comment by mondalaci** [comment]
@luteijn Middle click has similar cross-platform issues as modifiers. Can't trigger it on Mac.

I don't feel strongly about your second suggestion, but I find it conceptually cleaner to set None actions only one way.

**Comment by ert78gb** [comment]
IMHO breaking the generic logic is not straight forward;

**Comment by kareltucek** [comment]
(@mondalaci  @dgyimesi @ert78gb As was suggested in #848, there are at least another two options how to realize the feature request without voiding generality - either "<shortcut> + <click key>" or "<shortcut> + <mouseover>". I strongly support these, since they provide sufficient number of shortcut combination for future extensions of similar nature.)

**Comment by mondalaci** [comment]
@kareltucek I don't like the suggested solutions. Accidental keypresses can lead to unintended actions.

**Comment by kareltucek** [comment]
I mean, lets choose a shortcut - lets say Ctrl+N (as None), which will clear any key which is currently under the cursor.

(I can't see how a user can possibly type shortcut like that by accident.)

**Comment by mondalaci** [comment]
I understand what you're suggesting, but the idea of shortcuts that are dependent on the hovered item don't feel right to me.

**Comment by mondalaci** [comment]
We ended up [not implementing this](https://github.com/UltimateHackingKeyboard/agent/pull/897#issuecomment-455884232) due to the sake of consistency.
