### ISSUE TITLE
Run agent off-line so without UHK attached to computer

### ISSUE THREAD

**Issue by luteijn** [UltimateHackingKeyboard/agent#800]
When agent is started without the UHK connected, I think there should be an option to run it anyway, so one can work on trying things out, make an entire new layout, or work on a previously exported one.
Bonus points if the last (few?) configurations pushed to the keyboard are cached and available for working on 'off-line'. 

Currently it just blocks, looking for the keyboard forever, which isn't very useful if the keyboard is at work/home, while I'm at home/work instead.

**Comment by mondalaci** [comment]
Blocking has a purpose. Agent explicitly asks for a UHK to be connected. Users are expected to use [the demo](http://ultimatehackingkeyboard.github.io/agent/) in this case. I'm closing this issue.
