### ISSUE TITLE
Ctrl key key downs, but doesn't key up in a certain configuration

### ISSUE THREAD

**Issue by owlowlgo** [UltimateHackingKeyboard/agent#801]
Apologies in advance if this is not a bug, but I would like to describe some unexpected behavior with the following settings:

![image](https://user-images.githubusercontent.com/14905970/46253237-60609d00-c4b1-11e8-8a9d-fde423ebd6aa.png)

I have remapped the Ctrl key to "Ctrl + c", as a shortcut for Copy. Same with the Super key, but for Paste.

This works. However, it appears that the Ctrl key keys down, but a key up does not occur. This causes all consecutive keys to be pressed with the Ctrl key down. Hitting backspace somehow causes the Ctrl key to be released.

Oddly, this does not occur with another shortcut I assigned for "Ctrl + Space". (Switch between English and CJK language input)

![image](https://user-images.githubusercontent.com/14905970/46253286-5ee3a480-c4b2-11e8-83cd-560ebd2e781c.png)

My OS is Ubuntu, if that matters.

Thank you.

**Comment by mondalaci** [comment]
Thanks for reporting! I can clearly reproduce this, but this is a firmware issue. Would you please create the same issue in the firmware repo?
