### ISSUE TITLE
Add parentheses () scan codes to the Punctuation options

### ISSUE THREAD

**Issue by ajh3** [UltimateHackingKeyboard/agent#804]
I would like to set up my left and right shift keys to send ( and ) respectively, with Shift as a secondary role. This does not seem to be possible at the moment, as it is only possible to set them to the "9 (" or "0 )" scancodes, which send 9 and 0 instead of ( and ), even when Shift is set as a modifier. 

It is possible to send other types of brackets this way, like [] and {}, since they are already in the list of Punctuation options. Can you add () as well?

**Comment by mondalaci** [comment]
It's possible to set ( and ). Just just have to toggle left or right Shift. The same way you'd press these keys: Shift+9 results in )

**Comment by ajh3** [comment]
My settings seem to be what you describe, but pressing Shift results in typing 9, not (.

I also tried setting RShift as the modifier instead of LShift, as well as both LShift and RShift together, and the result is the same.

Am I doing something wrong? 

![l3gt02y](https://user-images.githubusercontent.com/40405382/46264704-82b7e200-c4d4-11e8-839b-862ace77a956.png)

**Comment by mondalaci** [comment]
Did you save your configuration to the keyboard? (The button in the right bottom corner)

**Comment by ajh3** [comment]
Yes. I have also tried this for scan codes other than 9(, and modifiers other than Shift. 

It seems that when a secondary role is defined for a key, any Modifiers set on that key stop working.

**Comment by mondalaci** [comment]
@ajh3 This works well for me with [firmware 8.5.1](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.5.1). Please flash it via Agent and give it a try.
