### ISSUE TITLE
Macro message out of date

### ISSUE THREAD

**Issue by sad2project** [UltimateHackingKeyboard/agent#806]
On the macro screen, it say "Please note that macro playback is not implemented yet. You can create macros, but they won't have any effect until firmware support is implemented. We're working on this."

This is despite the fact that I have a firmware that runs macros and the newest release of Agent.

**Comment by mondalaci** [comment]
I didn't forget about this. I simply don't want to branch to show/hide this message depending on the firmware version. I'd much rather simply remove the message, but first we'll have to factory flash a new firmware version that implements that macro engine, and then wait about a month for every such UHK to be delivered via Crowd Supply.

**Comment by mondalaci** [comment]
Closing in favor of #822.
