### ISSUE TITLE
Firmware version specific feature display

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#822]
If the firmware version of the right half is larger or equal to 8.4.3 then:
* Hide the "Please note that macro playback is not implemented yet. You can create macros, but they won't have any effect until firmware support is implemented. We're working on this." message from the macro tab of the key action popover and from the pages of the macros.
* Enable the --layer-double-tap=true feature.

**Comment by SirVer** [comment]
@mondalaci Is there an ETA for support for macros in the firmware?

**Comment by mondalaci** [comment]
@SirVer It's already done. Please update to the latest firmware.

**Comment by SirVer** [comment]
@mondalaci Will this come automatically with the next Agent release? In the current one it does not seem to be enabled.

**Comment by mondalaci** [comment]
It is enabled, just not displayed as such. It will be displayed correctly in the next Agent release.
