### ISSUE TITLE
Add option to disable animations

### ISSUE THREAD

**Issue by Nicd** [UltimateHackingKeyboard/agent#823]
When Agent is running on a HiDPI screen (like Retina display or 4k) and is covering the screen (like it does by default), the key popup animation is very slow and makes the user's experience worse. Please see this video for a demonstration: https://youtu.be/gPKzmnGdPeU

This issue has been reproduced on two MacBook Pro laptops (2014 and 2016 models) that weren't running anything intensive at the time and where other applications run without such issues. If the screen is resized to be small, the animations get faster.

The animations are not needed for the use of the application and disabling them would provide better UX. Alternatively if a fix for the animations' performance issues is found, that is also acceptable.

**Comment by kareltucek** [comment]
Regarding performance, I would like to add that I experience some problems even with standard low-dpi screen. The most annoying part is the search box in the first tab of the key popover - it takes usually around 2 sec to show results.

**Comment by mondalaci** [comment]
@kareltucek Please state the OS and spec of your computer.

**Comment by kareltucek** [comment]
ArchLinux
Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz (4 x 2.2Ghz)
Intel HD Graphics
8GB RAM

**Comment by mondalaci** [comment]
Closing this issue in favor of the generalized #716.
