### ISSUE TITLE
Agent cannot connect on macOS Mojave 

### ISSUE THREAD

**Issue by khwerhahn** [UltimateHackingKeyboard/agent#829]
Hi,

the setup process for the agent seems to fail. I can use the keyboard out of the box, but I cannot configure it with the Agent. I have `node` installed and did `brew install libusb libusb-compat`. I downloaded the latest mac dmg. When I open the app I get the following message:

![screenshot 2018-10-11 at 21 23 56](https://user-images.githubusercontent.com/3821617/46829021-db249480-cd9c-11e8-864a-3aa30e2a2c10.png)

Manually installing the script as displayed also fails:

![screenshot 2018-10-11 at 21 25 52](https://user-images.githubusercontent.com/3821617/46829132-41111c00-cd9d-11e8-9d7c-ac9aa4de9af7.png)

What am I doing wrong? 

System specs:
![screenshot 2018-10-11 at 21 25 31](https://user-images.githubusercontent.com/3821617/46829168-5ab26380-cd9d-11e8-8dc1-88c2a408ad41.png)

**Comment by mondalaci** [comment]
This message should only show on Linux. You're supposed to use the latest Agent dmg file to install Agent. Which Agent version did you try?

**Comment by khwerhahn** [comment]
UHK.Agent-1.2.11-mac.1.2.11.dmg

**Comment by mondalaci** [comment]
@ert78gb Can you check this?

**Comment by ert78gb** [comment]
It works perfectly for me, but I have an older mac with USB-A connector. My feeling something changed with the Type-C connector or the USB-A -> Type C connector cause the error.
@khwerhahn Can you use the keyboard for normal typing and only the agent not able to start?

**Comment by khwerhahn** [comment]
@ert78gb all functionality works fine (typing, mouse, etc) except for the agent. I can also change the keyboard type under settings. The keyboard is plugged into an apple thunderbolt screen which is connected via a usb-c dongle to the mac.

**Comment by mondalaci** [comment]
@ert78gb What is the condition which triggers the privilege escalation screen? It's surely not os == 'linux'.

**Comment by ert78gb** [comment]
@mondalaci The Agent show this screen when could not read any USB device info.

@khwerhahn Pls start the agent from the terminal and copy the log here. The log contains what are the available USB devices.

**Comment by mondalaci** [comment]
I think it'd be worth to check the OS explicitly, and if Agent can't read USB device info and the OS is not Linux then it should display something else instead of the privilege escalation screen. I'm not sure yet what it should display exactly, but I'll figure it out.

**Comment by khwerhahn** [comment]
@ert78gb could you please be more specific about how you want me to start it from the terminal? Clone and build? Launch the app via terminal command?

**Comment by mondalaci** [comment]
@khwerhahn Either. Starting an official release in the terminal would be the simplest way to do it.

**Comment by ert78gb** [comment]
@khwerhahn just 
- open a terminal
- run `open "/Applications/UHK Agent.app/Contents/MacOS/UHK Agent"` command. It will open a new terminal window and start Agent.
- if you finished/ got an error. Activate the new terminal window and press CMD+s and this command save the terminal content into file. After pls zip the file and attach. thx

**Comment by khwerhahn** [comment]
@ert78gb thanks. See attached.
[Terminal Saved Output.txt.zip](https://github.com/UltimateHackingKeyboard/agent/files/2481708/Terminal.Saved.Output.txt.zip)

**Comment by mondalaci** [comment]
According to the log, Agent can't open the device (your UHK). Please run Agent as root to see if it can access your UHK this way.

**Comment by mondalaci** [comment]
Is the `open` command necessary? I'm worried that it might interfere in some way. Would you be able to directly run Agent without `open` as root?

**Comment by khwerhahn** [comment]
It doesn`t change anything. Same outcome.

**Comment by mondalaci** [comment]
Can you check this on another Macbook Pro that runs a preferably fresh, virgin installation of macOS Mojave?

**Comment by mondalaci** [comment]
Closing this issue due to the lack of reply.
