### ISSUE TITLE
Agent freezes on Windows

### ISSUE THREAD

**Issue by aaronbabaron** [UltimateHackingKeyboard/agent#832]
Hey all,

I have the agent exe file on my windows pc. It takes about 3 minutes to boot up, and once it boots, it freezes every time i perform an action. If I scroll the mousewheel it freezes, if I try to click on anything it freezes, and eventually (a minute or two later) it unfreezes until I perform another action. It's basically unusable at this point, is there something I'm missing? I'm using build 1.2.11

**Comment by mondalaci** [comment]
1. Do you use a USB hub or docking station?
2. What are the specs of your computer?
3. What is your exact Windows version?

Please try to connect your UHK directly to your computer, and try every one of its USB ports.

**Comment by aaronbabaron** [comment]
1. No, the keyboard is plugged into a USB 3.0 port directly on the motherboard. tried a 2.0 port as well
2. i7 7700k, 32gb 3333mhz ram, 1080ti, 1.5gb m.2 storage
3. Windows 10 v 1803

**Comment by aaronbabaron** [comment]
So it turns out the issue is because I was loading the application using the downloaded .exe file

Once I used the installed exe it ran without issue. I didn't see any installation bars/prompt show up so I didn't know that the downloaded file was an installer and not the program itself.

**Comment by mondalaci** [comment]
This for the follow-up! This is very weird, and haven't heard about others having this issue. Have fun!
