### ISSUE TITLE
Mouse movement in macros 

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#833]
Hi,

let's assume macro which moves the mouse to an absolute position 50, 100:

- move -9999, -9999
- move 50, 100

For some reason, the mouse cursor ends up at coordinates (91, 183) (exactly). I assume that PC-sided drivers may be blamed for this due to speed/acceleration scaling on the PC side, even tough the settings seems to be in 1:1 ratio on my side. However even if this is "correct" behaviour, it still makes creation of such macros very difficult for regular user. 

I am neither sure where the problem is, nor what the ideal solution would be. 

Archlinux with standard Xorg server here. I am not aware of any non-default mouse sensitivity settings being applied. The behaviour persists even after applying `xset m 0 0`. Digging into UHK/mouse props yields the following:

	me@zotac ~ $ xinput list
	⎡ Virtual core pointer                          id=2    [master pointer  (3)]
	⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
	⎜   ↳ Wacom Intuos PT S 2 Pen stylus            id=10   [slave  pointer  (2)]
	⎜   ↳ Wacom Intuos PT S 2 Finger touch          id=11   [slave  pointer  (2)]
	⎜   ↳ Wacom Intuos PT S 2 Pad pad               id=12   [slave  pointer  (2)]
	⎜   ↳ Logitech M570                             id=17   [slave  pointer  (2)]
	⎜   ↳ Logitech M325                             id=18   [slave  pointer  (2)]
	⎜   ↳ Logitech K230                             id=19   [slave  pointer  (2)]
	⎜   ↳ Ultimate Gadget Laboratories Ultimate Hacking Keyboard    id=15   [slave  pointer  (2)]
	⎜   ↳ Ultimate Gadget Laboratories Ultimate Hacking Keyboard    id=21   [slave  pointer  (2)]
	⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
	    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
	    ↳ Power Button                              id=6    [slave  keyboard (3)]
	    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
	    ↳ Power Button                              id=8    [slave  keyboard (3)]
	    ↳ Sleep Button                              id=9    [slave  keyboard (3)]
	    ↳ Nuvoton w836x7hg Infrared Remote Transceiver      id=20   [slave  keyboard (3)]
	    ↳ Logitech K230                             id=22   [slave  keyboard (3)]
	    ↳ Ultimate Gadget Laboratories Ultimate Hacking Keyboard    id=13   [slave  keyboard (3)]
	    ↳ Ultimate Gadget Laboratories Ultimate Hacking Keyboard    id=14   [slave  keyboard (3)]
	    ↳ Ultimate Gadget Laboratories Ultimate Hacking Keyboard    id=16   [slave  keyboard (3)]
	me@zotac ~ $ xinput list-props 13
	Device 'Ultimate Gadget Laboratories Ultimate Hacking Keyboard':
	        Device Enabled (140):   1
	        Coordinate Transformation Matrix (142): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	        libinput Send Events Modes Available (260):     1, 0
	        libinput Send Events Mode Enabled (261):        0, 0
	        libinput Send Events Mode Enabled Default (262):        0, 0
	        Device Node (263):      "/dev/input/event8"
	        Device Product ID (264):        7504, 24866
	me@zotac ~ $ xinput list-props 14
	Device 'Ultimate Gadget Laboratories Ultimate Hacking Keyboard':
	        Device Enabled (140):   1
	        Coordinate Transformation Matrix (142): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	        libinput Send Events Modes Available (260):     1, 0
	        libinput Send Events Mode Enabled (261):        0, 0
	        libinput Send Events Mode Enabled Default (262):        0, 0
	        Device Node (263):      "/dev/input/event6"
	        Device Product ID (264):        7504, 24866
	me@zotac ~ $ xinput list-props 16
	Device 'Ultimate Gadget Laboratories Ultimate Hacking Keyboard':
	        Device Enabled (140):   1
	        Coordinate Transformation Matrix (142): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	        libinput Send Events Modes Available (260):     1, 0
	        libinput Send Events Mode Enabled (261):        0, 0
	        libinput Send Events Mode Enabled Default (262):        0, 0
	        Device Node (263):      "/dev/input/event7"
	        Device Product ID (264):        7504, 24866
	me@zotac ~ $
	me@zotac ~ $ xinput list-props 15
	Device 'Ultimate Gadget Laboratories Ultimate Hacking Keyboard':
	        Device Enabled (140):   1
	        Coordinate Transformation Matrix (142): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	        libinput Natural Scrolling Enabled (318):       0
	        libinput Natural Scrolling Enabled Default (319):       0
	        libinput Send Events Modes Available (260):     1, 0
	        libinput Send Events Mode Enabled (261):        0, 0
	        libinput Send Events Mode Enabled Default (262):        0, 0
	        Device Node (263):      "/dev/input/event7"
	        Device Product ID (264):        7504, 24866
	        libinput Drag Lock Buttons (320):       <no items>
	        libinput Horizontal Scroll Enabled (321):       1
	me@zotac ~ $ xinput list-props 21
	Device 'Ultimate Gadget Laboratories Ultimate Hacking Keyboard':
	        Device Enabled (140):   1
	        Coordinate Transformation Matrix (142): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	        libinput Natural Scrolling Enabled (318):       0
	        libinput Natural Scrolling Enabled Default (319):       0
	        libinput Scroll Methods Available (322):        0, 0, 1
	        libinput Scroll Method Enabled (323):   0, 0, 0
	        libinput Scroll Method Enabled Default (324):   0, 0, 0
	        libinput Button Scrolling Button (325): 2
	        libinput Button Scrolling Button Default (326): 2
	        libinput Middle Emulation Enabled (327):        0
	        libinput Middle Emulation Enabled Default (328):        0
	        libinput Accel Speed (329):     0.000000
	        libinput Accel Speed Default (330):     0.000000
	        libinput Accel Profiles Available (331):        1, 1
	        libinput Accel Profile Enabled (332):   1, 0
	        libinput Accel Profile Enabled Default (333):   1, 0
	        libinput Left Handed Enabled (334):     0
	        libinput Left Handed Enabled Default (335):     0
	        libinput Send Events Modes Available (260):     1, 0
	        libinput Send Events Mode Enabled (261):        0, 0
	        libinput Send Events Mode Enabled Default (262):        0, 0
	        Device Node (263):      "/dev/input/event9"
	        Device Product ID (264):        7504, 24866
	        libinput Drag Lock Buttons (320):       <no items>
	        libinput Horizontal Scroll Enabled (321):       1

**Comment by mondalaci** [comment]
OS drivers calculate some sort of inertia which makes the actual coordinates differ. The way around is to insert small delays between mouse movement macro actions.

**Comment by kareltucek** [comment]
Thanks for quick reply!

Turns out hat timeout itself does not suffice on my machine. I had to add one more small movement before the delay and then wait for at least 0.2 sec (0.1 would still misbehave badly). Even 5 second delay would not make difference by itself. So the final procedure is:

- move (-2000, -2000)
- move (-1, -1)
- wait 0.2 sec
- move (50,100)

**Comment by kareltucek** [comment]
However, with longer distances, even that doesn't work properly on my side. I will have to adjust the coordinates via trial & error :-/...
