### ISSUE TITLE
Pressing a combination of two buttons with secondary roles won't trigger a secondary role

### ISSUE THREAD

**Issue by anton-nikan** [UltimateHackingKeyboard/agent#836]
I have two buttons with secondary roles: both switch to different layers (say, left space switches to Fn, right space to Mod). I want right space to work as a backspace on Fn layer but holding left space (Fn) and pressing right space does not have any effect.

Attaching my configuration.

[UserConfiguration.txt](https://github.com/UltimateHackingKeyboard/agent/files/2492500/UserConfiguration.txt)

**Comment by mondalaci** [comment]
You did not configure any action for the right space of the Fn layer of your default keymap, hence it doesn't do anything. As soon as I mapped backspace, it worked flawlessly.

**Comment by anton-nikan** [comment]
I think I sent the wrong config, adding it again here. I still can't get it working by assigning backspace on the right space on Fn layer. See the screenshot how I have it. When I'm pressing left space-right space nothing happens. When I release right space nothing happens. When I release left space the space is added so it seems like it does not recognize the secondary function on the left space (which is Fn) when I press it with right space.

![uhk-fn-backspace](https://user-images.githubusercontent.com/593183/47204924-32be9380-d38d-11e8-982c-53b28ee53044.png)

[UserConfiguration.txt](https://github.com/UltimateHackingKeyboard/agent/files/2494889/UserConfiguration.txt)

**Comment by anton-nikan** [comment]
@mondalaci, did you manage to reproduce this with last config I sent?

**Comment by kareltucek** [comment]
@anton-nikan I've tried it and it works just fine... Are you using the latest firmware? (8.5.3) This used to be bugged on some older versions...

**Comment by anton-nikan** [comment]
Sorry guys for wasting your time. Somehow I checked the firmware section of the app and missed that it's not latest. Now it works, thanks.

**Comment by kareltucek** [comment]
No problem ;-)
