### ISSUE TITLE
Create a "clear layer" button

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/agent#838]
I would like to have a "clear layer" button. This button would do precisely what it suggests: it sets all actions of the layer to "None". Reason that I want this: I want to restart programming a layer, for instance one for a specific map for a game. Generally you want to copy Maps, because you will still want the Base QWERTY layer. However, in that case you'll also get all of the layers, including many buttons that you do not want.

**Comment by owlstead** [comment]
I would like to have a "clear layer" button. This button would do precisely what it suggests: it sets all actions of the layer to "None". Reason that I want this: I want to restart programming a layer, for instance one for a specific map for a game. Generally you want to copy Maps, because you will still want the Base QWERTY layer. However, in that case you'll also get all of the layers, including many buttons that you do *not* want.

**Comment by mondalaci** [comment]
I don't foresee this feature used by many. I'm marking this as an excotic feature, and may reconsider it later.

**Comment by kareltucek** [comment]
@owlstead #798 targets similar usecase ;-)

**Comment by owlstead** [comment]
Yeah, if there is a very quick way of clearing individual cells then this feature becomes less relevant. Maybe I'll play around a bit and hack the JSON files programmatically; clearing all keys - except the Map keys - should be easy. I've already edited in the QWERTY map after destroying it, but doing that manually is tricky. Nice that the agent has some checks build in on the correctness of the keymaps in the configuration anyway.

**Comment by luteijn** [comment]
some quick and dirty external 'tools' to manipulate json file to  splice/merge/clear/etc of layers/maps in perl/python are something I've considered making. So far have managed to repress the urge, mainly because I'd like to see the 'standard' stabilize first. Secondary reason is lack of time/energy :)

Similarly, me hacking on the firmware and cli versions of tools to up/download config to/from the UHK will have to wait a bit...
