### ISSUE TITLE
Hide "Save to Keyboard" button when storing firmware

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/agent#839]
I was very surprised when the button "Save to Keyboard" persisted on my screen when I was writing the firmware. Maybe it is a good idea to hide it. I didn't try if I could click it by the way, I just have my UHK and I don't want to brick it right away.

It's quite heavy, so an UHK would certainly make a great and expensive set of bricks - just joking guys :P

**Comment by owlstead** [comment]
I was very surprised when the button "Save to Keyboard" persisted on my screen when I was writing the firmware. Maybe it is a good idea to hide it. I didn't try if I could click it by the way, I just have my UHK and I don't want to brick it right away.

It's quite heavy, so an UHK would certainly make a great and expensive set of bricks - just joking guys :P

**Comment by mondalaci** [comment]
Writing the firmware is completely different from saving the configuration. The former is stored in the flash of the MCU. The latter is stored in a dedicated EEPROM IC. I think the current behavior is right.

**Comment by owlstead** [comment]
I'll retest what is happening when flashing the firmware, but I'd not close issues as easily as you do. If I remember correctly the rest of the screen is hidden, but not the button.

**Comment by mondalaci** [comment]
The reason I closed this is because based on your description, it does seem like a non-issue. If you provide a good reason why it is an issue, I will reopen it.
