### ISSUE TITLE
Make the Map-Switch keys stick on all maps

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/agent#840]
I managed to almost lock myself in when using the mapping keys. I forgot to add a map to a layer on a specific map. So hitting Fn-MapX did do nothing at all, I first had to switch to the first map just to be able to switch to another map. Choosing which map is activated by a key on a specific layer is nice - very nice. But I don't think the mapping should change between maps, that's just too confusing.

One disadvantage of changing this is when the key on the Fn layer gets reused and subsequently overwritten. But I think the current difficulty in placing the map keys in the right spot - without forgetting any map - is a much bigger disadvantage. Currently it is just too tricky to get right.

**Comment by kareltucek** [comment]
You've got a "map on all keymaps" checkbox on the key popover which solves your problem.

Also, in case you don't own another keyboard or mouse, you still have the temporary factory reset button on the back side, which you can use to fix the problems.

I don't understand what exactly you are requesting in this request but I'm am pretty sure that I am very strongly against that.

**Comment by mondalaci** [comment]
@owlstead I don't understand your terminology. I don't know what you mean by "mapping keys", a "map", and such. Please use the established UHK terminology of keymaps, layers, and possibly provide a concrete example of what you'd like to achieve.

I'm closing this one, and will reopen it if it turns to be an issue.
