### ISSUE TITLE
Save / load keyboard maps

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/agent#841]
One thing I see happening - especially if a user forum would exist - is the sharing of key maps and macro's.

Currently this is only possible by copying a full configuration. But it doesn't seem possible to store / load a single map. You can of course do this by hacking the JSON file, but it is easy to make mistakes when doing this, and then the configuration will not load, giving a very generic error message.

It would similarly be easy if you could load a standard map from the internet, in case you buggered up the map too extensively. Destroying & recreating all your custom maps doesn't seem to be the way to go when you just want to reset your basic QWERTY map.

Thought should go in saving / restoring macros and Map keys.

**Comment by mondalaci** [comment]
This will be part of much broader cloud sync / cloud profile functionality. I'd rather not have individual issues for this, but rather write a spec when the time comes.

**Comment by owlstead** [comment]
What happened to the "exotic feature" mark? I think it is awfully strange that there is no User Forum yet, and I find it disconcerning that sharing keyboard maps is not a feature on something that promotes hacking, to be honest. I'm writing up a review for the Dutch Tweakers site and I'll put this in as a major drawback.

**Comment by owlstead** [comment]
OK, that makes sense, let me know here if you need help with any of this. I was even considering implementing my own user forum (CMS'es such as Joomla have plugins for that), but I don't want to compete with one of the makers either.

**Comment by mondalaci** [comment]
Thanks for offering your help! We'll probably pick either Reddit or Discourse soon.
