### ISSUE TITLE
Create a way to cancel running macros

### ISSUE THREAD

**Issue by ajh3** [UltimateHackingKeyboard/agent#843]
I suggest adding a way to specify a key to cancel the currently-running macro. Some of my macros take several seconds to complete, and if I wrongly start one, it would be nice to be able to hit Escape (for example) to stop it, without having to wait for it to complete.

**Comment by piratk** [comment]
Alternatively, there could be a "keep button(s) pressed to continue macro"-feature, so, for instance, pressing "Fn+R" runs a macro which is 10s long, but when releasing "Fn", it would stop.

**Comment by mondalaci** [comment]
I'm reluctant to add this feature. Do you have something like this in [your firmware fork](https://github.com/kareltucek/firmware), @kareltucek?

**Comment by kareltucek** [comment]
Not in a straightforward manner, but yes, it can be done.

**Comment by mondalaci** [comment]
So glad to hear! Feel free to elaborate how. I'm closing this ticket.

**Comment by kareltucek** [comment]
One way is to signal by a "register" (basically a global variable which is accessible from macro command) - as described in kareltucek/firmware#44, but the receiver macro has to be written to react to this. Various magic can be done with other conditionals too, or even by using the postponer...

All these approaches however need the macro to explicitly contain a clause to voluntarily exit. 

If desired, I can easily add a new command that would simply stop all macros in a straightforward manner.

**Comment by mondalaci** [comment]
Thanks for elaborating! Please don't spend time on this unless there's a decent demand.
