### ISSUE TITLE
Macro reference count

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#847]
Small enhancement idea - it would be nice if agent showed count of references for each macro. I.e., how many times a macro is referenced from keymaps.

Usecase - I wanted to clean up my macros a bit - delete unused ones etc., but oops... Which ones are actualy unused? 

(of course, this is an extremely-low-priority request)

**Comment by mondalaci** [comment]
This feature makes sense to me, although I'm wondering if we should clutter the UI by displaying the counts. Maybe a "Delete unused macros" button would be a nicer solution.

**Comment by kareltucek** [comment]
I don't think that "Delete unused macros" is a good solution, because it makes a huge-and-ingeneral assumption about what the user actually wants. (In other words: I don't always want to delete all unused macros.)

I think that the count itself is not very important - it is the indication of unreferenced macros that matter. E.g., showing reference count (or some sort of indication) only for unreferenced macros would be totally sufficient.

**Comment by kareltucek** [comment]
(I am not sure which form it should take - these things can be indicated by very subtle means like different font type supplemented by mouseover tooltip or a small icon next to unreferenced macros...)

**Comment by mondalaci** [comment]
I tend to agree about a general solution. I think we should display the counts in the sidebar aligned rightwards within [bootstrap pills](https://getbootstrap.com/docs/3.3/components/#badges).  We should use subtle color that is not distracting to the eye.

**Comment by kareltucek** [comment]
Sounds fine ;-)

**Comment by cokert** [comment]
Is anyone actively working on this?  I have something that should be ready in the next few days that fixes this if not.

**Comment by mondalaci** [comment]
@cokert We haven't started working on this yet. Your contribution is definitely welcome.

**Comment by cokert** [comment]
I have this working, but I'm assuming we want the pills all aligned to the right, correct? 

![image](https://user-images.githubusercontent.com/1710772/57121535-425c6300-6d46-11e9-9d77-759dafccc38a.png)

**Comment by mondalaci** [comment]
Correct.

**Comment by cokert** [comment]
Ok, I have it aligned right (using a similar method to the star for startup keyboard).  This is what it looks like with double digit usage count.  Is this acceptable visually?
![image](https://user-images.githubusercontent.com/1710772/57227456-6ededc00-6fdf-11e9-929d-820ba2908225.png)

**Comment by mondalaci** [comment]
Yes, this looks great!

**Comment by cokert** [comment]
The algorithm I wrote that finds usage also pulls the key map in which the macro is used.  I was planning on adding a popover showing the maps and count in each map to the badge.  Do you guys want me to pursue that?  Or would you rather see a PR for what I have now so we can discuss specifics about the implementation?

**Comment by mondalaci** [comment]
I'm a big fan of taking small steps, so definitely feel free to submit a PR at this point.

**Comment by kareltucek** [comment]
I am trying the PR version right now since I've finally found time to refactor my keymaps and realized that I would probably not be able to so without this feature at all. 

Works like a charm. I don't seem to spot any performance issues even with my current config (appx. 20 keymaps, 100 macros). This allowed me to get rid of approximately 30 macros so far :-).

> Do you guys want me to pursue that?

I would definitely find it useful.
