### ISSUE TITLE
inter-layer copying

### ISSUE THREAD

**Issue by Dagon** [UltimateHackingKeyboard/agent#848]
It's convenient to have some keys repeated on multiple layers - for instance I set BOTH fn and mod layers to give F keys for the number row.  

It would be nice if there were a way to quickly copy from one layer to another, and nice to quickly clear definitions.  Perhaps ctrl-click on a key could copy the definition from the previously-viewed layer, and shift-click could set the key to "none".

**Comment by mondalaci** [comment]
All the modifiers that can be used in a cross-platform manner have already been overloaded. See the Help screen of Agent. There's also the "remap on all layers" feature which is similar, although not same.

I'm sorry, but we can't overload modifiers any more, and I don't think this feature would add too much value to most people.

**Comment by Dagon** [comment]
Fair enough.  perhaps a context menu on right-click rather than straight to record, then.

**Comment by mondalaci** [comment]
Yeah, but right click is already overloaded :)

**Comment by kareltucek** [comment]
Hmm... What about "press key while hovering over a virtual key"? It should be relatively easy to implement and provides plenty of keys for any future requests of this style? (Could be also used in #798 in order to keep consistency and generality.)

**Comment by mondalaci** [comment]
That'd work, but I don't feel strongly about this feature to be honest. We could implement a thousand features like this, each of them would be used by a very small group of people, but I'd much rather keep the codebase simple.

**Comment by Dagon** [comment]
I have to admit I don't feel strongly about this myself.  It's a convenience only, and cut/paste in the UserConfiguration.js file is available if you're copying a large number of keys.
