### ISSUE TITLE
Option NOT to lock layer key on double-click

### ISSUE THREAD

**Issue by Dagon** [UltimateHackingKeyboard/agent#849]
Layer keys set to "activate" automatically act like "toggle" when hit twice in rapid succession.  I would like to be able to disable this, so it never toggles me into Fn layer when I accidentally double-click.

double-click speed of the layer-select toggle should also be adjustable.

**Comment by mondalaci** [comment]
These are both duplicates of existing issues. The first implemented by a pending pull request.
