### ISSUE TITLE
Update agent to reflect firmware changes

### ISSUE THREAD

**Issue by jlsjonas** [UltimateHackingKeyboard/agent#858]
Please update the agent to reflect all the updates in the firmware. including updating the included firmware as it's heavily outdated.

notably:
- media keys bug is fixed in [latest](https://github.com/UltimateHackingKeyboard/firmware/releases) (for windows)
- **macros actually are supported now**

**Comment by mondalaci** [comment]
This has already been done.

**Comment by jlsjonas** [comment]
@mondalaci 
- macros actually are supported now

looks like that's already done indeed....
however 

- media keys bug is fixed in latest (for windows)
the firmware shipped with Agent is still the same as when I got my keyboard; which doesn't have the media keys bug fixed.

From non-dev user experience it's very hard to even realize that the media keys bug has been fixed; as you have to go through a couple github issues to realize it's fixed somewhere & then you still have to manually "override" a firmware flash.

I understand that this would become automatically tracked in time; but a huge issue like the above definitely warrants manually updating the included version until the auto update mechanism is there.
the included version is **over 6 months** old

**Comment by mondalaci** [comment]
There is a reason why the old firmware was flashed. Because of the freeze bug. I've been rolling out the new firmware release in a staged fashion. It'll be the default for every UHK soon.
