### ISSUE TITLE
Extended macro actions && agent's support for custom firmware tweaks

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#862]
/edit: long story short, there's a custom firmware allowing more macro actions via commands pasted into text actions.

Hi, I've been thinking about this for some time. Finally, I am writing it down. This is followup to UltimateHackingKeyboard/agent#216  and UltimateHackingKeyboard/firmware#156 . Furthermore, UltimateHackingKeyboard/firmware#199 complicates the introduced logic.

@luteijn, @mhantsch, @p4elkin, @isometric I think you might be interested in this, and I would like to hear your opinion, and possibly if you are gonna contribute into it too.

## Motivation

As you have surely noticed, there are quite often various feature requests which could be very easily implemented on the firmware side, yet creating a proper agent frontend for them is always too problematic to bother (for anyone). This reasoning also applies to custom tweaks of UHK in general, since firmware is fairly easy to understand and modify but the Agent is (diplomatically said) neither simple nor eloquently documented. 

So the main idea is that it would be nice to have a way to go around the agent in the implementation process somehow. I.e., it would be nice if there was a simple way to pass an arbitrary string list to the firmware through the Agent, without having Agent to process the string. For instance, a new macro action could be added, called something like "custom hook". This action would simply carry a stringlist through the agent, serializer, etc. and end up in some switch in the firmware, where the user would take care of handling it.

## My solution

Since getting an official support might take time and be otherwise problematic, I've decided to simply start a new fork of the firmware. This fork features the Text Macro Action modified so that it allows parsing simple commands. This way, custom functionality can be easily added to firmware, yet is compatible with the official agent.

Currently, commands for layer switching and keymap switching are included. Some delay mechanisms are included too, allowing implementation of mostly custom-style layer locking. See https://github.com/kareltucek/firmware and https://github.com/kareltucek/firmware/releases/tag/v8.5.3.kt . 

## Points for discussion and possible requests for UHK team

- Consider possibilities of supporting this style of actions officially. (My opinion on this is that it actually makes better sense to keep this sort of functionality in an unofficial repo anyway.)

- Actions of this style do not solve configurability of general features written on firmware side (at least not in a nice and straightforward manner). So it would be desirable to have some sort of global config containing key-value pairs which would allow users to enter arbitrary new keys and carry them over to the firmware in an analogous fashion. 

- It would be great if you could add references to forked repos (like mine and p4elkin's - those which actually contain some functionality) into the main github README or somewhere where other users can find them.

P.S., If anyone wonders why I am creating this in the agent repository, it is because it seems to be the default one for general feature-related talks, and because it is mainly about allowing custom tweaks to be interfaced through agent.

P.P.S., please convey my kind regards to those who were so considerate towards memory usage that they decided not to terminate strings by unnecessary null characters.

**Comment by mondalaci** [comment]
I agree that text macro actions are ideally suited for storing custom metadata for the time being, as they are basically a tree rooted in the Macros menu item, branching to individual macros which contain a name and branch to text macro actions. So it's a list of objects which are composed of a name and a list of strings which is fairly flexible.

Given our resources, implementing all of our planned features will likely take years, and this is how we can provide the most value, so I don't plan to allocate resources for this issue, but we can feature forks in the readme of the firmware. If you want to be featured there, feel free to send us a PR.

**Comment by kareltucek** [comment]
Ok, I will do so later. 

I've added a few more actions which mimicking secondary roles, doubletap actions. Also, I've hooked mouse actions. Long story short, as long as not more than one macro is required to run at a time, the following usecases are supported (I did not go through issues which are not marked as exotic features):

- UltimateHackingKeyboard/firmware#140
- UltimateHackingKeyboard/firmware#138
- #684
- #720
- #745
- #749

**Comment by luteijn** [comment]
Great. Thanks for taking this first step Karel, and Laci for the support/consideration. I suppose the same approach could be useful for testing new features of the official firmware before adding full agent support for them. 

I'm quite busy lately but will try to take a good look at this soon.

**Comment by p4elkin** [comment]
@kareltucek looks promising indeed, hope to find some time tmr and will also try to rebase it on my fork as well to see how the customisations would work together!

**Comment by kareltucek** [comment]
@p4elkin looking forward to that! I am quite curious how that will go. I am a bit afraid that joining the two things so that the macros respect your timing adjustments might be non-trivial, and I am not sure how will the two things work alongside if the macro timings are not altered.

**Comment by kareltucek** [comment]
I guess this issue is as good closed as it is open...

**Comment by kareltucek** [comment]
New release is up, with some new features:
- support for "chording shortcuts" utilizing modifiers (via `ifCtrl` etc conditions, only actions in which at most one non-modifier key is used)
- support for modifier dependent binding of scancodes
- refactor to provide better "hold layer" support
- super-cool runtime-macro recorder

Related issues:
- #678 - Theoretically, all basic requirements for implementation of Neo2 in userspace should be now met (mod dependent scancode binding, and more layers (can be mimicked via keyboard switching), although I am wondering how the people intend to produce all those special characters without doing something as insane as creating alt macros for all of them... 
- #617 - more layers can be mimicked, modifier dependent bindings
- #792 - either via `ifPlaytime` or via `holdLayerMax` commands
