### ISSUE TITLE
Fix device recovery mode

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#864]
The device recovery mode (#607) got broken in Agent 1.2.12 which needs to be fixed.

Don't auto-close the recovery screen after the recovery process started.

Add a white "Close" button rightwards of the "Fix device" button. Make it active only when the update process is not active. Make it close the recovery screen when clicked.

**Comment by p4elkin** [comment]
Not sure if this is the right ticket to drop this comment at, but looks like I've managed to brick my keyboard pretty badly:

I've been carrying on hacking with the firmware and once after I flashed the right half's update, the whole keyboard went into a state in which LED has FTY on forever (and all the layer leds are on), not responding to anything.

I tried to follow the steps described at #607, without any luck, blhost utility outputs ```Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=)``` on both mac and windows. On the latter, the OS reports that the device descriptor request has failed.

Most likely there was some stupidity from my side during the debugging (there's a chance that the version uploaded contains a typo which triggers array out of bounds access). I tried several cables to eliminate that issue (no result).

Is it a known possible pitfall? And is there any approach I could try to recover it without involving any extra hardware?

Thanks in advance!

**Comment by mondalaci** [comment]
@p4elkin Your issue is actually related. Make sure to [hardware reset](https://github.com/UltimateHackingKeyboard/firmware/issues/90#issuecomment-363211331) your UHK, then the bootloader will kick in, and so as the recovery screen. Use Agent 1.2.11.

**Comment by p4elkin** [comment]
@mondalaci thanks a lot for the pointer, now it is back, hardware reset FTW!
