### ISSUE TITLE
Keymapping in Macros

### ISSUE THREAD

**Issue by kirbo** [UltimateHackingKeyboard/agent#873]
Hi,

I noticed that macros don't follow the keymapping that i use.
For example, I'm using Finnish layout on Mac and the address becomes:
httpö--ultimatehackingkeyboard.com
..instead of:
https://ultimatehackingkeyboard.com

Then i noticed that if i modify the macro to type address:
https>&&ultimatehackingkeyboard.com
..instead, then it worked properly.

(Yeah, i had to also change the L CTRL to be L CMD instead, because i think the macro was meant to be tested/work on Windows, or something)

Took me a while to figure out why isn't if working/how can i get it to work.

Not sure is this a problem with agent or the firmware or something totally different, so feel free to move this in the correct project.

**Comment by kareltucek** [comment]
Take look at #870 ;-).

**Comment by kirbo** [comment]
Not sure but would any of these packages simplify the solution?
https://www.npmjs.com/package/node-key-sender
https://www.npmjs.com/package/keyboard-layout
https://www.npmjs.com/package/keyboard-js

..or some other. I'm not that familiar with keyboards/scancodes/etc., but i'm quite hopeful there would be an existing npm package to make it easier for solving this issue.

Just realised that the problem might not be with the agent, but in the firmware itself..

**Comment by mondalaci** [comment]
This is a fundamental USB related issue that cannot be addressed properly. You can read more at https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk
