### ISSUE TITLE
Clicking on a link with Mouse 3 inside the agent opens a new window

### ISSUE THREAD

**Issue by monutam91** [UltimateHackingKeyboard/agent#877]
Agent version: 1.2.12

Repro steps:

1. Open agent
2. Go to About
3. Click on link 'Agent on Github' with Mouse 3 (Mouse wheel)
4. It opens a new UHK Agent window with the page opened inside of it

**Comment by mondalaci** [comment]
Good catch! This should clearly open in the browser.

**Comment by cokert** [comment]
I've been looking into this a bit and found this link.  Not sure if you guys have looked into this much or are aware, but this seems to be a common issue.  https://stackoverflow.com/questions/44578022/electron-prevent-middle-click

**Comment by cokert** [comment]
I'm working on this and have the fix pretty much done (essentially, you just to add an auxclick handler in addition to the onclick handler as mentioned in the link).  I'm seeing two different ways of handling links in the code, though.  One decorates the a tag with externalLink, and one has a click handler in the .ts file.  What's the "preferred" way of handling links?  I can change all the links to one VS the other as part of fixing this.  It looks like they were implemented at two different times in two totally different ways.  IMO, the externalLink decorator seems cleaner.

Also, the help page has an embedded URL (it's the link for entering accented characters), where the other URLs are in a Constants file.  Do you guys want me to move the accented characters URL to a constant?

**Comment by mondalaci** [comment]
@cokert Thank you very much for the fix! I think it's as clean as possible, and extracting the URL into its own constant seems fine.

**Comment by mondalaci** [comment]
Fixed by #937.
