### ISSUE TITLE
Add new agent/firmware auto-check to agent

### ISSUE THREAD

**Issue by rtpguy** [UltimateHackingKeyboard/agent#887]
We're in the 21st century now, and software should at minimum check for newer versions when started (I don't believe it's needed to do a background process to run all the time, IMO).  

On Agent startup, a check should be done for whether or not newer versions of agent and UHK firmware have been released, ideally with a way to download/update from the agent UI w/out going to GitHub via browser.  At minimum, a link should be provided to release notes if not included as part of the enhancement.

**Comment by mondalaci** [comment]
Duplicate of #250.
