### ISSUE TITLE
Send macro on double-tap

### ISSUE THREAD

**Issue by jlsjonas** [UltimateHackingKeyboard/agent#888]
Allow executing a macro only on double-tab (or with a modifier key) to prevent accidental presses for sensitive macros

**Comment by mondalaci** [comment]
I'm sorry, but this feature is not planned.

**Comment by kareltucek** [comment]
@jlsjonas, if you don't fear custom firmware, you might like to check out https://github.com/kareltucek/firmware

**Comment by jlsjonas** [comment]
That's why I'm suggesting it for inclusion? @mondalaci 

Thanks for the link @kareltucek, I will definitely consider it.

**Comment by mondalaci** [comment]
@jlsjonas I understand. I wanted to give you a reason for closing this issue. There's an infinite number of features that we could potentially implement. Each of them would complicate Agent, but not many of them would be useful for most. Based on the feedback we receive from our users, is not a widely requested feature.
