### ISSUE TITLE
Option and Cmd key are swapped

### ISSUE THREAD

**Issue by agenthunt** [UltimateHackingKeyboard/agent#890]
Hi,
Has anyone noticed that Option and Cmd key are swapped. 
For ex: In a normal keyboard 'Cmd + Option' should switch  between applications where as in my keyboard 'Option + Tab' switches between applications?
As per documentation, 'Mod + D' is supposed to switch applications. That doesnt seem to be working as well. It is having the same effect as pressing 'Option'
I am using the default settings. 
Is this a bug ? 

Thanks,

**Comment by mondalaci** [comment]
Closing this, as none of these are actual issues, and they were double-posted to our support email. I'll answer in email.
