### ISSUE TITLE
Programmatically change the keymap

### ISSUE THREAD

**Issue by duesenklipper** [UltimateHackingKeyboard/agent#892]
I think it would be very useful if there were a command line way to switch to a new keymap. So I could listen for events in the OS (switching to a different application, or anything else) and fire off a command to UHK to switch to a different keymap, e.g. an application-specific keymap for my IDE.

Is this possible?

**Comment by mondalaci** [comment]
Adaptive mode will do application-specific keymap switching. See #555. In the meantime, you can use ${agentDir}/packages/usb/switch/keymap.js

**Comment by luteijn** [comment]
I think it's `${agentDir}/packages/usb/switch-keymap.js ` actually, so a dash instead of that final slash.
This seems to work fine although it does make agent lose connection.
