### ISSUE TITLE
Macro action to rebind keys

### ISSUE THREAD

**Issue by UndeadKernel** [UltimateHackingKeyboard/agent#893]
Would it be possible to give macros the ability to bind a certain key to another key or even another macro?

The use case: recreating emacs bindings by using different layers.
Example: in emacs, CTRL-SPC starts marking text, CTRL-SPC then stops marking text

I was thinking of implementing the functionality of CTRL-SPC by creating a macro that presses (without releasing) the shift key. The macro would then remap the CTRL-SPC key to a different macro than when pressed releases the shift key.

Would the firmware support such a functionality?

**Comment by mondalaci** [comment]
I'm sorry, but this is not planned. I'm afraid of macros that affect state after their execution, because such macros can be inadverently created by users and then produce unexpected behavior.

**Comment by kareltucek** [comment]
@UndeadKernel You can create a new keymap with the cursor keys (etc) with pressed shift, and switch to this keymap by a shortcut. The switch on Ctrl+Space can be achieved with custom firmware found at https://github.com/kareltucek/firmware , but I think that switching via standard UHK layers makes more sense in your case (I assume that having this bound to your keyboard would make emacs misbehave badly). 

In broader sense, the proposed features don't make much sense because they can be generally solved via keymap switching, which is simpler and safer.

**Comment by UndeadKernel** [comment]
@kareltucek, thanks for the advice. I was not aware that there could be forks of the firmware with an extended macro functionality. The repository you pointed me to looks great.

I'm currently switching keymaps when I press the control and alt key. In this other keymaps, I then emulate emacs bindings of the style `C-<char>` or `M-<char>`. This works great, it's only the marking of text that I miss using `C-SPC`.

I tried creating a macro that "presses shitf" and was hoping that the state of the key would stay on after the macro was finished. As expected, this is not the case: modified key states do not survive after a macro is finished.

**Comment by UndeadKernel** [comment]
@kareltucek, thanks for letting me know that your modified firmware also doesn't support "sticky" states.
I like your idea of switching layouts with `C-SPC` and having all movement keys set to have `shift` on.

Currently, I'm just emptying the existing layouts (i.e., mod, fn, mouse) and setting them up with my own keys. From other issues, I see that it's planned that more "user" created layers are enabled.

There is no functionality to delete all bindings in a layer correct?

**Comment by luteijn** [comment]
As far as I understand things, the USB keyboard protocol doesn't really enable you to send keydown, keyup events anymore in the sense that e.g. ps/2 and MIDI keyboards do. This means keys don't get stuck for long when such an event is missed by the host OS, as the next update has the whole state again, but also makes it harder to do neat things easily as the keyboard has to be smarter and can it can cause issues with software that expects a serial stream of keydown/up events that never happen exactly at the same time.

**Comment by kareltucek** [comment]
> There is no functionality to delete all bindings in a layer correct?

You could export json, edit the json and import again, but it is *not* a user friendly solution.

> Edit: Never mind, I just saw that I cannot change layers with C-SPC when the Control key already switches to another layer. I guess I have to switch to a new Keymap altogether.

You can bind layer switches from non-default layers on the extended firmware via macro commands too. Just be careful - the official layer switching does not play along well with the extended one. I would still recommend to put alternative "modes" to separate keymaps.
