### ISSUE TITLE
PLUGDEV does not exist on all linux distributions

### ISSUE THREAD

**Issue by benneti** [UltimateHackingKeyboard/agent#901]
As I understand it the "PLUGDEV" group is a ubuntu specific thing and so a more systemd standard approach should be taken.

I think replacing `MODE:="0666", GROUP="plugdev"` with `TAG+="uaccess"` may be better
(see [relevant udev rule](https://cgit.freedesktop.org/systemd/systemd/tree/src/login/70-uaccess.rules), [debian](https://wiki.debian.org/USB/GadgetSetup) and [archlinux discussion](https://wiki.archlinux.org/index.php/Talk:Udev)).
This should make the device accessible by the current active user.

**Comment by mondalaci** [comment]
Thanks for the suggestion! The new rules work with Linux Mint (Ubuntu derivative), and they should be more general.

**Comment by benneti** [comment]
great, thank you for the quick fix
