### ISSUE TITLE
[Incomplete] Locked Mod scancode(?) makes Windows 7 behave like Ctrl is pressed.

### ISSUE THREAD

**Issue by WloHu** [UltimateHackingKeyboard/agent#905]
**I have to update firmware then I will try again to reproduce it.**

When I have Mod layer locked and I use Alt+Tab the "switch window" GUI behaves like it received Ctrl+Alt+Tab shortcut which makes the window not disappear when Alt and Tab keys are released. I can freely use arrow keys to navigate. Among other ways the window disappears when I unlock Mod layer by typing Mod key once.

I also had various related issues while playing osu!:
- In my OSU layout I have arrow keys in Mod layer. Yesterday I've triggered Windows display rotation when Mod layer was locked and I pressed the arrow keys. I will try to reproduce it again because I'm not sure what actually happened there.
- If I lock Mod layer in multiplayer lobby and press any single character key the key is written but the game starts to repeatedly play sound of "keypress" after a brief (< 2sec) moment when nothing is pressed, again only Mod layer is locked.

**I will try make a video to reproduce it especially for "keypress sound" case to give better idea.**

**What else should I provide?** Do you know any display-pressed-key app or should I just record my keyboard (by phone because I don't have external webcam and I have no idea about video editing).

**Comment by mondalaci** [comment]
Please update to the [latest UHK firmware](https://github.com/UltimateHackingKeyboard/firmware/releases) via Agent, and let me know which of the above issues still persist.

**Comment by mondalaci** [comment]
Closing this issue due to the lack of replies. Will follow up and reopen if necessary.

**Comment by WloHu** [comment]
I've updated firmware to 8.5.3 (I don't know why Agent didn't up it to 8.5.4) and I couldn't reproduce the issue with `Ctrl-Alt-Tab` in Windows 7.

As for the osu! **it was mostly my error** because one of the keys was mapped to `Ctrl-Alt-F` instead just `F` (copy-paste layer FTW) which was in `Mod` layer together with arrow keys and a key chord (`Ctrl-Alt-F-Left`) triggered display rotation.
Also the **keypress sound issue was caused by above** mapping. However this is bizzare that I couldn't do it using regular modifier keys i.e.:
- typing in `Mod` layer `d Ctrl-Alt-F` (notice space) using 2 keys triggered the repeated sound, but
- typing the same keys using 4 keys (regular `Ctrl-Alt-F` using 3 keys) didn't trigger the sound.

I think the issue can stay closed because keypress sound may be osu!-specific thing. If any of this issues will occur again it the same way so that I can reproduce it reliably I will add comment here.

As we are at it: how `Mod` and `Fn` layer keys are implemented? Do they trigger internal switch in keyboard or send any scancodes to the OS?

**Comment by kareltucek** [comment]
> (I don't know why Agent didn't up it to 8.5.4)

Because Agent contains the firmware which was up to date when the agent was compiled & released (and that's 8.5.3). In order to update to 8.5.4., you have to download the tar file from the link above and flash it via Agent manually.

8.5.4. contains crucial changes in logic of sticky modifiers, which is tightly connected to the reported problem, so you should probably upgrade again and try again.

> As we are at it: how `Mod` and `Fn` layer keys are implemented? Do they trigger internal switch in keyboard or send any scancodes to the OS?

Obviously, keyboard side. I.e., neither layer switches nor keymap switches emit scancodes.
