### ISSUE TITLE
In Agent 1.2.12, Keymap Doesn't Doesn't Release Modifiers w/ Karabiner Elements Running

### ISSUE THREAD

**Issue by StitiS** [UltimateHackingKeyboard/agent#909]
Previous to updating Agent to 1.2.12 today, I was running 1.1.5 and everything was working fine.  Once I updated Agent, my Keypress binding that presses "Option + Backspace" no longer works as intended.  It doesn't release Option until I press another non-modifier key.  If I close Karabiner Elements this doesn't occur, however this is different behavior than before.  See the following screenshot from Karabiner Elements Key Event Viewer.  You can see it didn't release Option until after I pressed "j".

![screen shot 2019-01-28 at 3 26 36 pm](https://user-images.githubusercontent.com/9129183/51873220-2db89b00-2311-11e9-8e07-5c2278c233c6.jpg)

I wonder if it's some sort of timing parameter that KE isn't liking.  My workaround for this case is to rebind a Macro that does the Keypress event.

**Comment by mondalaci** [comment]
When you opened this issue, it contained the following:

> Before submitting a new issue, make sure to do the following:
> 
> 1. If you're using Karabiner Elements on your Mac, close it!
> 2. Install the latest Agent:
>    https://github.com/UltimateHackingKeyboard/agent/releases/latest
> 3. Use Agent to update to the latest firmware:
>    https://github.com/UltimateHackingKeyboard/firmware/releases/latest
> 4. Try to reproduce the issue, and only report it if it still persists.

According to 1) Karabiner Elements is the single most problematic application we ever encountered. If your UHK works well without it, it means that Karabiner Elements is the culprit. I'm closing this issue.
