### ISSUE TITLE
View current key map & layer in on top Window

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/agent#913]
What I would really like is an agent-kind of view that shows the current key map / layer in an on top window very much like an on screen keyboard. This way it would be much faster to learn specific key maps and the layers defined for it. This would alleviate the issue with the keyboard not displaying the functions that are assigned to the keys (which, in my case, only bear a passing resemblance with the original functions).

So the idea is that the view changes if I switch key maps / layers through the keyboard. This would require a permanent connection between the UHK and the software that displays the key map. There is nothing wrong with the current agent, so that window could be scaled down and re-used - without the additional fluff or editing capabilities. Possibly you could switch between the agent and the on-screen keyboard (using the keyboard vs editing the keyboard maps).

A **non**-feature request is to lite up the key that is pressed (as executing the key action would happen after you see the action displayed on the keyboard). This would make it possible to poll the keyboard instead of requiring a continuous connection, scanning for key-presses. I guess it would make sense that it doesn't *flash* a layer momentarily but that it only displays it while it is active for a longer time, with - as minimum - the delay between the polls of the keyboard.

This is a big feature request development wise (and I know / feel that dev. is strained), so I'm not going to press for it in any way.

**Comment by mondalaci** [comment]
By far the largest problem regarding the implementation of this is cross-platform OSD. That'd be a huge amount of work to implement, and given the number standing issues and future plans, I doubt if we can ever allocate time for this.

We'd rather implement #575 eventually which will take far less resources on our part.

**Comment by owlstead** [comment]
Fine by me, it was just a thought that I needed to get logged, maybe I'll start on it on my own, but my TLS 1.3 implementation is already taking much more time than planned :)
