### ISSUE TITLE
Agent falsely reports UHK detected.

### ISSUE THREAD

**Issue by parke** [UltimateHackingKeyboard/agent#915]
I am running Agent 1.2.12 on Lubuntu 18.04.

The file is: UHK.Agent-1.2.12-linux-x86_64.AppImage

When I run Agent, I decline the desktop integration, and then (after 10-ish seconds) Agent displays this message:

"Cannot talk to your UHK"
"Your UHK has been detected, but its permissions are not set up yet,
so agent can't talk to it."

This is interesting, because my UHK has NEVER been plugged into the
computer that Agent is running on.  So I don't know what Agent thinks
it is detecting, but it is certainly not the UHK!

Note:  In order to reproduce this problem later on, I needed to first run the following:

    $  sudo  rm  /etc/udev/rules.d/50-uhk60.rules

Output from Agent is attached.
[20190220_agent.log](https://github.com/UltimateHackingKeyboard/agent/files/2886965/20190220_agent.log)

**Comment by mondalaci** [comment]
Thank you for reporting this bug! I can clearly reproduce this in Agent 1.2.12. This works fine however in Agent 1.2.11, so it was introduced in 1.2.12. We'll fix it.
