### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by vinipsmaker** [UltimateHackingKeyboard/agent#916]
Is there a community forum where we can share layouts, mods, ...?

**Comment by owlstead** [comment]
I asked the same thing by mail, but I guess that the UHK team is hitting some real world limitations, such as freeing up enough time. The answer then was "soon", but yeah.

**Comment by vinipsmaker** [comment]
> Maybe Reddit would be the right place?

It'd work for me. Can you create the sub? Is ownership transferable in case the UHK team show up?

**Comment by mondalaci** [comment]
I will setup a Discourse forum eventually. I've been thinking about using Reddit, but it's [not a good platform for conversations](https://meta.discourse.org/t/difference-between-reddit-and-discourse/9741/3).

I'm closing this because it's not an Agent issue, but feel free to follow up.

**Comment by owlstead** [comment]
Discourse looks good. One problem: it seems incompatible with Reddit, so if we start up a community forum there ourselves then we might get two sites. Discourse allows free services for Open Source, but I'm not sure if UHK satisfies their requirements. It is fully open source, but I presume also for profit. Anyway, it would be tricky for me to open up a discourse channel I suppose, as I'm not representing UHK and can therefore not claim "Open Source" topic. I think. I'll try and find out more.

**Comment by mondalaci** [comment]
We'll self-host Discourse, and don't plan to use Reddit.
