### ISSUE TITLE
[Feature Request] Option to disable lock behavior

### ISSUE THREAD

**Issue by kroy-the-rabbit** [UltimateHackingKeyboard/agent#917]
I have no use for the modifier/function "lock" behavior that occurs when you double-click one of those buttons.  But more often than not, I accidentally push the button, and waste time trying to figure out why my keyboard is doing odd things.

I'd like a way to just disable the lock behavior.

**Comment by mondalaci** [comment]
It's already done. See the "New Agent feature" section of [this blog post](https://ultimatehackingkeyboard.com/blog/2018/12/13/shipping-uhk-webshop-orders).
