### ISSUE TITLE
Fix the "You seem to have an old udev rule file installed" message

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#918]
I [updated the udev file](https://github.com/UltimateHackingKeyboard/agent/commit/eee3322082aa4ff92f0122265ec9f31306980e8e) recently. It should be an improvement, but the old udev file should also work on almost every machine.

Please make Agent NOT show the following message when the previous OR the new udev file is installed.

> You seem to have an old udev rule file installed. New Agent versions require and updated udev rule file to find your UHK.

**Comment by ert78gb** [comment]
Currently, the code just compares the udev file on the client machine and the bundled version. If something is differences then the screen is visible.
For this enhancement not enough to compare the two. We have to parse it too and store in the code the possible good values.

I am not Linux specialist and I don't know what is the difference between the 2 settings but if we support both versions we have to test the agent with both sets before a release.

Based on my notes do you still want this feature?
