### ISSUE TITLE
When in toggled layer key mode, allow holding the layer key to temporarily disable the mode so you can type normally.

### ISSUE THREAD

**Issue by VinceG3** [UltimateHackingKeyboard/agent#926]
I've been using the Mod keymap as a 'text utility' mode that allows me access to one-keypress editing power tools, and so I remap the case Mod key to toggle the Mod layer. Would be great if while I was in Mod mode, I could hold the left mod key down so I can insert a character or two and go right back to mod mode when I let off of the left Mod key.

**Comment by mondalaci** [comment]
I'm sorry, but we can't make this happen without introducing a special case that would be rather confusing to the vast majority of users, so it's not planned. The secondary role feature is the closest to what you're after, but may not suit your needs.

I'm closing this issue, but feel free to follow up regardless.

**Comment by kareltucek** [comment]
if you don't mind spending some time on configuration, you might like to check out https://github.com/kareltucek/firmware (let me know if you need any help)...
