### ISSUE TITLE
Layer switchers are not correctly cleared

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#929]
Again. 

![2019-03-18-211730_1680x1050_scrot](https://user-images.githubusercontent.com/3447497/54560870-9b08b400-49c3-11e9-84b7-59c612454b55.png)

Steps to reproduce:
Add layer switch on the base layer. Clear the mapping again. Switch to the target layer (of the cleared mapping). Now the tab of the popover is locked and the mapping cannot be changed until restart of the agent (i.e., until full reload of user config).

**Comment by mondalaci** [comment]
Thanks for reporting! I can clearly reproduce this. We'll fix it.
