### ISSUE TITLE
UHK default configuration and add keymap presets

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#93]
I can see that there's both `default-keymaps.json` and `uhk-config.json` present in `src/config-serializer` containing redundant information which makes me think about the UHK configuration in general and add keymap presets in specific.

The idea is that the UHK should come preloaded with [a large number of keymaps](https://github.com/UltimateHackingKeyboard/agent/issues/91), so that users could have lot of options to choose from. So we'll take `uhk-config.json`, convert it binary format and load it into the EEPROM of the UHK in the factory.

Then the user will be able to infinitely tweak his/her configuration and diverge from the default configuration as desired.

But regardless, the add new keymap presets should always feature the keymaps of the default configuration. So the idea is to simply take the keymaps of the default configuration and offer them as the presets of the add new keymap UI.

But there's a twist to this. The presets should not contain macro actions and keymap switch actions. The reason is because these special actions reference keymaps and macros in the EEPROM which might have changed or deleted by the user.

`default-keymaps.json` should be removed after implementing the above.

**Comment by NejcZdovc** [comment]
Regarding presets. We talked with @fjozsef yesterday and we will have all presets in one folder called `preset-keymaps` (as you suggested) from which we will create one big json with webpack in compile cycle. New file would be called `preset-keymaps.json` (as you suggested).

So for now we will have two files `uhk-config.json` and `preset-keymaps.json` (which will replace `default-keymaps.json`).

One thing. Will we have factory reset action?

Scenario: User gets his keyboard. There will be default `uhk-config.json` on keyboard. He then adds few keyboards and customize everything. Then he decides to sell his keyboard and he would like to give the new buyer keyboard in same condition that he bought it.

If we will have factory reset (or reset to default), we need to define what is our default / initial state and where this state will be defined.

**Comment by mondalaci** [comment]
I would rather not go with separate files per keymaps despite my first suggestion. The reason is that we should be able to save the whole configuration soon with all the keymaps included, and create new keymaps via the GUI in no time. Then we'll be able to create and edit the desired keymaps very quickly.

The factory keymap will be implemented in the firmware itself and stored in the flash memory, not in the EEPROM. Upon pressing the factory reset button it'll be loaded as the current keymap. So Agent doesn't have to do anything in this respect.

**Comment by fjozsef** [comment]
What if the user only wants to reset his keymaps, but not his macros or settings?

**Comment by mondalaci** [comment]
There will be no such option provided.

The important thing about factory reset is that it totally disregards the EEPROM. I think this is a good design decision because the configuration parser will be quite complicated and it may break when encountering with various (possibly buggy) configuration items. If so, in the worst case the user can simply keep the factory reset button pressed, plug in his/her UHK to make it skip EEPROM parsing. Being able to recover this way is priceless.

It's also important to note that factory reset is not permament. It only pertains to the current session and does not modify the EEPROM. If you factory reset your UHK it'll load the factory keymap and then if you unplug its USB and replug it your configuration will be restored.

**Comment by fjozsef** [comment]
I know, but we could provide this option from agent.

**Comment by mondalaci** [comment]
If the user resets his factory keymap then given that the factory keymap won't use macros, macros don't matter in this case.

As for other settings, it's not clear what they will be. But given the above, I think it's not a good idea to read anything from the EEPROM when factory reset is involved.

**Comment by NejcZdovc** [comment]
This was discussed with @mondalaci via hangouts and based on our talk I will create md file with the whole flow.

**Comment by fjozsef** [comment]
Blocked #274

**Comment by mondalaci** [comment]
We have been talking about this, and concluded that this small redundancy is acceptable, so I'm closing this issue.
