### ISSUE TITLE
Remap key combinations

### ISSUE THREAD

**Issue by axaluss** [UltimateHackingKeyboard/agent#930]
I'd like to remap key combinations.
I.e. i'd like to remap ctrl+tab to alt+tab or to a macro.

**Comment by kareltucek** [comment]
Remapping arbitrary combinations is neither possible nor planned.

Your specific usecase (i.e., remapping of combinations consisting of modifiers) is planned via #617, unfortunately as far as I know, it is nowhere near to the final implementation.

Another option for this specific usecase is using an unofficial fork of the firmware - https://github.com/kareltucek/firmware . It contains macro commands for amending the control flow, including conditionals for ctrl/alt/shift/gui.

**Comment by mondalaci** [comment]
I want to make it clear that this is planned via #617, but we have no ETA on GitHub issues.
