### ISSUE TITLE
Add keymap switching to macros

### ISSUE THREAD

**Issue by waynew** [UltimateHackingKeyboard/agent#932]
I'm not sure if this is covered by another issue - I didn't find anything.

What I would love to have available is being able to swap keymaps as part of a macro action (or, fire a macro when swapping keymaps).

My use case is this: I use [synergy](https://symless.com/synergy) to run my UHK on Mac, Linux, and sometimes Windows. The problem is that Mac needs different keybindings than Linux for my browser, etc.

Usually I just use the mouse layer to move from this device to the next. Synergy does support creating hotkeys, so I could easily trigger a hotkey to move to my next device - the only problem is that my keys are still mapped incorrectly, so what I would like to do is be able to do something like say on my Linux keymap to bind Fn+w to run a macro that matches the Synergy shortcut to move one screen to the left, and then set the keymap to my Mac keymap. Then Fn+r on my Mac keymap triggers synergy to move one to the right and sets the keymap back to Linux.

Is it possible to do something like this currently with Agent? I haven't found it yet... I would find that *super* handy :heart:

**Comment by mondalaci** [comment]
Hey there!

Even though we don't plan to implement this feature because it's very niche, they may be a way. Assuming that synergy is able to run a script upon switching between OS workspaces, you can use `switch-keymap.js QWR` to switch between keymaps.

See https://github.com/UltimateHackingKeyboard/agent/blob/master/packages/usb/switch-keymap.js

Hope it helps!

**Comment by kareltucek** [comment]
I think that this is a very reasonable feature request. I don't see anything niche about it, since it is a vital feature to an entire class of application-specific workflow-oriented bindings.

Anyway, [this](https://github.com/kareltucek/firmware) firmware supports it.
