### ISSUE TITLE
Add help icon to explain what "Modifiers:" means when remapping a key.

### ISSUE THREAD

**Issue by mikew1** [UltimateHackingKeyboard/agent#933]
Maybe I'm missing something (high chance of that), but I don't understand the intended effect where one selects an ordinary key, say **A**, then, underneath where it says **Scancode:**, (currently set to **A**, in this case, obviously), there is a row of buttons titled **Modifiers:**. 

Say I select one (or more?) of those **Modifiers**, then press **Remap key**. At this point small icons appear on the graphical depiction of that key, in the agent UI.  I don't know what this is doing. I've tried to guess (I don't own a UHC yet - I'm a potential buyer trying out the software), but no joy.

Other icons have a small **?**, which is helpful, but this one doesn't.  
Looks a wonderful keyboard. Very practical. Thank you for making it.

I note the web build of agent is v. 1.2.8, whereas desktop (which I can't run as I don't own a keyboard yet), is v.1.2.12. (Could you maybe bump the web version so potential buyers can try the latest?).

**Comment by mikew1** [comment]
I believe I've found the answer - perhaps you could confirm if I've understood this correctly? (and in which case the suggestion of a small '?' icon to explain this, in your UI, still stands).  

The meaning of **Modifiers** underneath **Scancode** is more intuitive to grasp if one tries it from a layer other than the base layer. I believe it means one can map a key to a key chord, including the modifiers as selected. Thus it's a limited form of macro in a way; limited to key chords utilising modifier keys.

If I've understood correctly, this is brilliant, because I can remap the default emacs navigation keys which are shared by other osx gui apps as follows. These keys are terrible in ergonomic terms, but what we can do here is remap C-b ('back one char'), C-f ('forward one char'), C-n ('next line'), C-p ('previous line'), to keys on the home row. Since for this I've used the Fn layer (removing the media keys for the time being) I can remap the left space to Fn and with that i just hit that slim key with my thumb then I have _home-position navigation keys_ without changing anything in emacs, _which also work in almost all osx gui apps!_ Can you please confirm this would work?  This is exactly what I've been looking for. So long as I've got this right; marvellous!

<img width="790" alt="Screen Shot 2019-03-29 at 16 51 02" src="https://user-images.githubusercontent.com/8282106/55245157-e2543780-5242-11e9-9931-7f9c17763427.png">

**Comment by luteijn** [comment]
https://en.m.wikipedia.org/wiki/Modifier_key - tl;dr: 'modifiers' refers to keys like ctrl, alt, shift, super, hyper.

Yes, you can remap keys to their shifted (or ctrl-shifted or whatever combo of modifiers you want) versions, or to some other key completely.

**Comment by mondalaci** [comment]
@mikew1 You're spot on regarding the functionality of the modifiers. I like your suggested tooltip, and we'll add it.

@ert78gb When opening the scancode select2, it pushes downward nearby elements by 1px. This shouldn't happen. Please also fix this.
