### ISSUE TITLE
Macros hold key support.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#934]
Feature proposal - add support for fourth key macro sub action - hold. I.e., add hold to the press/tap/release enum. Also, add delay "until release". The difference to the *tap* action is that hold would wait with release until the key is physically released. Of course, this mechanism does not become interesting until macro engine can work in "non-blcoking" mode. 

Of course, feel free to close this straight away, I just though it would be nice to have this proposal stashed on the official tracker ;-).

**Comment by mondalaci** [comment]
Would you please list some valid use cases? I'm asking because nobody has requested this feature before.

**Comment by kareltucek** [comment]
Theoretically, tap vs hold makes great difference for computer games. Layouts which contain "tap" events become totally unusable in such cases.

Regarding specific usecase, I have none in mind which would be suited for your firmware. I decided to post this here mostly because I am extending the enum on my side right now to make the macro language more user-friendly. So it made sense to post the proposal here just to "let you know". 

With my firmware, for instance "shift with doubletap to caps lock" uses either sequence `press shift + delayUntilRelease + release shift` or directly `hold shift`. I use the `delayUntilRelease` very often for things related to layer switching logic, although the command has been refactored into higher-level abstractions in many instances.

**Comment by mondalaci** [comment]
Thanks for explaining!

I appreciate your proposal, but given that nobody else has ever requested such features, I'd rather not include them.

Regardless, I must say I'm very impressed by your work. I've taken a look at it the other day, and I'd have never thought that the UHK firmware ever gets extended in such extensive ways. Keep it up!

**Comment by kareltucek** [comment]
Thanks for the nice words ;-).

**Comment by conradob** [comment]
Sorry for bringing this up again. But comparing to Ergodox that have `Hyper` and `Meh` keys which in summary is a key combination of Alt+Ctrl+Shift and Cmd/Ctrl (`Meh` doesn't send  Cmd/Ctrl) we could also achieve this with the @kareltucek  suggestion. If not, Is there a way to achieve this behaviour with UHK?

**Comment by kareltucek** [comment]
You can install the discussed firmware fork from https://github.com/kareltucek/firmware and then use its extended macro langugage which supports it. Something like `$holdKey CAGS-` should work.

**Comment by radevop** [comment]
I also need way to keep some of mod's (Alt/Ctrl/Shift) key tapped for some time. Can you plz take this proposal at work?

My user cases:
1. Define some key that will hold selected mod key tapped alltime utill I'll hit it again.
2. Or define some key that will hold selected mod key tapped alltime utill I'll hit this mod (to release it).

**Comment by kareltucek** [comment]
Just to make it clear, this proposal (as originally meant) does *not* solve your use cases - it only allows you to make macros behave same as regular keys (but optinally add more actions at the start or end of the macro).

But regarding time-unlimited key lock, there have been multiple requests for it, so I think I might implement it on the mentioned fork. (Currently, it is possible only via an active wait loop and a register flag, which works but is not very convenient.)
