### ISSUE TITLE
feature request: describe what command is being escalated for wrt polkit

### ISSUE THREAD

**Issue by jzacsh** [UltimateHackingKeyboard/agent#935]
**first**: the permissions detection, and then alternative (`cat` this into `udev` folder) is really an awesome catch and degrading flow. nice work!

so this is just a **nit feature request**: it would be good to show what exactly you're prompting me to run (when you ask me to enter my sudo password), so I can consider running it myself. I hit cancel, because I'd rather know what's being run (think about it, and then run it *myself*)

from the alternative `cat` description I see, I get the impression that's not what agent was trying to do for me.

**Comment by jzacsh** [comment]
ah, i see: [`rules/setup-rules.sh`][setupRulesSh] (per [`sudo.service.ts`][sudoServiceTs]) is what was being asked to run. and that turns out to be exactly what's in the "manual" step.

Based on _"This is most likely because the `polkit` package is not installed on your system"_ I misunderstood and thought there was some better command that would've run (if i'd agreed to enter my password), so the `cat` line was just a manual hack.

[sshot]: https://github.com/UltimateHackingKeyboard/agent/issues/781#issuecomment-423360756
[setupRulesSh]: https://github.com/UltimateHackingKeyboard/agent/blob/v1.2.12/rules/setup-rules.sh#L4
[sudoServiceTs]: https://github.com/UltimateHackingKeyboard/agent/blob/v1.2.12/packages/uhk-agent/src/services/sudo.service.ts#L59

**Comment by mondalaci** [comment]
Thanks for reporting! So should we consider this a non-issue?

**Comment by mondalaci** [comment]
I consider this done.
