### ISSUE TITLE
need to flash through usb hub

### ISSUE THREAD

**Issue by axaluss** [UltimateHackingKeyboard/agent#940]
on 1.2.12 i still can't flash my uhk.
I'm trying to flash my uhk on my macbook pro, which does not have any compatible USB ports.
So I am forced to use some kind of USB hub/adapter.
https://pastebin.com/qwEE4Paf

**Comment by mondalaci** [comment]
I'm sorry, but we can hardly do anything about this. A Mini USB to USB-C cable would probably solve this issue.
