### ISSUE TITLE
Mod+Enter shortcut

### ISSUE THREAD

**Issue by mstaniszczak** [UltimateHackingKeyboard/agent#942]
At begin thank you for made so great keyboard and agent for it. For now I have one problem. It's not any kind of blocker, just strange behavior. I use very often alt+enter shortcut (PyCharm), but here I decide to redefine this shortcut to Mod+Enter as a alt+enter (on agent level). And it works, but only after I push enter twice. I can live with it, but maybe there is some solution for it?

**Comment by mondalaci** [comment]
First up, thanks for the nice words!

This should work well. Do you use Karabiner, Hyper-V, or any software that may modify keyboard input?

**Comment by mstaniszczak** [comment]
No, nothing similar. I use ubuntu, without any software which can modify keyboard input. But on the evening I'll check it also on Arch Linux, and maybe on my wife PC with Windows, and then I'll let you know. Maybe you right and that's problem, only with my machine/os. Good point.

**Comment by mondalaci** [comment]
Closing this issue due to the lack of follow-ups. May be related to https://github.com/UltimateHackingKeyboard/firmware/issues/221
