### ISSUE TITLE
ghost typing of "." and .  double spaces

### ISSUE THREAD

**Issue by fugufish** [UltimateHackingKeyboard/agent#945]
running latest agent, I am consistently getting a . second space or .  a "." (as demonstrated in this ticket . as I intentionally didn't edit . them out

**Comment by fugufish** [comment]
I . was running . on 8.5.3, and flashed . to . latest problem persists

**Comment by fugufish** [comment]
problem also persists with the alt space key on the left hand side 

b b b b b  b b . b b

^^^^^^^^^^^^^^^^^^^^^^

**Comment by mondalaci** [comment]
This is not an Agent-specific issue, but hardware specific. Please shoot an email to support@ultimatehackingkeyboard.com - I'll be able to help you there quicker.

**Comment by fugufish** [comment]
👍
