### ISSUE TITLE
Brush resizing in Affinity Photo

### ISSUE THREAD

**Issue by ajh3** [UltimateHackingKeyboard/agent#946]
Resizing a brush in Affinity Photo involves the following: 

1. Click and hold right mouse button
2. Press and hold Alt
3. Click and hold left mouse button
4. Move mouse left or right.
5. Release all mouse and keyboard keys.

I am trying to create a macro which performs steps 1-3, so all I have to do is drag the mouse. However I can't get it to work, and unsure which step is failing.

Here is the configuration:

![2019-05-08 18_14_37-UHK Agent](https://user-images.githubusercontent.com/40405382/57420795-069a2100-71be-11e9-8cd5-15738cb1fd21.jpg)

Any suggestions? Thanks.

**Comment by luteijn** [comment]
I think that at the end of a macro, all keys and buttons are 'released'. So you probably have to add several macros, each including some mouse movement to the macro, e.g. enough to resize the brush by 1, 2, 3, 5, 8, 13, 21 steps up or down, and then combine them to adjust the size...

**Comment by kareltucek** [comment]
@mondalaci, this is real life usecase for #934.

@ajh3, if you don't mind flashing a custom firmware, you can achieve the functionality with https://github.com/kareltucek/firmware . It would suffice to add a text macro action containing `$delayUntilRelease` at the end of macro...

**Comment by mondalaci** [comment]
@ajh3 The UHK firmware doesn't support holding mouse buttons + modifiers while holding a key. By triggering a macro, you can only hold buttons and keys, then move a mouse by x pixels, then release the buttons and keys. @kareltucek's firmware fork allows exactly what you're after.

@kareltucek This is a real life use case for #934, indeed, but it's a niche one. I may reconsider this eventually if this use case turns out to be more prevalent.

**Comment by kareltucek** [comment]
Yep, just pointing out and crossreferencing ;-).

**Comment by ajh3** [comment]
Thanks. I flashed the custom firmware, but I cannot understand the help doc. @kareltucek would you mind explaining in more detail how to write the macro? Thanks so much.

@mondalaci Affinity Photo is niche, although FYI Photoshop uses a very similar command for its brush resizing. And outside of regular shortcuts like Undo, it is one of the most used shortcuts by PS users.

**Comment by mondalaci** [comment]
@ajh3 Gocha, will keep it in mind. Please note that it's already possible to create a UHK macro that you're looking for which moves the mouse by a *fixed* amount of pixels. I'm not sure how useful it is, but I'd be interested to hear your opinion.

**Comment by kareltucek** [comment]
@ajh3, I've extended the readme by a "getting started" section. You are welcome to go through it and point out any shortcomings (but if you do, probably create new ticket in that repository). But basically, just use the macro you have posted at the top, add new "Type text" macro, and paste `$delayUntilRelease`.

**Comment by kareltucek** [comment]
@mondalaci I should probably have left the question to Ajh, but I'm gonna reply anyway - the strength of a stylus/mouse movement for brush resizing is exactly in its interactive nature - you move exactly the distance by which you want the brush to be resized. Extremely comfortable, especially with stylus&tablet. Fixed steps on buttons just do not cut it.  

A solution could also be to rebind the modifier in the Affinity software to standard modifiers. The ridiculous modifier (alt+both mouse buttons) was most likely designed for stylus (where left button means touch of stylus against the tablet)...

**Comment by ajh3** [comment]
@kareltucek Thanks, that cleared it up, and it works perfectly. Good firmware!

As for the brush, I agree. Fixed adjustments aren't really enough. In PS/Affinity, the `[` and `]` keys are already used for low-precision/quick (although not exactly 'fixed') brush sizing. This shortcut is for precision resizing.

> A solution could also be to rebind the modifier in the Affinity software to standard modifiers.

Unfortunately, not possible :(

Anyway, I'm good for now, and I appreciate all the help. I do suspect this will come up again as UHK becomes more popular. 

Keep up the good work!

**Comment by kareltucek** [comment]
good to hear :-)
