### ISSUE TITLE
Possibility to modify the layout of the agent

### ISSUE THREAD

**Issue by sribst** [UltimateHackingKeyboard/agent#948]
The agent is based on a QWERTY layout but I personally use AZERTY as main layout (as everybody do in my country)

It would be nice to be able to configure (even manually) the base layout of the agent so the 'A' key view (or else) is really an 'A' on the OS.

I'm not sure to be clear, sorry...

**Comment by mondalaci** [comment]
This is fundamentally problematic and not planned to be implemented. [See why](https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk).

**Comment by sribst** [comment]
Wrongly explain, sorry
I do understand but what I mean is I would like to access the mapping used be the agent between scancode and character to preview the keyboard in order to modify it.
I do understand that for the software to guess wich layout is used by the OS is a fundamental problem but I think to have an option on the agent to configure this mapping only in order to have a better view in the agent seems doable no ?

**Comment by mondalaci** [comment]
The fundamental problem is that the UHK firmware is unaware of the OS layout. As such, the same scancode will result in different characters depending on the OS layout of the computer you connect your UHK to.
