### ISSUE TITLE
Sequence keymap

### ISSUE THREAD

**Issue by Siecje** [UltimateHackingKeyboard/agent#950]
Is it possible to type `öä` and have the result be `{`, for example.

**Comment by mondalaci** [comment]
I'm sorry, but this is not planned to be supported.

**Comment by Siecje** [comment]
Thanks for the quick reply!

**Comment by kareltucek** [comment]
Possible with https://github.com/kareltucek/firmware . Search for `ifShortcut`, `ifGesture` and possibly for `resolveSecondary`.
