### ISSUE TITLE
Create feature modules

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#96]
Since we have updated to angular 2 rc.6 our root module have come very large. We should create our own [feature modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules).

**Comment by ert78gb** [comment]
Could you prioritise this issue? I will do it if we discuss it. It Very annoying I could not use the IntelliJ auto import functionality.

**Comment by ert78gb** [comment]
Could we talk about this issue? I would like to use angular-cli and angular module system.
My plan is:
- create an angular-cli (common) module from web and shared folders.
- create an electron module (electron-main) that use common module

maybe we could use [lena](https://github.com/lerna/lerna) to manage different packages if we wanna separate to independent packages of the app.

**Comment by mondalaci** [comment]
Sure, let's talk about it! I have a feeling that it'll be a long discussion. Conducting a Hangouts group talk would the best way forward.
