### ISSUE TITLE
Why can't the fn key be used like any other modifier?

### ISSUE THREAD

**Issue by jsarbour** [UltimateHackingKeyboard/agent#973]
Why can't I use the function keys like any other modifier key? I want to map the chord of mod+L (right arrow) + fn to 'jump to end of line' ("end"), and left arrow + fn to home (start of line), but I can't use fn as a modifier like I can ctrl/alt/shift.

What gives?

**Comment by luteijn** [comment]
There is a conceptual difference between  Fn, Mod, Mouse (that are unique to the UHK) and Shift, Control, Alt, Super (found on most keyboards) in that the first aren't modifiers at all, but layer switchers. At the moment, there are only four layers per keymap, and only one can be active at a time. One way to think of this is that the UHK handles the layer-switching, but leaves the handling of modifiers to the OS

The UHK's hardware keys are all the same (except for size/shape) to the firmware, but the interface between the UHK and the OS is still the same as a real USB-keyboard. Some of the thinking behind this interface still leaks through to how the firmware handles things, so you can't yet e.g. split 1 and ! or ` and ~,  as those are sent to the OS as 1 and ` with or without shift modifier.

You'll still have to handle some things at the other end of the cable with a program like autohotkey.

**Comment by jsarbour** [comment]
Thanks, great answer. I'll look into some other workaround.
