### ISSUE TITLE
MacroAction refactoring

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#98]
@mondalaci:
> How about merging {Hold,Press,Release}{Key,Modifiers}MacroAction.ts to KeyMacroAction.ts? Then we'd add an action field for Hold|Press|Release and a fields field for Key|Modifiers|KeyAndModifiers. We could use 2 bits of the macro action type byte to store action, and another 2 to store fields. The length of the action item would be dependent on the value of fields. This space optimized, single-class strategy is the same that we're already using for key actions.

> We could do the same kind of merging for {Hold,Press,Release}MouseButtonsMacroAction.ts to MouseButtonsMacroAction.ts.

Copied from https://github.com/UltimateHackingKeyboard/agent/pull/87#issuecomment-244359347

**Comment by fjozsef** [comment]
@mondalaci Will it be possible e.g to mix Hold with additional modifiers? It seems to me the current version doesn't support this. If it should support then we have to merge, if they don't then I propose to create `KeyMacroAction` and `ModifiersMacroAction`.

**Comment by mondalaci** [comment]
Yes, a single macro action should be able to store a set of modifiers and a scancode because this allows for a more compact storage of such macro actions.

**Comment by fjozsef** [comment]
Do we want to merge these also in the binary representation?

**Comment by mondalaci** [comment]
Yes, the binary representation should always be consistent with the other representations.
