### ISSUE TITLE
Make native kboot firmware update not crash on Windows

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#984]
The new, native (and unreleased) TypeScript kboot implementation crashes on Windows. I'm running Windows 10 on my test laptop, but probably other Windows versions are also affected. The crash happens after the "Try to connect to the LEFT keyboard" message. Sometimes directly after this message and other times a few messages later. The crash usually happens but not every time. Windows pops up a general "UHK Agent has stopped working" error message popup upon such crashes.

**Comment by ert78gb** [comment]
Pls use the `DEBUG=kboot*` environment variable to `kboot` writes the logs.
I can set this variable by default in the agent package.json and it will the default developer setting

**Comment by mondalaci** [comment]
I attached [the firmware update log](https://github.com/UltimateHackingKeyboard/agent/files/3439570/agent-log.txt) on Windows 10. This time, I can't even see a popup. Agent just suddenly crashes without displaying anything. Sometimes, the firmware update succeeds, but most of the time, it fails.

**Comment by mondalaci** [comment]
Attached is the [new fimware update log](https://github.com/UltimateHackingKeyboard/agent/files/3449305/agent-log.txt) of master on Windows 10.

**Comment by mondalaci** [comment]
[kboot-firmware-upgrade.ts.log](https://github.com/UltimateHackingKeyboard/agent/files/3464223/kboot-firmware-upgrade.ts.log)

**Comment by mondalaci** [comment]
[kboot-firmware-upgrade2.ts.log](https://github.com/UltimateHackingKeyboard/agent/files/3464238/kboot-firmware-upgrade2.ts.log)

**Comment by mondalaci** [comment]
[kboot-firmware-upgrade3.ts.log](https://github.com/UltimateHackingKeyboard/agent/files/3464298/kboot-firmware-upgrade3.ts.log)

**Comment by mondalaci** [comment]
blhost has been reverted in #1008. This makes this issue not a bug but an enhancement. This issue is blocked by a node-hid or hidapi bug that causes the crash on Windows.

**Comment by mondalaci** [comment]
Fixed by #1180.
