### ISSUE TITLE
Set log level from command line

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/agent#988]
After the #450 implementation, every 250ms will write devices communication log. To decrease the size of the log in the customer environment have to introduce a log level method. 
The industry standard for development uses environment variables.
More customer-friendly solution if the user can set the log level from the application. 1 possible place is in the Agent/Setting page

**Comment by mondalaci** [comment]
Please only use environment variables. Don't display this option on the UI.

**Comment by mondalaci** [comment]
Let's make the following log categories:
- `usb` for USB reads and writes
- `config` for binary and JSON configuration
- `misc` for everything else
- `all` would include all the above

By default, only enable `misc`

Make the log categories specifiable via the `--log` parameter. For example `--log misc,usb`

We should also support `--help`, make it display the options and not start Agent when it's specified.
